### ISSUE TITLE
如果在mac上多开微信客户端

### ISSUE THREAD

**Issue by loufq** [Sunnyyoung/WeChatTweak-macOS#1]
现在只能打开一个客户端，如何多开。模拟网页端性能感觉不行，另外有些功能无法实现

**Comment by Sunnyyoung** [comment]
@loufq 多开这个暂时没有研究，能做的话会更新的

**Comment by Sunnyyoung** [comment]
@loufq Hi～已实现任意多开功能，参考 0ec8de7b53ce741856b2d4bda82afe6e62fcb80f

**Comment by loufq** [comment]
多谢
