### ISSUE TITLE
Bartender 对使用了Tweak的微信隐藏失败

### ISSUE THREAD

**Issue by fanvinga** [Sunnyyoung/WeChatTweak-macOS#102]
同 #67
系统版本:10.14 Beta (18A377a)
微信版本:Version. 2.3.18 (11431)
Commit:c7a4ece7a0392a751017879ab32481a9261d9093
Bartender版本:3.0.47
备注:Bartender提示如下
![image](https://user-images.githubusercontent.com/26292849/44912665-91886900-ad5d-11e8-89cd-563947334c98.png)

**Comment by Sunnyyoung** [comment]
我这里测试没有问题哦

**Comment by izhangxm** [comment]
我这里也不行 我使用的是最新版本的微信

**Comment by izhangxm** [comment]
具体版本号
![image](https://user-images.githubusercontent.com/16874796/58447951-c84aae80-8138-11e9-87d9-ee07ae580ea6.png)
