### ISSUE TITLE
以前Mac版保存的聊天历史记录没了。。。

### ISSUE THREAD

**Issue by JonahWong** [Sunnyyoung/WeChatTweak-macOS#11]
为什么？
就不能在Readme里写清楚有关缺陷么，好决定到底要不要装！

**Comment by xsnaruto** [comment]
玩这些东西做好数据备份不是基本常识吗？和不建议开发者装 beta 系统一样，如果你不懂的话不推荐装也是「常识」了。

**Comment by JonahWong** [comment]
beta 至少也会提示相关风险。

**Comment by xsnaruto** [comment]
这是 GitHub 诶，正式版都存在 bug，你用 GitHub 上的东西肯定做好准备再用呀。无聊你用哪里的东西，做备份也是常识。升级正式版系统也可能出问题啊，重要的是别人不会为你负责呀。吸取教训吧，以后勤做备份。如果不了解的东西不要随便用了，如果要用自己不懂的东西，就做好相关准备。不是说这个项目没问题，我只是想说，希望用别人的东西，真是不要随便下载下来就直接用了。万一别人放的就是恶意代码或者病毒呢，第一批就是各类小白了。

**Comment by Mregret** [comment]
弱弱的问一句，我从wechattweak.framework 打开没反应，求指导

**Comment by Sunnyyoung** [comment]
@Mregret 参考 #12

**Comment by Sunnyyoung** [comment]
@JonahWong 首先我并不觉得是缺陷

执行命令`cp -R ~/Library/Containers/com.tencent.xinWeChat/Data/Library/Application\ Support/com.tencent.xinWeChat ~/Library/Application\ Support/com.tencent.xinWeChat`可迁移聊天记录

**Comment by JonahWong** [comment]
@Sunnyyoung 试了，历史记录没用回来。还是说这个命令应该在安装插件后立即执行？反正我在历史记录丢失以后再运行这个命令是没用的。
