### ISSUE TITLE
Version. 2.3.19 (11654), 使用alfred搜索联系人会闪退

### ISSUE THREAD

**Issue by leoyeer** [Sunnyyoung/WeChatTweak-macOS#111]
如题，必现

**Comment by Sunnyyoung** [comment]
@leoyeer 更新至最新版吧，已经修复了这个问题的
![image](https://user-images.githubusercontent.com/5926284/47612990-01e30a80-dac1-11e8-9afb-497c46c241bb.png)

**Comment by leoyeer** [comment]
好的
