### ISSUE TITLE
Wechat Tweak Security Risks

### ISSUE THREAD

**Issue by Soindigo** [Sunnyyoung/WeChatTweak-macOS#114]
[https://xlab.tencent.com/cn/2018/10/23/weixin-cheater-risks/#more-398](url)
端口48065的安全风险可以避免吗 没有使用alfred

**Comment by Sunnyyoung** [comment]
@Soindigo 这个已经修复了的

**Comment by Soindigo** [comment]
> @Soindigo 这个已经修复了的

现在没有问题了嘛  那就放心了 :)
