### ISSUE TITLE
V2.3.18 撤回会奔溃

### ISSUE THREAD

**Issue by EVANRAN** [Sunnyyoung/WeChatTweak-macOS#116]
微信 Version. 2.3.18 (11431)， 撤回消息会奔溃

**Comment by Sunnyyoung** [comment]
@EVANRAN 更新到最新的插件试试看？

**Comment by EVANRAN** [comment]
> @EVANRAN 更新到最新的插件试试看？

可能我装完没重启微信吧，现在好了。

**Comment by EVANRAN** [comment]
可能我装完没重启微信吧，现在好了。

> @EVANRAN 更新到最新的插件试试看？
