### ISSUE TITLE
make: *** No rule to make target `install'.  Stop.

### ISSUE THREAD

**Issue by ichengfu** [Sunnyyoung/WeChatTweak-macOS#12]
非程序员，按照小众软件介绍的方法到sudo make install时报错，是不是还要安装其他的东西？

**Comment by Sunnyyoung** [comment]
1. 打开`Terminal`
2. 输入`cd `(注意有个空格)
3. 把下载的文件夹拖进`terminal`，并按回车
4. 执行`sudo make install`
