### ISSUE TITLE
微信2.3.24用不了了

### ISSUE THREAD

**Issue by aiyuchen** [Sunnyyoung/WeChatTweak-macOS#133]
<img width="550" alt="企业微信截图_5dc065d1-d6e2-44c5-97a4-4e53e10ee1d7" src="https://user-images.githubusercontent.com/578141/54502935-03c24300-4968-11e9-8424-11dc097d710b.png">

**Comment by klaek** [comment]
Hi same here?
 i'm on MacOS 10.13.6 using WeChat 2.3.24.
The helper menu won't appear after i do make install. tried reinstalling, not working.
![image](https://user-images.githubusercontent.com/23697039/55679530-9f2f4e00-593f-11e9-9f07-f017c038023a.png)
any advice or is there anything wrong?

**Comment by cha0ran** [comment]
mark，同失效，待更新。

**Comment by cha0ran** [comment]
@Sunnyyoung 免认证登录似乎不是很稳定，之前报失效是因为一直卡在登录界面，也刷新不出二维码，刚又测试卡登录框大概1～2秒左右。难道是腾讯服务器问题？

**Comment by FantasticSkyBaby** [comment]
@Sunnyyoung 最新App Store版本没办法多开

**Comment by yshtcn** [comment]
更新后确实无法使用了，app store版本2.3.24（12246）

**Comment by libingtong** [comment]
> @cha0ran @klaek @aiyuchen
> 
> 工作正常喔，麻烦各位更新 App Store 最新版本微信客户端，并重新执行 `sudo make install`
> ![image](https://user-images.githubusercontent.com/5926284/55884700-17657000-5bdb-11e9-986a-d827952f1ddc.png)
> ![image](https://user-images.githubusercontent.com/5926284/55884713-1b918d80-5bdb-11e9-86b4-af904d965903.png)
> ![image](https://user-images.githubusercontent.com/5926284/55884760-382dc580-5bdb-11e9-9b00-513d025c9d0f.png)

多开功能失效。

**Comment by fzsimlu** [comment]
同样，多开功能失效，期待更新
