### ISSUE TITLE
确认在最新微信2.3.24中多开失效

### ISSUE THREAD

**Issue by bylucky** [Sunnyyoung/WeChatTweak-macOS#134]
重新安装也是无法开启登录窗口

**Comment by bylucky** [comment]
期待更新

**Comment by xixiruo** [comment]
期待更新

**Comment by imruxin** [comment]
更新到这个版本后，退出微信，然后重新 sudo make install，无法多开，然后防撤回无效（但有记录已拦截，不过内容却没了）。

**Comment by fzsimlu** [comment]
期待更新

**Comment by idoall** [comment]
期待更新

**Comment by libingtong** [comment]
> 重新安装也是无法开启登录窗口

微信修改了检查应用进程的方法，我是直接硬改了微信来破解的。

**Comment by libingtong** [comment]
> 重新安装也是无法开启登录窗口

可以用010 Editor打开微信的执行文件，找到AADF902，把83 FD 02 的02改成更大的数字，比如08，就同时允许8个客户端，改成FF就是255个客户端。修改完之后直接覆盖源文件，重新sudo make install就行了。

**Comment by mritd** [comment]
@libingtong 我尝试在 MacOS/WeChat 二进制下查找 AADF902，但是并没有找到 😌

**Comment by libingtong** [comment]
@mritd 
AADF902是文件便宜地址，是在这个地址上的。83 FD 02是这地址的内容。

**Comment by mritd** [comment]
@libingtong 感谢，已成功

**Comment by hanagm** [comment]
希望成功的可以附带一下修改后的文件地址，直接覆盖是否可以...有很多人可能并不会修改。。。比如我

**Comment by mritd** [comment]
Finder 导航到 应用程序 目录，右键微信，选择 显示包内容，Copy `Contents/MacOS/WeChat` 到任意位置，编辑并修改，然后再拖回去(提前备份原文件)

**Comment by stewedliver** [comment]
@libingtong 萌新感蟹大佬！

**Comment by idoall** [comment]
@libingtong 感谢，问题解决了

**Comment by zhouwd** [comment]
地址可能不大一样，我是用 010 Editor 搜索的 `83 FD 02 72 71`  然后修改02  为 08 。最后成功了。感谢大佬！

**Comment by Sunnyyoung** [comment]
@libingtong 感谢

@zhouwd 
@idoall 
@stewedliver 
@mritd 
@hanagm 
@fzsimlu 
@imruxin 
@bylucky 

778990ac2c91c8259aad0160393e930f993b34a6 已经修复

**Comment by cnfjice** [comment]
微信已经更新到2.3.26.17了，希望作者可以更新下插件喔。。。
