### ISSUE TITLE
双开微信时，点击第二个登录的微信时，总会自动弹出第一个登录的微信的窗口。

### ISSUE THREAD

**Issue by libingtong** [Sunnyyoung/WeChatTweak-macOS#135]
双开微信时，如果第二个微信收到新消息，点击第二个微信的通知消息时，总会自动弹出第一个登录的微信的窗口。

**Comment by libingtong** [comment]
这应该属于新增功能了，毕竟微信只支持单窗口，所有默认激活单窗口也是合理的，修改的话可能也比较麻烦。

**Comment by winterant** [comment]
这个问题现在好解决嘛？点通知横幅，总是会跳到另一个微信
