### ISSUE TITLE
怎么完全卸载？

### ISSUE THREAD

**Issue by HeHongling** [Sunnyyoung/WeChatTweak-macOS#136]
问题：怎么能强制卸载这个插件，跟幽灵似的卸载不掉  
现象：每次截图，~/Documents 文件下都会生成 `JietuSDKStat.plist` 文件和 `MMappedKV` 文件夹  
步骤：
1.   
  ```
  sudo make uninstall
  ```
  提示 Can not find the WeChat backup file.  

2. 
  ```
  sudo make install
  sudo make uninstall
  ```
  提示 Uninstall successfully，但是现象依然存在

3. 用 App Uninstaller 完全卸载微信，并重启电脑，现象还是存在

**Comment by libingtong** [comment]
因为你的备份文件被删掉了，install时会把WeChat改为WeChat.bak，卸载就是把备份文件重命名回去。

**Comment by HeHongling** [comment]
> 因为你的备份文件被删掉了，install时会把WeChat改为WeChat.bak，卸载就是把备份文件重命名回去。

如果是这样的话，install + uninstall 应该可以解决这个问题的，但是目前发现并没有~

**Comment by Sunnyyoung** [comment]
@HeHongling 用的最新版本吗？我没有出现过上述情况

**Comment by HeHongling** [comment]
> @HeHongling 用的最新版本吗？我没有出现过上述情况

不是最新版，之前安装过一次老版本，但是不太适合我的需求，没多久就卸载了，所以也不记得是哪个版本了。
但是之后 `~/Documents` 一直出现 `MMappedKV`，查了下可能和这个插件相关，所以想确认下是否你的这个插件导致的。
p.s. Google 搜索 `MMappedKV` 能看到其他一些用户也出现 `MMappedKV` 删不掉的情况。

**Comment by Sunnyyoung** [comment]
@HeHongling 删除了也会出现吗？以前会有，现在插件做了处理，正常情况不会出现上述文件

**Comment by HeHongling** [comment]
> @HeHongling 删除了也会出现吗？以前会有，现在插件做了处理，正常情况不会出现上述文件

会出现，删除后，每次使用**微信截图**功能就会在 `~/Documents`目录下新建 `MMappedKV` 文件夹和 `JietuSDKStat.plist` 文件，不过不确定是否插件导致的

**Comment by HeHongling** [comment]
是另外一个微信插件导致的，和本插件无关，不好意思打扰了。。。
