### ISSUE TITLE
cannot read/load local chat history 

### ISSUE THREAD

**Issue by Chen-tao** [Sunnyyoung/WeChatTweak-macOS#14]
as you see .

**Comment by Sunnyyoung** [comment]
Run command `cp -R ~/Library/Containers/com.tencent.xinWeChat/Data/Library/Application\ Support/com.tencent.xinWeChat ~/Library/Application\ Support/com.tencent.xinWeChat` to migrate.

**Comment by Chen-tao** [comment]
It works. Thanks ~ _Maybe can add this to QA or wiki in the future._
