### ISSUE TITLE
现在的双开功能不能用了吗？

### ISSUE THREAD

**Issue by cn-panda** [Sunnyyoung/WeChatTweak-macOS#140]
选择登陆新账号后
![image](https://user-images.githubusercontent.com/29268708/57513916-ee530f00-7341-11e9-8da2-4c560e662b6e.png)
在最近使用栏目 只有图标显示
但是没第二个登陆账号窗口弹出

我的系统是
![image](https://user-images.githubusercontent.com/29268708/57514036-29edd900-7342-11e9-85ed-66a5dc1bb23c.png)

**Comment by YeziGZ** [comment]
我也遇到了类似问题，点击登录新微信，程序坞闪动了一下，没有弹出新的登录窗口。

**Comment by Sunnyyoung** [comment]
可以的啊，麻烦检查下是否已安装最新的插件

**Comment by yang0262** [comment]
多开是否不能用同一部手机以切换账号的方式？

**Comment by Sunnyyoung** [comment]
@yang0262 暂时不能
