### ISSUE TITLE
可以像微信小助手一样  设置一个屏蔽微信更新的功能吗

### ISSUE THREAD

**Issue by Trenttttt** [Sunnyyoung/WeChatTweak-macOS#144]
如题   现在很担心一更新微信就不能用多开了   WeChatPlungin可以屏蔽掉微信的更新提醒    但是多开还是tweak好用  嘻嘻嘻

**Comment by Sunnyyoung** [comment]
用的是 DMG 版本？推荐用 App Store 版本
