### ISSUE TITLE
请问编译失败提示这个错误该怎么解决？

### ISSUE THREAD

**Issue by agcai** [Sunnyyoung/WeChatTweak-macOS#145]
请问编译失败提示这个错误该怎么解决？

Showing Recent Messages
:-1: /Users/andy/Downloads/WeChatTweak-macOS-master/Pods/Target Support Files/Pods-WeChatTweak/Pods-WeChatTweak.debug.xcconfig: unable to open file (in target "WeChatTweak" in project "WeChatTweak") (in target 'WeChatTweak')

**Comment by Sunnyyoung** [comment]
应该是要打开 workspace 文件吧
