### ISSUE TITLE
Version. 2.3.25 (12481)构建失败

### ISSUE THREAD

**Issue by mqliutie** [Sunnyyoung/WeChatTweak-macOS#146]
刚更新了微信, sudo make install 后登录微信没有tweak了

**Comment by Sunnyyoung** [comment]
@mqliutie 确认以下是否安装成功了

**Comment by mqliutie** [comment]
提示是成功的 但是和正常不一样 这次就输出一行

我去应用程序修改了下微信名然后没改成功,回来就成功了...也不知道咋回事,先关了 以后反正不乱升级微信了. 总弹升级很烦
