### ISSUE TITLE
LaunchBar怎么使用？

### ISSUE THREAD

**Issue by TwTuu** [Sunnyyoung/WeChatTweak-macOS#148]
LaunchBar 要怎么调用wechat？

**Comment by Voleking** [comment]
双击安装 WeChatTweak.lbaction 这个文件就可以了

**Comment by viko16** [comment]
@TwTuu 
![image](https://user-images.githubusercontent.com/5064777/60945935-7c864a00-a31f-11e9-871f-bf3003dd6e28.png)

LaunchBar 内输入 wechattweak (实际上输入前几个字母就能找到)，找到这个自定义 Action，空格后输入关键字搜索即可，回车直接打开对应会话。
