### ISSUE TITLE
在 2.3.26 (12715) 版本中失效了

### ISSUE THREAD

**Issue by tyhunter** [Sunnyyoung/WeChatTweak-macOS#152]
➜  WeChatPlugin-MacOS-master sudo make install
/Applications/WeChat.app/Contents/MacOS/WeChat already exists. Overwrite it? [y/n] y
LC_CODE_SIGNATURE load command found. Remove it? [y/n] y
Added LC_LOAD_DYLIB to /Applications/WeChat.app/Contents/MacOS/WeChat
Install successfully!

但是菜单栏没有出现Tweak，确认应用名称正确

**Comment by Sunnyyoung** [comment]
@tyhunter 有重启客户端吗

**Comment by yljphp** [comment]
遇到了同样问题

**Comment by yulinit** [comment]
拉一下代码  重新sudo make install  一下   然后重启微信   就行了

**Comment by yljphp** [comment]
还是不行的
![image](https://user-images.githubusercontent.com/8953279/63926124-e4ceed80-ca7d-11e9-986b-ab383b983793.png)
