### ISSUE TITLE
可以看到撤回的图片吗

### ISSUE THREAD

**Issue by dsky1990** [Sunnyyoung/WeChatTweak-macOS#153]
![image](https://user-images.githubusercontent.com/1579516/63585056-d2ae0480-c5d0-11e9-94de-04d482edbe1d.png)
现在只能看到提示

**Comment by Sunnyyoung** [comment]
@dsky1990 可以啊，图片就是上面的某一条消息

**Comment by dsky1990** [comment]
@Sunnyyoung 好的，看到了，谢啦
