### ISSUE TITLE
撤回提示疑问

### ISSUE THREAD

**Issue by yueyu2421** [Sunnyyoung/WeChatTweak-macOS#157]
前辈你好，新版本的防撤回插件不能保留原本未撤回的那个聊天气泡内容吗，例如对方撤回图片或者表情以后，新版本提示就成了：XX撤回[图片]。请问能不能修改为以前的

**Comment by yueyu2421** [comment]
那个撤回方法

**Comment by Sunnyyoung** [comment]
气泡就在上面的消息记录，并没有删除的

**Comment by yueyu2421** [comment]
看到啦，感谢前辈您回复，谢谢
