### ISSUE TITLE
本人设计师，想协助绘制 Dark Mode WeChat

### ISSUE THREAD

**Issue by sheephe** [Sunnyyoung/WeChatTweak-macOS#158]
RT

**Comment by Sunnyyoung** [comment]
Dark Mode 研究了下，工作量挺大的，还是等微信自己适配吧

**Comment by sheephe** [comment]
<a href="https://ibb.co/K9jLsm7"><img src="https://i.ibb.co/mHCXySt/Demo.jpg" alt="Demo" border="0"></a>
