### ISSUE TITLE
2.3.26可以装吗

### ISSUE THREAD

**Issue by closernow** [Sunnyyoung/WeChatTweak-macOS#159]
原作者删库了，难民遇到救世主，谢谢sunnyyoung，我不太会安装这个，看了说明文档，还是弄不懂。。。release里面只有源码，我也不知道如何去安装。。。求教育
今天我的安卓版微信无法登陆了，提示要更新到新版才可以登录macos版微信，只要更新了，完了小助手就没了，不过之前小助手版本好像就只有防撤回能用，其他的都失效了。

**Comment by Sunnyyoung** [comment]
可以，Wiki 有教程可以看看

**Comment by Sunnyyoung** [comment]
https://github.com/Sunnyyoung/WeChatTweak-macOS/wiki/%E5%AE%89%E8%A3%85
