### ISSUE TITLE
聊天时出现的bug

### ISSUE THREAD

**Issue by QAQTOT** [Sunnyyoung/WeChatTweak-macOS#161]
![image](https://user-images.githubusercontent.com/18019247/65655065-70bc4100-e04d-11e9-9779-6906181d3381.png)
安装后会定期出现撤回的黄框，发送消息时会当前消息先会变黄再变白

**Comment by Sunnyyoung** [comment]
没遇到过喔，大概多久出现的？或者录制个视频会更好

**Comment by QAQTOT** [comment]
好的稍等

**Comment by QAQTOT** [comment]
[https://github.com/QAQTOT/bug/blob/master/1569469025825539.mp4](url) 视频

**Comment by Sunnyyoung** [comment]
是最新版本的微信吗

**Comment by QAQTOT** [comment]
是的，删了聊天记录也是这样，应该不是聊天记录多的问题

**Comment by QAQTOT** [comment]
又发现一个bug，用久了微信很容易闪退

**Comment by Sunnyyoung** [comment]
好吧我看看

**Comment by QAQTOT** [comment]
辛苦了，大佬

**Comment by SimonLing** [comment]
我也出现了

**Comment by 0u0u0** [comment]
同
