### ISSUE TITLE
微信 2.3.27 (12839) 版本，安装打开微信即闪退

### ISSUE THREAD

**Issue by Dynamicer** [Sunnyyoung/WeChatTweak-macOS#162]
`sudo make install` 以后重新打开微信就报错了，具体内容如下：
Process:               WeChat [500]
Path:                  /Applications/WeChat.app/Contents/MacOS/WeChat
Identifier:            com.tencent.xinWeChat
Version:               2.3.27 (12839)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           WeChat [500]
User ID:               501

Date/Time:             2019-09-26 13:48:13.029 +0800
OS Version:            Mac OS X 10.14.6 (18G95)
Report Version:        12
Anonymous UUID:        9141F1AE-4039-1D18-DA4C-4B16033E3DF6

Time Awake Since Boot: 61 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @executable_path/WeChatTweak.framework/WeChatTweak
  Referenced from: /Applications/WeChat.app/Contents/MacOS/WeChat
  Reason: no suitable image found.  Did find:
	/Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework/WeChatTweak: stat() failed with errno=13
	/Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework/WeChatTweak: stat() failed with errno=13

Binary Images:
       0x10d94a000 -        0x10fd1bfff +com.tencent.xinWeChat (2.3.27 - 12839) <F51F6469-8FB6-3D3A-9F9C-4ADB0A3D55E6> /Applications/WeChat.app/Contents/MacOS/WeChat
       0x1107a4000 -        0x1107f4ff7 +org.sparkle-project.Sparkle (1.21.2 2-g1f87bcbe - 1.21.2) <0732575A-E826-36FE-ACB9-F190D52A117C> /Applications/WeChat.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle
       0x11084a000 -        0x110996ff7 +com.tencent.WCDB (1.0.3 - 1) <9BE05138-9FD2-393B-A56E-0EC1DB983090> /Applications/WeChat.app/Contents/Frameworks/WCDB.framework/Versions/A/WCDB
       0x110a34000 -        0x110b17fff +com.Tencent.JietuFramework (1.0.0 - 10021) <7EE9E4A3-25F4-3A61-9F12-F2812475820B> /Applications/WeChat.app/Contents/Frameworks/JietuFramework.framework/Versions/A/JietuFramework
       0x110ba5000 -        0x110babff7 +com.tencent.MMLibHooks (1.0 - 1) <F3D1B3FD-EA42-3409-9418-052A4A7D9718> /Applications/WeChat.app/Contents/Frameworks/MMLibHooks.framework/Versions/A/MMLibHooks
       0x110bc0000 -        0x110be2ff7 +com.deusty.CocoaLumberjack (2.3.0 - 1) <6BDB40E8-05DA-32DE-8C81-37632C48E80B> /Applications/WeChat.app/Contents/Frameworks/CocoaLumberjack.framework/Versions/A/CocoaLumberjack
       0x110c09000 -        0x110c2bffb +com.alamofire.AFNetworking (3.0.0 - 3.1.0) <BDD10371-3F15-3EF9-A0A7-E80EAC53ADF6> /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking
       0x110c50000 -        0x110cf0fff +tencent.matrixreport (1.0 - 1) <2586BD60-1797-3862-B461-CA38A7E71FAA> /Applications/WeChat.app/Contents/Frameworks/matrixreport.framework/Versions/A/matrixreport
       0x117a64000 -        0x117ace70f  dyld (655.1.1) <DFC3C4AF-6F97-3B34-B18D-7DCB23F2A83A> /usr/lib/dyld
    0x7fff3a6a9000 -     0x7fff3a885ffb  com.apple.avfoundation (2.0 - 1550.4) <5854207B-6106-3DA4-80B6-36C42D042F26> /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
    0x7fff3a94d000 -     0x7fff3aa52fff  com.apple.AVKit (1.1 - 446.50.101) <56AD537F-0BA5-360D-8B83-D5BB16A1BF4E> /System/Library/Frameworks/AVKit.framework/Versions/A/AVKit
    0x7fff3bc87000 -     0x7fff3ca3cffb  com.apple.AppKit (6.9 - 1671.60.107) <2F7E5984-E89A-3451-A3DF-FAAA509CF884> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff3cf71000 -     0x7fff3d1e8ff7  com.apple.audio.toolbox.AudioToolbox (1.14 - 1.14) <04F482F1-E1C1-3955-8A6C-8AA152AA06F3> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fff3d1ea000 -     0x7fff3d1eafff  com.apple.audio.units.AudioUnit (1.14 - 1.14) <ABC54269-002D-310D-9654-46CF960F863E> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
    0x7fff3d543000 -     0x7fff3d8e4fff  com.apple.CFNetwork (978.0.7 - 978.0.7) <B2133D0D-1399-3F17-80F0-313E3A241C89> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7fff3d8f9000 -     0x7fff3d8f9fff  com.apple.Carbon (158 - 158) <56AD06AA-7BB4-3F0B-AEF7-9768D0BC1C98> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff3ddfb000 -     0x7fff3ddfbfff  com.apple.Cocoa (6.11 - 23) <8D092DD2-0CA4-34C9-872C-8BBFAE1995A4> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff3e670000 -     0x7fff3eab4fe7  com.apple.CoreFoundation (6.9 - 1575.19) <B2850F42-CE01-3156-B121-FD4777290C8F> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff3eab6000 -     0x7fff3f145fff  com.apple.CoreGraphics (2.0 - 1265.9) <BC95B558-EF77-3A57-A0BC-11606C778991> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
    0x7fff3f468000 -     0x7fff3f4e0fff  com.apple.corelocation (2245.16.14) <0F59F59B-AC14-3116-83C5-CF7BC57D9EB1> /System/Library/Frameworks/CoreLocation.framework/Versions/A/CoreLocation
    0x7fff3f764000 -     0x7fff3f868fff  com.apple.CoreMedia (1.0 - 2290.13) <A739B93D-23C2-3A34-8D61-6AC924B9634F> /System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia
    0x7fff3f8c5000 -     0x7fff3f8c5fff  com.apple.CoreServices (946 - 946) <6EC9F377-EBD8-3358-92D1-6586F6F1E8E9> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff4029d000 -     0x7fff403ffff3  com.apple.CoreText (352.0 - 584.26.3.2) <59919B0C-CBD5-3877-8D6F-D6048F1E5F42> /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText
    0x7fff40400000 -     0x7fff40440ff3  com.apple.CoreVideo (1.8 - 281.4) <10CF8E52-07E3-382B-8091-2CEEEFFA69B4> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
    0x7fff40441000 -     0x7fff404d0fff  com.apple.framework.CoreWLAN (13.0 - 1375.2) <BF4B29F7-FBC8-3299-98E8-C3F8C04B7C92> /System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLAN
    0x7fff408f2000 -     0x7fff40c9fffb  com.apple.Foundation (6.9 - 1575.19) <A85BF812-B784-36B9-89BB-E29772B0708C> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff40faa000 -     0x7fff41039fff  com.apple.framework.IOKit (2.0.2 - 1483.260.4) <8A90F547-86EF-3DFB-92FE-0E2C0376DD84> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff4109e000 -     0x7fff41229fef  com.apple.ImageIO.framework (3.3.0 - 1850.2) <75E46A31-D87D-35CE-86A4-96A50971FDB2> /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
    0x7fff41966000 -     0x7fff427c6fff  com.apple.JavaScriptCore (14607 - 14607.3.9) <9B7D9E8B-619D-34A1-8FA9-E23C0EA3CD02> /System/Library/Frameworks/JavaScriptCore.framework/Versions/A/JavaScriptCore
    0x7fff44263000 -     0x7fff442acff7  com.apple.MultipeerConnectivity (155.2 - 155.2) <4624CB7E-98C6-357C-A3BB-1819C38EABBC> /System/Library/Frameworks/MultipeerConnectivity.framework/Versions/A/MultipeerConnectivity
    0x7fff48300000 -     0x7fff4830fffb  com.apple.opengl (17.7.3 - 17.7.3) <94B5CF34-5BD6-3652-9A8C-E9C56E0A9FB4> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff49111000 -     0x7fff49111fff  com.apple.quartzframework (1.5 - 23) <31783652-5E36-3773-8847-9FECFE2487F0> /System/Library/Frameworks/Quartz.framework/Versions/A/Quartz
    0x7fff49112000 -     0x7fff49369ff7  com.apple.QuartzCore (1.11 - 701.14) <33E846BE-1794-3186-9BF2-6ADF62C782A3> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff4936a000 -     0x7fff493c1fff  com.apple.QuickLookFramework (5.0 - 775.6) <CB74C63F-E223-3783-9021-8E28091BCDA6> /System/Library/Frameworks/QuickLook.framework/Versions/A/QuickLook
    0x7fff49b9f000 -     0x7fff49e9ffff  com.apple.security (7.0 - 58286.270.3.0.1) <DF7677A7-9765-3B6A-9D1C-3589145E4B65> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff4a2fb000 -     0x7fff4a368fff  com.apple.SystemConfiguration (1.17 - 1.17) <30C8327F-3EFF-3520-9C50-016F8B6B954F> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff4a5c7000 -     0x7fff4a928fff  com.apple.VideoToolbox (1.0 - 2290.13) <7FCB2FC0-EFB8-37C2-B0D3-60AE9FDFE230> /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox
    0x7fff4cd83000 -     0x7fff4d2d3ff7  com.apple.WebKit (14607 - 14607.3.9) <AE6029DD-0CED-3FEF-92D5-DB8D4F9757F9> /System/Library/Frameworks/WebKit.framework/Versions/A/WebKit
    0x7fff675eb000 -     0x7fff675ecffb  libSystem.B.dylib (1252.250.1) <B1006948-7AD0-3CA9-81E0-833F4DD6BFB4> /usr/lib/libSystem.B.dylib
    0x7fff6782e000 -     0x7fff67881ff7  libc++.1.dylib (400.9.4) <9A60A190-6C34-339F-BB3D-AACE942009A4> /usr/lib/libc++.1.dylib
    0x7fff681ed000 -     0x7fff682ddfff  libiconv.2.dylib (51.200.6) <2047C9B7-3F74-3A95-810D-2ED8F0475A99> /usr/lib/libiconv.2.dylib
    0x7fff682de000 -     0x7fff6853fffb  libicucore.A.dylib (62141.0.1) <A0D63918-76E9-3C1B-B255-46F4C1DA7FE8> /usr/lib/libicucore.A.dylib
    0x7fff68e22000 -     0x7fff695a7fdf  libobjc.A.dylib (756.2) <7C312627-43CB-3234-9324-4DEA92D59F50> /usr/lib/libobjc.A.dylib
    0x7fff6970e000 -     0x7fff69726ffb  libresolv.9.dylib (65.200.2) <893142A5-F153-3437-A22D-407EE542B5C5> /usr/lib/libresolv.9.dylib
    0x7fff69b85000 -     0x7fff69c67ff3  libxml2.2.dylib (32.10) <AA4E1B1F-0FDE-3274-9FA5-75446298D1AC> /usr/lib/libxml2.2.dylib
    0x7fff69c91000 -     0x7fff69ca3ff7  libz.1.dylib (70.200.4) <B048FC1F-058F-3A08-A1FE-81D5308CB3E6> /usr/lib/libz.1.dylib

**Comment by Sunnyyoung** [comment]
`WeChatTweak.framework` 复制失败了，尝试手动将 `WeChatTweak.framework` 复制到 `/Applications/WeChat.app/Contents/MacOS/` 目录下

**Comment by Dynamicer** [comment]
> `WeChatTweak.framework` 复制失败了，尝试手动将 `WeChatTweak.framework` 复制到 `/Applications/WeChat.app/Contents/MacOS/` 目录下

看了一下， `WeChatTweak.framework` 是一个 0kb 的空文件，的确是复制失败了，删掉重新复制就解决了，谢谢！
