### ISSUE TITLE
无法唤醒微信

### ISSUE THREAD

**Issue by lowking** [Sunnyyoung/WeChatTweak-macOS#164]
微信在桌面1打开，然后option+space输入“wc 联系人”回车，无法唤醒（无论是最小化，还在前端聚焦都无法唤醒）。
但是切到其他桌面就可以正常唤醒。

**Comment by Sunnyyoung** [comment]
未能复现，录个视频看看？

**Comment by lowking** [comment]
> 未能复现，录个视频看看？

录了个视频，100多M无法上传，我传到我的百度网盘，地址如下：
链接: https://pan.baidu.com/s/1YkUBOxp2mvNFFmXZgHSUzQ 提取码: 926s

**Comment by Sunnyyoung** [comment]
我没有百度……
