### ISSUE TITLE
Catalina出来啦，现在插件失效了，求更新

### ISSUE THREAD

**Issue by Jincong** [Sunnyyoung/WeChatTweak-macOS#166]
RT

**Comment by Sunnyyoung** [comment]
![image](https://user-images.githubusercontent.com/5926284/66531306-dfb19380-eb3d-11e9-9bfa-ef70b3f97dbc.png)
一切正常，是否更新微信后没有重新安装插件

**Comment by Jincong** [comment]
但为什么我这里就不行呢。。。(分别在微信打开和关闭的时候安装，然后重启了微信
<img width="576" alt="Screen Shot 2019-10-11 at 08 49 02" src="https://user-images.githubusercontent.com/18282831/66609127-fc180380-ec03-11e9-9f91-bd9f0de7d4c3.png">

**Comment by yingkong1987** [comment]
<img width="778" alt="image" src="https://user-images.githubusercontent.com/2038099/66730820-87083080-ee86-11e9-8ab4-747eac89df64.png">

**Comment by Sunnyyoung** [comment]
@Jincong 试试卸载了再装

**Comment by Jincong** [comment]
唔，刚刚尝试卸载，发现卸载失败，估计是原来那个zip文件下载下来的时候出问题了，重新下载一次再安装就好了。谢谢啦。
