### ISSUE TITLE
更新了最新的插件，在群里聊天时候各种已撤回的黄色通知

### ISSUE THREAD

**Issue by NavinChen** [Sunnyyoung/WeChatTweak-macOS#167]
如题，我自己发的消息也显示撤回通知……我都没撤回，卸载重新安装插件依然如此

**Comment by NavinChen** [comment]
包括文件助手里也是……无语

**Comment by linsage** [comment]
微信版本 Version. 2.3.27 (12850)
出现上述问题，所有聊天窗口显示撤回框
![image](https://user-images.githubusercontent.com/12984934/66617205-b90b5f80-ec06-11e9-8a74-3d065e18207d.png)

**Comment by NavinChen** [comment]
> 什么版本的微信

Version. 2.3.26 (12718)

**Comment by NavinChen** [comment]
更新了官网最新版本的微信，依然如此，和上面发的图情况一致

**Comment by Dynamicer** [comment]
是的，同样的问题~

**Comment by cnBruceHong** [comment]
Version. 2.3.27 (12850) 一样的问题

**Comment by Sunnyyoung** [comment]
我看看先哦，如果太影响使用，可以先回滚到上一个版本

**Comment by 347154468** [comment]
我这里也是 是回滚微信版本吗

**Comment by 347154468** [comment]
Version. 2.3.27 (12850)

**Comment by Sunnyyoung** [comment]
https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/tag/1.0.7

**Comment by jp3049** [comment]
昨天使用了备份微信聊天记录到电脑的功能，把手机的聊天记录备份到了电脑上，然后出现了这个问题

**Comment by tnbe** [comment]
手机端撤销了一次  就出现这个问题了  每个聊天窗口都有一个  插件卸载重装无效   微信2.3.29

**Comment by Sunnyyoung** [comment]
已更新，大家尝试 https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/tag/1.1.2

**Comment by trulynb** [comment]
bug依然存在   微信Version. 2.3.29 (12948)    助手1.1.3

**Comment by gqbre** [comment]
这两天又出现了... 之前好的

**Comment by Sunnyyoung** [comment]
最新版修复
