### ISSUE TITLE
IOS登录两个微信号之后，在互相切换时，MacOS上面的微信都会自动退出

### ISSUE THREAD

**Issue by whuai** [Sunnyyoung/WeChatTweak-macOS#172]
如题，如果手机使用的是iPhone，想要在两个账号之间切换，而这个切换动作会导致MacOS上面的微信都自动退出，这样还需要重新登录，很不友好，不知道这个问题能不能解决？

并且使用iPhone的时候，很难在Mac上登录两个账号，只能登录一个之后，然后在手机上将手机设置为飞行模式，然后切换，让其切换失败，然后再关闭飞行模式，再去登录，这样才能保证MacOS上面有两个活着的微信登录。

解决方案可能就是把微信的退出消息过滤掉，而微信本身提供了“消息自动同步”的功能，但退出这样的消息，可能还是同步了。

只能说大家都用微信，所以不得不用微信，这样的设计太烂了！！！

**Comment by juzj** [comment]
这个问题能解决吗？我也遇到这样的问题

**Comment by Sunnyyoung** [comment]
手机微信退出登陆肯定会把电脑微信也一起退出的，这个没有好的办法
