### ISSUE TITLE
免验证登录第二天仍需扫码登录

### ISSUE THREAD

**Issue by sean-zhuh** [Sunnyyoung/WeChatTweak-macOS#173]
开启免验证后，试了如下几种
1）手机微信未打开，mac端断网后/重启后能成功免验证登录
2）手机微信打开，mac端断网后/重启后也能成功免验证登录
但第二天在联网之前点了登录按钮再联网就提醒扫码登录

**Comment by sean-zhuh** [comment]
有什么办法不用扫码就能登吗，我只有一个小灵通，给跪了

**Comment by Sunnyyoung** [comment]
暂未复现此问题，如继续有问题请提新 issue。
