### ISSUE TITLE
WeChat Version. 2.3.27 (12862)

### ISSUE THREAD

**Issue by KerwinCheung** [Sunnyyoung/WeChatTweak-macOS#178]
WeChat Version. 2.3.27 (12862) is invalid

**Comment by MarcSteven** [comment]
App Version: Version 2.3.27 (12853)
Verbose: v2.3.27.16 (0x12031b10)
System: OSX 10.15 build(19A602)
Model: MacBookPro11,1
Hash: c1f7ae5c3b
Build Date: Oct 10 2019
Build Time: 16:43:33
Lang: en-CN
It's also invalid.

**Comment by nimengbo** [comment]
+1

**Comment by Sunnyyoung** [comment]
Try https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/tag/1.1.2
