### ISSUE TITLE
sudo make install报错

### ISSUE THREAD

**Issue by 1282772905** [Sunnyyoung/WeChatTweak-macOS#179]
`xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun`

报错信息如上

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo参与者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA

**Comment by KerwinCheung** [comment]
> CommandLineTools
你只要重新安装commandLineTools就可以了 。。。。。这不是项目问题

**Comment by 1282772905** [comment]
好的，已经安装好了，谢谢😄
