### ISSUE TITLE
KeyBinding会失效

### ISSUE THREAD

**Issue by Carlis-cpu** [Sunnyyoung/WeChatTweak-macOS#180]
其实是很好用的插件，无奈装了之后会令系统的Keybindingdict行为完全失效，对于我们这种打字离不开 Home 和 End 键的人来说，太灾难了
只好无奈卸载

**Comment by Sunnyyoung** [comment]
具体什么表现呢？

**Comment by Carlis-cpu** [comment]
我会在 ~/Library/KeyBindings/DefaultKeyBinding.dict 里把这两个键的行为设成
{
  "\UF729"  = moveToBeginningOfParagraph:; // home
  "\UF72B"  = moveToEndOfParagraph:; // end
}
但是 WeChat 一旦装上这个插件之后，这两个键会失效

**Comment by Sunnyyoung** [comment]
新版微信还存在这个问题吗
