### ISSUE TITLE
安装的时候提示 make: *** No rule to make target `install'. Stop.

### ISSUE THREAD

**Issue by andyzu** [Sunnyyoung/WeChatTweak-macOS#187]
andyzu@hfhtMacBook-Pro  ~/Desktop  sudo make install
Password:
make: *** No rule to make target `install'.  Stop.

密码确定正确！

**Comment by liuzhenweipp** [comment]
M2芯片的 Mac，也是这个问题。1.5 版本的wechattweak-cli也装了。完全磁盘权限、APP 管理、开发者模式都开了。还是卡住了
