### ISSUE TITLE
WeChat Version. 2.3.29 (12934) 最新外测版「浮窗」功能兼容

### ISSUE THREAD

**Issue by KenmuHuang** [Sunnyyoung/WeChatTweak-macOS#189]
WeChat Version. 2.3.29 (12934) 最新外测版，新增了「浮窗」功能，同步了手机的「浮窗」收藏内容。
插件安装后，没有浮窗按钮，能否兼容下这新版。谢谢！
<img width="75" alt="屏幕快照 2019-11-20 22 51 06" src="https://user-images.githubusercontent.com/11454770/69249459-dad60a00-0be8-11ea-8f12-12e132718fdf.png">

**Comment by KenmuHuang** [comment]
新版本撤回功能失效

**Comment by KenmuHuang** [comment]
浮窗消失，原来旧版就存在的兼容问题

**Comment by Sunnyyoung** [comment]
新版微信已修复
