### ISSUE TITLE
自定义 MMappedKV 文件夹位置

### ISSUE THREAD

**Issue by Voleking** [Sunnyyoung/WeChatTweak-macOS#19]
强迫症希望能够自定义 MMappedKV 的位置。Thx

**Comment by oxoxoxox** [comment]
是的 显示在Documents下面感觉好难受 就像Android手机上每个软件都要在根目录下给自己新建一个文件夹一样
规范一点 放在 /User/XXX/Library 下面是最好的
或者以.开头也行 隐藏起来

**Comment by zhenhappy** [comment]
同样有这个需求，我的Document是用icloud同步的，感觉一整天他都再同步，好蛋疼

**Comment by Sunnyyoung** [comment]
@Voleking 
@oxoxoxox 
@zhenhappy 
Fixed 0ae9a88345703b173060e991a80a9d37a4232a35

**Comment by Voleking** [comment]
@Sunnyyoung 现在又会在 Document 下建立 MemoryStat 的文件夹？

**Comment by zhangrunhao** [comment]
@Sunnyyoung 现在在Document下再次出现了MMappedKV文件夹,  应该如何操作, `sudo make install` 应该在哪里执行?
