### ISSUE TITLE
时间被标记为黄色已撤回

### ISSUE THREAD

**Issue by jayzh1010** [Sunnyyoung/WeChatTweak-macOS#191]
![image](https://user-images.githubusercontent.com/3736511/69687549-44c94480-10fe-11ea-9e26-f70eb94f4383.png)
![image](https://user-images.githubusercontent.com/3736511/69687557-4b57bc00-10fe-11ea-9aea-b0e4767d8fad.png)

如图，所有时间点都会被标记为黄色已撤回。

wechatTweak版本：最新1.1.1
wechat版本：Version. 2.3.28 (12864)

**Comment by lvcode** [comment]
同样的问题~
求助@ Sunnyyoung

**Comment by Crazy-dog-egg** [comment]
同样的问题

**Comment by xiaoyigg** [comment]
同样的问题 求助 卸载重装一样的

**Comment by GitHubWuYi** [comment]
同样的问题+1 ，持续很久了。

**Comment by Sunnyyoung** [comment]
Fixed https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/tag/1.1.2
