### ISSUE TITLE
撤回功能无法使用

### ISSUE THREAD

**Issue by fynmm** [Sunnyyoung/WeChatTweak-macOS#192]
无法防撤回，还有免登录之后历史聊天记录没了
微信：2.3.29（12948）
免登录功能没问题
![image](https://user-images.githubusercontent.com/16110189/69934697-a67a1c00-150d-11ea-9f28-9830c9b8268b.png)

**Comment by 0xJacky** [comment]
+1

**Comment by guo519300884** [comment]
+1

**Comment by YarnYang** [comment]
+1

**Comment by yueryueryueryuer** [comment]
+1

**Comment by yuhuazhu** [comment]
+1

**Comment by Jeferry** [comment]
+1

**Comment by Kenmmm** [comment]
+1

**Comment by CoderZyc** [comment]
+1

**Comment by lvster-zz** [comment]
微信自动升级了个版本，撤回功能失效了。

设备类型：MacBookPro14,2
系统版本：版本 10.14.6（版号 18G1012）
系统语言：zh-Hans
微信版本：[2019-12-11 20:48:11] v2.3.29.16 (13326) #9e516ffe7e
微信语言：zh-Hans
历史版本：[2019-10-23 21:18:59] v2.3.28.16 (12864) #e15d5bcf0
网络状态：Reachable via WiFi
显  示  器：*(1440x900)/Retina

**Comment by Sunnyyoung** [comment]
Fixed https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/tag/1.1.2
