### ISSUE TITLE
10.15 安装报错

### ISSUE THREAD

**Issue by ousui** [Sunnyyoung/WeChatTweak-macOS#195]
wechat: Version. 2.3.29 (13326) 
macos: 10.15.1 (19B88)
```
xcode-select: error: malformed developer path ("/Library/Developer/CommandLineTools")
```

**Comment by Sunnyyoung** [comment]
试试执行 `sudo xcode-select -r`

**Comment by ousui** [comment]
> 试试执行 `sudo xcode-select -r`

不行呐，默认目录就是报错的目录

```
> sudo xcode-select -p
/Library/Developer/CommandLineTools
```

找到原因了，应该是升级系统以后，command line tools 不知道为何没啦，需要重新安装。
正在重新安装。
