### ISSUE TITLE
作者你好！！！

### ISSUE THREAD

**Issue by TERPIXXX** [Sunnyyoung/WeChatTweak-macOS#199]
请问如何在mac上安装呢！！？感谢十分！！（来自电脑小白最诚挚的询问）

**Comment by MuyePeikon** [comment]
https://github.com/Sunnyyoung/WeChatTweak-macOS/wiki/%E5%AE%89%E8%A3%85

**Comment by TERPIXXX** [comment]
> https://github.com/Sunnyyoung/WeChatTweak-macOS/wiki/%E5%AE%89%E8%A3%85


谢谢谢谢！！！_

**Comment by TERPIXXX** [comment]
但为什么cloned完了以后sudo make install没有反应...!?求解！

**Comment by JeasonL** [comment]
terminal上面怎么显示？
