### ISSUE TITLE
能不能有个稍微详细一点的教程

### ISSUE THREAD

**Issue by ibear1213** [Sunnyyoung/WeChatTweak-macOS#2]
能不能有个稍微详细一点的教程，不懂开发的小白研究半天没找到怎么才能用，谢谢了！

**Comment by paullkim** [comment]
为了微信多账号登录找到了此代码，但作为小白，弄了好几个小时也没搞清楚如何在MscOS安装使用，可否提供相关教程，感谢！

**Comment by Sunnyyoung** [comment]
@ibear1213 @paullkim 

1. 下载项目到任意地方
2. 打开 `Terminal.app`
3. 执行 `cd 项目所在路径`
4. 执行 `sudo make install`
5. 提示 `success` 则成功

**Comment by paullkim** [comment]
你好，执行 sudo make install 之后会出现以下报错：

xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

请问，该如何解决？

**Comment by Sunnyyoung** [comment]
@paullkim 执行 `xcode-select --install` 试试看

**Comment by ibear1213** [comment]
谢谢 已解决！

**Comment by paullkim** [comment]
已解决问题，的确是没有安装 xcode 的问题，感谢！
