### ISSUE TITLE
安装以后聊天记录没有了

### ISSUE THREAD

**Issue by backwind1233** [Sunnyyoung/WeChatTweak-macOS#20]
哭啊，安装以后聊天记录没有了

**Comment by Sunnyyoung** [comment]
@backwind1233 https://github.com/Sunnyyoung/WeChatTweak-macOS/wiki/%E5%AE%89%E8%A3%85#%E8%81%8A%E5%A4%A9%E8%AE%B0%E5%BD%95%E8%BF%81%E7%A7%BB
