### ISSUE TITLE
安装后打开微信：“WeChat”因为出现问题而无法打开。

### ISSUE THREAD

**Issue by haiiv** [Sunnyyoung/WeChatTweak-macOS#201]
进程报这样的错误，安装后微信打不开，有老师帮看看吗？
/Applications/WeChat.app/Contents/MacOS/WeChat ; exit;
bogon:~ you$ /Applications/WeChat.app/Contents/MacOS/WeChat ; exit;
dyld: Library not loaded: @executable_path/WeChatTweak.framework/WeChatTweak
  Referenced from: /Applications/WeChat.app/Contents/MacOS/WeChat
  Reason: no suitable image found.  Did find:
	/Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework/WeChatTweak: file too short
	/Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework/WeChatTweak: stat() failed with errno=1
	/Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework/WeChatTweak: file too short
	/Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework/WeChatTweak: stat() failed with errno=1
Abort trap: 6
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[进程已完成]

**Comment by Sunnyyoung** [comment]
没有安装成功，尝试把 framework 文件复制到 WeChat 相同目录下吧

**Comment by haiiv** [comment]
> 没有安装成功，尝试把 framework 文件复制到 WeChat 相同目录下吧

安装时显示安装成功了，谢谢老师回复，小白有点没太弄明白
安装后，微信包里的MacOS目录里已经产生了WeChatTweak.framework，
**请问Alfred workflow及依赖JRSwizzle、insert_dylib是必须的吗**？这三个我都没装，是不是这个原因呢
谢谢老师开发了程序，还给别人解决问题！
下面是我安装时候的输出内容。
```
bogon:WeChatTweak-macOS-1.1.3 you$ sudo make install
/Applications/WeChat.app/Contents/MacOS/WeChat already exists. Overwrite it? [y/n] y
LC_CODE_SIGNATURE load command found. Remove it? [y/n] y
Added LC_LOAD_DYLIB to /Applications/WeChat.app/Contents/MacOS/WeChat
Install successfully!
```

**Comment by Sunnyyoung** [comment]
`Alfred workflow` 是配合 Alfred 使用的，如果没有需求可以不管
`JRSwizzle` 是代码上的依赖，用户无需关心
`insert_dylib` 是安装过程需要用到的工具

安装完目录下有 framework 文件就行了
