### ISSUE TITLE
1.1.3版本的插件bug

### ISSUE THREAD

**Issue by QAQTOT** [Sunnyyoung/WeChatTweak-macOS#204]
1.1.3版本插件用过以后，又会出现原来把时间标记上已撤回的问题

**Comment by QAQTOT** [comment]
![image](https://user-images.githubusercontent.com/18019247/71658547-724d8180-2d7f-11ea-9b86-f0f77b2d9cf5.png)

**Comment by googooog** [comment]
+1

**Comment by DDDLeo** [comment]
+1

**Comment by Sunnyyoung** [comment]
最新版 RC 已修复，如有问题请提新 issue。
