### ISSUE TITLE
撤回样式问题

### ISSUE THREAD

**Issue by mqliutie** [Sunnyyoung/WeChatTweak-macOS#208]
我用的遮罩样式,  前段事件一直没问题, 昨天开始出现问题, 消息乱串, 普通对话框很多撤回...

![image](https://user-images.githubusercontent.com/11795518/72308636-d47b8000-36b7-11ea-805b-ecdb3fc6a50c.png)

**Comment by poison501** [comment]
尝试卸载，拉取最新版本，重新安装，

**Comment by mqliutie** [comment]
@poison501  重新安装无效,  我卸载了微信, 重新安装微信, 有重新跑脚本后目前没什么问题了

**Comment by DDDLeo** [comment]
> @poison501 重新安装无效, 我卸载了微信, 重新安装微信, 又重新跑脚本后目前没什么问题了
> 
> 希望作者能说明下什么原因导致的, 我们要怎么做能规避这些

微信重装那聊天记录岂不是没了。。。

**Comment by mqliutie** [comment]
> > @poison501 重新安装无效，我卸载了微信，重新安装微信，又重新跑脚本后目前没什么问题了
> > 希望作者能说明下什么原因导致的，我们要怎么做能规避这些
> 
> 微信重装那聊天记录岂不是没了。。。

聊天记录我的一直都是没有啊...  只要重新登录一下就没记录 难道你不是么...

**Comment by DDDLeo** [comment]
> > > @poison501 重新安装无效，我卸载了微信，重新安装微信，又重新跑脚本后目前没什么问题了
> > > 希望作者能说明下什么原因导致的，我们要怎么做能规避这些
> > 
> > 
> > 微信重装那聊天记录岂不是没了。。。
> 
> 聊天记录我的一直都是没有啊... 只要重新登录一下就没记录 难道你不是么...

你估计是设置了退出时自动清理···我这必存着，以备不时之需哈哈

**Comment by mqliutie** [comment]
> > > > @poison501 重新安装无效，我卸载了微信，重新安装微信，又重新跑脚本后目前没什么问题了
> > > > 希望作者能说明下什么原因导致的，我们要怎么做能规避这些
> > > 
> > > 
> > > 微信重装那聊天记录岂不是没了。。。
> > 
> > 
> > 聊天记录我的一直都是没有啊... 只要重新登录一下就没记录 难道你不是么...
> 
> 你估计是设置了退出时自动清理・・・我这必存着，以备不时之需哈哈

果然... 消息记录我没勾,  默认应该就是没勾的吧...

**Comment by macahaha** [comment]
出现相同的问题

**Comment by woxiqingxian** [comment]
这个问题有解？我重装之后可以，第二天之后，又是一样的情况。

**Comment by Sunnyyoung** [comment]
请各位尝试 https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/tag/1.2.1-RC2 ，如继续有问题请提新 issue。
