### ISSUE TITLE
截图的时候，会在Documents生成plist

### ISSUE THREAD

**Issue by imagicw** [Sunnyyoung/WeChatTweak-macOS#21]
每次截图都会在Documents生成jietuSDKStat.plist文件。卸载之后就不会生成。

**Comment by imagicw** [comment]
上次忘记附上文件了。

[JietuSDKStat.plist.zip](https://github.com/Sunnyyoung/WeChatTweak-macOS/files/1290649/JietuSDKStat.plist.zip)

**Comment by Sunnyyoung** [comment]
Fixed 0ae9a88345703b173060e991a80a9d37a4232a35
