### ISSUE TITLE
撤回不生效，新版本会阻碍打开小程序

### ISSUE THREAD

**Issue by kriscog0114** [Sunnyyoung/WeChatTweak-macOS#210]
1.撤回不生效，测试了一下没有防撤回功能
2.新版本不安装时可以打开小程序，安装后变成打开新账号，tweak会被调用导致无法打开小程序。变成打开新账号了，卸载后可以。

**Comment by kriscog0114** [comment]
之前测试过，可以防撤回，但是不知道什么时候失效了，难道是因为更新的问题？

**Comment by zwo** [comment]
逆向看了下，小程序跟微信使用同样的程序实例，微信的逻辑比较奇葩，判断实例个数大于1就走小程序初始化流程，改起来困难很大，不知道作者有没什么好办法。

**Comment by CookieXie** [comment]
今天微信自动更新了，微信版本Version. 2.3.29 (13326)，我重新下插件装插件都用不了防撤回了。

**Comment by pinklinux** [comment]
Version. 2.4.0 (13774) Beta 145 打开小程序会弹出一个新的微信登录窗口,然后就退出了.

**Comment by cnBruceHong** [comment]
哪来的小程序？？？

**Comment by gqbre** [comment]
> 哪来的小程序？？？

测试版

**Comment by JeasonL** [comment]
#223  beta版登录窗口与小程序冲突问题已修改

**Comment by Nefffi** [comment]
小程序可以打开，防撤回功能选项没了 @WeChat 2.4.0

**Comment by Sunnyyoung** [comment]
新版微信已修复
