### ISSUE TITLE
微信版本更新，防撤回无法使用

### ISSUE THREAD

**Issue by googooog** [Sunnyyoung/WeChatTweak-macOS#214]
Version. 2.3.30 (13329)
新版本防撤回失效
请修复
谢谢

**Comment by chiasa** [comment]
准确的说还可以使用，只是会把时间作为撤回信息做遮照。建议回退上一个微信版本。

**Comment by ucstone** [comment]
能够拦截；
即使没有撤回的消息，自己发出的也会有拦截提示

**Comment by androidcn** [comment]
请问支持 2.4呢？

**Comment by thomashooo** [comment]
按照教程自行琢磨：https://blog.sunnyyoung.net/wei-xin-macos-ke-hu-duan-lan-jie-che-hui-gong-neng-shi-jian/
wechat2.6.1搜：[MessageService DelRevokedMsg:msgData:]

**Comment by thomashooo** [comment]
qq也可以：https://www.jianshu.com/p/7d020777764e

**Comment by thomashooo** [comment]
windows也可以https://www.v2ex.com/t/525542
工具https://x64dbg.com

**Comment by Sunnyyoung** [comment]
最新版已修复，如有问题请提新 issue。
