### ISSUE TITLE
卸载出现 Can not find the WeChat backup file.

### ISSUE THREAD

**Issue by babyhai** [Sunnyyoung/WeChatTweak-macOS#218]
作者 ， 你好 ！
我卸载它时 ， 进入到 WeChatTweak-macOS 目录 ， 执行   sudo make uninstall  出现错误

![image](https://user-images.githubusercontent.com/22759331/77217188-7bb6e080-6b5b-11ea-8040-4dbe9519a087.png)

请问如何卸载？

**Comment by Sunnyyoung** [comment]
你确定安装了吗

**Comment by Sunnyyoung** [comment]
如仍有问题请重新提 issue。
