### ISSUE TITLE
Mac端无法正常打开小程序

### ISSUE THREAD

**Issue by Nefffi** [Sunnyyoung/WeChatTweak-macOS#219]
Mac端打开小程序，会新增一个微信登录窗口，无法打开任何小程序。

**Comment by mqliutie** [comment]
[你收到了一个小程序，请在手机上查看]

为啥我都看不到小程序

**Comment by 0u0u0** [comment]
感觉作者已经放弃适配新版了……现在防撤回好像也不行了

**Comment by mingyuz00** [comment]
最新的mac版本，可以说是内测版本Version. 2.4.1 (14492) Beta 144。这个版本可以显示小程序，但是双开之后，确实会无法调起小程序

**Comment by vwadev** [comment]
mac 微信 Version. 2.4.1 (14491) 无法打开小程序。点击小程序就提示要登录帐号

**Comment by Sunnyyoung** [comment]
新版微信已修复

**Comment by donly** [comment]
mac 最新版本 WX `Version 3.2.0 (19442)` 打不开小程序，提示：`Unable to open`

插件版本 `1.2.2`
