### ISSUE TITLE
拦截撤回时，有时候会被撤回另一条信息。

### ISSUE THREAD

**Issue by loseheaven** [Sunnyyoung/WeChatTweak-macOS#22]
RT，不知道如何表达清楚，就是简单测试防撤回功能的时候，感觉挺正常。但是实际聊天的时候，别人撤回的那条的确是被拦截住了，但是继续聊着聊着就发现，突然另外一条别的消息就消失了，可能是别人的消息，也可能是自己的消息。貌似非必现，有时候对方撤回次数的比较多的容易出现。

**Comment by Sunnyyoung** [comment]
@loseheaven 这个我检查下
