### ISSUE TITLE
安装最新版本，最新消息前面都有会已撤回

### ISSUE THREAD

**Issue by xbdsky** [Sunnyyoung/WeChatTweak-macOS#224]
![2222.png](https://i.loli.net/2020/04/14/7rYgNmK8cvTqaDB.png)

**Comment by zcSkr** [comment]
顶帖

**Comment by MRZHL** [comment]
微信版本 2.3.31?

**Comment by xbdsky** [comment]
> 微信版本 2.3.31?
Yes

**Comment by xbdsky** [comment]
Version. 2.3.31 (13292)

**Comment by zcSkr** [comment]
今天更新的Version. 2.4.1 (14470)也是，从2.3.31开始

**Comment by VNRKDOEA** [comment]
+1

**Comment by jackond** [comment]
同样的问题，每条信息都会有这么一个横幅

**Comment by MRZHL** [comment]
解决了么？

**Comment by zhanzixuan** [comment]
同问

**Comment by Sunnyyoung** [comment]
请各位尝试 https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/tag/1.2.1-RC2 ，如继续有问题请提新 issue。
