### ISSUE TITLE
在其他mac上登录后，需要再次验证

### ISSUE THREAD

**Issue by ztlevi** [Sunnyyoung/WeChatTweak-macOS#23]
在其它mac上登录微信后需要再次验证才能够登录，有办法取消掉这个Feature吗？

**Comment by Sunnyyoung** [comment]
@ztlevi 这么没办法咯，微信服务端的限制，同时这也是由于安全原因才这么做的。

**Comment by ztlevi** [comment]
也是，credentials 应该是切换机子就更新了吧
