### ISSUE TITLE
安装重启后不能登录新的微信

### ISSUE THREAD

**Issue by X-CCS** [Sunnyyoung/WeChatTweak-macOS#230]
你好！这是我的系统
![image](https://user-images.githubusercontent.com/39707537/86887833-c4ef6800-c12b-11ea-80a6-565d909fb5ff.png)
我按照教程安装成功之后，右键没有`登录新账号`的选项
![image](https://user-images.githubusercontent.com/39707537/86888092-35968480-c12c-11ea-9a1e-0300fb1bf0fb.png)
但是微信小助手中显示有。
目前是没法正常的开启多开微信的功能，请问是有什么问题吗？

**Comment by munn** [comment]
我也是，微信2.4.2版本

**Comment by Sunnyyoung** [comment]
尝试下最新版 1.2.0
