### ISSUE TITLE
微信版本2.4.2开启免认证登陆会导致聊天界面空白

### ISSUE THREAD

**Issue by AllenYSL** [Sunnyyoung/WeChatTweak-macOS#231]
开启免认证登陆会导致聊天界面空白。关闭此项后显示正常。
macOS版本10.15.6
微信版本2.4.2

**Comment by whisper0429** [comment]
Yes,it is.

**Comment by stringlii** [comment]
Yes,it is.

**Comment by jymr92** [comment]
Version. 2.4.2 (15067)
是的，100%复现

**Comment by fengbin150215** [comment]
!求助我也遇到了这个问题！！版本号相同

**Comment by Wooge123** [comment]
提供一个微信版本，所有功能正常使用，扫码获取下载地址：

<img src="https://user-images.githubusercontent.com/17154921/88478795-b0113200-cf7d-11ea-854e-52230ad23673.png" width="200px" />

**Comment by alwzying** [comment]
期望作者大大更新

**Comment by iFunbox** [comment]
是滴~

**Comment by LiweiDong** [comment]
求更新 @Sunnyyoung

**Comment by Sunnyyoung** [comment]
可尝试 https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/tag/1.2.1-RC1
