### ISSUE TITLE
现版本的微信防撤回功能是失效了吗？

### ISSUE THREAD

**Issue by Jincong** [Sunnyyoung/WeChatTweak-macOS#234]
现在最新版本的微信，不管是设置为Inherited 还是 all，都没能拦截撤回。已经尝试过重装微信和小助手。

**Comment by mercynoo** [comment]
好像是的。。怀疑微信那边封杀了？

**Comment by nimalhuang** [comment]
seems works for me. WeChat version 2.5.0(15735)

**Comment by Sunnyyoung** [comment]
请各位尝试 https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/tag/1.2.1-RC2 ，如继续有问题请提新 issue。
