### ISSUE TITLE
无法通过快捷键截图

### ISSUE THREAD

**Issue by wshj** [Sunnyyoung/WeChatTweak-macOS#241]
系统：mac 11.0.1；微信：2.5.0；本软件tag：1.1.3
通过快捷键截图时，提示需要勾选屏幕录制权限，但是勾选后无用，重新取消重新勾选依旧不行。重启微信也没用

**Comment by Sunnyyoung** [comment]
测试并无问题

**Comment by Sunnyyoung** [comment]
如继续有问题请提新 issue。
