### ISSUE TITLE
不兼容 apple M1

### ISSUE THREAD

**Issue by calvinyv** [Sunnyyoung/WeChatTweak-macOS#243]
运行make install报错如下：
xcrun: error: unable to load libxcrun (dlopen(/Library/Developer/CommandLineTools/usr/lib/libxcrun.dylib, 0x0005): could not use '/Library/Developer/CommandLineTools/usr/lib/libxcrun.dylib' because it is not a compatible arch).

**Comment by Sunnyyoung** [comment]
执行 `xcode-select --install`
