### ISSUE TITLE
Version. 2.6.1 (16871)

### ISSUE THREAD

**Issue by ZSH-HSZ** [Sunnyyoung/WeChatTweak-macOS#245]
Version. 2.6.1 (16871) 这个版本用不了插件，不限时微信小助手，然后登录之后聊天页面是空白，什么都不显示

**Comment by Sunnyyoung** [comment]
尝试 https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/tag/1.2.1-RC2 ，如继续有问题请提新 issue。
