### ISSUE TITLE
安装完之后打开微信工具栏没有任何东西，不能用了？

### ISSUE THREAD

**Issue by lowking** [Sunnyyoung/WeChatTweak-macOS#247]
![image](https://user-images.githubusercontent.com/33308659/108682692-9643c780-752b-11eb-8263-447e933230f9.png)
![image](https://user-images.githubusercontent.com/33308659/108682795-ba070d80-752b-11eb-9b64-1d53c84fe16f.png)

**Comment by mqliutie** [comment]
建议使用这个  `https://github.com/MustangYM/WeChatExtension-ForMac`
这个项目好像很久没人维护了

**Comment by lowking** [comment]
> 建议使用这个 `https://github.com/MustangYM/WeChatExtension-ForMac`
> 这个项目好像很久没人维护了

谢谢，可以用
