### ISSUE TITLE
3.3.0功能失效

### ISSUE THREAD

**Issue by ccxwhy** [Sunnyyoung/WeChatTweak-macOS#249]
wechat更新之后防撤回生效了

**Comment by Sunnyyoung** [comment]
官网下载的？

**Comment by Sunnyyoung** [comment]
我看到官网最新的是 `3.0.2` 🤔，已经修复 #255 ，你试试

**Comment by ezjason** [comment]
Can not find the framework, please build first
拉取最新的后下载依赖报错了

**Comment by Sunnyyoung** [comment]
@ezjason https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/latest/download/WeChatTweak-macOS.zip
