### ISSUE TITLE
Can not find the framework, please build first.

### ISSUE THREAD

**Issue by James-Lam** [Sunnyyoung/WeChatTweak-macOS#257]
执行`sudo make install` 提示`Can not find the framework, please build first.`

版本：v1.2.0

**Comment by Sunnyyoung** [comment]
下载这个 [Link](https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/latest/download/WeChatTweak-macOS.zip)

**Comment by James-Lam** [comment]
> 下载这个 [Link](https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/latest/download/WeChatTweak-macOS.zip)

响应迅速，感谢！
