### ISSUE TITLE
微信3.0.2失效

### ISSUE THREAD

**Issue by Lukeeeeeeeeee** [Sunnyyoung/WeChatTweak-macOS#259]
<img width="1164" alt="WeChat869ff2231e02d8d67afc5cc440fc5785" src="https://user-images.githubusercontent.com/25240164/117534053-66806800-b022-11eb-898e-177a91ab41d1.png">
看到支持 3.0.2 就更新了，结果发现设置里面没有 Tweak 选项，防撤回失效

**Comment by Sunnyyoung** [comment]
重新安装了吗？

**Comment by Lukeeeeeeeeee** [comment]
> 重新安装了吗？

重新执行 sudo make install，我尝试下重新下载包

**Comment by Lukeeeeeeeeee** [comment]
> 重新安装了吗？

打开微信状态
执行 make install 
![image](https://user-images.githubusercontent.com/25240164/117534612-ce37b280-b024-11eb-8ed9-a6472c07a6ab.png)
然后退出微信，重新执行
<img width="500" alt="WeChat217480a85b1370c848656bea9184dd06" src="https://user-images.githubusercontent.com/25240164/117534653-f9ba9d00-b024-11eb-8c82-5e7e457d9b6d.png">

设置中还是没有 Tweak

执行命令后
![image](https://user-images.githubusercontent.com/25240164/117534712-371f2a80-b025-11eb-91f2-1866f3e55c7f.png)

**Comment by Sunnyyoung** [comment]
安装报错了，感觉是系统隐私设置拦截了 `insert_dylib` 的运行
![image](https://user-images.githubusercontent.com/5926284/117535746-c62e4180-b029-11eb-919e-0ac32aa4760c.png)
到这里看看是否有拦截

**Comment by Lukeeeeeeeeee** [comment]
> 安装报错了，感觉是系统隐私设置拦截了 `insert_dylib` 的运行
> ![image](https://user-images.githubusercontent.com/5926284/117535746-c62e4180-b029-11eb-919e-0ac32aa4760c.png)
> 到这里看看是否有拦截

大佬厉害，是被拦击了，点击了允许后，需要 uninstall 然后重新 install 下就可以了
