### ISSUE TITLE
 微信2.3.2版本 无法防止消息撤回

### ISSUE THREAD

**Issue by x1aolong** [Sunnyyoung/WeChatTweak-macOS#26]
大神你好, 安装了您这个插件后免手机认证登录可以实现, 但是消息防撤回无法实现, 用的自己的账号给自己发送消息然后撤回, 直接显示撤回了. 
操作步骤: 插件我直接down到桌面, 终端进去sudo make install的, 显示successfully.
想问问我这个情况如何解决? 谢谢~

**Comment by Sunnyyoung** [comment]
@x1aolong 自己撤回自己的消息是正常撤回的，只会拦截别人撤回的消息。:-)
