### ISSUE TITLE
更新之后编译报错了

### ISSUE THREAD

**Issue by kaka77** [Sunnyyoung/WeChatTweak-macOS#260]
$ sudo make install
Can not find the framework, please build first.
make: *** [install] Error 1  😭

**Comment by kaka77** [comment]
现在打开微信，二维码一直都加载不出来了，重新下载  微信 dmg 替换打开还是不行，二维码出不来。:(

**Comment by Sunnyyoung** [comment]
通过这里下载 https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/latest/download/WeChatTweak-macOS.zip

二维码加载问题大概率是网络问题

**Comment by shaohongwu** [comment]
Can not find the framework, please build first.
你这是怎么解决的，我也是这个问题

**Comment by kaka77** [comment]
> Can not find the framework, please build first.
> 你这是怎么解决的，我也是这个问题

网络刚好出问题了，直接https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/latest/download/WeChatTweak-macOS.zip  下载试试。

**Comment by kaka77** [comment]
还是要先卸载之前的动态库，再编译新的sudo make install ，不然“撤回提示”显示的位置也有问题。

**Comment by kaka77** [comment]
还是有bug, 没有撤回的消息显示撤回，黄色遮罩没有在消息背后，在空白位置。

**Comment by Sunnyyoung** [comment]
@kaka77 想体验撤回样式的用这个 https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/tag/1.2.1-RC2，还没正式发布
