### ISSUE TITLE
install失败

### ISSUE THREAD

**Issue by Imhemers** [Sunnyyoung/WeChatTweak-macOS#263]
最新mac版本 3.0.3出现如下问题
![image](https://user-images.githubusercontent.com/18650947/117600240-2930ed00-b17e-11eb-86a1-0e0a99244e2f.png)

**Comment by Sunnyyoung** [comment]
https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/latest/download/WeChatTweak-macOS.zip
