### ISSUE TITLE
Mac Version. 3.0.3 (18062) Beta 9 撤回功能不生效

### ISSUE THREAD

**Issue by lllhf** [Sunnyyoung/WeChatTweak-macOS#267]
Mac 最新版本 3.0.3 撤回功能不生效，升级后执行 install 插件，偏好配置可以看到撤回 tweak 设置，但是好友消息撤回没生效..
PS：上个版本 3.0.2 也不行..再之前的版本，就一直提示升级，升级后还是 3.0.0 的那些版本，撤回功能就没问题，从 3.0.2 就不行了 orz

以上，盼大神看看找时间修复~

以上上，插件功能10分好评！点赞！

![image](https://user-images.githubusercontent.com/12790221/117783908-91162f00-b275-11eb-943b-055161a39bcb.png)

![image](https://user-images.githubusercontent.com/12790221/117784364-126dc180-b276-11eb-8741-ad61a1f8443b.png)

![image](https://user-images.githubusercontent.com/12790221/117784408-1dc0ed00-b276-11eb-88bf-9f692fa3ee87.png)

**Comment by Sunnyyoung** [comment]
用 App Store 最新版吧，Beta 版本这些不管了，维护成本高。

**Comment by lllhf** [comment]
刚从 App Store 下了最新的 3.0.3，也是不行..

![image](https://user-images.githubusercontent.com/12790221/117793456-d2f7a300-b27e-11eb-950e-ba6711fe34ed.png)

![image](https://user-images.githubusercontent.com/12790221/117793513-e1de5580-b27e-11eb-93b2-45df2d0d4d28.png)

**Comment by lllhf** [comment]
really sorry.. orz

没看到代码有更新，一直用的都是旧的工程来处理，难怪一直不生效 :( 更新后已经可以了 :)

谢谢你百忙之中还能这么及时回复，再次感谢 Sunny 大神！工具很好用！
