### ISSUE TITLE
安装后没反应

### ISSUE THREAD

**Issue by 502880166** [Sunnyyoung/WeChatTweak-macOS#270]
大佬好，我用的直接食用包安装的，安装后微信没有变化，系统是11.2.3，微信是3.03，请问是什么问题

**Comment by Sunnyyoung** [comment]
确定安装成功了吗？安装成功后需要重启微信。

**Comment by 502880166** [comment]
> 确定安装成功了吗？安装成功后需要重启微信。

显示安装完成，微信电脑都重启了还是没反应

**Comment by Sunnyyoung** [comment]
安装成功的截图有吗

**Comment by 502880166** [comment]
> 安装成功的截图有吗

<img width="570" alt="QQ20210513-222938@2x" src="https://user-images.githubusercontent.com/53418367/118140278-cd46bc80-b43a-11eb-8987-42b0bb27849a.png">

**Comment by Sunnyyoung** [comment]
```bash
cd /Users/zhuxujun/Downloads/WeChatTweak-macOS; sudo make install
```

应该是这样

**Comment by 502880166** [comment]
谢谢。我试试

**Comment by 502880166** [comment]
> ```shell
> sudo make install
> ```

谢谢大佬，可以了，感谢🙏
