### ISSUE TITLE
截图功能缺失

### ISSUE THREAD

**Issue by CoderMrUku** [Sunnyyoung/WeChatTweak-macOS#271]
已经开启了“屏幕录制”权限，但截图时还是提示未开启。多次取消勾选再勾选都不能截图。

**Comment by Sunnyyoung** [comment]
是 Intel 设备还是 ARM 设备呢，我测试正常

**Comment by CoderMrUku** [comment]
arm架构，macOS 11.3.1

**Comment by Sunnyyoung** [comment]
安装完插件后执行：`sudo codesign -f -s - --deep /Applications/WeChat.app` 看看有没有问题

**Comment by QuXiaoMing** [comment]
+1  不能截图
刚升级 macOS 10.15 Big Sur, MBP 2020 16

**Comment by CoderMrUku** [comment]
> +1 不能截图
> 刚升级 macOS 10.15 Big Sur, MBP 2020 16

我卸载重装了微信， 也不能截图

**Comment by hanyufeng0504** [comment]
bigSur 11.3.1 sudo codesign -f -s - --deep /Applications/WeChat.app这个方法不起作用, 微信截屏依然无法使用

**Comment by Sunnyyoung** [comment]
emm，目前看起来没办法

**Comment by henryxie2093** [comment]
用mac自带的问题不大
