### ISSUE TITLE
[Features] 添加拦截自己撤回的消息

### ISSUE THREAD

**Issue by GeorgeBin** [sunnyyoung/WeChatTweak-macOS#274]
可否增加拦截自己撤回的消息？

**Comment by Sunnyyoung** [comment]
为什么要拦截自己撤回的消息？

**Comment by GeorgeBin** [comment]
方便看到自己撤回的具体是什么（以便于在电脑上可以看到完整的聊天历史）
例如自己在手机微信上发送的内容，在手机上撤回后，电脑上的记录想要保存下来，方便看到自己撤回的具体是什么。这样整个聊天历史才是完整的。

备注：可以当做一个额外的功能😁

**Comment by jiangzhibin** [comment]
屏幕录制右边列表里  点减号 把微信去了。然后点加号 再重新加一次。退出重登微信就正常了
