### ISSUE TITLE
wechat.alfredworkflow报错

### ISSUE THREAD

**Issue by haoxuexiaoyao** [Sunnyyoung/WeChatTweak-macOS#28]
你好，原生微信支持这个wechat.alfredworkflow么？我安装之后出现如下错误？
<img width="671" alt="11111" src="https://user-images.githubusercontent.com/4811366/30254806-27e98762-96d0-11e7-8ee0-5edd97c01ec5.png">

**Comment by Sunnyyoung** [comment]
@haoxuexiaoyao 微信原生不支持的，你需要先安装 Tweak，参考 [Wiki](https://github.com/Sunnyyoung/WeChatTweak-macOS/wiki)
