### ISSUE TITLE
你好！ 无法安装

### ISSUE THREAD

**Issue by chendryad** [Sunnyyoung/WeChatTweak-macOS#280]
WeChatTweak-macOS % sudo make install
sh: line 1: 37334 Bus error: 10           /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk '' -find make 2> /dev/null
make: error: unable to find utility "make", not a developer tool or in PATH

**Comment by Sunnyyoung** [comment]
执行 `xcode-select -r` 后再次尝试安装

**Comment by chendryad** [comment]
多谢！！现在终端告诉我安装成功了，但是我打开微信还是没有任何改变

**Comment by Sunnyyoung** [comment]
emm，那你执行 `sudo make uninstall` 之后再 `sudo make install` 重装一下试试看

**Comment by chendryad** [comment]
成了，但是貌似在设置里面才能找到tweak， 我记得以前左上角有选项栏的🙈🙈

**Comment by Sunnyyoung** [comment]
那个应该不是我的
