### ISSUE TITLE
sudo make install Can not find the framework, please build first. Or download the latest release zip: https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/latest.

### ISSUE THREAD

**Issue by yearRomance** [Sunnyyoung/WeChatTweak-macOS#281]
sudo make install
Can not find the framework, please build first.
Or download the latest release zip: https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/latest.

**Comment by Sunnyyoung** [comment]
Did you see `Or download the latest release zip: https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/latest.`?
