### ISSUE TITLE
Neither installation nor uninstallation can be performed

### ISSUE THREAD

**Issue by cuixiaohuan** [Sunnyyoung/WeChatTweak-macOS#283]
![image](https://user-images.githubusercontent.com/16948912/122360367-efc37c80-cf88-11eb-8b5c-375f42ca746a.png)
Neither installation nor uninstallation can be performed. My WeChat version is 3.0.3.

**Comment by cuixiaohuan** [comment]
After I installed it, I updated the WeChat version, and then I could not uninstall it.

how  should i do?

**Comment by Sunnyyoung** [comment]
https://osxdaily.com/2018/10/09/fix-operation-not-permitted-terminal-error-macos/
