### ISSUE TITLE
mac weichat 3.1.3没生效

### ISSUE THREAD

**Issue by GaoZhenguo929** [Sunnyyoung/WeChatTweak-macOS#287]
微信3.1.3更新完，插件不生效了

**Comment by Sunnyyoung** [comment]
![image](https://user-images.githubusercontent.com/5926284/124687115-e3d33680-df06-11eb-87c1-f6a4ff3ad0c6.png)
你是不是没有重新安装一遍

**Comment by GaoZhenguo929** [comment]
![1625631089518](https://user-images.githubusercontent.com/28918326/124699351-3c153300-df1d-11eb-8734-52e30f20345c.jpg)
重新装了，没出来

**Comment by Sunnyyoung** [comment]
抱歉，未能复现，请检查流程是否有问题

**Comment by GaoZhenguo929** [comment]
问题已解决，由于我习惯mac长期不关机，导致没能生效，重新启动mac之后生效了
