### ISSUE TITLE
sudo make install报错

### ISSUE THREAD

**Issue by 47code** [Sunnyyoung/WeChatTweak-macOS#288]
最开始我是git clone到本地，1.2.0时可以使用sudo make install正常安装。

今天更新到最新到5f2481fe1a2670d0e8d31ae889f79b339c41a108，安装时报错如下。

Can not find the framework, please build first.
Or download the latest release zip: https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/latest.
make: *** [install] Error 1

根据提示，我下载WeChatTweak-macOS.zip，解压后再执行上述命令，依然报同样的错误，请问如何解决？谢谢

**Comment by 47code** [comment]
我回退到1.2.0也无法安装了，尴尬

**Comment by Sunnyyoung** [comment]
下载解压之后，有 `cd` 到对应目录？
