### ISSUE TITLE
3.1.1版本被微信安全提醒了

### ISSUE THREAD

**Issue by chance395** [Sunnyyoung/WeChatTweak-macOS#289]
![IMG_0047](https://user-images.githubusercontent.com/19421270/125223416-5163d600-e2fe-11eb-82be-8f5eab87b4ca.PNG)
3.1.1版本被微信安全提醒了

**Comment by Sunnyyoung** [comment]
一直都是只用我这个吗？有没有用过别的

**Comment by tikdoge** [comment]
大概率用过隔壁的那啥，tweak已经用了很久了 没收到过

**Comment by chance395** [comment]
半年前用过别的后面他那个不能用了就没用过了，两个月前开始用你的今天第一次收到提醒，不晓得为啥。后面收到新的提醒再来反馈



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月12日(星期一) 中午12:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Sunnyyoung/WeChatTweak-macOS] 3.1.1版本被微信安全提醒了 (#289)





 
一直都是只用我这个吗？有没有用过别的

**Comment by Sunnyyoung** [comment]
应该是用过别的导致

**Comment by Alienkukuda** [comment]
> 应该是用过别的导致

楼主还没有被警告不，隔壁小助手的我已经被警告了

**Comment by chance395** [comment]
目前就那一次



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月13日(星期二) 下午4:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Sunnyyoung/WeChatTweak-macOS] 3.1.1版本被微信安全提醒了 (#289)





  
应该是用过别的导致
  
楼主还没有被警告不，隔壁小助手的我已经被警告了

**Comment by heshangcode** [comment]
等待这个是否有反馈

**Comment by chance395** [comment]
今天又被提醒了，





------------------ 原始邮件 ------------------
发件人: 和尚 ***@***.***&gt;
发送时间: 2021年7月14日 20:08
收件人: Sunnyyoung/WeChatTweak-macOS ***@***.***&gt;
抄送: leo.li ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[Sunnyyoung/WeChatTweak-macOS] 3.1.1版本被微信安全提醒了 (#289)

**Comment by 349607651** [comment]
你是不是之前的没有卸载干净

**Comment by chance395** [comment]
MACOS系统都是两个月前重装的，最近半年只用过这个哈

**Comment by amaoagoua** [comment]
我用12号中午被风险提示  用隔壁小助手 多开4个号 被风险提示了两个号 ，另外两个号无异常，被提示的两个号均尝试过他的检测僵尸粉功能，另我12号晚上换上此作者的插件到目前为止，未被提示，而隔壁小助手13号又爆发了一下警告提示 。

**Comment by tikdoge** [comment]
被提醒的基本都是用了隔壁或者不该用的功能。Sunnyyoung大大的从一开始用到现在没问题没提醒，只登录了两个微信（原生的本身也支持双开）其他撤回免认证也在用。这个东西不该用的功能就不要去用，本身有些功能就属于那啥，提醒被封的好好找自己原因吧，Sunnyyoung大大的我周围也在用很好，没乱七八糟的功能

**Comment by tikdoge** [comment]
另外不建议在微信3.xx以下使用

**Comment by chance395** [comment]
昨天晚上发现我还用了这个插件
WeChatExtension-ForMac
去看了哈，基本确定是这个的锅。这个issue可以关闭了  不是作者大大的锅
