### ISSUE TITLE
增加一个 聊天置底 的功能？

### ISSUE THREAD

**Issue by Ale-cc** [Sunnyyoung/WeChatTweak-macOS#290]
引用我朋友的话说就是：
其实防撤回也就是个舔头，聊天置底和免认证登录都很实用的。
--
毕竟微信群那么多不可能都退了，
微信官方的【不显示】功能毛用都没有。

**Comment by iszhuzhi** [comment]
聊天置底 的功能 ，真的太好用了

>>>>需求环境：鄙人有些不必要的群又不敢退，但是又偶尔会看看，又不想时刻被打扰，就置顶底

**Comment by iszhuzhi** [comment]
>>操作路径
--微信消息列表个人或者群聊[右键]，增加可选项[置底]
--进行[置底]操作后，消息对话框出现在消息列表的最底

和置顶功能操作

**Comment by seiry** [comment]
小龙知乎内行哈哈哈，用`归档`表达，会更贴切些

**Comment by Sunnyyoung** [comment]
这个暂不考虑了，需求不强

**Comment by cdh1991** [comment]
> 这个暂不考虑了，需求不强

求大佬考虑一下，工作时无关信息太多了
