### ISSUE TITLE
最新3.1.6安裝沒問題吧 小助手會封號

### ISSUE THREAD

**Issue by ClayMoreBoy** [Sunnyyoung/WeChatTweak-macOS#293]
同標題

**Comment by Sunnyyoung** [comment]
最新 App Store 3.1.5 (18851) 版本没问题

**Comment by Ethan0595** [comment]
Version. 3.1.6 (19114) Beta 10  

安全吗

**Comment by CCBrother** [comment]
我是3.1.5 (18851)，运行了，不行啊。。。

**Comment by CCBrother** [comment]
> 最新 App Store 3.1.5 (18851) 版本没问题

微信3.1.5 (18851) 版本，目前安装不了

**Comment by Sunnyyoung** [comment]
@CCBrother 运行了什么，怎么不行了，安装不了什么意思

**Comment by CCBrother** [comment]
> @CCBrother 运行了什么，怎么不行了，安装不了什么意思

我把你的工程下载下来，pod install，编译成功了，然后再cd到项目，cd WeChatTweak-macOS， 再sudo make install，小助手没有安装到微信上

**Comment by Sunnyyoung** [comment]
@ClayMoreBoy @Ethan0595 没有用过其他同类工具的都没问题

**Comment by Sunnyyoung** [comment]
@CCBrother 需要打开 Xcode 项目文件编译

**Comment by ClayMoreBoy** [comment]
可用 缺少框架的 要下載編譯好

**Comment by iszhuzhi** [comment]
保护我方大神，学习了

**Comment by CCBrother** [comment]
> @CCBrother 需要打开 Xcode 项目文件编译
可以用了，但是马上收到微信警告了哈

**Comment by fxdgg** [comment]
所以还是不要随意升级微信版本吧，目前版本3.0.4安全

**Comment by wang0168** [comment]
微信版本 3.1.5 会闪退
