### ISSUE TITLE
想请教如何自行编译

### ISSUE THREAD

**Issue by heshangcode** [Sunnyyoung/WeChatTweak-macOS#294]
下载了源代码，如何进行自行编译然后使用

**Comment by 349607651** [comment]
可以直接用

**Comment by Sunnyyoung** [comment]
如果不知道怎么编译的话那还是下载 https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/download/1.2.1/WeChatTweak-macOS.zip 直接使用吧

**Comment by heshangcode** [comment]
> 如果不知道怎么编译的话那还是下载 https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/download/1.2.1/WeChatTweak-macOS.zip 直接使用吧

其实就是想学习学习一下进行自行编译

**Comment by Sunnyyoung** [comment]
@heshangcode 执行 `pod install` 之后打开 xcworkspace 编译即可
