### ISSUE TITLE
微信检查出了外挂

### ISSUE THREAD

**Issue by panxyush** [Sunnyyoung/WeChatTweak-macOS#295]
你好，微信已经能够检测出你的插件为外挂并且进行提示和警告了。

**Comment by chance395** [comment]
我以前也来提过 结果发现是我同时安装了这个WeChatExtension-ForMac导致的，建议你看哈有没有安装这个插件。上次让作者背锅了  很不好意思

**Comment by Sunnyyoung** [comment]
@panxyush 大概率是使用过别的同类工具导致
