### ISSUE TITLE
执行sudo make install时出现错误

### ISSUE THREAD

**Issue by geekvxyz** [Sunnyyoung/WeChatTweak-macOS#296]
日志如下

xattr: [Errno 9] Bad file descriptor: './WeChatTweak.xcodeproj/xcshareddata/xcschemes'
xattr: [Errno 9] Bad file descriptor: './WeChatTweak.xcodeproj/xcshareddata'
xattr: [Errno 9] Bad file descriptor: './WeChatTweak.xcodeproj'
xattr: [Errno 9] Bad file descriptor: './Screenshot'
xattr: [Errno 9] Bad file descriptor: './.bundle'
xattr: [Errno 9] Bad file descriptor: './WeChatTweak/Category'
xattr: [Errno 9] Bad file descriptor: './WeChatTweak/Resources'
xattr: [Errno 9] Bad file descriptor: './WeChatTweak/Controller/zh-Hans.lproj'
xattr: [Errno 9] Bad file descriptor: './WeChatTweak/Controller/en.lproj'
xattr: [Errno 9] Bad file descriptor: './WeChatTweak/Controller/Base.lproj'
xattr: [Errno 9] Bad file descriptor: './WeChatTweak/Controller/zh-Hant.lproj'
xattr: [Errno 9] Bad file descriptor: './WeChatTweak/Controller'
xattr: [Errno 9] Bad file descriptor: './WeChatTweak/Manager'
xattr: [Errno 9] Bad file descriptor: './WeChatTweak/Supporting Files/zh-Hans.lproj'
xattr: [Errno 9] Bad file descriptor: './WeChatTweak/Supporting Files/en.lproj'
xattr: [Errno 9] Bad file descriptor: './WeChatTweak/Supporting Files/zh-Hant.lproj'
xattr: [Errno 9] Bad file descriptor: './WeChatTweak/Supporting Files'
xattr: [Errno 9] Bad file descriptor: './WeChatTweak/Vendor'
xattr: [Errno 9] Bad file descriptor: './WeChatTweak'
xattr: [Errno 9] Bad file descriptor: './.github'
xattr: [Errno 9] Bad file descriptor: './WeChatTweak.xcworkspace/xcshareddata'
xattr: [Errno 9] Bad file descriptor: './WeChatTweak.xcworkspace'
xattr: [Errno 9] Bad file descriptor: './.git/objects/pack'
xattr: [Errno 9] Bad file descriptor: './.git/objects/info'
xattr: [Errno 9] Bad file descriptor: './.git/objects'
xattr: [Errno 9] Bad file descriptor: './.git/info'
xattr: [Errno 9] Bad file descriptor: './.git/logs/refs/heads'
xattr: [Errno 9] Bad file descriptor: './.git/logs/refs/remotes/origin'
xattr: [Errno 9] Bad file descriptor: './.git/logs/refs/remotes'
xattr: [Errno 9] Bad file descriptor: './.git/logs/refs'
xattr: [Errno 9] Bad file descriptor: './.git/logs'
xattr: [Errno 9] Bad file descriptor: './.git/hooks'
xattr: [Errno 9] Bad file descriptor: './.git/refs/heads'
xattr: [Errno 9] Bad file descriptor: './.git/refs/tags'
xattr: [Errno 9] Bad file descriptor: './.git/refs/remotes/origin'
xattr: [Errno 9] Bad file descriptor: './.git/refs/remotes'
xattr: [Errno 9] Bad file descriptor: './.git/refs'
xattr: [Errno 9] Bad file descriptor: './.git'
xattr: [Errno 9] Bad file descriptor: './WeChatTweak.lbaction/Contents/Resources'
xattr: [Errno 9] Bad file descriptor: './WeChatTweak.lbaction/Contents/Scripts'
xattr: [Errno 9] Bad file descriptor: './WeChatTweak.lbaction/Contents'
xattr: [Errno 9] Bad file descriptor: './WeChatTweak.lbaction'
xattr: [Errno 9] Bad file descriptor: '.'
make: *** [install] Error 1

**Comment by iszhuzhi** [comment]
遇到同问题+1

**Comment by NotWang** [comment]
+1 我也是，出现这个错误装不了  系统版本 12.0 Beta版(21A5284e)

**Comment by NotWang** [comment]
![image](https://user-images.githubusercontent.com/32693877/126674699-26099a2c-96ce-4c43-956f-c10efb8d31e1.png)
我开始也是,后来发现是makefile有句话有问题，我也不知道为啥。注释掉手动删除掉附加属性就可以了
