### ISSUE TITLE
没法进行make install安装

### ISSUE THREAD

**Issue by ahuaiph** [Sunnyyoung/WeChatTweak-macOS#297]
执行命令过程如下：
![image](https://user-images.githubusercontent.com/49918030/126278220-b3e672e0-0f85-4e4f-a8b7-21a3437c4dd0.png)

![image](https://user-images.githubusercontent.com/49918030/126278234-60605baa-97a8-4775-a772-b7af1f436175.png)

sudo make install时报错显示没有找到框架，请进行build，是什么意思啊？怎么解决呢？

**Comment by Solsticez** [comment]
我也是

**Comment by tikdoge** [comment]
好好阅读再来提问

**Comment by iszhuzhi** [comment]
> 好好阅读再来提问

[安装出现错误：Can not find the framework, please build first.
下载的是源码文件需要自行编译]

哈哈，我也是直接点【开箱自用】的包，且还 安装xcod，依旧安装错误

**Comment by iszhuzhi** [comment]
1. 打开终端输入【xcode-select --install】
2. 终端输入【cd】记得多个空格，再将【WeChatTweak-macOS】拽到终端里
3. 输入【sudo make install】，然后回车
4. 输入你的电脑密码，同意微信多开小助手WeChatTweak进行安装

经过以上步骤，我已经 安装上了，微信版本号为3.1.5

[目前登录了3个微信,完美]

**Comment by sougoukk** [comment]
> 执行命令过程如下：
> ![image](https://user-images.githubusercontent.com/49918030/126278220-b3e672e0-0f85-4e4f-a8b7-21a3437c4dd0.png)
> 
> ![image](https://user-images.githubusercontent.com/49918030/126278234-60605baa-97a8-4775-a772-b7af1f436175.png)
> 
> sudo make install时报错显示没有找到框架，请进行build，是什么意思啊？怎么解决呢？

需要编译哈。。错误是can‘t find fk。。

**Comment by Sunnyyoung** [comment]
下载 https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/latest/download/WeChatTweak-macOS.zip
