### ISSUE TITLE
wechat.alfredworkflow可以考虑Spotlight搜索版么？

### ISSUE THREAD

**Issue by galaxy001** [Sunnyyoung/WeChatTweak-macOS#30]
感觉原生的会常见些。

而且，现在也有python的api：
https://github.com/w0lfschild/Flashlight

**Comment by alexluoli** [comment]
需要什么版本的alfred？

**Comment by Sunnyyoung** [comment]
@galaxy001 这个我看看
@alexluoli Alfred 3，2的我没有做，有兴趣的话可以试试看能不能直接用，或者自己做一个
