### ISSUE TITLE
公众号能用系统默认浏览器直接打开吗

### ISSUE THREAD

**Issue by lyseky** [Sunnyyoung/WeChatTweak-macOS#301]
好烦微信的公众号每次打开内置的浏览器，又慢又破，能嗲用系统默认浏览器直接打开最好了

**Comment by Sunnyyoung** [comment]
可以，单链接正常，多链接的会崩溃，等待解决

**Comment by lyseky** [comment]
期待解决bug

**Comment by Sunnyyoung** [comment]
Fixed in 4de5ca9fec19da2e58b38b9e1060ae5bec6f93de
