### ISSUE TITLE
Current WeChat version may be compromised. For your security, this login session has expired.

### ISSUE THREAD

**Issue by char1eslu** [Sunnyyoung/WeChatTweak-macOS#303]
你们有人收到这个提示吗

<img width="302" alt="image" src="https://user-images.githubusercontent.com/20885743/127757390-0abe29dc-5dd8-4921-b8f2-fe4dea2f2a64.png">

**Comment by Sunnyyoung** [comment]
正常提示，无风险

**Comment by char1eslu** [comment]
> 正常提示，无风险

好嘞，多谢大佬回复，一直在用，感谢
