### ISSUE TITLE
请问哪里能下到历史版本，3.0.2

### ISSUE THREAD

**Issue by F5F5** [Sunnyyoung/WeChatTweak-macOS#304]
当前支持并经验证版本：3.0.2

3.0.0使用最新版本防撤回无效。。。

**Comment by Sunnyyoung** [comment]
用最新版本微信客户端吧，默认只支持最新客户端，旧版本不支持

**Comment by F5F5** [comment]
@Sunnyyoung 请问是 Readme 忘记改了吗？😅
