### ISSUE TITLE
sudo make install时候出错

### ISSUE THREAD

**Issue by cxin-william** [Sunnyyoung/WeChatTweak-macOS#307]
Can not find the framework, please build first.
Or download the latest release zip: https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/latest.
make: *** [install] Error 1

**Comment by Sunnyyoung** [comment]
错误信息很清楚了，下载 https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/latest
