### ISSUE TITLE
这个会有被封的风险吗？

### ISSUE THREAD

**Issue by blue20080** [Sunnyyoung/WeChatTweak-macOS#308]
如题？
之前一直用：https://github.com/MustangYM/WeChatExtension-ForMac/
后来遭遇大面积封禁。
现在改用这个，在担心中。

**Comment by Sunnyyoung** [comment]
用过别的，会有风险，建议停用一段时间

**Comment by LynnLLY** [comment]
+1,大胆用,警告了在卸载

**Comment by gofunbox** [comment]
一直用 木事
