### ISSUE TITLE
Support iOS-WeChat on macOS

### ISSUE THREAD

**Issue by sequencer** [Sunnyyoung/WeChatTweak-macOS#313]
目前iOS WeChat已经可以通过[PlayCover](https://github.com/Letscoder/PlayCover)在macOS上运行了。
iOS/Mac 的微信理论是一个codebase 所以有可能可以共享插件。
最重要的是，要hook iOS对MacOS的检测功能，我怀疑是这个API: [isiosapponmac](https://developer.apple.com/documentation/foundation/processinfo/3608556-isiosapponmac)
想讨论一下利用这个tweak同时支持的可能性。

**Comment by Sunnyyoung** [comment]
iOS 处理逻辑不太一样，参考 [WeChatTweak-iOS](https://github.com/Sunnyyoung/WeChatTweak-iOS)，并且对 iOS 进行修改会有更高的风险问题，所以暂不考虑支持。

**Comment by sequencer** [comment]
理解，iOS的tweak按道理来说是用的 cydia substrate 作为hook。但是我想的是 iOS on Mac 理论来说可以 fishhook 重构之后按照Mac的方案做dynamic lib注入了。（如果我说错了请纠正，并没做过iOS/Mac的相关开发）
我目前想做的就是一个基础的iOS-WeChat on Mac的钩子层用于防止微信检测在Mac上使用iOS版。
理论来说Hook [isiosapponmac](https://developer.apple.com/documentation/foundation/processinfo/3608556-isiosapponmac)接口即可。

**Comment by Sunnyyoung** [comment]
这么说的话，可以尝试一下

**Comment by sequencer** [comment]
是的，我一直想试试看，但是没有测试用的微信账号，怕封号lol。
