### ISSUE TITLE
安装提示没找到微信，微信版本3.1.5

### ISSUE THREAD

**Issue by codeOct** [Sunnyyoung/WeChatTweak-macOS#316]
![image](https://user-images.githubusercontent.com/34015358/130175245-d41a6cdf-3187-41ae-a72a-aa62d6e13a47.png)

**Comment by cylllllll** [comment]
`ls /Applications/WeChat.app/Contents/MacOS/WeChat`
微信不在这个路径吗？

**Comment by codeOct** [comment]
> ls /Applications/WeChat.app/Contents/MacOS/WeChat

![image](https://user-images.githubusercontent.com/34015358/130212747-f3c460b9-a8df-4b70-af36-9593423ad2d6.png)

**Comment by cylllllll** [comment]
`微信.app` 重命名过？
试试把`微信.app`重命名为`WeChat.app`试试

**Comment by codeOct** [comment]
> `微信.app` 重命名过？
> 把`微信.app`重命名为`WeChat.app`试试呢

重命名后安装成功，估计是官网的版本和App Store版本不一致导致的吧？

**Comment by cylllllll** [comment]
试了下官网版本文件名也是`WeChat.app`，不太清楚原因
<img width="728" alt="image" src="https://user-images.githubusercontent.com/17983727/130423456-f148bb37-be0d-46f3-8ff3-5fbace884cde.png">

**Comment by Sunnyyoung** [comment]
建议删除微信重新从 App Store 下载
