### ISSUE TITLE
截图功能异常

### ISSUE THREAD

**Issue by hypergravity** [Sunnyyoung/WeChatTweak-macOS#319]
快捷键截图的时候显示需要添加权限，但是明明已经添加了啊……

**Comment by cdcdx** [comment]
我也遇到相同的问题，期待恢复

**Comment by kahnli** [comment]
我的测试正常  3.2版

**Comment by Sunnyyoung** [comment]
已修复，请卸载并重新安装最新微信，参考 https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/tag/1.2.2 安装 Tweak
