### ISSUE TITLE
arm架构的微信在考虑支持吗?

### ISSUE THREAD

**Issue by deanglc** [Sunnyyoung/WeChatTweak-macOS#323]
https://dldir1.qq.com/weixin/mac/WeChatMac_Beta.dmg
这是默认的最新beta版本微信下载链接,目前原生支持M1了.

**Comment by Sunnyyoung** [comment]
这两天发布新的安装器

**Comment by Sunnyyoung** [comment]
已经更新支持了，看最新文档。
