### ISSUE TITLE
微信3.1.5 (18851) intel芯片 Mac OS X 10.14.6，安装后打开微信报错

### ISSUE THREAD

**Issue by andyzu** [Sunnyyoung/WeChatTweak-macOS#324]
Process:               WeChat [58210]
Path:                  /Applications/WeChat.app/Contents/MacOS/WeChat
Identifier:            com.tencent.xinWeChat
Version:               3.1.5 (18851)
App Item ID:           836500024
App External ID:       843075893
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           WeChat [58210]
User ID:               501

Date/Time:             2021-09-07 23:46:21.144 +0800
OS Version:            Mac OS X 10.14.6 (18G103)
Report Version:        12
Anonymous UUID:        BE1F6CCA-1860-4735-5BC3-FB79AAAB27EB

Sleep/Wake UUID:       DA0EE114-C5EB-4B9E-AE56-75A2B17C7533

Time Awake Since Boot: 100000 seconds
Time Since Wake:       4100 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @executable_path/WeChatTweak.framework/WeChatTweak
  Referenced from: /Applications/WeChat.app/Contents/MacOS/WeChat
  Reason: no suitable image found.  Did find:
	/Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework/WeChatTweak: file too short
	/Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework/WeChatTweak: file too short

Binary Images:
       0x102511000 -        0x1070ecfff +com.tencent.xinWeChat (3.1.5 - 18851) <FE57E653-267D-3FE1-BCDC-B49E167836F5> /Applications/WeChat.app/Contents/MacOS/WeChat
       0x1089d5000 -        0x108ef4fff +com.tencent.ilinknetwork (1.1.4 - 1.1.4) <CD5ADA11-BB16-3650-B832-8C4C1A13770A> /Applications/WeChat.app/Contents/Frameworks/ilink_network.framework/Versions/A/ilink_network
       0x108f62000 -        0x1090a2fff +com.tencent.WCDB (1.0.3 - 1) <B3038F97-238D-38AB-A048-80BE576DF81D> /Applications/WeChat.app/Contents/Frameworks/WCDB.framework/Versions/A/WCDB
       0x10913a000 -        0x10913fff7 +com.tencent.MMLibHooks (1.0 - 1) <1617CFCE-1655-35D6-90D4-7BD80BBDCF28> /Applications/WeChat.app/Contents/Frameworks/MMLibHooks.framework/Versions/A/MMLibHooks
       0x10914b000 -        0x10916dff7 +com.deusty.CocoaLumberjack (2.3.0 - 1) <6BDB40E8-05DA-32DE-8C81-37632C48E80B> /Applications/WeChat.app/Contents/Frameworks/CocoaLumberjack.framework/Versions/A/CocoaLumberjack
       0x1091a5000 -        0x1091c7ffb +com.alamofire.AFNetworking (3.0.0 - 3.1.0) <BDD10371-3F15-3EF9-A0A7-E80EAC53ADF6> /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking
       0x10920a000 -        0x109355ffb +com.tencent.wc.mp.matrixreport (1.0 - 1) <C29DB913-09F8-3137-8325-0AA3A0E8C429> /Applications/WeChat.app/Contents/Frameworks/matrixreport.framework/Versions/A/matrixreport
       0x112b22000 -        0x112b8c70f  dyld (655.1.1) <DFC3C4AF-6F97-3B34-B18D-7DCB23F2A83A> /usr/lib/dyld
    0x7fff42311000 -     0x7fff424edffb  com.apple.avfoundation (2.0 - 1550.4) <5854207B-6106-3DA4-80B6-36C42D042F26> /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
    0x7fff425b5000 -     0x7fff426bafff  com.apple.AVKit (1.1 - 446.50.101) <56AD537F-0BA5-360D-8B83-D5BB16A1BF4E> /System/Library/Frameworks/AVKit.framework/Versions/A/AVKit
    0x7fff426bb000 -     0x7fff426bbfff  com.apple.Accelerate (1.11 - Accelerate 1.11) <762942CB-CFC9-3A0C-9645-A56523A06426> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
    0x7fff438ef000 -     0x7fff446a4ffb  com.apple.AppKit (6.9 - 1671.60.109) <EFB74848-E23F-3FC3-B167-BA1F960996CC> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff44bd9000 -     0x7fff44e50ff7  com.apple.audio.toolbox.AudioToolbox (1.14 - 1.14) <04F482F1-E1C1-3955-8A6C-8AA152AA06F3> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fff44e52000 -     0x7fff44e52fff  com.apple.audio.units.AudioUnit (1.14 - 1.14) <ABC54269-002D-310D-9654-46CF960F863E> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
    0x7fff451ab000 -     0x7fff4554cfff  com.apple.CFNetwork (978.0.7 - 978.0.7) <B2133D0D-1399-3F17-80F0-313E3A241C89> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7fff45561000 -     0x7fff45561fff  com.apple.Carbon (158 - 158) <56AD06AA-7BB4-3F0B-AEF7-9768D0BC1C98> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff45a63000 -     0x7fff45a63fff  com.apple.Cocoa (6.11 - 23) <C930D6CD-930B-3D1E-9F15-4AE6AFC13F26> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff45d4c000 -     0x7fff45dd2fff  com.apple.audio.CoreAudio (4.3.0 - 4.3.0) <1E8E64E6-0E58-375A-97F7-07CB4EE181AC> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7fff462d8000 -     0x7fff4671dff7  com.apple.CoreFoundation (6.9 - 1575.22) <51040EEE-7C5D-3433-A271-86B47B0562BF> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff4671f000 -     0x7fff46daefff  com.apple.CoreGraphics (2.0 - 1265.9) <BC95B558-EF77-3A57-A0BC-11606C778991> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
    0x7fff470d1000 -     0x7fff47149fff  com.apple.corelocation (2245.16.14) <0F59F59B-AC14-3116-83C5-CF7BC57D9EB1> /System/Library/Frameworks/CoreLocation.framework/Versions/A/CoreLocation
    0x7fff473cd000 -     0x7fff474d1fff  com.apple.CoreMedia (1.0 - 2290.13) <A739B93D-23C2-3A34-8D61-6AC924B9634F> /System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia
    0x7fff4752e000 -     0x7fff4752efff  com.apple.CoreServices (946 - 946) <2EB6117A-6389-311B-95A0-7DE32C5FCFE2> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff47f06000 -     0x7fff48068ff3  com.apple.CoreText (352.0 - 584.26.3.2) <59919B0C-CBD5-3877-8D6F-D6048F1E5F42> /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText
    0x7fff48069000 -     0x7fff480a9ff3  com.apple.CoreVideo (1.8 - 281.4) <10CF8E52-07E3-382B-8091-2CEEEFFA69B4> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
    0x7fff480aa000 -     0x7fff48139fff  com.apple.framework.CoreWLAN (13.0 - 1375.2) <BF4B29F7-FBC8-3299-98E8-C3F8C04B7C92> /System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLAN
    0x7fff4855b000 -     0x7fff48908ffb  com.apple.Foundation (6.9 - 1575.22) <CDB9A3E1-41A5-36EC-A24E-94FBCC752D6A> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff48c13000 -     0x7fff48ca2fff  com.apple.framework.IOKit (2.0.2 - 1483.260.4) <8A90F547-86EF-3DFB-92FE-0E2C0376DD84> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff48d07000 -     0x7fff48e92fef  com.apple.ImageIO.framework (3.3.0 - 1850.2) <75E46A31-D87D-35CE-86A4-96A50971FDB2> /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
    0x7fff495cf000 -     0x7fff4a42ffff  com.apple.JavaScriptCore (14607 - 14607.3.9) <9B7D9E8B-619D-34A1-8FA9-E23C0EA3CD02> /System/Library/Frameworks/JavaScriptCore.framework/Versions/A/JavaScriptCore
    0x7fff4becc000 -     0x7fff4bf15ff7  com.apple.MultipeerConnectivity (155.2 - 155.2) <4624CB7E-98C6-357C-A3BB-1819C38EABBC> /System/Library/Frameworks/MultipeerConnectivity.framework/Versions/A/MultipeerConnectivity
    0x7fff4c2b3000 -     0x7fff4c2d6ff7  com.apple.audio.OpenAL (1.8 - 1.8) <2EE5236C-775B-36B1-97A8-DEE5FB80F5B5> /System/Library/Frameworks/OpenAL.framework/Versions/A/OpenAL
    0x7fff4ff69000 -     0x7fff4ff78ffb  com.apple.opengl (17.7.3 - 17.7.3) <94B5CF34-5BD6-3652-9A8C-E9C56E0A9FB4> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff50d7a000 -     0x7fff50d7afff  com.apple.quartzframework (1.5 - 23) <31783652-5E36-3773-8847-9FECFE2487F0> /System/Library/Frameworks/Quartz.framework/Versions/A/Quartz
    0x7fff50d7b000 -     0x7fff50fd2ff7  com.apple.QuartzCore (1.11 - 701.14) <33E846BE-1794-3186-9BF2-6ADF62C782A3> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff50fd3000 -     0x7fff5102afff  com.apple.QuickLookFramework (5.0 - 775.6) <CB74C63F-E223-3783-9021-8E28091BCDA6> /System/Library/Frameworks/QuickLook.framework/Versions/A/QuickLook
    0x7fff51807000 -     0x7fff51b07fff  com.apple.security (7.0 - 58286.270.3.0.1) <DF7677A7-9765-3B6A-9D1C-3589145E4B65> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff51bc6000 -     0x7fff51bcafff  com.apple.xpc.ServiceManagement (1.0 - 1) <FCF7BABA-DDDD-3770-8DAC-7069850203C2> /System/Library/Frameworks/ServiceManagement.framework/Versions/A/ServiceManagement
    0x7fff51f63000 -     0x7fff51fd0fff  com.apple.SystemConfiguration (1.17 - 1.17) <30C8327F-3EFF-3520-9C50-016F8B6B954F> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff5222f000 -     0x7fff52590fff  com.apple.VideoToolbox (1.0 - 2290.13) <7FCB2FC0-EFB8-37C2-B0D3-60AE9FDFE230> /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox
    0x7fff549eb000 -     0x7fff54f3bff7  com.apple.WebKit (14607 - 14607.3.9) <AE6029DD-0CED-3FEF-92D5-DB8D4F9757F9> /System/Library/Frameworks/WebKit.framework/Versions/A/WebKit
    0x7fff6f24f000 -     0x7fff6f250ffb  libSystem.B.dylib (1252.250.1) <B1006948-7AD0-3CA9-81E0-833F4DD6BFB4> /usr/lib/libSystem.B.dylib
    0x7fff6f484000 -     0x7fff6f491fff  libbz2.1.0.dylib (38.200.3) <272953A1-8D36-329B-BDDB-E887B347710F> /usr/lib/libbz2.1.0.dylib
    0x7fff6f492000 -     0x7fff6f4e5ff7  libc++.1.dylib (400.9.4) <9A60A190-6C34-339F-BB3D-AACE942009A4> /usr/lib/libc++.1.dylib
    0x7fff6fe51000 -     0x7fff6ff41fff  libiconv.2.dylib (51.200.6) <2047C9B7-3F74-3A95-810D-2ED8F0475A99> /usr/lib/libiconv.2.dylib
    0x7fff6ff42000 -     0x7fff701a3ffb  libicucore.A.dylib (62141.0.1) <A0D63918-76E9-3C1B-B255-46F4C1DA7FE8> /usr/lib/libicucore.A.dylib
    0x7fff70a86000 -     0x7fff7120bfdf  libobjc.A.dylib (756.2) <7C312627-43CB-3234-9324-4DEA92D59F50> /usr/lib/libobjc.A.dylib
    0x7fff71372000 -     0x7fff7138affb  libresolv.9.dylib (65.200.2) <893142A5-F153-3437-A22D-407EE542B5C5> /usr/lib/libresolv.9.dylib
    0x7fff717e9000 -     0x7fff718cbff3  libxml2.2.dylib (32.10) <AA4E1B1F-0FDE-3274-9FA5-75446298D1AC> /usr/lib/libxml2.2.dylib
    0x7fff718f5000 -     0x7fff71907ff7  libz.1.dylib (70.200.4) <B048FC1F-058F-3A08-A1FE-81D5308CB3E6> /usr/lib/libz.1.dylib
    0x7fff71977000 -     0x7fff71983ff3  libswiftAVFoundation.dylib (??? - ???) <0343ADA8-C7A9-38CF-9834-D455F914E6B3> /usr/lib/swift/libswiftAVFoundation.dylib
    0x7fff7198a000 -     0x7fff7199dff3  libswiftAppKit.dylib (??? - ???) <390B2331-342E-367F-9308-01447A4442E6> /usr/lib/swift/libswiftAppKit.dylib
    0x7fff719b6000 -     0x7fff71d27ff7  libswiftCore.dylib (5.0 - 1001.8.63.13) <4FE40B7B-1413-3A25-959B-D78B78682D12> /usr/lib/swift/libswiftCore.dylib
    0x7fff71d28000 -     0x7fff71d2dff3  libswiftCoreAudio.dylib (??? - ???) <7DCC2F3C-C9E9-3FCC-81A0-E1C536626EF5> /usr/lib/swift/libswiftCoreAudio.dylib
    0x7fff71d2e000 -     0x7fff71d35ffb  libswiftCoreData.dylib (??? - ???) <7D7D21CE-8F68-390F-BE47-2AB1DC0439ED> /usr/lib/swift/libswiftCoreData.dylib
    0x7fff71d36000 -     0x7fff71d38ff3  libswiftCoreFoundation.dylib (??? - ???) <3192FF82-E322-3B09-805F-6AEB48C00478> /usr/lib/swift/libswiftCoreFoundation.dylib
    0x7fff71d39000 -     0x7fff71d47ff3  libswiftCoreGraphics.dylib (??? - ???) <FEFE340D-865B-3C8C-AF13-AB1DE8866C01> /usr/lib/swift/libswiftCoreGraphics.dylib
    0x7fff71d48000 -     0x7fff71d4bffb  libswiftCoreImage.dylib (??? - ???) <4AC0B024-190B-31F8-8EC5-C9E2761C580E> /usr/lib/swift/libswiftCoreImage.dylib
    0x7fff71d4c000 -     0x7fff71d50fff  libswiftCoreLocation.dylib (??? - ???) <601B6BF4-B840-3D74-8C9D-143A12076164> /usr/lib/swift/libswiftCoreLocation.dylib
    0x7fff71d51000 -     0x7fff71d57fff  libswiftCoreMedia.dylib (??? - ???) <C6607E85-DBA1-3A32-B0E5-88789A019133> /usr/lib/swift/libswiftCoreMedia.dylib
    0x7fff71d5e000 -     0x7fff71d64ffb  libswiftDarwin.dylib (??? - ???) <FD515CE3-A057-36EC-A787-E78F773973F3> /usr/lib/swift/libswiftDarwin.dylib
    0x7fff71d65000 -     0x7fff71d7bfff  libswiftDispatch.dylib (??? - ???) <40AA9542-FE66-37F0-B0BE-70C8D057488C> /usr/lib/swift/libswiftDispatch.dylib
    0x7fff71d7c000 -     0x7fff71f0dff7  libswiftFoundation.dylib (??? - ???) <A24C3092-3B6D-3680-945E-292A0D31436F> /usr/lib/swift/libswiftFoundation.dylib
    0x7fff71f1c000 -     0x7fff71f1eff3  libswiftIOKit.dylib (??? - ???) <C7E2E0F9-D04C-348E-A5B6-DD59A9F40BDD> /usr/lib/swift/libswiftIOKit.dylib
    0x7fff71f2c000 -     0x7fff71f33fff  libswiftMetal.dylib (??? - ???) <03736BFF-B1E4-32FB-B3C3-12FFF7681854> /usr/lib/swift/libswiftMetal.dylib
    0x7fff71f75000 -     0x7fff71f78ff7  libswiftObjectiveC.dylib (??? - ???) <A4201F26-A2B3-3F2A-8B0F-D17F166C26BC> /usr/lib/swift/libswiftObjectiveC.dylib
    0x7fff71f83000 -     0x7fff71f88ffb  libswiftQuartzCore.dylib (??? - ???) <FB83F05B-766E-3211-8CC7-E8B634B34BA0> /usr/lib/swift/libswiftQuartzCore.dylib
    0x7fff720c0000 -     0x7fff720c2ffb  libswiftXPC.dylib (??? - ???) <61CDCF0E-FFD3-31FD-A6B1-175B06EA6659> /usr/lib/swift/libswiftXPC.dylib
    0x7fff720ca000 -     0x7fff720eaffb  libswiftsimd.dylib (??? - ???) <8D005E6E-A365-394E-8042-493162C9D7F2> /usr/lib/swift/libswiftsimd.dylib

Model: MacBookPro11,3, BootROM 162.0.0.0.0, 4 processors, Intel Core i7, 2.5 GHz, 16 GB, SMC 2.19f12
Graphics: kHW_IntelIrisProItem, Intel Iris Pro, spdisplays_builtin
Graphics: kHW_NVidiaGeForceGTX750MItem, NVIDIA GeForce GT 750M, spdisplays_pcie_device, 2 GB
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364B544631473634485A2D314736453120
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364B544631473634485A2D314736453120
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x134), Broadcom BCM43xx 1.0 (7.77.61.2 AirPortDriverBrcmNIC-1305.8)
Bluetooth: Version 6.0.14d3, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0512F, 500.28 GB
USB Device: USB 3.0 Bus
USB Device: DataTraveler 3.0
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB Receiver
Thunderbolt Bus: MacBook Pro, Apple Inc., 17.1

**Comment by Sunnyyoung** [comment]
建议用 https://github.com/Sunnyyoung/WeChatTweak-CLI 尝试安装
