### ISSUE TITLE
大佬，1.2.2的安装方法变了嘛，已经编译好的版本点击下载是Not Found哦

### ISSUE THREAD

**Issue by char1eslu** [Sunnyyoung/WeChatTweak-macOS#325]

**Comment by Sunnyyoung** [comment]
还没发布新的安装器，等等

**Comment by char1eslu** [comment]
> 还没发布新的安装器，等等

哈哈哈，好嘞，辛苦啦，多谢大佬

**Comment by amaoagoua** [comment]
在线等 ，有些网站那你的东西拿去卖35块rmb

**Comment by Sunnyyoung** [comment]
https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/latest 直接用这个

**Comment by Sunnyyoung** [comment]
参考：https://github.com/Sunnyyoung/WeChatTweak-macOS#%E4%BD%BF%E7%94%A8
