### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by jhw621** [Sunnyyoung/WeChatTweak-macOS#328]
mac系统：10.13.6
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /usr/local/bin/wechattweak-cli
  Reason: image not found
[1]    2044 abort      sudo wechattweak-cli --install

 麻烦问一下这是什么问题呢？

**Comment by Sunnyyoung** [comment]
https://github.com/Sunnyyoung/WeChatTweak-macOS/issues/327#issuecomment-916745195

**Comment by jhw621** [comment]
好的可以了，感谢大神 ~ 下载了这个报错Install failed: “WeChat” couldn’t be moved to “tmp” because an item with the same，我下了个低版本的微信可以啦

**Comment by Sunnyyoung** [comment]
重新安装下最新版微信就行，安装器有些兼容问题导致的，新版本修复。

**Comment by zhangmrit** [comment]
> 重新安装下最新版微信就行，安装器有些兼容问题导致的，新版本修复。

我也遇到了，好像是安装或者卸载的时候意外退出了就导致这样了，打开包内容，主要是切换那个WeChat.bak,其实最好建个文件夹去判断，这也就不存在了，无论是卸载还是安装，都是从文件夹里拷贝出来替换默认的
