### ISSUE TITLE
1.2.2怎么安装呢

### ISSUE THREAD

**Issue by luo1666666** [Sunnyyoung/WeChatTweak-macOS#329]

**Comment by Sunnyyoung** [comment]
@luo1666666 文档说明挺清晰的了

@doudouliyouniaoshi 这个不是我写的

最好还是按照我的教程来。

**Comment by halotitee** [comment]
> @luo1666666 文档说明挺清晰的了
> 
> @doudouliyouniaoshi 这个不是我写的
> 
> 最好还是按照我的教程来。

请问安装1.2.2的话，需要卸载原来版本吗？

**Comment by Sunnyyoung** [comment]
@halotitee 最好卸载下～ CLI 升级兼容版本还没发

**Comment by halotitee** [comment]
> @halotitee 最好卸载下～ CLI 升级兼容版本还没发

了解🙏感谢
