### ISSUE TITLE
安装完wechattweak-cli后sudo失败

### ISSUE THREAD

**Issue by demo3025** [Sunnyyoung/WeChatTweak-macOS#331]
![image](https://user-images.githubusercontent.com/41543156/133362244-ac990a83-f9f8-420b-b95f-032b226446e3.png)
brew install wechattweak-cli后执行sudo wechattweak-cli --install失败,如图,请问是有什么操作漏掉了吗

**Comment by Sunnyyoung** [comment]
貌似是系统问题，一般重新执行下就可以

**Comment by demo3025** [comment]
执行完之后打开微信就提示
![image](https://user-images.githubusercontent.com/41543156/133365733-a9557f3c-7e92-4dce-b88b-d634da88e352.png)
卸载微信后重新按流程操作还是这样子的,请问有没有什么处理办法,微信3.2.0,电脑系统信息:
![image](https://user-images.githubusercontent.com/41543156/133365809-20ba058d-d01b-492c-beb3-ddbf098c72fa.png)

**Comment by demo3025** [comment]
都是sudo这一步不成功

**Comment by Sunnyyoung** [comment]
安装成功了吗，提示 Install success

**Comment by demo3025** [comment]
没有成功,都是这样
![image](https://user-images.githubusercontent.com/41543156/133367272-7e2cefa5-6343-4b06-852e-b918df0153d4.png)

**Comment by Sunnyyoung** [comment]
麻烦执行：`which codesign_allocate` 看看

**Comment by demo3025** [comment]
![image](https://user-images.githubusercontent.com/41543156/133379746-4ad99698-d368-441b-99b5-17c5e32dbf69.png)

**Comment by Sunnyyoung** [comment]
https://github.com/Sunnyyoung/WeChatTweak-CLI/issues/3 参考这个试试？

**Comment by demo3025** [comment]
![image](https://user-images.githubusercontent.com/41543156/133393235-966ff27d-0126-4af9-b5e7-2688e4fc9467.png)
我看了下别人是安装brew install wechattweak-cli这个步骤失败,我这边是成功的噢,只是我sudo wechattweak-cli --install这一步失败,我也是微信官网下载的最新版微信

**Comment by demo3025** [comment]
方便说下您系统是什么版本吗

**Comment by Sunnyyoung** [comment]
![image](https://user-images.githubusercontent.com/5926284/133405151-5b6268a3-e7fa-46ae-b83c-70599f72338d.png)

我看你上面那个报错是文件丢失了，重新装下微信

**Comment by demo3025** [comment]
重新装了好多遍了都不行

**Comment by demo3025** [comment]
我试下升级11.6

**Comment by demo3025** [comment]
不清楚是否是版本原因,我更新至11.6安装成功,中间虽然失败,但是重装微信后就通畅了,最后安装成功,打开微信提示文件损坏,输入命令已解决,感谢
