### ISSUE TITLE
安装时报错：fatal: unable to access

### ISSUE THREAD

**Issue by JJ7539** [Sunnyyoung/WeChatTweak-macOS#332]
jj@bogon ~ % brew install sunnyyoung/repo/wechattweak-cli
==> Tapping sunnyyoung/repo
Cloning into '/usr/local/Homebrew/Library/Taps/sunnyyoung/homebrew-repo'...
fatal: unable to access 'https://github.com/sunnyyoung/homebrew-repo/': Failed to connect to github.com port 443: Operation timed out
Error: Failure while executing; `git clone https://github.com/sunnyyoung/homebrew-repo /usr/local/Homebrew/Library/Taps/sunnyyoung/homebrew-repo --origin=origin --template=` exited with 128.

**Comment by Sunnyyoung** [comment]
这个是网络问题
