### ISSUE TITLE
No such file or directory @ dir_s_rmdir

### ISSUE THREAD

**Issue by ManutdGTA** [Sunnyyoung/WeChatTweak-macOS#333]
brew install wechattweak-cli  

Download failed on Cask 'wechattweak-cli' with message: No such file or directory @ dir_s_rmdir - /usr/local/var/homebrew/locks/9feb3c633b17f573c2e45691ab9c14f57db260cbd494f1cda985b8ab9617031e--wechattweak-cli.incomplete.lock

macos 11.6

**Comment by Sunnyyoung** [comment]
Run `brew install sunnyyoung/repo/wechattweak-cli`

**Comment by ManutdGTA** [comment]
> Run `brew install sunnyyoung/repo/wechattweak-cli`

一样还是这个报错
brew install sunnyyoung/repo/wechattweak-cli
Error: Can't create update lock in /usr/local/var/homebrew/locks!
Fix permissions by running:
  sudo chown -R $(whoami) /usr/local/var/homebrew
Error: Download failed on Cask 'wechattweak-cli' with message: No such file or directory @ dir_s_rmdir - /usr/local/var/homebrew/locks/9feb3c633b17f573c2e45691ab9c14f57db260cbd494f1cda985b8ab9617031e--wechattweak-cli.incomplete.lock

**Comment by Sunnyyoung** [comment]
`sudo chown -R $(whoami) /usr/local/var/homebrew`

**Comment by ManutdGTA** [comment]
> `sudo chown -R $(whoami) /usr/local/var/homebrew`

打了这条后，再brew install sunnyyoung/repo/wechattweak-cli 终于好了，谢谢
