### ISSUE TITLE
求助：第一步就报错了···brew tap sunnyyoung/repo

### ISSUE THREAD

**Issue by kuangxiaoye** [Sunnyyoung/WeChatTweak-macOS#334]
Error: Invalid cask: /usr/local/Homebrew/Library/Taps/sunnyyoung/homebrew-repo/Casks/swift-runtime-support.rb
Cask 'swift-runtime-support' is unreadable: undefined method `method_missing_message' for Utils:Module

Error: Invalid cask: /usr/local/Homebrew/Library/Taps/sunnyyoung/homebrew-repo/Casks/wechattweak-cli.rb
Cask 'wechattweak-cli' is unreadable: undefined method `method_missing_message' for Utils:Module

Error: Cannot tap sunnyyoung/repo: invalid syntax in tap!

**Comment by Sunnyyoung** [comment]
什么系统版本呢

**Comment by fredericky123** [comment]
我第一步也报错了
==> Tapping sunnyyoung/repo
Cloning into '/usr/local/Homebrew/Library/Taps/sunnyyoung/homebrew-repo'...
fatal: unable to access 'https://github.com/sunnyyoung/homebrew-repo/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 
Error: Failure while executing; `git clone https://github.com/sunnyyoung/homebrew-repo /usr/local/Homebrew/Library/Taps/sunnyyoung/homebrew-repo` exited with 128.

系统版本11.5.2

**Comment by Sunnyyoung** [comment]
@fredericky123 你是网络问题

**Comment by xxnian95** [comment]
> Error: Invalid cask: /usr/local/Homebrew/Library/Taps/sunnyyoung/homebrew-repo/Casks/swift-runtime-support.rb
> Cask 'swift-runtime-support' is unreadable: undefined method `method_missing_message' for Utils:Module
> 
> Error: Invalid cask: /usr/local/Homebrew/Library/Taps/sunnyyoung/homebrew-repo/Casks/wechattweak-cli.rb
> Cask 'wechattweak-cli' is unreadable: undefined method `method_missing_message' for Utils:Module
> 
> Error: Cannot tap sunnyyoung/repo: invalid syntax in tap!

```bash
brew update --verbose
```

then brew tap again.

If no use, reset the brew repo:

```bash
cd "$(brew --repo homebrew/cask)"
git clean -dfx
git reset --hard origin/master
git pull origin master
```
