### ISSUE TITLE
11.5.2  微信 Version. 3.2.0 (19442)  不能防撤回了

### ISSUE THREAD

**Issue by kkrepocom** [Sunnyyoung/WeChatTweak-macOS#336]
设备类型：MacBookPro14,1
系统版本：版本11.5.2（版号20G95）
系统语言：zh-Hans
微信版本：[2021-09-03 23:21:40] v3.2.0.16 (19442) #1c905fa707
微信语言：zh-Hans
历史版本：[2021-09-02 13:33:26] v3.1.5.16 (18851) #9dfb2032a7
网络状态：Reachable via WiFi or Ethernet
显  示  器：*(1440x900)/Retina, (1920x1080)

通过 brew 安装的，也显示安装成功了 
重启微信，重启电脑都不行 

![image](https://user-images.githubusercontent.com/43947662/133609131-26a36241-5f26-4912-b195-0c76cf35004f.png)

**Comment by tikdoge** [comment]
确定都按照步骤安装完了？
`$ brew install sunnyyoung/repo/wechattweak-cli`
`$ sudo wechattweak-cli --install   # Install`

**Comment by Sunnyyoung** [comment]
1. 确保微信没有使用过其他同类工具
2. 确保更新到最新 CLI 工具
3. 执行 wechattweak-cli --uninstall
4. 执行 wechattweak-cli --install

**Comment by csbebeto** [comment]
设备类型：MacBookPro12,1
系统版本：版本 10.13.6（版号 17G14033）
系统语言：zh-Hans
微信版本：[2021-09-03 18:06:10] v3.2.0.19 (19439) #ffa0296ca6
微信语言：zh-Hans
历史版本：[2021-09-23 13:52:23] v3.2.0.16 (19442) #1c905fa707
网络状态：Reachable via WiFi or Ethernet
显  示  器：*(1280x800)/Retina
我这安装完成微信都打不开了，只能删除wechat,然后把备份的wecha.bak改回来才能打开

**Comment by kkrepocom** [comment]
> 1. 确保微信没有使用过其他同类工具
> 2. 确保更新到最新 CLI 工具
> 3. 执行 wechattweak-cli --uninstall
> 4. 执行 wechattweak-cli --install

brew 安装了确实没有生效， 最后使用 wechattweak-cli --install 安装，可以使用了
