### ISSUE TITLE
重新卸载再按照，还是安装后提示您没有权限打开微信

### ISSUE THREAD

**Issue by heshangcode** [Sunnyyoung/WeChatTweak-macOS#339]
macOS：11.5.2 (20G95)
微信版本：3.2.0 (19439)
按照 FAQ，卸载了微信，重新下载官网的版本安装还是没有权限打开
卸载只卸载了应用程序，因为为了保留聊天记录。
![image](https://user-images.githubusercontent.com/39662806/134113214-d1c0ceeb-3959-4499-8308-42be058d5d79.png)

**Comment by xiaotianxt** [comment]
遇到类似问题，不过我安装的是mas版本

**Comment by Crazy-Steven** [comment]
同样遇到此类问题，mac:11.2.2wechat:3.2.0

**Comment by shan-guo** [comment]
同样遇到此类问题，**mac: 11.2.3(20D91)**  **wechat: 3.2.0** 😭

**Comment by zhang0630** [comment]
masos 11.6 WeChat 3.2.0 商店版 先安装 WeChatTweak-CLI，然后执行sudo wechattweak-cli --install。打开微信提示没有权限，重装微信还是提示没有权限。之后执行sudo wechattweak-cli --uninstall再执行sudo wechattweak-cli --install还是提示没权限。重启了一下再打开微信就ok了。

**Comment by goSunadeod** [comment]
macos： 10.15.7 wechat3.2.0 安装之后就无法打开 unstall之后才可以打开微信

**Comment by xiaotianxt** [comment]
> masos 11.6 WeChat 3.2.0 商店版 先安装 WeChatTweak-CLI，然后执行sudo wechattweak-cli --install。打开微信提示没有权限，重装微信还是提示没有权限。之后执行sudo wechattweak-cli --uninstall再执行sudo wechattweak-cli --install还是提示没权限。重启了一下再打开微信就ok了。

芜湖，用这个方式这个成功啦

**Comment by fanghengwei** [comment]
> masos 11.6 WeChat 3.2.0 商店版 先安装 WeChatTweak-CLI，然后执行sudo wechattweak-cli --install。打开微信提示没有权限，重装微信还是提示没有权限。之后执行sudo wechattweak-cli --uninstall再执行sudo wechattweak-cli --install还是提示没权限。重启了一下再打开微信就ok了。

用这个方法，卸载重装2次就能打开了

**Comment by goSunadeod** [comment]
具体就是需要重启电脑
