### ISSUE TITLE
卸载失败

### ISSUE THREAD

**Issue by 894399965** [Sunnyyoung/WeChatTweak-macOS#34]
提示
Can not find the WeChat backup file.
make: *** [uninstall] Error 1

请问如何解决呢？难道这是强制备份吗？

**Comment by Sunnyyoung** [comment]
检查下 `/Applications/WeChat.app/Contents/MacOS/` 目录下有没有 `WeChat.bak` 文件

**Comment by 894399965** [comment]
果然是因为没有`WeChat.bak`，所以我直接在目录下改了`Wechat`的扩展名为`WeChat.bak`，然后就能正常卸载重装了。
