### ISSUE TITLE
微信 3.2.1 (19701) Beta 10 版本，此脚本无效

### ISSUE THREAD

**Issue by AdamTyn** [Sunnyyoung/WeChatTweak-macOS#340]
微信 3.2.1 (19701) Beta 10 版本，macos 11.5.2 ，此脚本无效

**Comment by jackeyWanFei** [comment]
![image](https://user-images.githubusercontent.com/20556765/134831183-591cab32-19ca-4c1a-bac1-fa8883b113cd.png)

就你牛皮，搞beta版本的

**Comment by AdamTyn** [comment]
我也不知道怎么就变成beta了 我淦

**Comment by shuiRong** [comment]
我也发现我的时3.2.2了。貌似是前端时间微信自己提示有更新...

我以为AS版本的应用禁止自己下载更新（然后提示用户更新）。
