### ISSUE TITLE
M1 使用代码安装后微信卡死并退出后无法再次打开

### ISSUE THREAD

**Issue by limingyi1225** [Sunnyyoung/WeChatTweak-macOS#343]
M1 使用代码安装后微信卡死并退出后无法再次打开

**Comment by Sunnyyoung** [comment]
卸载之后正常吗？

**Comment by quanxin** [comment]
Intel 也遇到这个问题。卸载之后可以恢复正常。
![企业微信20210930-143727](https://user-images.githubusercontent.com/7403386/135400348-4656d279-16a5-4dde-b963-bd680479ec7a.png)

**Comment by Sunnyyoung** [comment]
麻烦重装 App Store 版本微信试试，另外提供一下 macOS 系统版本信息

**Comment by quanxin** [comment]
> 麻烦重装 App Store 版本微信试试，另外提供一下 macOS 系统版本信息

另外我也试过了，从AppStore下载的，再执行安装命令，结果还是和上面一样，无法打开了。unistall之后恢复正常。

**Comment by quanxin** [comment]
> > > 麻烦重装 App Store 版本微信试试，另外提供一下 macOS 系统版本信息
> > 
> > 
> > 另外我也试过了，从AppStore下载的，再执行安装命令，结果还是和上面一样，无法打开了。unistall之后恢复正常。
> 
> 我跟你遇到的问题一样,不过我重启了一下系统,就能用了.

果然。。。非常感谢~

**Comment by Sunnyyoung** [comment]
1. 卸载再安装
2. 重启电脑

基本都可以解决了
