### ISSUE TITLE
最新測試版v3.2.11(19746)出現“警告”

### ISSUE THREAD

**Issue by ClayMoreBoy** [Sunnyyoung/WeChatTweak-macOS#344]
v3.2.11(19746)![image](https://user-images.githubusercontent.com/6189207/135602642-884669b4-24a0-4ed8-ba26-6933bab9d730.png)

**Comment by Sunnyyoung** [comment]
什么警告

**Comment by ClayMoreBoy** [comment]
封號 @Sunnyyoung

**Comment by Sunnyyoung** [comment]
确认下是否之前有使用过其他同类工具

**Comment by ClayMoreBoy** [comment]
之前就是兩月前的小助手
