### ISSUE TITLE
微信 Version. 3.2.0 (19439) 安装成功后，偏好设置无菜单项

### ISSUE THREAD

**Issue by qiaohewei** [Sunnyyoung/WeChatTweak-macOS#347]
微信 Version. 3.2.0 (19439)
安装成功后，偏好设置无菜单项
![image](https://user-images.githubusercontent.com/21193340/136388354-a79ad82f-4107-4a7a-a8b3-865390a08bd6.png)

MacBook-Pro Downloads % brew install sunnyyoung/repo/wechattweak-cli
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 1 formula.

Warning: Cask 'wechattweak-cli' is already installed.

To re-install wechattweak-cli, run:
  brew reinstall wechattweak-cli
MacBook-Pro Downloads % brew uninstall sunnyyoung/repo/wechattweak-cli
==> Uninstalling Cask wechattweak-cli
==> Unlinking Binary '/usr/local/bin/wechattweak-cli'
==> Purging files for version 1.2 of Cask wechattweak-cli
MacBook-Pro Downloads % brew install sunnyyoung/repo/wechattweak-cli
==> Downloading https://github.com/Sunnyyoung/WeChatTweak-CLI/releases/download/
Already downloaded: /Users/hewitt/Library/Caches/Homebrew/downloads/f9a25cad1abc6ec535a537b726546b038ccaae209f36a2d74e188049370baf4e--wechattweak-cli
==> Installing Cask wechattweak-cli
==> Linking Binary 'wechattweak-cli' to '/usr/local/bin/wechattweak-cli'
🍺  wechattweak-cli was successfully installed!

**Comment by Sunnyyoung** [comment]
你执行了 `sudo wechattweak-cli --install` 了吗？？

**Comment by qiaohewei** [comment]
> 你执行了`sudo wechattweak-cli --install`？

执行后无法打开 【应用程序“微信.app”无法打开。】
卸载后可以正常打开

hewitt@HewittdeMacBook-Pro ~ % sudo wechattweak-cli --install 
Password:
------ Backup ------
Created WeChat.bak...
------ Download ------
------ Unzip ------
Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS
------ Insert Dylib ------
Binary is a fat binary with 2 archs.
LC_CODE_SIGNATURE load command found. Remove it.
LC_CODE_SIGNATURE load command found. Remove it.
Added LC_LOAD_DYLIB to all archs in /Applications/WeChat.app/Contents/MacOS/WeChat
------ Codesign ------
Execute command: cp /Applications/WeChat.app/Contents/MacOS/WeChat /tmp/WeChat
Execute command: codesign --force --deep --sign - /tmp/WeChat
Execute command: cp /tmp/WeChat /Applications/WeChat.app/Contents/MacOS/WeChat
Install success!
