### ISSUE TITLE
10.12.6安装报错

### ISSUE THREAD

**Issue by Fantast-WLB** [Sunnyyoung/WeChatTweak-macOS#35]
微信版本2.3.2.16，sudo make install 输完密码报错Can not find the WeChat.
make: *** [install] Error 1

**Comment by Sunnyyoung** [comment]
@Fantast-WLB 你的微信是放在 `/Applications/` 目录下的吗？

**Comment by Fantast-WLB** [comment]
@Sunnyyoung 是的，需要修改路径？

**Comment by Sunnyyoung** [comment]
@Fantast-WLB 检查下 `/Applications/WeChat.app/Contents/MacOS/WeChat` 路径是否能正常找到
 WeChat

**Comment by Fantast-WLB** [comment]
@Sunnyyoung 目测是中文的问题，感谢
