### ISSUE TITLE
导出表情有时候会识别成链接

### ISSUE THREAD

**Issue by iOSleep** [Sunnyyoung/WeChatTweak-macOS#353]
<img width="278" alt="QQ20211015-123918@2x" src="https://user-images.githubusercontent.com/26478957/137433112-4aa797db-9ef5-45a2-bdde-fe1e8fcd1996.png">

另外建议 cli 加一个 `--version` 方法

**Comment by Sunnyyoung** [comment]
![image](https://user-images.githubusercontent.com/5926284/151981481-50d3c304-c5dd-470e-9ae1-7f46e317968c.png)
试试最新的？
