### ISSUE TITLE
我安装几次命令都不行

### ISSUE THREAD

**Issue by mashubin** [Sunnyyoung/WeChatTweak-macOS#355]
Install failed: Download failed with error: Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x7fe6f8c07a80 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDownloadTask <7574D4DD-A876-4B9F-AEA0-60F60EE48C8F>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDownloadTask <7574D4DD-A876-4B9F-AEA0-60F60EE48C8F>.<1>"
), NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/latest/download/WeChatTweak.framework.zip, NSErrorFailingURLKey=https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/latest/download/WeChatTweak.framework.zip, _kCFStreamErrorDomainKey=4}
大佬，这个得怎么解决

**Comment by Sunnyyoung** [comment]
重装下插件，不行的话重启下电脑刷新下权限
