### ISSUE TITLE
使用brew安装后 微信3.2.1版本无法启动

### ISSUE THREAD

**Issue by hainuo** [Sunnyyoung/WeChatTweak-macOS#361]
使用命令行启动发现 
➜  ~ open -n /Applications/WeChat.app
The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10826 "kLSNoLaunchPermissionErr: User doesn't have permission to launch the app (managed networks)" UserInfo={_LSFunction=_LSLaunchWithRunningboard, _LSLine=2436, NSUnderlyingError=0x7fa6d04184f0 {Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x7fa6d0418c70 {Error Domain=NSPOSIXErrorDomain Code=153 "Unknown error: 153" UserInfo={NSLocalizedDescription=Launchd job spawn failed with error: 153}}}}}

**Comment by Sunnyyoung** [comment]
看 FAQ
