### ISSUE TITLE
122版本导致微信321版本闪退

### ISSUE THREAD

**Issue by wjfz** [Sunnyyoung/WeChatTweak-macOS#369]
不过重新安装121版本依然可以使用

**Comment by Sunnyyoung** [comment]
AppStore 版本的微信吗？我的工作正常

**Comment by xiaopigfly** [comment]
同321版本也闪退，重新执行：`sudo codesign --sign - --force --deep /Applications/WeChat.app` 即可

**Comment by itlaosiji** [comment]
执行了就没办法防撤回了

**Comment by wjfz** [comment]
> 执行了就没办法防撤回了

拿121版tweak对321版本的微信操作可以正常使用 @itlaosiji

**Comment by xiaopigfly** [comment]
![image](https://user-images.githubusercontent.com/17631557/141419992-003c0f93-a4ec-4c96-8545-8fda3c80230f.png)


> 执行了就没办法防撤回了

一样可以防撤回

**Comment by Sunnyyoung** [comment]
问题未能复现，工作正常
