### ISSUE TITLE
聊天记录无法显示

### ISSUE THREAD

**Issue by zhaowweny** [Sunnyyoung/WeChatTweak-macOS#37]
安装后列表上绝大部分用户的聊天记录都是空的，卸载了就正常了，希望可以修复啊。我安装后把WeChatTweak-macOS这个文件夹就删了，吓得我以为聊天记录都被删了，后来还找数据恢复软件。。。后来重新安装再卸载后就可以显示聊天记录了，我去喝杯茶压压惊🍵，贴上相关信息。
----------------------------------
设备类型：MacBookPro11,2
系统版本：版本 10.12.6（版号 16G29）
系统语言：zh-Hans
微信版本：Version. 2.3.2 (9414)  v2.3.2.16 (0x12030210) #8fcecb354
微信语言：zh-Hans
历史版本：[2017-09-06 09:14:37.613] Version. 2.3.2 (9414)  v2.3.2.16 (0x12030210) #8fcecb354
网络状态：Reachable via WiFi
显  示  器：*(1440x900)/Retina

**Comment by Sunnyyoung** [comment]
临时解决方案：https://github.com/Sunnyyoung/WeChatTweak-macOS/wiki/%E5%AE%89%E8%A3%85#%E8%81%8A%E5%A4%A9%E8%AE%B0%E5%BD%95%E8%BF%81%E7%A7%BB

自动路径识别这周末再把它修复了吧 :-)

**Comment by zhaowweny** [comment]
@Sunnyyoung 这个方案也不行，我迁移了，安装后还是无法显示聊天记录，而且卸载后没必要迁移回去，因为原来的并没有被删除，再迁移回去会在com.tencent.xinWeChat目录下再创建一个一样的文件夹。等你修复吧😂
