### ISSUE TITLE
Bug: 安装完成后微信无法打开

### ISSUE THREAD

**Issue by aaronyyan** [Sunnyyoung/WeChatTweak-macOS#370]
macOS Version. 12.1 Beta版(21C5021h)
WeChat Version. 3.2.1 (19796)
WeChatTweak-macOS Version. Latest

问题描述:
使用 Homebrew 安装完成后无法打开
![iShot2021-11-01 13.23.17.png](https://i.loli.net/2021/11/01/54Kp8xaroRMQ6AN.png)

**Comment by aaronyyan** [comment]
[https://i.loli.net/2021/11/01/54Kp8xaroRMQ6AN.png](url)

**Comment by guchengod** [comment]
+1 确实无法打开

**Comment by xu10000** [comment]
+1

**Comment by bareboy** [comment]
+1

**Comment by Darrenzzy** [comment]
+1

**Comment by EvangelYJY** [comment]
+1

**Comment by Sunnyyoung** [comment]
各位看 FAQ 了吗？

**Comment by zhaocongdong** [comment]
请大家仔细查看FAQ和已经关闭的issues
