### ISSUE TITLE
1.2.2版本homebrew安装升级之后防撤回失效

### ISSUE THREAD

**Issue by bearhunt110** [Sunnyyoung/WeChatTweak-macOS#371]
我从app store升级了微信现在是3.2.1版本Version. 3.2.1 (19797)
系统版本是monterey 12.0.1（版号21A559）
然后防撤回失效了，是因为升级monterey的关系吗

**Comment by Sunnyyoung** [comment]
安装完重启微信了吗

**Comment by bearhunt110** [comment]
> 安装完重启微信了吗

我重启过了，wo hai@我还卸载了微信在安装，同时重新装了防撤回
