### ISSUE TITLE
安装之后打不开，提示没有权限

### ISSUE THREAD

**Issue by NapsterLong** [Sunnyyoung/WeChatTweak-macOS#374]
您没有权限打开应用程序“微信”
![image](https://user-images.githubusercontent.com/17425788/140276463-b8644386-15c2-434d-bf39-1c941e5ed519.png)

**Comment by NapsterLong** [comment]
Mac 11.6
微信 3.2.1
插件 1.2.2

**Comment by ZhangTaoK** [comment]
看 FAQ

**Comment by BenjaminX** [comment]
https://github.com/Sunnyyoung/WeChatTweak-macOS/issues/330#issuecomment-955883560

**Comment by ClayMoreBoy** [comment]
重啓電腦

**Comment by Sunnyyoung** [comment]
1. 卸载再安装
2. 重启电脑

基本都可以解决了
