### ISSUE TITLE
安装后提示 “微信.app无法打开”

### ISSUE THREAD

**Issue by bennieniu** [Sunnyyoung/WeChatTweak-macOS#375]
![image](https://user-images.githubusercontent.com/25980157/140881335-76b726a8-c3d0-4da9-a2d4-91d959976d79.png)
通过"sudo wechattweak-cli --install"命令安装后，提示上图，
必须通过uninstall卸载后才可以打开。

**Comment by bennieniu** [comment]
系统版本：12.0.1

**Comment by zhaocongdong** [comment]
> 系统版本：12.0.1

本人10.15.7 ，运行：sudo codesign --sign - --force --deep /Applications/WeChat.app 可以解决微信无法打开问题

**Comment by bennieniu** [comment]
> > 系统版本：12.0.1
> 
> 本人10.15.7 ，运行：sudo codesign --sign - --force --deep /Applications/WeChat.app 可以解决微信无法打开问题

卧槽，解决了，谢谢大佬！！
