### ISSUE TITLE
新版本的微信Version. 3.2.1 安装完成无法打开

### ISSUE THREAD

**Issue by huyifanstar** [Sunnyyoung/WeChatTweak-macOS#377]
新版本的微信 打开闪一下就没了

**Comment by pzxiaoyi** [comment]
+1
系统：12.0.1    M1
微信：3.2.1
直接提示无法打开微信

**Comment by pzxiaoyi** [comment]
> +1 系统：12.0.1 M1 微信：3.2.1 直接提示无法打开微信

使用 sudo codesign --sign - --force --deep /Applications/WeChat.app
已经可以正常使用

**Comment by huyifanstar** [comment]
> > +1 系统：12.0.1 M1 微信：3.2.1 直接提示无法打开微信
> 
> 使用 sudo codesign --sign - --force --deep /Applications/WeChat.app 已经可以正常使用

可以了，多谢
