### ISSUE TITLE
无法打开微信

### ISSUE THREAD

**Issue by yt1a0a** [Sunnyyoung/WeChatTweak-macOS#378]
~~Version 3.2.2 (20221)~~

3.2.2 (20297) Beta 9 正常

**Comment by kmahyyg** [comment]
Same problem here. Kept telling me App can't open. Latest version using M1.

**Comment by ernestyao** [comment]
有同样问题

设备类型：MacBookPro18,3
系统版本：版本12.0.1（版号21A559）
系统语言：zh-Hans
微信版本：[2021-10-17 09:53:03] v3.2.1.16 (19797) #9a86491f79
微信语言：zh-Hans
历史版本：[2021-11-18 15:35:31] v3.2.1.16 (19797) #9a86491f79
网络状态：Reachable via WiFi or Ethernet
显  示  器：*(1512x982)/Retina

**Comment by afarwind** [comment]
有同样的问题
设备类型：MacBookPro（arm64）
系统版本：版本12.0.1（版号21A559）
微信版本：Version. 3.2.1 (19797)

**Comment by tikdoge** [comment]
都不看FQA或者翻翻别人的反馈？

**Comment by ernestyao** [comment]
> 都不看FQA或者翻翻别人的反馈？

FAQ里哪一条提到这个问题？这不是codesign的问题啊。而且你认为我没试过重装？

**Comment by kmahyyg** [comment]
Thanks to author's work. I am really disgusted by someone in this issue, and he got blocked by me.
Today, I'm so glad to announce I found a complete solution to this problem: Uninstall WeChat from My beloved Mac.

**Comment by yt1a0a** [comment]
> Version 3.2.2 (20221)

Downgrade version to Version: 3.2.1 (19796), and reinstall, It works again.

The available version: https://dldir1.qq.com/weixin/mac/WeChatMac.dmg

**Comment by EagleHao** [comment]
解决办法：重启Mac
 
我安装完插件后，微信打不开，卸载插件微信又可以打开，但是没有防撤回。然后我再次安装完插件，微信还是打不开，重启一下电脑，之后就可以打开了，也有防撤回了。

**Comment by D-Crump** [comment]
今天安装后在Intel和M1上都无法打开，看了下其他说重启即可，试了下重启就行了

**Comment by simosun** [comment]
Beta 3.2.2.10 今天升级的版本，无法启动微信了

**Comment by poison501** [comment]
Version. 3.2.2 (20346) 安装插件后微信无法打开
重启后，工作一切正常

**Comment by simosun** [comment]
> 

亲测，已经可用

**Comment by JiangNaa** [comment]
重启电脑就可以了

**Comment by RichieXu** [comment]
借楼问一下新系统12下可以正常使用了吗 微信版本3.2.2（20346）

**Comment by ernestyao** [comment]
感谢楼上几位，的确是重启电脑后就可以正常打开了。另外新系统12是指macOS 12.0.1吧，就是安装微信、安装插件，然后重启电脑就行了。

**Comment by Sunnyyoung** [comment]
1. 卸载再安装
2. 重启电脑

基本都可以解决了

**Comment by Wuyou-HIC** [comment]
> > Version 3.2.2 (20221)
> 
> Downgrade version to 3.2.1 (19796), and reinstall, It works again.
> 
> The available version: https://dldir1.qq.com/weixin/mac/WeChatMac.dmg

Do you still have the Wechat for Mac 3.2.1?
