### ISSUE TITLE
微信Beta 3.2.2.10

### ISSUE THREAD

**Issue by simosun** [Sunnyyoung/WeChatTweak-macOS#381]
能正常安装，但是启动微信时候报错；

**Comment by iszhuzhi** [comment]
ennn，我今天才收到3.2.2版本更新提示，哈哈有了折叠群聊，这功能太强大了

**Comment by simosun** [comment]
> ennn，我今天才收到3.2.2版本更新提示，哈哈有了折叠群聊，这功能太强大了

相比较能多登录账号，我宁愿不要这功能；

**Comment by mzlp** [comment]
Version. 3.2.2 (20338)使用brew方式安装提示成功，打开微信-偏好设置，未找到Tweak设置项

**Comment by simosun** [comment]
> Version. 3.2.2 (20338)使用brew方式安装提示成功，打开微信-偏好设置，未找到Tweak设置项

右击dock上的微信图标，看弹出来的菜单有没有《登录新的账号》，就知道有没有真的挂成功了。

**Comment by simosun** [comment]
重启一下电脑，就可以用了
