### ISSUE TITLE
是否可以封装更多server的接口

### ISSUE THREAD

**Issue by svcvit** [Sunnyyoung/WeChatTweak-macOS#39]
以前一直有用各种聊天机器人，类似[ItChat](https://github.com/littlecodersh/ItChat)，基本都是采用模拟登录web端微信方式进行的封装，经常会因为微信改版而不稳定，是否可以把macos的接收消息，发送消息封装成server的接口，这样感觉会有更多好玩的事情可以做。

**Comment by Sunnyyoung** [comment]
@svcvit 可以是可以，但是工作量挺大的，没太多时间
