### ISSUE TITLE
最新版本微信安装后无法打开

### ISSUE THREAD

**Issue by 81pla** [Sunnyyoung/WeChatTweak-macOS#390]
微信版本3.2.2  使用最新方式安装后打不开，卸载后就可以
<img width="419" alt="QQ20211210-092903@2x" src="https://user-images.githubusercontent.com/17949410/145502362-9062e95b-9c3d-46ca-9df6-6430b4049819.png">

**Comment by Sunnyyoung** [comment]
1. 卸载并重新安装
2. 重启电脑

**Comment by k2y1982** [comment]
卸载微信还是wechattweak?

**Comment by wangleiyun** [comment]
有问题，M1Pro笔记本

**Comment by 81pla** [comment]
重新安装重启后就正常了
