### ISSUE TITLE
安装不成功，mac12.0.1

### ISSUE THREAD

**Issue by zhangguapipi** [Sunnyyoung/WeChatTweak-macOS#391]
zhangguapi@zhangguapideiMac-Pro WeChatTweak-macOS-master % brew install wechattweak-cli
Warning: No available formula with the name "wechattweak-cli".
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.

**Comment by Sunnyyoung** [comment]
`brew install sunnyyoung/repo/wechattweak-cli`
