### ISSUE TITLE
这个链接打不开是怎么回事

### ISSUE THREAD

**Issue by zzlphp** [Sunnyyoung/WeChatTweak-macOS#40]
http://localhost:48065/wechat/search

**Comment by zzlphp** [comment]
urlopen error [Errno 61] Connection refused

**Comment by Sunnyyoung** [comment]
@zzlphp 
1. 检查是否安装 Tweak
2. 安装完有没有重启微信客户端

**Comment by zzlphp** [comment]
1 是不是微信客户端设置里面多了 Tweak 就说明安装好了 Tweak?
2 安装完重启过好几次客户端了

目前还是不可用

**Comment by zzlphp** [comment]
已经重新安装微信客户端,重新安装 Tweak 可以了 !!!  Thanks
