### ISSUE TITLE
付费版本表情导出ok，但无法发送

### ISSUE THREAD

**Issue by halotitee** [Sunnyyoung/WeChatTweak-macOS#400]
![Screen Shot 2021-12-23 at 14 19 08](https://user-images.githubusercontent.com/23644866/147197134-fd33025f-adac-4cbc-a2d4-f28dca83975b.png)

-付费表情，导出之后，以文件形式发送。出现【版权问题】提示。而且对方收不到。部分导出发送ok，部分导出不能正常发送。

-尝试重装 cli 1.2.2，问题依然存在

-MacOS bigSur 11.6.2
-Wechat 3.2.2 (20346) （Store下载）
-Macbook Air Early 2014

**Comment by Sunnyyoung** [comment]
图片资源问题，自己修改一下图片

**Comment by halotitee** [comment]
谢谢指点，已找到解决方案，用下面网站即可

https://ezgif.com/optimize
