### ISSUE TITLE
安装报错 哭了呜呜

### ISSUE THREAD

**Issue by kuangxiaoye** [Sunnyyoung/WeChatTweak-macOS#402]
Error: Invalid cask: /usr/local/Homebrew/Library/Taps/sunnyyoung/homebrew-repo/Casks/applereserver.rb
Cask 'applereserver' is unreadable: undefined method `method_missing_message' for Utils:Module
Error: Invalid cask: /usr/local/Homebrew/Library/Taps/sunnyyoung/homebrew-repo/Casks/swift-runtime-support.rb
Cask 'swift-runtime-support' is unreadable: undefined method `method_missing_message' for Utils:Module
Error: Invalid cask: /usr/local/Homebrew/Library/Taps/sunnyyoung/homebrew-repo/Casks/wechattweak-cli.rb
Cask 'wechattweak-cli' is unreadable: undefined method `method_missing_message' for Utils:Module
Error: Cannot tap sunnyyoung/repo: invalid syntax in tap!

**Comment by Sunnyyoung** [comment]
你是想安装 WeChatTweak 还是 AppleReserver
