### ISSUE TITLE
安装后微信打不开了

### ISSUE THREAD

**Issue by 344108150** [Sunnyyoung/WeChatTweak-macOS#407]
安装后没有效果，我就退出微信，然后重新打开就打不开了，没有任何提示

**Comment by remember-5** [comment]
卸载重新装，建议看下FAQ https://github.com/Sunnyyoung/WeChatTweak-macOS#faq

**Comment by Silence566** [comment]
打不开重启下电脑就行了

**Comment by KingAmo** [comment]
在终端执行一下下面的命令：
```
sudo codesign --sign - --force --deep /Applications/WeChat.app
```

**Comment by jnchen** [comment]
> 在终端执行一下下面的命令：
> 
> ```
> sudo codesign --sign - --force --deep /Applications/WeChat.app
> ```

有效
