### ISSUE TITLE
sudo make install

### ISSUE THREAD

**Issue by laozhongyi-0326** [Sunnyyoung/WeChatTweak-macOS#409]
sudo make install
Makefile installation has been deprecated!!!
For more information: https://github.com/Sunnyyoung/WeChatTweak-CLI.
也不知道该怎么整了，微信卸载重新装也不行，大概率是之前装过旧版本

**Comment by Sunnyyoung** [comment]
额……说明不是写得很清楚吗？

**Comment by laozhongyi-0326** [comment]
大佬，那我这后面怎么操作呢，之前都是新装的都很顺利，现在该怎么操作。

**Comment by laozhongyi-0326** [comment]
@Sunnyyoung 说明只知道弃用了，但是我不知道该怎么操作了。

**Comment by laozhongyi-0326** [comment]
> 额……说明不是写得很清楚吗

**Comment by Sunnyyoung** [comment]
https://github.com/Sunnyyoung/WeChatTweak-CLI 有新的安装说明
