### ISSUE TITLE
升级后重装的话，我没操作成功

### ISSUE THREAD

**Issue by laozhongyi-0326** [Sunnyyoung/WeChatTweak-macOS#410]
`git clone https://github.com/Sunnyyoung/WeChatTweak-macOS.git`
![image](https://user-images.githubusercontent.com/34592750/149444317-d848955f-17fc-4799-a6e5-9241dc9aed02.png)
`cd WeChatTweak-macOS/`
`sudo make install`
![image](https://user-images.githubusercontent.com/34592750/149444432-a7d21656-1e2d-406f-be84-b38da37d3f59.png)
`sudo wechattweak-cli --install`
![image](https://user-images.githubusercontent.com/34592750/149444213-a79e3489-8c79-48f7-b347-9da7c3f92a1a.png)

**Comment by Sunnyyoung** [comment]
执行一下 `brew install sunnyyoung/repo/swift-runtime-support`
