### ISSUE TITLE
实在搞不定，再开一个tk

### ISSUE THREAD

**Issue by jameslhc** [Sunnyyoung/WeChatTweak-macOS#411]
重新安装后还是不行，不知道怎么办了
<img width="566" alt="截屏2022-01-14 20 20 05" src="https://user-images.githubusercontent.com/48267688/149514755-82c71463-5acc-4126-a54b-2ab7ba5c8873.png">

**Comment by Sunnyyoung** [comment]
重启下电脑

**Comment by jameslhc** [comment]
> 重启下电脑

重启过了，看到其他issue有过这个问题重启好了，我这个就不行。。。真是很奇怪

**Comment by jameslhc** [comment]
不甘心，刚刚又重试一次OK了。。。
