### ISSUE TITLE
截屏功能异常

### ISSUE THREAD

**Issue by cqiang1993** [Sunnyyoung/WeChatTweak-macOS#412]
通过安装tweak工具之后，使用截屏功能，会提示没有权限，但是确认过隐私设置是允许屏幕录制的，重启多次都没有效果
![截屏2022-01-15 13 53 25](https://user-images.githubusercontent.com/15382148/149610847-fca2c974-7ae6-4a7c-a763-61cb59187a0d.png)

**Comment by lydials** [comment]
个人尝试，把微信的权限关掉再打开，然后重启微信就好了

**Comment by cqiang1993** [comment]
已经多次尝试了，依旧不行

**Comment by cqiang1993** [comment]
> 个人尝试，把微信的权限关掉再打开，然后重启微信就好了

已经多次尝试了，依旧不行

**Comment by GeliBear** [comment]
打开安全隐私，把截屏录制权限的app点那个减号全删掉，然后点加号重新加一遍

**Comment by cqiang1993** [comment]
> 

可以了，谢谢
