### ISSUE TITLE
3.3.0版本安装后没有效果

### ISSUE THREAD

**Issue by liu5656** [Sunnyyoung/WeChatTweak-macOS#415]
试过重新安装、重启都没有效果

**Comment by zhangsusu0416** [comment]
我这里也是今天早晨自动更新升级了微信的3.3.0版本,消息拦截撤回功能完全失效了🤣

**Comment by zhangsusu0416** [comment]
> 

在command窗口重新执行 sudo wechattweak-cli --install  并且重启电脑和微信客户端即可,我已经重新搞好了

**Comment by liu5656** [comment]
多谢，可以了，
最好关闭微信再来安装。
