### ISSUE TITLE
Version. 3.3.0 (20901)微信无法打开

### ISSUE THREAD

**Issue by GeliBear** [Sunnyyoung/WeChatTweak-macOS#416]
微信Version. 3.3.0 (20901)
Mac mini M1
系统版本：12.1 
sudo wechattweak-cli --install 安装后微信提示无法打开。卸载后可以打开

**Comment by xieshenace** [comment]
![image](https://user-images.githubusercontent.com/35596347/149854677-996d7be4-6c96-47ce-94c8-e3f9e8a23c10.png)

先卸载再重新装，按照readme提示安装。

**Comment by xiongwu1** [comment]
我的安装后微信能打开，但是没有生效

**Comment by GeliBear** [comment]
> 关闭微信安装 不行的话重启电脑即可

重启电脑就好了，谢谢
