### ISSUE TITLE
An SSL error has occurred and a secure connection to the server cannot be made

### ISSUE THREAD

**Issue by lmh666nbnb** [Sunnyyoung/WeChatTweak-macOS#418]
Install failed: Download failed with error: Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSErrorFailingURLStringKey=https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/latest/download/WeChatTweak.framework.zip, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDownloadTask <401F6CA5-13E7-410A-B70A-B92D9468DD6C>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDownloadTask <401F6CA5-13E7-410A-B70A-B92D9468DD6C>.<1>"
), NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/latest/download/WeChatTweak.framework.zip, NSUnderlyingError=0x600000700f00 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9836, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9836, _NSURLErrorNWPathKey=satisfied (Path is satisfied), viable, interface: lo0}}, _kCFStreamErrorCodeKey=-9836}

**Comment by Sunnyyoung** [comment]
网络问题

**Comment by GaoZhenguo929** [comment]
我也是安装失败，跟这个报错一样

**Comment by GaoZhenguo929** [comment]
手动make就好了

**Comment by daniellauyu** [comment]
> 手动make就好了

咋手动make

**Comment by Ale-cc** [comment]
> > 手动make就好了
> 
> 咋手动make

我用这个示例手动make就可以了 用cli工具也是这个报错
[手动make安装](https://github.com/Sunnyyoung/WeChatTweak-macOS/issues/410)
