### ISSUE TITLE
3.3.0插件失效啦 大佬

### ISSUE THREAD

**Issue by akudamatata** [Sunnyyoung/WeChatTweak-macOS#422]
我有尝试在3.3.0的微信上重装wechat tweak 
但是并没有成功加载插件 在设置里也没有

**Comment by Sunnyyoung** [comment]
#415

**Comment by zhouxl** [comment]
sudo wechattweak-cli --install，然后重启电脑，依然还没有，3.3.0
从微信官网安装的，然后用app store 的覆盖安装了

**Comment by Sunnyyoung** [comment]
@zhouxl 肯定哪里有问题

**Comment by chance395** [comment]
#415 执行了没效果
哦豁
