### ISSUE TITLE
无法安装，求助！

### ISSUE THREAD

**Issue by Wayne-007** [Sunnyyoung/WeChatTweak-macOS#423]
![image](https://user-images.githubusercontent.com/42962450/150906035-59f89195-6efe-4901-bf5c-02d85313c92b.png)

**Comment by chenshuaikang** [comment]
试着更新一下brew

**Comment by chenshuaikang** [comment]
试着更新一下brew

rm -rf /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
brew update

**Comment by Sunnyyoung** [comment]
检查下 homebrew 是否更新成功
