### ISSUE TITLE
微信3.3.0装了插件登录不上，一登录就提示崩溃，怎么解决？

### ISSUE THREAD

**Issue by jhw621** [Sunnyyoung/WeChatTweak-macOS#424]
![image](https://user-images.githubusercontent.com/8390317/151113879-afc315c3-3f33-4c16-b017-e08722b8b944.png)

**Comment by Sunnyyoung** [comment]
这个不是我的项目导致的……

**Comment by ShineZcx** [comment]
3.3.0好像用不了这个项目了

**Comment by Sunnyyoung** [comment]
@ShineZcx 我用得好好的

**Comment by ShineZcx** [comment]
已经收到邮件了，辛苦了~
