### ISSUE TITLE
微信Version. 3.3.0 (20901)，撤回显示功能异常

### ISSUE THREAD

**Issue by BytePrince** [Sunnyyoung/WeChatTweak-macOS#426]
没有主动撤回过消息，但仍显示消息被撤回。
https://pic.imgdb.cn/item/61fa44292ab3f51d91f2d855.jpg
https://pic.imgdb.cn/item/61fa44252ab3f51d91f2d47b.png

**Comment by Sunnyyoung** [comment]
这个已知 bug，暂时重启解决

**Comment by xsjd-hub** [comment]
重启也解决不了 发消息时间间隔长了就又会出现

**Comment by Sunnyyoung** [comment]
@xsjd-hub 试试最新的版本，尝试修复了
