### ISSUE TITLE
不知道是不是插件的问题

### ISSUE THREAD

**Issue by iOSleep** [Sunnyyoung/WeChatTweak-macOS#427]
<img width="343" alt="WeChateb5f40750835fe0b8b04ea411d4c3f65" src="https://user-images.githubusercontent.com/26478957/152749651-7920befd-1791-4964-ba97-ce0d09b6eed8.png">

不确定这到底是什么

**Comment by kyusenzei** [comment]
我也一样

**Comment by Sunnyyoung** [comment]
什么时候出现的

**Comment by iOSleep** [comment]
@Sunnyyoung 用了最新的插件后，但是我不知道这是提示的什么...

**Comment by Sunnyyoung** [comment]
@iOSleep 开小号建个群模拟下各种情况？我试了好像不能复现😂

**Comment by kyusenzei** [comment]
> @iOSleep 开小号建个群模拟下各种情况？我试了好像不能复现😂

我是屏蔽群消息，把设置改成接收所有消息，然后这个群里有人撤回的时候就会出现

**Comment by iOSleep** [comment]
> > @iOSleep 开小号建个群模拟下各种情况？我试了好像不能复现😂
> 
> 我是屏蔽群消息，把设置改成接收所有消息，然后这个群里有人撤回的时候就会出现

@Sunnyyoung  似乎就是这种情况，我改成跟随聊天设置，就一天没收到了

**Comment by Sunnyyoung** [comment]
@iOSleep @kyusenzei 好，我看看

**Comment by pdszhmilo** [comment]
> @iOSleep @kyusenzei 好，我看看

没错没错,作者大大.我也是遇到这个问题了.今天刚更新最新版本.个人聊天没问题.群组聊天的话.撤回mac系统推送则显示null,群组聊天框则是不显示谁撤回啥消息,但是消息是被拦截成功的...

**Comment by Sunnyyoung** [comment]
各位试试 1.2.5 版本，已经修复。
