### ISSUE TITLE
如果撤回自己的消息，会闪退

### ISSUE THREAD

**Issue by magicalSam** [Sunnyyoung/WeChatTweak-macOS#43]
如果撤回自己的消息，会出现闪退现象。

**Comment by Sunnyyoung** [comment]
`macOS 10.13 (17A365)` + `WeChat 2.3.2 (9414)` 测试没问题。

**Comment by magicalSam** [comment]
谢谢大佬，问题已解决，之前用的是WeChat 2.0.0 有问题，刚升级了WeChat 测试没问题。
