### ISSUE TITLE
安装之后和安装之前没啥区别.....需要卸载重装吗

### ISSUE THREAD

**Issue by shdjllajksd** [Sunnyyoung/WeChatTweak-macOS#430]

**Comment by Sunnyyoung** [comment]
想要什么区别呢？你现在遇到什么问题

**Comment by shdjllajksd** [comment]
> 想要什么区别呢？你现在遇到什么问题

就是安装之后也没有发现多什么功能，撤回什么的都没有。。。

**Comment by Sunnyyoung** [comment]
1. 用的是 App Store 版本微信吗
2. 之前有安装过吗
3. 你是怎么进行安装的，有没有用 wechattweak-cli

**Comment by shdjllajksd** [comment]
> 1. 用的是 App Store 版本微信吗
> 2. 之前有安装过吗
> 3. 你是怎么进行安装的，有没有用 wechattweak-cli

1.是APP Store微信，最新版本
2.之前没有安装过
3.运行 brew install sunnyyoung/repo/wechattweak-cli

**Comment by shdjllajksd** [comment]
> https://cli.tweaks.app
> 
> 有详细的说明，还缺一步：`sudo wechattweak-cli install`

好了，抱歉没有看到这个，感谢
