### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by kid-oh** [Sunnyyoung/WeChatTweak-macOS#431]
执行 sudo wechattweak-cli install 时报错
Error: Missing one of: '--install', '--uninstall'
Help:  --install <install>  Install or Uninstall tweak
Usage: tweak --install --uninstall
  See 'tweak --help' for more information.

**Comment by heshangcode** [comment]
我也是这样，不知道楼主解决了吗

**Comment by kid-oh** [comment]
> 我也是这样，不知道楼主解决了吗

卸载tweak再重新安装
