### ISSUE TITLE
Add Raycast extension support

### ISSUE THREAD

**Issue by sunnyyoung** [sunnyyoung/WeChatTweak-macOS#437]
https://www.raycast.com/store

**Comment by panxlhe** [comment]
+1

**Comment by Jax0rz** [comment]
+2

**Comment by Jax0rz** [comment]
Recast is much better then Alfred .Any date to release the raycast version?

**Comment by absir1949** [comment]
+1

**Comment by Leeiio** [comment]
+1

**Comment by LawrenceLiuQuanzhou** [comment]
+1

**Comment by LawrenceLiuQuanzhou** [comment]
关于Raycast，我个人进行了一些尝试，发现作者为了适配Alfred，本地内置了一个HTTP服务。

你可以本地访问 `http://localhost:48065/wechat/search?keyword={query}` 来模糊搜索联系人，这个跟Alfred的Web search和Raycast的QuickLink其实相似，通过替换 `{query}` 来直接向链接查询。

返回的结果是一个字典，里面包括昵称、头像、用户名和arg什么的，然后可以通过 `http://localhost:48065/wechat/start?session={arg}` 的方式来直接打开微信对应的联系人。

然后我就琢磨着能不能写个脚本让Raycast也支持。

但是想了想，这个流程大致如下：
1. 输入用户名
2. 将用户名和链接组成新的链接
3. GET链接，得到返回的字典
4. 将字典转换成头像+昵称+用户名的形式供用户选择
5. 从用户选中的字典中抽取arg值，并组合成新的链接
6. 打开此链接

问题就出在4上面。

Raycast虽然提供了给脚本传输参数的方法，但是并没有提供进一步选择脚本输出的参数，然后进行进一步行动，这类的方法。

要想实现第四点，必须写Raycast的拓展。

然后我又去找官方的拓展编辑手册，发现Raycast的拓展要用Node JS来写。

问题就出在这里：

**我不会Node JS**🤣。

所以有没有会Node JS的老哥？可以去写一个，实现起来应该不难，Raycast直接提供一个列表的方法，你只要把对应的变量设置成列表的key，然后再完成5, 6就行了。

这两天我去看看入门教程，要是没人写就我来试试，但还是希望能有现成的轮子用。

等一个大佬。🙃

**Comment by Jax0rz** [comment]
我写了个Raycast的微信插件，欢迎大家贡献代码[wechat](https://github.com/Jax0rz/wechat)

**Comment by raffeyang** [comment]
可以关闭issue了，已经正式发布插件到Raycast商店，点击安装。
<p align="center">
<a href="https://www.raycast.com/raffeyang/wechat"><img src="https://www.raycast.com/raffeyang/wechat/install_button@2x.png" height="64" style="height: 64px;" alt=""></a>
</p>
