### ISSUE TITLE
安装失败，求解

### ISSUE THREAD

**Issue by lumoshhx** [Sunnyyoung/WeChatTweak-macOS#438]
WeChatTweak.framework % sudo ./wechattweak-cli --install
Error: Internal error. Invalid state while parsing command-line arguments.
Usage: wechattweak-cli <subcommand>
  See 'wechattweak-cli --help' for more information.

**Comment by Sunnyyoung** [comment]
https://github.com/Sunnyyoung/WeChatTweak-macOS#%E4%BD%BF%E7%94%A8

```bash
$ sudo wechattweak-cli install   # 安装/更新
$ sudo wechattweak-cli uninstall # 卸载
```

**Comment by AmintaCCCP** [comment]
> WeChatTweak.framework % sudo ./wechattweak-cli --install Error: Internal error. Invalid state while parsing command-line arguments. Usage: wechattweak-cli See 'wechattweak-cli --help' for more information.

命令敲错了
$ sudo wechattweak-cli --install   # 安装/更新
少了两个-

**Comment by Sunnyyoung** [comment]
@AmintaCCCP @lumoshhx 看你们当前安装 `wechattweak-cli` 的版本，实际命令以 `--help` 输出为准。

**Comment by 47code** [comment]
您好，遇到无法安装的问题，包括这个issue相同的。
1.执行：brew install sunnyyoung/repo/wechattweak-cli
报错：Error: Failure while executing; `git clone https://github.com/sunnyyoung/homebrew-repo /usr/local/Homebrew/Library/Taps/sunnyyoung/homebrew-repo --origin=origin --template=` exited with 128.

2.下载后，对wechattweak-cli执行：sudo wechattweak-cli install
报错：sudo: wechattweak-cli: command not found

3.执行：sudo ./wechattweak-cli --install
报错：Error: Internal error. Invalid state while parsing command-line arguments.

辛苦看看什么原因，谢谢

**Comment by Sunnyyoung** [comment]
@47code 执行 `sudo ./wechattweak-cli install`

另外错误信息提示很清楚的了。
