### ISSUE TITLE
可不可以把安装教程写的详细一点啊

### ISSUE THREAD

**Issue by tongcheung0218** [Sunnyyoung/WeChatTweak-macOS#439]
初学者完全看不懂 好不容易安装了brew 发现后面的步骤完全执行不起来

**Comment by tongcheung0218** [comment]
感谢作者！

**Comment by Sunnyyoung** [comment]
1. 安装 homebrew
2. 通过 homebrew 安装 `wechattweak-cli`
3. 执行 `sudo wechattweak-cli install` 就可以了

**Comment by tongcheung0218** [comment]
> 

请问第二部如何安装，按作者提供的代码 复制粘贴发现没有用

**Comment by tongcheung0218** [comment]
是因为我的brew安装的有问题吗？我是在gitee上安装的，官方的好像被墙了

**Comment by OndayX** [comment]
> 

brew -v，检查brew的安装情况，如果出版本号就说明brew安装是OK的

**Comment by OndayX** [comment]
> 请问第二部如何安装，按作者提供的代码 复制粘贴发现没有用

这个应该是和网络环境有关，我是安装了好几次才提示成功的，不行的话换个网络环境再尝试

**Comment by 78wee** [comment]
搞了半天$这个指令不用加。为什么作者会在指令前加了个$??? 这让我花了大半天时间才搞定。😂

哭了。

homebrew 安装都很快

**Comment by iszhuzhi** [comment]
第一步 安装homebrew
>>>知乎有个一键安装 homebrew大佬安装 详情查看https://zhuanlan.zhihu.com/p/111014448
【终端直接执行】：  /bin/zsh -c "$(curl -fsSL https://gitee.com/cunkai/HomebrewCN/raw/master/Homebrew.sh)" speed
根据提示随便挑个源、待输入开机密码自动安装

第二步  安装wechattweak-cli 
>>>大佬源地址 https://github.com/Sunnyyoung/WeChatTweak-CLI
【终端直接执行】：brew install sunnyyoung/repo/wechattweak-cli

第三步  安装软件
【终端直接执行】执行：sudo wechattweak-cli install 

致敬大佬，已经安装使用上了，开心😺

切记以上得开启科学上网

**Comment by maykore** [comment]
> 搞了半天$这个指令不用加。为什么作者会在指令前加了个$??? 这让我花了大半天时间才搞定。😂
> 
> 哭了。
> 
> homebrew 安装都很快

卧槽  我也是因为一直复制代码，$这个符号原来不是，搞了好几天，哭

**Comment by dgjj1991** [comment]
用这个成功安装上了，真不容易
