### ISSUE TITLE
亲测重启微信的话还需要手机验证的。

### ISSUE THREAD

**Issue by mkblbj** [Sunnyyoung/WeChatTweak-macOS#44]
重启微信还需要通过手机验证的，这方面无效。
macOS 10.12.6 A1707

**Comment by Sunnyyoung** [comment]
@mkblbj 你在设置页面中打开了免验证开关了吗？

**Comment by mkblbj** [comment]
打开了这个开关依旧无效，我再重装下微信试试。还有就是访问钥匙串的提醒麻烦您提醒下是安全的。再次感谢您做出这么好的插件，造福大众！

**Comment by mkblbj** [comment]
重装微信后打开开关有效了。感谢！🙏
