### ISSUE TITLE
崩溃，提示第三方插件

### ISSUE THREAD

**Issue by s0k** [Sunnyyoung/WeChatTweak-macOS#440]
我是今天刚下载的插件

系统版本：12.2.1 (21D62)

微信版本：Version. 3.3.0 (20901)

<img width="400" alt="image" src="https://user-images.githubusercontent.com/35159280/157000900-b28392cc-973d-46f3-94cd-bf7f8e6b0247.png">

想问一下是否有其他风险，比如封号等？

**Comment by binghan2000** [comment]
20901没出现问题呀

**Comment by s0k** [comment]
> 20901没出现问题呀

我的就那天提示了一次，现在还是没什么问题。
