### ISSUE TITLE
最新版微信3.3.1安装该插件后打不开

### ISSUE THREAD

**Issue by ZijieJin** [Sunnyyoung/WeChatTweak-macOS#441]
命令行里面提示安装完成，然后点击微信图标提示无法打开

**Comment by ZijieJin** [comment]
重新签名即可

**Comment by kEv1nZ0** [comment]
> 重新签名即可，已解决

怎么重新签名啊

**Comment by ZijieJin** [comment]
> > 重新签名即可，已解决
> 
> 怎么重新签名啊

代码里面codesign那一行再跑一遍就行了

**Comment by kEv1nZ0** [comment]
> > > 重新签名即可，已解决
> > 
> > 
> > 怎么重新签名啊
> 
> 代码里面codesign那一行再跑一遍就行了

可以发一下命令嘛，不大懂

**Comment by ZijieJin** [comment]
> > > > 重新签名即可，已解决
> > > 
> > > 
> > > 怎么重新签名啊
> > 
> > 
> > 代码里面codesign那一行再跑一遍就行了
> 
> 可以发一下命令嘛，不大懂

sudo codesign --sign - --force --deep /Applications/WeChat.app

**Comment by kEv1nZ0** [comment]
sudo codesign --force --deep --sign - /Applications/WeChat.app/Contents/MacOS/WeChat
 解决了，感谢回复 ，原来是我打少了个字母，无语

**Comment by ZijieJin** [comment]
> sudo codesign --force --deep --sign - /Applications/WeChat.app/Contents/MacOS/WeChat
> 解决了，感谢回复 ，原来是我打少了个字母，无语

Good!

**Comment by yihuanlin** [comment]
我的提示应用不允许分叉资源什么的诶。我之前Xcode的证书好像有点问题不知道是不是这个原因（我没有注册付费的那种开发者账号）
```
sudo codesign --sign - --force --deep /Applications/WeChat.app
/Applications/WeChat.app: resource fork, Finder information, or similar detritus not allowed
```
