### ISSUE TITLE
Install failed: Execute command: codesign --force --deep --sign - /Applications/WeChat.app/Contents/MacOS/WeChat failed:

### ISSUE THREAD

**Issue by aohun** [Sunnyyoung/WeChatTweak-macOS#445]
Install failed: Execute command: codesign --force --deep --sign - /Applications/WeChat.app/Contents/MacOS/WeChat failed:
<img width="844" alt="image" src="https://user-images.githubusercontent.com/37433539/157358659-3a054226-5bb8-42cc-98e8-4c81b75d216b.png">

**Comment by Fitz77777** [comment]
+1 你解决了吗？
macOS 12.3 (21E230)
微信 3.3.0 AppStore版本

**Comment by Haface** [comment]
同样的问题，老哥你微信版本号多少？

**Comment by Hyejeongdd** [comment]
微信Version. 3.3.1 (21164) 遇到同样的问题

**Comment by dreamingchow** [comment]
这个release下载解压后是WeChatTweak.framework，你们都是咋安装的？

**Comment by Fitz77777** [comment]
从微信官网下载安装包 重新安装可以用。但是没有视频号，版本应该比App Store低？不过能用就行了

**Comment by dreamingchow** [comment]
> 从微信官网下载安装包 重新安装可以用。但是没有视频号，版本应该比App Store低？不过能用就行了

官网显示3.3.0，下载安装后看的版本号是Version. 3.3.1 (21163)，视频号也有，也能正常安装tweak，谢谢。

**Comment by iOSleep** [comment]
> > 从微信官网下载安装包 重新安装可以用。但是没有视频号，版本应该比App Store低？不过能用就行了
> 
> 官网显示3.3.0，下载安装后看的版本号是Version. 3.3.1 (21163)，视频号也有，也能正常安装tweak，谢谢。

谨防自动更新 😭

**Comment by iOSleep** [comment]
官网下的屏蔽自动更新...
- DOMAIN,dldir1.qq.com,REJECT #☹️ update

**Comment by dreamingchow** [comment]
> 官网下的屏蔽自动更新...
> 
> * DOMAIN,dldir1.qq.com,REJECT #☹️ update

这个加在哪里？

**Comment by Sunnyyoung** [comment]
#457

**Comment by lumoshhx** [comment]
求问这个具体怎么解决的？安装失败，然后微信打不开，官网重新下载安装可行？不用从app store下载是吗？后续的更新呢？
