### ISSUE TITLE
maxOS 12.3,安装后 截屏无效

### ISSUE THREAD

**Issue by kayoSun** [Sunnyyoung/WeChatTweak-macOS#449]
maxOS 12.3,安装后 截屏无效

**Comment by printinfo** [comment]
如果是截屏提示没有权限的话，先把权限关了，重新启动微信再打开再重启微信就好了

**Comment by lydials** [comment]
> 如果是截屏提示没有权限的话，先把权限关了，重新启动微信再打开再重启微信就好了

按照上述操作执行后仍然截屏提示没有权限

**Comment by hydra77** [comment]
> 如果是截屏提示没有权限的话，先把权限关了，重新启动微信再打开再重启微信就好了

我今天刚更新，也提示截屏无权限，按照上述操作，还是不行。

**Comment by Fitz77777** [comment]
到安全性与隐私，录制屏幕权限里面把 微信.app 删掉，再打开微信请求权限，授权，再打开微信就好了。

**Comment by hydra77** [comment]
> 到安全性与隐私，录制屏幕权限里面把 微信.app 删掉，再打开微信请求权限，授权，再打开微信就好了。

谢谢，删除后，好了。

**Comment by Hitagismywaifu** [comment]
> 到安全性与隐私，录制屏幕权限里面把 微信.app 删掉，再打开微信请求权限，授权，再打开微信就好了。

删除权限再添加后还是无法截屏，求解

**Comment by SUOYL** [comment]
M1 删除权限再添加后还是无法截屏，求解

**Comment by ljwheyxy** [comment]
> 到安全性与隐私，录制屏幕权限里面把 微信.app 删掉，再打开微信请求权限，授权，再打开微信就好了
Macbook Pro 2019 16寸，有用！

**Comment by ljwheyxy** [comment]
> 



> > 到安全性与隐私，录制屏幕权限里面把 微信.app 删掉，再打开微信请求权限，授权，再打开微信就好了。
> 
> 删除权限再添加后还是无法截屏，求解

M1吗？系统版本多少？

**Comment by Hitagismywaifu** [comment]
> > > 到安全性与隐私，录制屏幕权限里面把 微信.app 删掉，再打开微信请求权限，授权，再打开微信就好了。
> > 
> > 
> > 删除权限再添加后还是无法截屏，求解
> 
> M1吗？系统版本多少？

M1 12.3

**Comment by Matthrews** [comment]
> > 到安全性与隐私，录制屏幕权限里面把 微信.app 删掉，再打开微信请求权限，授权，再打开微信就好了。
> 
> 删除权限再添加后还是无法截屏，求解

worked

**Comment by Sunnyyoung** [comment]
#478
