### ISSUE TITLE
Can`t find Wechat.

### ISSUE THREAD

**Issue by qingsong-xu** [Sunnyyoung/WeChatTweak-macOS#45]
I clone the WeChatTweak codes，and ‘cd WeChatTweak-macOS’ run 'sudo make install' then prompt me "Can not find the WeChat.make: *** [install] Error 1".Please help me to do it. Thank you.

**Comment by Sunnyyoung** [comment]
Check location `/Applications/WeChat.app/Contents/MacOS/WeChat`.

**Comment by mqliutie** [comment]
只有这两个, 没有WeChat.app咋回事啊, 需要重新装微信?
WebStorm.app/           wechatwebdevtools.app/
