### ISSUE TITLE
Alfred无法正常使用

### ISSUE THREAD

**Issue by wu-guibing** [Sunnyyoung/WeChatTweak-macOS#451]
安装后Alfred不能正常使用，系统版本Monterey 12.3，WeChat版本Version. 3.3.0 (20901)，Alfred json压缩已打开。无法正常运行截图如下，能否答疑并出个较完善的教程，谢谢老师。
<img width="805" alt="截屏2022-03-16 12 21 31" src="https://user-images.githubusercontent.com/101689303/158516286-0861c0e2-b97a-450e-ade4-1f9442f1b9b2.png">
<img width="768" alt="截屏2022-03-16 12 20 43" src="https://user-images.githubusercontent.com/101689303/158516292-10854fd1-002f-469f-9d0f-1be62a8b9f08.png">
：

**Comment by Sunnyyoung** [comment]
最新版 macOS 12.3 完全移除了 python2，导致 python 命令不可用，请将 script 中的 python 改成  python3 试试？

**Comment by wu-guibing** [comment]
已经将script中 python全部替换为python3，仍然无法正常运行，截图如下。

<img width="773" alt="截屏2022-03-16 14 06 49" src="https://user-images.githubusercontent.com/101689303/158527383-e2ada45c-dbf2-4260-ad01-8f2e984bf950.png">

**Comment by wu-guibing** [comment]
请教下大佬，相关依赖的py及pyc文件中的路径是否均需做出修改
<img width="672" alt="截屏2022-03-16 14 18 39" src="https://user-images.githubusercontent.com/101689303/158529027-f93e0504-da61-4876-86f7-1f80c496e625.png">
？

**Comment by Sunnyyoung** [comment]
https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/tag/1.3.0
