### ISSUE TITLE
微信版本Version. 3.3.1 (21164)，安装后提示无权限打开

### ISSUE THREAD

**Issue by superwong777** [Sunnyyoung/WeChatTweak-macOS#452]
商店版本Version. 3.3.1 (21164)，不小心勾选了自动更新后，重新安装后提示无权限打开，尝试给wechat自签或者跳过签名均不能解决问题，望大佬查看～谢谢

**Comment by elixzhang** [comment]
> 商店版本Version. 3.3.1 (21164)，不小心勾选了自动更新后，重新安装后提示无权限打开，尝试给wechat自签或者跳过签名均不能解决问题，望大佬查看～谢谢

我也是啊，看来以后要关掉自动更新

**Comment by dreamingchow** [comment]
这个release版本下载解压后是WeChatTweak.framework目录，怎么使用啊？

**Comment by Silvdawn** [comment]
我微信更新了，目前使用无问题；可以看看常问问题6

**Comment by dreamingchow** [comment]
> 我微信更新了，目前使用无问题；可以看看常问问题6

这个release版本下载解压后是WeChatTweak.framework目录，怎么使用啊？

**Comment by Searchld** [comment]
/Applications/WeChat.app: internal error in Code Signing subsystem

**Comment by dreamingchow** [comment]
> > 商店版本Version. 3.3.1 (21164)，不小心勾选了自动更新后，重新安装后提示无权限打开，尝试给wechat自签或者跳过签名均不能解决问题，望大佬查看～谢谢
> 
> 我也是啊，看来以后要关掉自动更新

去官网下，装好后显示版本号Version. 3.3.1 (21163)，可以正常安装sudo wechattweak-cli install。
这里的[WeChatTweak-macOS]要怎么安装啊？

**Comment by panxlhe** [comment]
昨天我也自动更新了害，求解决

**Comment by dreamingchow** [comment]
> 昨天我也自动更新了害，求解决

去官网下，装好后显示版本号Version. 3.3.1 (21163)，可以正常安装sudo wechattweak-cli install。

**Comment by kanzakiken** [comment]
我是重启一下就好了

**Comment by elixzhang** [comment]
> > 昨天我也自动更新了害，求解决
> 
> 去官网下，装好后显示版本号Version. 3.3.1 (21163)，可以正常安装sudo wechattweak-cli install。

商店版本是 21164

**Comment by Sunnyyoung** [comment]
https://github.com/Sunnyyoung/WeChatTweak-CLI/issues/21#issuecomment-1070195448

**Comment by superwong777** [comment]
> 这个release版本下载解压后是WeChatTweak.framework目录，怎么使用啊？

用大佬的brew命令安装，需要良好的网络环境～

**Comment by superwong777** [comment]
> [Sunnyyoung/WeChatTweak-CLI#21 (comment)](https://github.com/Sunnyyoung/WeChatTweak-CLI/issues/21#issuecomment-1070195448)

谢谢大佬回复，昨天做了排他测试，发现APP STORE版本的安装后不能正常打开，官网的就可以；
请方便时处理，感谢

**Comment by Sunnyyoung** [comment]
#457
