### ISSUE TITLE
源码怎么运行

### ISSUE THREAD

**Issue by Mjiac** [Sunnyyoung/WeChatTweak-macOS#454]
前辈好，请问我下载的源码，应该怎么运行去加载插件

**Comment by Sunnyyoung** [comment]
你想直接使用还是调试？

**Comment by MrChenMj** [comment]
使用和调试，请前辈指导一下，谢谢

**Comment by Sunnyyoung** [comment]
1. 安装好 pod 依赖
2. 打开 Xcode 项目文件 build
3. 到目录下执行 `make debug` 即可运行，Xcode 可 attach 微信 Process

**Comment by MrChenMj** [comment]
前辈，但是断点，断不住？无法debug

**Comment by Sunnyyoung** [comment]
make debug 跑起来后，Xcode attach WeChat 就可以在对应代码片段断点了
