### ISSUE TITLE
macOS 12.3官方移除python2,导致alfredworkflow无法使用

### ISSUE THREAD

**Issue by xieqingduan** [Sunnyyoung/WeChatTweak-macOS#455]
macOS 12.3官方移除python2,导致alfredworkflow无法使用，能否出个支持python3的alfredworkflow

**Comment by fjiabinc** [comment]
#是的,我也是更新了新版导致无法使用[](https://files.catbox.moe/kfxlxg.png)

**Comment by fjiabinc** [comment]
是的,我也是更新到了最新的版本,导致无法使用
<img width="886" alt="Xnip2022-03-19_21-43-54" src="https://user-images.githubusercontent.com/38276720/159123661-08b24a44-4ca9-4849-972f-2f583c36e4a8.png">
.

**Comment by xieqingduan** [comment]
@Sunnyyoung 大佬能帮忙解决一下吗，装回python2不能用

**Comment by xieqingduan** [comment]
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/26042834/159128645-b030d09e-a5be-4fa3-a964-f18e80fa1fce.png">

**Comment by xieqingduan** [comment]
安装完python2后，修改如下
<img width="804" alt="image" src="https://user-images.githubusercontent.com/26042834/159153151-2cedd261-3e19-43e8-9597-49a08519cb85.png">

**Comment by fjiabinc** [comment]
> 安装完python2后，修改如下
> <img alt="image" width="804" src="https://user-images.githubusercontent.com/26042834/159153151-2cedd261-3e19-43e8-9597-49a08519cb85.png">

最好还是支持python3

**Comment by Sunnyyoung** [comment]
这两天抽时间重写

**Comment by Sunnyyoung** [comment]
https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/tag/1.3.0
