### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by shubibin** [Sunnyyoung/WeChatTweak-macOS#456]
<img width="1003" alt="iShot2022-03-18 20 13 07" src="https://user-images.githubusercontent.com/70150845/159001095-ce2e4c2b-1adc-4238-93f6-eeada1e9fad8.png">

微信打不开了

**Comment by 1138306694** [comment]
尝试右键Dock栏图标，并且在访达中打开，然后右键微信选择显示简介，然后使用Rosetta打开

**Comment by Sunnyyoung** [comment]
#457
