### ISSUE TITLE
WeChat(3.3.1) App Store Version 安装失败问题

### ISSUE THREAD

**Issue by Sunnyyoung** [Sunnyyoung/WeChatTweak-macOS#457]
临时解决办法：安装官网版本 <https://weixin.qq.com>

**Comment by huangkouping** [comment]
App Store里面的版本，Intel芯片的正常，M1的不行

**Comment by ernestyao** [comment]
是的，从隔壁issue来的，我换成官网一次就安装成功了。2021 MBP 14，macOS 12.3

**Comment by 1138306694** [comment]
m1芯片的，如果不想卸载App Store里的版本，在开发者大大解决m1的问题之前，可以考虑使用Rosetta转译运行商店的版本，亲测可用，我的版本 芯片 m1pro  macOS：12.3  wechat版本 3,3,1

**Comment by gofunbox** [comment]
安装成功 但是菜单没了 不能防撤回了~~

**Comment by 1138306694** [comment]
> 安装成功 但是菜单没了 不能防撤回了~~

emmm俺的还有！！！

**Comment by Rilife** [comment]
qq啥时候整一下呀  大佬

**Comment by fjiabinc** [comment]
最新版本如果不想重新安装出现要签名的话下载这个工具重新把微信签名一下就可以打开,功能都还在
<img width="705" alt="Xnip2022-03-20_20-05-05" src="https://user-images.githubusercontent.com/38276720/159161364-a25cd2f5-9f12-456f-90c7-bceed820ea7d.png">

**Comment by D-Crump** [comment]
> App Store里面的版本，Intel芯片的正常，M1的不行

M1的使用暂时可以使用 Rosetta 打开就可以使用了。

**Comment by p0we7** [comment]
> 最新版本如果不想重新安装出现要签名的话下载这个工具重新把微信签名一下就可以打开,功能都还在 <img alt="Xnip2022-03-20_20-05-05" width="705" src="https://user-images.githubusercontent.com/38276720/159161364-a25cd2f5-9f12-456f-90c7-bceed820ea7d.png">

已经下载不到了，macwk 网站删了。

**Comment by fjiabinc** [comment]
> 

那就没办法啦

**Comment by fjiabinc** [comment]
> > 最新版本如果不想重新安装出现要签名的话下载这个工具重新把微信签名一下就可以打开,功能都还在 <img alt="Xnip2022-03-20_20-05-05" width="705" src="https://user-images.githubusercontent.com/38276720/159161364-a25cd2f5-9f12-456f-90c7-bceed820ea7d.png">
> 
> 已经下载不到了，macwk 网站删了。

如果是m1芯片,我可以打包一份给你啦.

**Comment by 996WJC** [comment]
微信 3.4.0.10 ，我安装了最新版的微信，还是内测版本的，发现按照之前的办法去安装tweak，安装后，微信无法打开了，试了几次，包括重启Mac，也是不行。

**Comment by X-Kay** [comment]
您的邮件我已经收到，我会尽快给您回复。

**Comment by n00d1e5** [comment]
App Store 3.4.0 (21723) 版本目前已经可以正常安装 WeChatTweak。

**Comment by Sunnyyoung** [comment]
@n00d1e5 感谢提醒，确认问题已被修复。

**Comment by HuaiAnGG** [comment]
m1 芯片已经成功安装，微信版本：Version. 3.4.0 (21723)

方法可见：[m1芯片安装防撤回](https://github.com/Sunnyyoung/WeChatTweak-CLI/blob/master/README.md)

**Comment by fjiabinc** [comment]
你好，邮件已收到，会尽快查阅。
