### ISSUE TITLE
请问workflow如何安装呢？

### ISSUE THREAD

**Issue by williamlee1982** [Sunnyyoung/WeChatTweak-macOS#459]
如题，找遍了文档和issue，没有找到work flow在哪里安装，请问该如何处理呢？谢谢

**Comment by greatoe** [comment]
我下载了 master/WeChat.alfredworkflow，然而这是4年前的文件，能安装到 Alfred，但不能正常使用。

**Comment by Sunnyyoung** [comment]
https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/tag/1.3.0 最新版可以用了
