### ISSUE TITLE
安装求助！

### ISSUE THREAD

**Issue by Melonss** [Sunnyyoung/WeChatTweak-macOS#46]
是否能开发朋友圈浏览的功能

**Comment by Sunnyyoung** [comment]
@Melonss 朋友圈的接口已经失效

**Comment by Melonss** [comment]
@Sunnyyoung 另外还想问下，关于聊天记录消失的问题，使用了wiki里的迁移命令，貌似并没有用，打开后还是没有之前的聊天记录

**Comment by Sunnyyoung** [comment]
@Melonss 重启了微信没有

**Comment by Melonss** [comment]
@Sunnyyoung 重启了好几次了，还是没有

**Comment by Sunnyyoung** [comment]
@Melonss 这两天修复需要迁移聊天记录这个问题

**Comment by Melonss** [comment]
好的，非常感谢！

**Comment by Melonss** [comment]
@Sunnyyoung 这个修复完后，更新是否还需要重新安装？

**Comment by Sunnyyoung** [comment]
@Melonss 是的，直接执行 `sudo make install` 就可以更新

**Comment by Melonss** [comment]
非常感谢!

**Comment by Sunnyyoung** [comment]
聊天记录文件的问题已经修复 0ae9a88345703b173060e991a80a9d37a4232a35

**Comment by Melonss** [comment]
@Sunnyyoung 更新了之后似乎还是看不到之前的聊天记录，是否是还需要使用迁移命令？

**Comment by Sunnyyoung** [comment]
这不太科学，麻烦你检查下 `~/Library/Containers/com.tencent.xinWeChat/Data/Library/Application\ Support/com.tencent.xinWeChat` 目录有没有文件。

**Comment by Melonss** [comment]
@Sunnyyoung 有文件的，一个文件夹

**Comment by Melonss** [comment]
@Sunnyyoung 卸载也重新执行过sudo make install命令，仍然没有聊天记录，麻烦看看是不是哪里有问题
