### ISSUE TITLE
微信自动登录问题

### ISSUE THREAD

**Issue by yubeing** [Sunnyyoung/WeChatTweak-macOS#461]
商店版本的微信卸载后安装了官网版本的 并且安装成功，微信里也有tweak菜单了，但是手机却没有自动登录按钮了。 请问这个是否是这个导致的问题呢？

**Comment by yubeing** [comment]
没问题了 已找到了答案

**Comment by xiaojiebin** [comment]
> 没问题了 已找到答案

你是怎么解决的？
