### ISSUE TITLE
安装失败 求助

### ISSUE THREAD

**Issue by hcl666** [Sunnyyoung/WeChatTweak-macOS#463]
我的电脑是英特尔版本
用的brew安装后 找到执行文件执行  sudo ./wechattweak-cli install  就是下面的错误
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/28346798/160852910-e2cd4483-cd86-4bf2-aabe-a73c65d45b99.png">

**Comment by hcl666** [comment]
我的微信是从App Store下载的

**Comment by Sunnyyoung** [comment]
@hcl666 先暂时改用官网版本吧

**Comment by Sunnyyoung** [comment]
#457 App Store 版本 WeChat 3.4.0 (21723) 已经修复该问题。
