### ISSUE TITLE
看不到对方撤回的提示

### ISSUE THREAD

**Issue by Alex-Shen1121** [sunnyyoung/WeChatTweak-macOS#464]
对方已经撤回 并且已经成功拦截了消息。但是看不见提示对方撤回的信息。
己方：
![image](https://user-images.githubusercontent.com/73343630/160947111-dd799076-9133-441f-927f-c3584e5deb50.png)
对方：
<img width="646" alt="image" src="https://user-images.githubusercontent.com/73343630/160947128-89129f83-7cd6-42ce-9a91-bdfb671026ee.png">
版本信息：
系统12.3 M1 Pro
<img width="891" alt="image" src="https://user-images.githubusercontent.com/73343630/160947142-b6905810-8e86-4b66-9d4f-6f7a27ac40a0.png">

**Comment by Alex-Shen1121** [comment]
并且在对方撤回时，会看见群组：（null）的消息弹窗

**Comment by Fenhy** [comment]
bug +1

**Comment by tangwj188** [comment]
+1

**Comment by icodea** [comment]
+1

**Comment by yuanchen1** [comment]
+1

**Comment by yuanchen1** [comment]
测试了一下， 群聊的撤回会提示是撤回信息， 私聊虽然会拦截但是没有提示撤回信息

**Comment by gujiwuqing** [comment]
> 测试了一下， 群聊的撤回会提示是撤回信息， 私聊虽然会拦截但是没有提示撤回信息

目前有发现私聊拦截但是没有提示撤回消息

**Comment by yuanchen1** [comment]
> > 测试了一下， 群聊的撤回会提示是撤回信息， 私聊虽然会拦截但是没有提示撤回信息
> 
> 目前有发现私聊拦截但是没有提示撤回消息

请问一下你是用的哪个版本

**Comment by xiebruce** [comment]
我这边一切正常
<img width="402" alt="image" src="https://user-images.githubusercontent.com/13575500/164891687-316c6ea3-5da6-42e7-b29c-a5d35507dbde.png">

macOS: `11.5.1 (20G80)`
架构：`Intel`
微信：`Version. 3.4.0 (21712)`，dmg包安装，而后通过微信自己提示更新直接点的更新。
Wechattweak version: `1.3.1`

**Comment by gujiwuqing** [comment]
> > > 测试了一下， 群聊的撤回会提示是撤回信息， 私聊虽然会拦截但是没有提示撤回信息
> > 
> > 
> > 目前有发现私聊拦截但是没有提示撤回消息
> 
> 请问一下你是用的哪个版本

Version. 3.4.0 (21712)
<img width="546" alt="image" src="https://user-images.githubusercontent.com/44566835/165325766-398f06ac-8796-4727-af98-8880c672f094.png">

**Comment by yuanchen1** [comment]
> > > > 测试了一下， 群聊的撤回会提示是撤回信息， 私聊虽然会拦截但是没有提示撤回信息
> > > 
> > > 
> > > 目前有发现私聊拦截但是没有提示撤回消息
> > 
> > 
> > 请问一下你是用的哪个版本
> 
> Version. 3.4.0 (21712) <img alt="image" width="546" src="https://user-images.githubusercontent.com/44566835/165325766-398f06ac-8796-4727-af98-8880c672f094.png">



> > > > 测试了一下， 群聊的撤回会提示是撤回信息， 私聊虽然会拦截但是没有提示撤回信息
> > > 
> > > 
> > > 目前有发现私聊拦截但是没有提示撤回消息
> > 
> > 
> > 请问一下你是用的哪个版本
> 
> Version. 3.4.0 (21712) <img alt="image" width="546" src="https://user-images.githubusercontent.com/44566835/165325766-398f06ac-8796-4727-af98-8880c672f094.png">
<img width="317" alt="sc_20220427181034" src="https://user-images.githubusercontent.com/35587570/165495702-46dbf200-1b04-4160-8629-d76e57b59951.png">
是因为我M1的原因的

**Comment by yuanchen1** [comment]
> > > > 测试了一下， 群聊的撤回会提示是撤回信息， 私聊虽然会拦截但是没有提示撤回信息
> > > 
> > > 
> > > 目前有发现私聊拦截但是没有提示撤回消息
> > 
> > 
> > 请问一下你是用的哪个版本
> 
> Version. 3.4.0 (21712) <img alt="image" width="546" src="https://user-images.githubusercontent.com/44566835/165325766-398f06ac-8796-4727-af98-8880c672f094.png">
是因为M1的原因吗
<img width="317" alt="sc_20220427181034" src="https://user-images.githubusercontent.com/35587570/165495837-08bd2b25-ea5f-4510-9aee-91e3c007b2ff.png">

**Comment by zhuiyue132** [comment]
+1

**Comment by zhuiyue132** [comment]
> +1

重启电脑，问题解决
