### ISSUE TITLE
安装助手后微信app意外退出

### ISSUE THREAD

**Issue by YaoCancan** [Sunnyyoung/WeChatTweak-macOS#465]
mac 12.2
wechat:3.4.0
<img width="245" alt="截屏2022-03-31 12 45 02" src="https://user-images.githubusercontent.com/10437409/160978723-ef78c87a-2d12-432f-8c74-dd85bbeb1656.png">

重启 卸载都试过了。

**Comment by bing-zhub** [comment]
遇到了同样的问题

**Comment by Alex-Shen1121** [comment]
是不是m1版本？试一下用Rosetta打开微信

**Comment by YaoCancan** [comment]
> 

Intel哦😯

**Comment by fjiabinc** [comment]
> mac 12.2 wechat:3.4.0 <img alt="截屏2022-03-31 12 45 02" width="245" src="https://user-images.githubusercontent.com/10437409/160978723-ef78c87a-2d12-432f-8c74-dd85bbeb1656.png">
> 
> 重启 卸载都试过了。



> 

需要重新给微信签名就可以用啦

**Comment by YaoCancan** [comment]
> > mac 12.2 wechat:3.4.0 <img alt="截屏2022-03-31 12 45 02" width="245" src="https://user-images.githubusercontent.com/10437409/160978723-ef78c87a-2d12-432f-8c74-dd85bbeb1656.png">
> > 重启 卸载都试过了。
> 
> > 
> 
> 需要重新给微信签名就可以用啦

签了

**Comment by YaoCancan** [comment]
降级3.3可用，但是撤回的消息看不到，null
