### ISSUE TITLE
LaunchBar 报错

### ISSUE THREAD

**Issue by jkhnfk** [sunnyyoung/WeChatTweak-macOS#468]
运行提供的 LaunchBar Action 时，输入字符后报错。如下图。
<img width="532" alt="image" src="https://user-images.githubusercontent.com/28684021/161887432-63925930-7604-40fc-9707-76b3eb229d56.png">

An error occurred while running “WeChatTweak”
TypeError: undefined is not a function (near '...result.data.map...') (line 19).

您好。请问这是啥原因？
谢谢。

**Comment by Sunnyyoung** [comment]
LaunchBar 已经没有在用了，后续应该不考虑维护，有能力的话可以给我提 Pull Request～

**Comment by jkhnfk** [comment]
因为对github不熟，试着操作了一下，不知道对不对。

**Comment by sunnyyoung** [comment]
#502
