### ISSUE TITLE
安装求助一下，macOS 12.3.1，微信官方下载的3.3.0版本微信

### ISSUE THREAD

**Issue by ken0000000** [Sunnyyoung/WeChatTweak-macOS#469]

**Comment by ken0000000** [comment]
<img width="578" alt="QQ20220406-115038@2x" src="https://user-images.githubusercontent.com/49803506/161892375-3f3827c5-0c04-47a0-adea-8a42bea0c98d.png">

**Comment by ken0000000** [comment]
都是最新下载的安装文件，就是不能安装成功，「brew」都是安装好的

**Comment by Liam0205** [comment]
执行

```
sudo wechattweak-cli --install
```

注意 `install` 之前的两个 hyphen。

**Comment by ken0000000** [comment]
感谢大哥🙏

**Comment by Sunnyyoung** [comment]
> 执行
> 
> ```
> sudo wechattweak-cli --install
> ```
> 
> 注意 `install` 之前的两个 hyphen。

最新的 CLI 应该是执行 `sudo wechattweak-cli install`

**Comment by Liam0205** [comment]
> > 执行
> > ```
> > sudo wechattweak-cli --install
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 注意 `install` 之前的两个 hyphen。
> 
> 最新的 CLI 应该是执行 `sudo wechattweak-cli install`

他的报错提示，显然不是最新版本的啦……
