### ISSUE TITLE
无法搜索到微信聊天记录

### ISSUE THREAD

**Issue by Melonss** [Sunnyyoung/WeChatTweak-macOS#47]
今天下午更新10.13官方补丁后使用Alfred搜索联系人一直显示Searching，已重装测试过，仍然存在此问题，请查下是否出问题了，另外...老问题，聊天记录仍然没正常显示以前的记录>.<

**Comment by Melonss** [comment]
已经能搜索到联系人，但是历史记录仍然不行

**Comment by Sunnyyoung** [comment]
无法复现
