### ISSUE TITLE
求助  安装失败 

### ISSUE THREAD

**Issue by lixiaole12** [Sunnyyoung/WeChatTweak-macOS#471]
<img width="563" alt="WechatIMG12475" src="https://user-images.githubusercontent.com/29861213/161919461-a357f3b5-51cd-4dad-b8f7-6e7bb783160d.png">
<img width="494" alt="WechatIMG12477" src="https://user-images.githubusercontent.com/29861213/161919483-83bc1725-fda6-438a-9223-f01694d9a82e.png">

**Comment by lixiaole12** [comment]
已解决，谷歌下载个包就行了
<img width="240" alt="image" src="https://user-images.githubusercontent.com/29861213/162678172-0788a134-e43e-4397-ae36-8c1d62168ccf.png">

**Comment by fanghengwei** [comment]
请问在哪儿下这个包？我也遇到了同样的问题

**Comment by lixiaole12** [comment]
> 问题在哪里下这个包？我也遇到了同样的问题

谷歌，你把错误信息复制上去搜一下就看到了
