### ISSUE TITLE
新版本 3.4 无法安装,显示 installment has been depreciated

### ISSUE THREAD

**Issue by vvjyun** [Sunnyyoung/WeChatTweak-macOS#476]

**Comment by Sunnyyoung** [comment]
Makefile installation has been deprecated!!!
For more information: https://github.com/Sunnyyoung/WeChatTweak-CLI.

哪里没看明白？

**Comment by vvjyun** [comment]
最新版 3.4.0(21654) Beta10 安装不了,新版本有识别二维码 搜一搜公众号小程序朋友圈等重大功能的更新

> Makefile installation has been deprecated!!! For more information: https://github.com/Sunnyyoung/WeChatTweak-CLI.
> 
> 哪里没看明白？

**Comment by vvjyun** [comment]
> Makefile installation has been deprecated!!! For more information: https://github.com/Sunnyyoung/WeChatTweak-CLI.
> 
> 哪里没看明白？

教程对于编程小白用户来说有些难,看的其他网站和公众号的教程比如这个https://www.macdo.cn/43210.html,发现之前 3.3 的版本可以安装,更新了 3.4 版本发现没有 WeChatTweak 了,原来的方法也安装不了了.公众号名叫Mac 的作者说是还没适配 3.4 新版本

**Comment by Sunnyyoung** [comment]
3.4.0 我用得好好的，文档和安装流程我想想怎么优化吧

**Comment by vvjyun** [comment]
> 3.4.0 我用得好好的，文档和安装流程我想想怎么优化吧

小白用户的电脑一般都没安装 homebrew,安装个 homebrew 以及学会怎么用 homebrew 感觉就难倒一大堆小白了,看了很多博客 B 站评论公众号留言绝大部分人都不会安装,还有 UP 主和公众号博客文章介绍很复杂的安装教程比如这个https://mp.weixin.qq.com/s/DndTa8dUROsjJ4hT-fkH_g  
https://www.bilibili.com/video/BV1hL4y17778?share_source=copy_web   

2Remove file attributes: xattr -d com.apple.quarantine wechattweak-cli 3Make sure the binary executable: chmod +x wechattweak-cli 手动安装这两个步骤都不会操作,是要有什么软件打开吗?

**Comment by willsame** [comment]
homebrew 安装有什么难的？安装不了的，基本都是自己的网络环境不行，需要翻墙，安装homebrew后才是最简单的安装方式了，我觉得不会弄的，还是别折腾了，老老实实用官方版本，不蛮好的吗，想用防撤回的，要么自己学下，要么叫别人帮忙，开源作者的文档写的这么明白了，都整不明白命令行的，还是别玩了吧

**Comment by Sunnyyoung** [comment]
@vvjyun #364 后续增加 PKG 安装方式，可以关注下～
