### ISSUE TITLE
最新系统+最新微信版本安装插件后，无法使用微信自带的截图功能

### ISSUE THREAD

**Issue by HelloWilliam** [Sunnyyoung/WeChatTweak-macOS#478]
macOS:12.3.1
wechat:3.3.1

1、安装插件后，无法使用微信自带的截屏功能，想截图，一直提示我去安全隐私勾选屏幕权限，我也一直反复确认去勾选，最终还是无效
2、卸载插件后，仍然无法使用，只有重新安装微信，才能正常使用截图

**Comment by masterdavidz** [comment]
macos :11.6.1
wechat:3.3.1
同样无法截图

**Comment by cnyyk** [comment]
报告同样问题。

反复确认勾选，最终仍然无效。

**Comment by cnyyk** [comment]
```bash
sudo rm -rf /Applications/WeChat.app

brew install wechat --force

sudo wechattweak-cli install
```
上面执行之后，

1. 将隐私里的微信删除，重新加入。
2. ctrl + 右键点击，打开，允许

问题解决。

**Comment by HelloWilliam** [comment]
```
brew install wechat --force
```
这个是安装的不是最新版的微信吧？
@cnyyk

**Comment by zhangsubo** [comment]
MacOS：12.3.1
WeChat：Version. 3.4.0 (21712)
同样问题

**Comment by cnyyk** [comment]
是的。建议 @Sunnyyoung 在某个位置标注，无法截图的，从隐私里移除微信重新加入注入后的微信即可。无需重装。

背景：
5 天未开机，今天开机，提示 3.4.0.x 可用。
遂升级之。
命令行 
```bash
brew upgrade wechattweak-cli

sudo wechattweak-cli install
```
重新打开后，提示无法截图，实际上隐私里面已经允许了。
于是：
**```打开安全隐私，屏幕，删除微信，重新添加微信```**
搞定。

**Comment by Sunnyyoung** [comment]
@cnyyk 嗯，按照这个思路，我在 CLI 增加了这一步的操作 https://github.com/Sunnyyoung/WeChatTweak-CLI/commit/eb5010dc08e0677eb8c896e099e0576f8f97e976

**Comment by cnyyk** [comment]
> @cnyyk 嗯，按照这个思路，我在 CLI 增加了这一步的操作 [Sunnyyoung/WeChatTweak-CLI@eb5010d](https://github.com/Sunnyyoung/WeChatTweak-CLI/commit/eb5010dc08e0677eb8c896e099e0576f8f97e976)

棒棒哒

**Comment by HelloWilliam** [comment]
@cnyyk @Sunnyyoung 你们都是大神啊

**Comment by xiebruce** [comment]
老实说，微信&QQ截图，箭头都设置的最小了，还这么粗大，我真是受不了，我是喜欢在截图用箭头，用框框，圈圈的做标记的，但这么粗大的箭头经常会挡住文字
<img width="272" alt="image" src="https://user-images.githubusercontent.com/13575500/164386247-0bc6f843-d1f8-401c-9577-84aaed701135.png">

我平时截图一直用xnip，细至1px，粗至50px，可粗可细，随便调，还能滚动截图
<img width="309" alt="image" src="https://user-images.githubusercontent.com/13575500/164386531-ff374c45-52ee-4e18-8716-dea2ab1c5873.png">

**Comment by Sunnyyoung** [comment]
https://github.com/Sunnyyoung/WeChatTweak-CLI/commit/eb5010dc08e0677eb8c896e099e0576f8f97e976 下个 CLI 版本中发布。

**Comment by 799964990** [comment]
> @cnyyk 嗯，按照这个思路，我在 CLI 增加了这一步的操作 [sunnyyoung/WeChatTweak-CLI@eb5010d](https://github.com/sunnyyoung/WeChatTweak-CLI/commit/eb5010dc08e0677eb8c896e099e0576f8f97e976)

你好，请问一下，这个文件全路径是什么，
