### ISSUE TITLE
HighSierra 无法打开微信

### ISSUE THREAD

**Issue by caesarjing** [Sunnyyoung/WeChatTweak-macOS#48]
![image](https://user-images.githubusercontent.com/3026356/31485057-1aaf9034-af65-11e7-8817-2320075a6bbc.png)
如图，无法打开微信

**Comment by googooog** [comment]
微信更新后程序失效了

**Comment by 0u0u0** [comment]
同10.13，微信更新后重新安装，一切正常。

**Comment by caesarjing** [comment]
还是不好用啊 @0u0u0 macOS有执行什么脚本么？

**Comment by 0u0u0** [comment]
@caesarjing 没有啊，就是直接  sudo

**Comment by Sunnyyoung** [comment]
No issue found.
