### ISSUE TITLE
M1不能安装的看过来，这里有解决方案！！！！！！！！！！！！！

### ISSUE THREAD

**Issue by nodeInLive** [Sunnyyoung/WeChatTweak-macOS#480]
需要在 应用程序 里找到微信.app，显示简介，勾选 使用Rosetta打开

**Comment by mwpgxl** [comment]
只想说老哥牛逼, 老哥好人

**Comment by BenjaminX** [comment]
这就是转移使用 X86 的版本了啊，微信 App Store 版本是 Universal 版的，意思就是一个包里包含了 X86 + ARM 两套。

**Comment by mayonghua** [comment]
internal error in Code Signing subsystem 一直提示这个怎么处理,,,,,, 我下载的是 App Store 的

**Comment by mayonghua** [comment]
> 

你的微信在哪下载的,通过哪种方式安装的

**Comment by thouger** [comment]
可以装啊，直接装没问题啊

**Comment by nodeInLive** [comment]
appstore安装的

**Comment by jnchen** [comment]
appStore里面安的，不用x86打不开

**Comment by chenrui333** [comment]
右击 app, click on `get info`, then `Open using Rosetta`.

![image](https://user-images.githubusercontent.com/1580956/164580460-f426429a-9f37-48c1-b081-ddc28e3de15a.png)
