### ISSUE TITLE
依旧是撤回问题

### ISSUE THREAD

**Issue by TurkeyD** [sunnyyoung/WeChatTweak-macOS#481]
![image](https://user-images.githubusercontent.com/69117862/163569208-557f6e0d-7973-4595-975a-506694f44075.png)
安装的时候 显示这个  
使用rosetta打开 倒是能登陆微信 并且撤回可以使用
![image](https://user-images.githubusercontent.com/69117862/163569699-9e65378c-2897-4257-a127-2e48e6cfe0a8.png)
![image](https://user-images.githubusercontent.com/69117862/163569262-29127d76-6c18-4a91-91a5-c12ece36062b.png)
问题是撤回不提示~~
使用通知栏的话  提示数组
![image](https://user-images.githubusercontent.com/69117862/163569581-6f758669-ef1f-4e41-ad13-02fc3bd2760f.png)
![image](https://user-images.githubusercontent.com/69117862/163569440-3ec8e2da-2393-4fe3-9d69-447f912fb111.png)
不知道是哪里的问题  我看不止我一个出现这种问题

**Comment by SugarZeal328** [comment]
同样的情况，MacBook Air M1，系统版本12.3.1，微信版本3.4.0 (21723)
