### ISSUE TITLE
version3.4.0(去官网下载)成功安装插件 (1.3.0) 到 3.4.0 微信。

### ISSUE THREAD

**Issue by mayonghua** [Sunnyyoung/WeChatTweak-macOS#485]
M1  Pro MacBook Pro 12.3.1 (21E258) 成功安装插件 (1.3.0) 到 3.4.0 微信。

操作如下
取消 Open in Rosetta
sudo wechattweak-cli install

**Comment by DWTennant** [comment]
intel 微信安装失败！

**Comment by ZijieJin** [comment]
同，我M1pro的笔记本安装成功，intel的Mac mini 2018安装失败

**Comment by ChunShingLee** [comment]
安装了打不开啊。。。

**Comment by dtcui** [comment]
mac intel 微信安装失败

**Comment by Hiddensu** [comment]
sudo wechattweak-cli install
intel 3.4.0安装成功，感谢！！！

**Comment by xiebruce** [comment]
> 同，我M1pro的笔记本安装成功，intel的Mac mini 2018安装失败

我认为安装成功和失败，主要是要看微信版本+macOS版本，而不是看M1还是Intel，更不是看是Macbook Pro还是mini

**Comment by ZijieJin** [comment]
1.3.1版本插件安装成功

**Comment by freedomct** [comment]
sudo wechattweak-cli install
intel 3.4.0安装成功，感谢！！！

**Comment by Sunnyyoung** [comment]
请检查 WeChat 客户端是否为 App Store 最新版本 3.4.0 (21723)，或者官网最新版本。

**Comment by YHLY** [comment]
<img width="550" alt="image" src="https://user-images.githubusercontent.com/13590902/165431581-78238880-2f4b-4dbc-80ef-3c34a18fe37f.png">
<img width="741" alt="image" src="https://user-images.githubusercontent.com/13590902/165431466-8dab461f-89e2-4ddc-859b-0691477b5b7f.png">

<img width="260" alt="image" src="https://user-images.githubusercontent.com/13590902/165431398-5ffe74b3-2929-4f5d-b3db-5d16d5357338.png">

**Comment by tttttb** [comment]
m1 pro微信3.4.0 app store版安装1.3.1成功，但是没有免认证登陆，每次打开都需要在手机上弹窗点一下。
