### ISSUE TITLE
fishhook 版本太旧

### ISSUE THREAD

**Issue by MartinLau7** [Sunnyyoung/WeChatTweak-macOS#486]
fishhook 需要更新下版本，不然在 12.3+ 上就算你注入成功也会直接闪退 @Sunnyyoung

**Comment by MartinLau7** [comment]
https://github.com/facebook/fishhook

**Comment by missuo** [comment]
可以了，谢谢大佬。

**Comment by Sunnyyoung** [comment]
感谢反馈，已经修复更新 https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/tag/1.3.1
