### ISSUE TITLE
我的可以，重新安装下，先卸载 sudo wechattweak-cli uninstall，然后重新安装 下 $ brew install sunnyyoung/repo/wechattweak-cli ，然后重新安装下 brew reinstall --cask wechattweak-cli，再更新下 sudo wechattweak-cli install ，我这么操作的，就可以了，不然也是一样的打开失败

### ISSUE THREAD

**Issue by dabenliu** [Sunnyyoung/WeChatTweak-macOS#488]
我的可以，重新安装下，先卸载 sudo wechattweak-cli uninstall，然后重新安装 下 $ brew install sunnyyoung/repo/wechattweak-cli ，然后重新安装下 brew reinstall --cask wechattweak-cli，再更新下 sudo wechattweak-cli install ，我这么操作的，就可以了，不然也是一样的打开失败

_Originally posted by @willsame in https://github.com/Sunnyyoung/WeChatTweak-macOS/issues/482#issuecomment-1101020399_

**Comment by Sunnyyoung** [comment]
?

**Comment by sparkshou** [comment]
> brew reinstall --cask wechattweak-cli

过程中 微信开着关着呀？
