### ISSUE TITLE
😂更新了正式版最新版本微信，重新安装成功了，电脑也重启过了，但是好像是没生效，是什么问题🐴

### ISSUE THREAD

**Issue by ChunShingLee** [sunnyyoung/WeChatTweak-macOS#490]
设备类型：MacBookPro14,1
系统版本：版本12.2.1（版号21D62）
系统语言：zh-Hans
微信版本：[2022-04-21 16:45:16] v3.4.0.12 (21765) #549bdcee69 
微信语言：zh-Hans
历史版本：[2022-04-19 16:55:07] v3.4.0.17 (21712) #798d935741
网络状态：Reachable via WiFi or Ethernet
显  示  器：*(1920x1080)

**Comment by Sunnyyoung** [comment]
没生效指的是什么

**Comment by lizhaode** [comment]
就是撤回的内容还是看不到

我也遇到了相同的情况
