### ISSUE TITLE
微信自带截图功能失效

### ISSUE THREAD

**Issue by Liyou-ZY** [sunnyyoung/WeChatTweak-macOS#491]
系统版本为Monterey12.3，安装完插件后一直显示截图功能没有权限，系统设置中授予屏幕录制权限后依旧如此。

**Comment by xiebruce** [comment]
先把微信的屏幕录制权限删掉，再重新添加一次试试

**Comment by ji8czi** [comment]
系统版本12.3.1有相同问题，已近删除重新添加也是不行

**Comment by kanzakiken** [comment]
同12.3,也有这个问题,虽然平时自己并不用微信自带的截图

**Comment by psxjoy** [comment]
> 先把微信的屏幕录制权限删掉，再重新添加一次试试

有效，谢谢！

**Comment by xiebruce** [comment]
> > 先把微信的屏幕录制权限删掉，再重新添加一次试试
> 
> 有效，谢谢！

macOS、微信、以及WeChatTweak分别是什么版本？
Mac 是M1还是Intel？
说一下这些信息，有助于大家判断为什么你的可以，而他们的就不行

**Comment by psxjoy** [comment]
> 



> > > 先把微信的屏幕录制权限删掉，再重新添加一次试试
> > 
> > 
> > 有效，谢谢！
> 
> macOS、微信、以及WeChatTweak分别是什么版本？ Mac 是M1还是Intel？ 说一下这些信息，有助于大家判断为什么你的可以，而他们的就不行

macOS：12.3.1（Intel）
微信：3.4.0
WeChatTweak：1.3.1

**Comment by xiebruce** [comment]
> 

我还漏说了一点，你是appstore安装还是dmg安装(直接微信提示更新那安装也属于非appstore)

**Comment by xiebruce** [comment]
> > 
> 
> > > > 先把微信的屏幕录制权限删掉，再重新添加一次试试
> > > 
> > > 
> > > 有效，谢谢！
> > 
> > 
> > macOS、微信、以及WeChatTweak分别是什么版本？ Mac 是M1还是Intel？ 说一下这些信息，有助于大家判断为什么你的可以，而他们的就不行
> 
> macOS：12.3.1（Intel） 微信：3.4.0 WeChatTweak：1.3.1

我还漏说了一点，你是appstore安装还是dmg安装(直接微信提示更新那安装也属于非appstore)

**Comment by jourdon** [comment]
> 

和楼上同样的问题。appstore 安装的，截图功能失效，权限删除重新添加也不行。
