### ISSUE TITLE
M1芯片 系统Monterey 12.1 安装报错

### ISSUE THREAD

**Issue by wb595755591** [Sunnyyoung/WeChatTweak-macOS#493]
报错信息如下：
Error: Internal error. Invalid state while parsing command-line arguments.
Usage: wechattweak-cli <subcommand>
  See 'wechattweak-cli --help' for more information.

**Comment by Sunnyyoung** [comment]
错误信息不是说得很清楚吗？

**Comment by wb595755591** [comment]
憨批了。😂
