### ISSUE TITLE
Install failed: Execute command: codesign --force --deep --sign - /

### ISSUE THREAD

**Issue by nmww** [sunnyyoung/WeChatTweak-macOS#494]
sudo wechattweak-cli install  
------ Download ------
------ Unzip ------
Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS
------ Backup ------
WeChat.bak exists, skip it...
------ Remove Codesign ------
Execute command: codesign --remove-sign /Applications/WeChat.app/Contents/MacOS/WeChat
------ Insert Dylib ------
Binary is a fat binary with 2 archs.
Binary already contains a load command for that dylib. Skip it.
Binary already contains a load command for that dylib. Skip it.
Added LC_LOAD_DYLIB to all archs in /Applications/WeChat.app/Contents/MacOS/WeChat
------ Add Codesign ------
Execute command: codesign --force --deep --sign - /Applications/WeChat.app/Contents/MacOS/WeChat
Install failed: Execute command: codesign --force --deep --sign - /Applications/WeChat.app/Contents/MacOS/WeChat failed: {
    NSAppleScriptErrorAppName = "wechattweak-cli";
    NSAppleScriptErrorBriefMessage = "/Applications/WeChat.app/Contents/MacOS/WeChat: internal error in Code Signing subsystem";
    NSAppleScriptErrorMessage = "/Applications/WeChat.app/Contents/MacOS/WeChat: internal error in Code Signing subsystem";
    NSAppleScriptErrorNumber = 1;
    NSAppleScriptErrorRange = "NSRange: {0, 97}";
}

**Comment by zr19960628** [comment]
发现同样问题 微信版本3.4.1

**Comment by zr19960628** [comment]
微信版本3.4也不行
