### ISSUE TITLE
微信官网下载的3.4,intel的macOS12.3.1 可以多开,但是没有tweak菜单....

### ISSUE THREAD

**Issue by sparkshou** [Sunnyyoung/WeChatTweak-macOS#496]
撤回当然也无效....

**Comment by Sunnyyoung** [comment]
有详细截图吗

**Comment by sparkshou** [comment]
> 

<img width="653" alt="image" src="https://user-images.githubusercontent.com/20182392/165272571-f99b2c6b-51b2-4867-9153-62f4f2d650e2.png">

这是双开的截图和上面的菜单栏……

**Comment by Sunnyyoung** [comment]
<img width="681" alt="image" src="https://user-images.githubusercontent.com/5926284/165273668-da8907cb-b2ce-4651-8e52-b278c469f946.png">

你是搞混了吗？

**Comment by sparkshou** [comment]
> 

啊~~~~我是之前用过,是在帮助后面有一个菜单的……谢谢大佬,找到了!!!感谢
