### ISSUE TITLE
撤回的时候没有提示

### ISSUE THREAD

**Issue by Hanyu96** [sunnyyoung/WeChatTweak-macOS#497]
macos 11.6.5 intel
微信3.4.0
对方已经撤回的消息，我这边看不到撤回了

**Comment by zz412000428** [comment]
macOS 12.3.1 intel
微信3.4.0
确认可以拦截撤回消息

**Comment by Kerwin1202** [comment]
macOS 12.5 m1
微信3.4.1
确认可以拦截撤回消息 但是没有已拦截提示 消息还在

**Comment by ashanyue** [comment]
macos 12.0.1
微信版本 3.5.5

可以防撤回，但是聊天里面没有标记消息已经撤回
