### ISSUE TITLE
更新微信至3.4以后安装插件后无法打开微信

### ISSUE THREAD

**Issue by lait233** [sunnyyoung/WeChatTweak-macOS#498]
<img width="260" alt="image" src="https://user-images.githubusercontent.com/31282366/165511192-75747796-d9e9-4a3e-b6c5-607e5bda3f11.png">
如图。
MacBook Pro 16寸 2019  32g
macos：12最新版（intel）
微信版本：最新3.4

使用sudo wechattweak-cli --install 安转小助手后如图所示无法打开微信。安装过程是一切顺利的
```shell
Password:
------ Backup ------
Created WeChat.bak...
------ Download ------
------ Unzip ------
Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS
------ Insert Dylib ------
Binary is a fat binary with 2 archs.
LC_CODE_SIGNATURE load command found. Remove it.
LC_CODE_SIGNATURE load command found. Remove it.
Added LC_LOAD_DYLIB to all archs in /Applications/WeChat.app/Contents/MacOS/WeChat
------ Codesign ------
Execute command: cp /Applications/WeChat.app/Contents/MacOS/WeChat /tmp/WeChat
Execute command: codesign --force --deep --sign - /tmp/WeChat
Execute command: cp /tmp/WeChat /Applications/WeChat.app/Contents/MacOS/WeChat
Install success!
```

sudo wechattweak-cli --uninstall 卸载后正常打开。

尝试了重启电脑。重装 wechattweak-cli 还是不行

然后我重新安装回3.3.1版本的微信也这样了。哭死。。。

**Comment by lait233** [comment]
然后我找了一下那个狼人开的已停更小助手的issue。尝试了一个命令解决了
> sudo  codesign --sign - --force --deep /Applications/WeChat.app

但是不知道为啥会这样？作者可以优化一下吗

**Comment by shijua** [comment]
重启一下一般就可以了

**Comment by FrankFu916** [comment]
一般提示无法打开签名下就行了

**Comment by nageshuizeii** [comment]
> 然后我找了一下那个狼人开的已停更小助手的issue。尝试了一个命令解决了
> 
> > sudo  codesign --sign - --force --deep /Applications/WeChat.app
> 
> 但是不知道为啥会这样？作者可以优化一下吗

m1 max 12.4 微信 3.4.0 (21712) 需要这两部操作，才可以正常使用

**Comment by thefreelight** [comment]
> 

非常感谢，一度以为不可用了，用的m1，mbp一样需要这两步
