### ISSUE TITLE
免认证登录功能没了吗

### ISSUE THREAD

**Issue by shijua** [Sunnyyoung/WeChatTweak-macOS#499]
如题，从3.3版本更新到3.4版本重新安装插件后免认证登录功能没了
（虽然有微信自带免认证的可以用，但是手机再两天没有使用之后电脑端微信会强行退出登录并且要求扫码，但是使用插件中的免认证登录就不会，可以的话能不能加回来qwq）

**Comment by Sunnyyoung** [comment]
微信这么做就有他的风控原因，做这个不排除有封号风险

**Comment by shijua** [comment]
好的好的，感谢大佬
