### ISSUE TITLE
打补丁后自己撤回消息会闪退

### ISSUE THREAD

**Issue by NeverBehave** [Sunnyyoung/WeChatTweak-macOS#5]
OS版本：10.12.3 未关闭SIP
[Crash Log](https://paste.ee/p/emcxd)
如果信息不全可以追问，抱歉打扰了XD

**Comment by NeverBehave** [comment]
微信更新到2.2.8似乎好了……估计是版本问题

**Comment by Sunnyyoung** [comment]
@NeverBehave 应该是版本的问题把，2.2.1 的版本我没测试，毕竟挺老的了🤔，那就暂时不管了...
