### ISSUE TITLE
安裝以後偏好設置裡面沒有小助手的設置圖標

### ISSUE THREAD

**Issue by yjl336** [sunnyyoung/WeChatTweak-macOS#505]
安裝以後偏好設置裡面沒有小助手的設置圖標，怎麼關閉無手機認證自動登錄？

**Comment by Sunnyyoung** [comment]
是不是只安装了 cli 没有执行下一步

**Comment by wuyang-io** [comment]
> 
我的偏好设置也灭有关闭手机认证这个选项
请问除了安装wechattweak-cli还要做什么呢？

**Comment by wuyang-io** [comment]
> 是不是只安装了cli

我的偏好设置也有这个手机认证选项
，请问除了安装还安装了我们的关闭功能吗？

**Comment by Sunnyyoung** [comment]
`sudo wechattweak-cli install`

**Comment by yfc1995** [comment]
> 是不是只安装了 cli 没有执行下一步

下一步需要什么命令啊
