### ISSUE TITLE
可以把自动登录功能添加回来吗？

### ISSUE THREAD

**Issue by jzhjm** [Sunnyyoung/WeChatTweak-macOS#509]
RT，可以把自动登录功能添加回来吗？
当手机端微信不更新到最新版的话，就无法使用官方提供的自动登录功能

**Comment by kinosang** [comment]
另有部分情境下, 官方自动登录消失的情况 (疑似与重装有关)

**Comment by ykpercy** [comment]
第一次登录需要手机扫码，可以取消吗

**Comment by Sunnyyoung** [comment]
官方已经支持了，就不做第三方支持了，有风险。
