### ISSUE TITLE
安装最新的提示“微信无法打开”

### ISSUE THREAD

**Issue by Xigua7i** [Sunnyyoung/WeChatTweak-macOS#513]
MacOS: 12.3.1
WeChatTweak:  2022-05-23 16:13:10版本
通过sudo wechattweak-cli install 命令更新后，微信提示：无法打开

**Comment by ken0000000** [comment]
需要重启电脑

**Comment by xieshenace** [comment]
亲测不需要重启电脑。
重复执行：
sudo wechattweak-cli --uninstall
sudo wechattweak-cli --install

即可正常，
