### ISSUE TITLE
截图功能失效

### ISSUE THREAD

**Issue by mateoZzz** [Sunnyyoung/WeChatTweak-macOS#517]

**Comment by Reece-Lu** [comment]
+1，截图功能失效

**Comment by IvenWings** [comment]
M1，+1

**Comment by ken0000000** [comment]
在「系统设置-屏幕录制」删除微信，进行重新添加。

**Comment by mateoZzz** [comment]
「系统设置-屏幕录制」后也无法解决，微信都删除了好几次

**Comment by ocliys** [comment]
注意, 在「系统设置-屏幕录制」 不是点击 "-" 号删除, 而是在屏幕录制直接删除微信app, 然后再添加, 即可恢复截图

**Comment by IvenWings** [comment]
> 注意, 在「系统设置-屏幕录制」 不是点击 "-" 号删除, 而是在屏幕录制直接删除微信app, 然后再添加, 即可恢复截图

macOS Monterey 12.3.1 M1 已解决 感谢，不过好像是点击 "-" 删除然后再点击 "+"，最后重开微信就好了

**Comment by Elwyn00** [comment]
> 12.3.1

同已解决，感谢

**Comment by mateoZzz** [comment]
macOS Monterey 12.4 M1 pro 已解决 感谢，「系统设置-屏幕录制」点击 "-" 删除然后再点击 "+"，最后重开微信就好了

**Comment by poison501** [comment]
> 注意, 在「系统设置-屏幕录制」 不是点击 "-" 号删除, 而是在屏幕录制直接删除微信app, 然后再添加, 即可恢复截图

感谢，Monterey 12.3.1 + Wechat 3.4.0 好用

**Comment by 54dujianchao** [comment]
我也是同样的问题
MAC版本 MacBook Pro (13-inch, M1, 2020)
系统版本 12.4
微信版本：Version. 3.5.0 (22920) （dmg、APPStore 均试过，结果一样）

截图不能用，卸载了、增删权限十几次、均无效

**Comment by ken0000000** [comment]
> 我也是同样的问题 MAC版本 MacBook Pro (13-inch, M1, 2020) 系统版本 12.4 微信版本：Version. 3.5.0 (22920) （dmg、APPStore 均试过，结果一样）
> 
> 截图不能用，卸载了、增删权限十几次、均无效

还是要卸载干净「方法可以百度，有对应的工具」卸载之后权限里面有没有微信权限，重新安装设置，如果还不行，安装正常WX是否正常。

**Comment by Sunnyyoung** [comment]
参考 FAQ 7: https://github.com/Sunnyyoung/WeChatTweak-macOS#faq
