### ISSUE TITLE
请问brew 怎样调整下载到最新的release？

### ISSUE THREAD

**Issue by Knight90** [Sunnyyoung/WeChatTweak-macOS#522]
使用brew install wechattweak-cli会提示download的是1.2的wechattweak-cli即
Downloading https://github.com/Sunnyyoung/WeChatTweak-CLI/releases/download/1.2/wechattweak-cli

这个有办法调整到最新的release吗？

**Comment by Sunnyyoung** [comment]
`brew upgrade wechattweak-cli --cask`

**Comment by MoienBowen** [comment]
$ brew upgrade wechattweak-cli --cask
Warning: Not upgrading wechattweak-cli, the latest version is already installed

$ wechattweak-cli version
1.3.1

我看了下 repo，最新版本是 1.4。
https://github.com/Sunnyyoung/WeChatTweak-CLI/releases/ 

@Sunnyyoung

**Comment by chenrui333** [comment]
> $ brew upgrade wechattweak-cli --cask Warning: Not upgrading wechattweak-cli, the latest version is already installed
> 
> $ wechattweak-cli version 1.3.1
> 
> 我看了下 repo，最新版本是 1.4。 https://github.com/Sunnyyoung/WeChatTweak-CLI/releases/
> 
> @Sunnyyoung

> `version                 Get current version of WeChatTweak.`

WeChatTweak 的 latest release 就是 1.3.1, cli 和 WeChatTweak 的版本并不一致

**Comment by Sunnyyoung** [comment]
算是 bug，漏改了……

**Comment by Sunnyyoung** [comment]
`wechattweak-cli` 读到的是 `WeChatTweak.framework` 的版本，所以是正常的
