### ISSUE TITLE
3.4.1 (21939)没有适配

### ISSUE THREAD

**Issue by JasonDusson** [Sunnyyoung/WeChatTweak-macOS#523]
3.4.1 (21939）好像无法安装适配

**Comment by peipeijiang** [comment]
Version 3.4.1 (21939) 右键没有启动另一个微信选项

**Comment by JasonDusson** [comment]
> Version 3.4.1 (21939) 右键没有启动另一个微信选项

没敢试，嗨，现在电脑微信聊天工作记录都没有了。。

**Comment by Sunnyyoung** [comment]
适配什么

**Comment by JasonDusson** [comment]
> 适配什么

微信无法打开。难道是操作方式不对？

**Comment by JasonDusson** [comment]
安装完成之后要重启。。。忘记重启了。。。
