### ISSUE TITLE
微信功能被限制

### ISSUE THREAD

**Issue by FearOfHot** [Sunnyyoung/WeChatTweak-macOS#524]
有没有好兄弟被限制了群聊和朋友圈功能的 不知道是不是用了插件的原因。。

**Comment by kanzakiken** [comment]
我这的这些功能没有问题

**Comment by FearOfHot** [comment]
> 我这的这些功能没有问题

目前限制已经解除了 应该和插件无关 可能是发表敏感言论了 具体客服也没说
