### ISSUE TITLE
消息撤回样式为遮罩时，颜色可以自定义么

### ISSUE THREAD

**Issue by yuhuazhu** [Sunnyyoung/WeChatTweak-macOS#525]
目前黑色聊天背景，那个撤回遮罩一长条看去好亮，或者颜色去掉也可以

**Comment by MartinLau7** [comment]
你可以修改代码自己编译

**Comment by yuhuazhu** [comment]
@MartinLau7 
没改cli安装之前，修改代码安装是可以的，后面换cli就搞不定了
原来的AntiRevoke.m
`((MMMessageCellView *)self).layer.backgroundColor = 
recalled ? [NSColor.systemYellowColor colorWithAlphaComponent:0.3].CGColor : nil;`
修改后的
`((MMMessageCellView *)self).layer.backgroundColor = 
recalled ? NSColor.clearColor.CGColor : nil;`

**Comment by MartinLau7** [comment]
你不用 cil 安装也可以啊，都有源码了啊...

**Comment by yuhuazhu** [comment]
项目从旧电脑隔空投送过来的，
build的时候，总提示执行sh文件的时候没权限，
看了下sh文件，发现就是软连接命令，
把WeChatTweak.framework这个文件夹删了，就能ln成功了
最后成功安装并打开微信了
