### ISSUE TITLE
微信截图功能无法使用

### ISSUE THREAD

**Issue by landzf** [Sunnyyoung/WeChatTweak-macOS#527]
M1版本安装了防撤回之后，系统一直提示需要打开截图权限，但权限已经打开了
<img width="668" alt="image" src="https://user-images.githubusercontent.com/53946991/178692272-94d58946-2057-42b0-bab8-1b8fb80a93b6.png">

**Comment by landzf** [comment]
> M1版本安装了防撤回之后，系统一直提示需要打开截图权限，但权限已经打开了
> <img alt="image" width="668" src="https://user-images.githubusercontent.com/53946991/178692272-94d58946-2057-42b0-bab8-1b8fb80a93b6.png">

**Comment by 54dujianchao** [comment]
我也是同样的问题
MAC版本 MacBook Pro (13-inch, M1, 2020)
系统版本 12.4
微信版本：Version. 3.5.0 (22920)   （dmg、APPStore 均试过，结果一样）

截图不能用，卸载了、增删权限十几次、均无效

**Comment by landzf** [comment]
在安全性与隐私的增删权限的界面，把微信删除掉重新添加



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月27日(星期三) 中午11:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [Sunnyyoung/WeChatTweak-macOS] 微信截图功能无法使用 (Issue #527)





 
我也是同样的问题
 MAC版本 MacBook Pro (13-inch, M1, 2020)
 系统版本 12.4
 微信版本：Version. 3.5.0 (22920)   （dmg、APPStore 均试过，结果一样）
 
截图不能用，卸载了、增删权限十几次、均无效

**Comment by jwcn** [comment]
> 我也是同样的问题 MAC版本 MacBook Pro (13-inch, M1, 2020) 系统版本 12.4 微信版本：Version. 3.5.0 (22920) （dmg、APPStore 均试过，结果一样）
> 
> 截图不能用，卸载了、增删权限十几次、均无效

不是取消勾，再答上勾是删除(点击微信-再点下面的➖)，然后再点➕，找到微信添加进去
