### ISSUE TITLE
截图无法使用，屏幕录制已经给过权限了

### ISSUE THREAD

**Issue by Misterzzp** [sunnyyoung/WeChatTweak-macOS#530]
[未命名.pdf](https://github.com/Sunnyyoung/WeChatTweak-macOS/files/9205609/default.pdf)

**Comment by chris-zhu** [comment]
> [未命名.pdf](https://github.com/Sunnyyoung/WeChatTweak-macOS/files/9205609/default.pdf)

重新授权，重新执行这个命令，亲测有效。
```bash
$ sudo wechattweak-cli install   # 安装/更新
```

**Comment by Misterzzp** [comment]
没有用，无所谓了，我用其他的截图好了

**Comment by kylin4ever** [comment]
隐私-屏幕录制 把微信删掉重新添加，亲测有效

**Comment by dividez** [comment]
macOs 最新版本微信客户端， 使用截图 就闪退了

**Comment by Sunnyyoung** [comment]
App Store 版本 `Version 3.5.5 (23491)` 测试正常。

**Comment by cnyyk** [comment]
> macOs 最新版本微信客户端， 使用截图 就闪退了

同样问题，brew 安装的。一会转为 appstore 版本的试试看
