### ISSUE TITLE
微信最新版本还没适配，v3.5.0.16 (0x13050010) 

### ISSUE THREAD

**Issue by 18684729182** [Sunnyyoung/WeChatTweak-macOS#534]
最新版的还没适配，安装最新版后，没有出现防撤回跟躲开

**Comment by ACodingJie** [comment]
<img width="472" alt="image" src="https://user-images.githubusercontent.com/44465791/182088402-e0566eed-f54b-47f4-b3df-548775081a36.png">

重新 sudo wechattweak-cli install 试下呢

**Comment by doudouliyouniaoshi** [comment]
> <img alt="image" width="472" src="https://user-images.githubusercontent.com/44465791/182088402-e0566eed-f54b-47f4-b3df-548775081a36.png">
> 
> 重新 sudo wechattweak-cli install 试下呢

这个版本的微信是在哪下载的？

**Comment by ACodingJie** [comment]
> > <img alt="image" width="472" src="https://user-images.githubusercontent.com/44465791/182088402-e0566eed-f54b-47f4-b3df-548775081a36.png">
> > 重新 sudo wechattweak-cli install 试下呢
> 
> 这个版本的微信是在哪下载的？

app store

**Comment by doudouliyouniaoshi** [comment]
> > > <img alt="图像" width="472" src="https://user-images.githubusercontent.com/44465791/182088402-e0566eed-f54b-47f4-b3df-548775081a36.png">重新 sudo wechattweak-cli install 试下呢> >> >> > 这个版本的微信在哪里下载的？>> 应用程序商店！[上传 image.png...]()我从商店下载的怎么是这个版本

**Comment by 18684729182** [comment]
> > > > <img alt="图像" width="472" src="https://user-images.githubusercontent.com/44465791/182088402-e0566eed-f54b-47f4-b3df-548775081a36.png">重新 sudo wechattweak-cli install 试下呢> >> >> > 这个版本的微信在哪里下载的？>> 应用程序商店！上传 image.png...我从商店下载的怎么是这个版本Version. 3.5.0 (22923)

重启一下试试，我的刚才更新后重启微信又可以了

**Comment by doudouliyouniaoshi** [comment]
> > > > > <img alt="图像" width="472" src="https://user-images.githubusercontent.com/44465791/182088402-e0566eed-f54b-47f4-b3df-548775081a36.png">重新 sudo wechattweak-cli install 试下呢> >> >> > 这个版本的微信在哪里下载的？>> 应用程序商店！上传 image.png...我从商店下载的怎么是这个版本Version. 3.5.0 (22923)
> 
> 重启一下试试，我的刚才更新后重启微信又可以了

不行 我已经重启N次了  微信也试了官网下载的  都不行 一直报错  签名那个有问题

**Comment by MartinLau7** [comment]
签名有问题 手动用命令强制签名。

**Comment by doudouliyouniaoshi** [comment]
> 

sudo wechattweak-cli install
------ Download ------
------ Unzip ------
Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS
------ Backup ------
WeChat.bak exists, skip it...
------ Remove Codesign ------
Execute command: codesign --remove-sign /Applications/WeChat.app/Contents/MacOS/WeChat
Install failed: Execute command: codesign --remove-sign /Applications/WeChat.app/Contents/MacOS/WeChat failed: {
NSAppleScriptErrorAppName = "wechattweak-cli";
NSAppleScriptErrorBriefMessage = "xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/Co/Applications/WeChat.app/Contents/MacOS/WeChat: the codesign_allocate helper tool cannot be found or used";
NSAppleScriptErrorMessage = "xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/Command/Applications/WeChat.app/Contents/MacOS/WeChat: the codesign_allocate helper tool cannot be found or used";
NSAppleScriptErrorNumber = 1;
NSAppleScriptErrorRange = "NSRange: {0, 87}";
}
这个能怎么搞

**Comment by change3799** [comment]
请问解决了吗？我有点想更新。。 。

**Comment by MoienBowen** [comment]
我的微信版本显示为 Version. 3.5.0 (22923)，下载自 App Store，没有上述问题啊。
点击关于微信里面的系统信息版本，显示的微信版本为 [2022-07-21 xx:xx:xx] v3.5.0.16 (22923) #3cd0ceb735

**Comment by doudouliyouniaoshi** [comment]
> 请问解决了吗？我有点想更新。。 。

我还没搞定，然后我用时间机器给倒回去了3.4版本了 不知道为啥 有没有可能是系统11.6.8的问题，你可以试试看

**Comment by qiweifan** [comment]
> <img alt="image" width="472" src="https://user-images.githubusercontent.com/44465791/182088402-e0566eed-f54b-47f4-b3df-548775081a36.png">
> 
> 重新 sudo wechattweak-cli install 试下呢

后面的Tweak窗口是怎么出现的？

**Comment by MoienBowen** [comment]
@qiweifan 退出微信后，终端执行
brew install sunnyyoung/repo/wechattweak-cli
sudo wechattweak-cli install

**Comment by chenrui333** [comment]
tested out with `sudo wechattweak-cli install`, works for me with wechat 3.5.0 (`Version 3.5.0 (22923)`)

**Comment by doudouliyouniaoshi** [comment]
> sudo wechattweak-cli install
> ------ Download ------
> ------ Unzip ------
> Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS
> ------ Backup ------
> WeChat.bak exists, skip it...
> ------ Remove Codesign ------
> Execute command: codesign --remove-sign /Applications/WeChat.app/Contents/MacOS/WeChat
> Install failed: Execute command: codesign --remove-sign /Applications/WeChat.app/Contents/MacOS/WeChat failed: {
> NSAppleScriptErrorAppName = "wechattweak-cli";
> NSAppleScriptErrorBriefMessage = "xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/Co/Applications/WeChat.app/Contents/MacOS/WeChat: the codesign_allocate helper tool cannot be found or used";
> NSAppleScriptErrorMessage = "xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/Command/Applications/WeChat.app/Contents/MacOS/WeChat: the codesign_allocate helper tool cannot be found or used";
> NSAppleScriptErrorNumber = 1;
> NSAppleScriptErrorRange = "NSRange: {0, 87}";
> }
> 这个能怎么搞

搞定了 是缺了xcode，，，用了xcode-select --install这个代码安装完了软件 再运行sudo wechattweak-cli install就可以了

**Comment by jinrichardJIN** [comment]
貌似只有防撤回 没有多开
当前版本Version. 3.5.0 (22923)

**Comment by WangEn** [comment]
一般更新后我的操作就是：
关闭微信，然后执行：
``` bash
sudo wechattweak-cli --uninstall
sudo wechattweak-cli --install
```

如果不能打开，重复一遍就好

**Comment by Sunnyyoung** [comment]
本项目只对 App Store 最新版本做完整支持，App Store 版本 `Version 3.5.5 (23491)` 测试正常。
