### ISSUE TITLE
内测版提示等信息失效

### ISSUE THREAD

**Issue by Kerwin1202** [Sunnyyoung/WeChatTweak-macOS#536]
内测版 https://dldir1.qq.com/weixin/mac/WeChatMac_Beta.dmg

撤回之后提示这个 并且聊天框 没有任何突出信息

<img width="358" alt="image" src="https://user-images.githubusercontent.com/16319833/185151583-9b42fae0-3be9-4143-9243-010e5be6a1a9.png">

**Comment by Kerwin1202** [comment]
替换之后会影响原本的软件迁移聊天记录功能

**Comment by Sunnyyoung** [comment]
本项目只对 App Store 最新版本做完整支持喔～
