### ISSUE TITLE
3.5.5.18 (23481) 提供了插件侦测能力，另外截图会导致程序崩溃，暂时卸载

### ISSUE THREAD

**Issue by cnyyk** [Sunnyyoung/WeChatTweak-macOS#539]
反侦测如下图所示
![wechat-anti-plugin](https://user-images.githubusercontent.com/275233/187122714-e4712675-2535-4c58-8f5d-48439c35a14e.gif)

版本 3.5.5.18 (23481)
cli 最后版本 1.4 / 1.3.1
错误日志

![Screen Shot 2022-08-29 at 12 02 44](https://user-images.githubusercontent.com/275233/187122361-6283edab-5c10-4101-b730-d8a445afd398.png)

**Comment by Sunnyyoung** [comment]
本项目只对 App Store 最新版本做完整支持喔～

**Comment by cnyyk** [comment]
> 本项目只对 App Store 最新版本做完整支持喔～

收到，谢谢。一直用的 brew 安装。换回 App Store 试试。

感谢你无私开源、造福众生。
