### ISSUE TITLE
「已解决」微信里的链接点击后无法直接打开？

### ISSUE THREAD

**Issue by WhiteInk404** [Sunnyyoung/WeChatTweak-macOS#54]
安装WeChatTweak之后，微信聊天里的链接，无法直接点击跳转到浏览器打开。
目前的状态是：点击链接之后，默认浏览器（Chrome）会重新打开一个窗口，但是，显示的是空白，窗口也不会跳到屏幕最前端。
之前的状态是：点击链接之后，默认浏览器在原窗口中新建Tab页面打开链接，窗口跳到屏幕最前端。

**Comment by WhiteInk404** [comment]
解决了，重新安装之后一切正常了。不知道原因是啥。

**Comment by Sunnyyoung** [comment]
这个是Chrome的问题
