### ISSUE TITLE
撤/回已经没用。微信3.5.0

### ISSUE THREAD

**Issue by change3799** [sunnyyoung/WeChatTweak-macOS#541]

**Comment by Sunnyyoung** [comment]
Version 3.5.5 (23491) 工作正常

**Comment by kilvn** [comment]
Version 3.5.5 (23481)   截图 esc取消    每次都闪退

**Comment by AGou-ops** [comment]
可以用啊，bro.

**Comment by uncle-bo** [comment]
我的不显示tweak的UI，也没有任何提示；同样微信3.5.0，mac air m1.

**Comment by woody3rd** [comment]
3.5.5依旧有效，=

**Comment by 996WJC** [comment]
> Version. 3.6.0 (24160) 有效

我的是3.4微信版本，一直不敢更新微信，怕更新到3.6版本，会无法安装成功，可以说一下经验么 老哥？

**Comment by Syzq** [comment]
> > Version. 3.6.0 (24160) 有效
> 
> 我的是3.4微信版本，一直不敢更新微信，怕更新到3.6版本，会无法安装成功，可以说一下经验么 老哥？

更新完微信，iTerm2 执行 `sudo wechattweak-cli install` 再重新打开微信就行了

**Comment by 996WJC** [comment]
> 

iTerm2 ，指的是电脑里面的终端么？

**Comment by 996WJC** [comment]
> 



> > > Version. 3.6.0 (24160) 有效
> > 
> > 
> > 我的是3.4微信版本，一直不敢更新微信，怕更新到3.6版本，会无法安装成功，可以说一下经验么 老哥？
> 
> 更新完微信，iTerm2 执行 `sudo wechattweak-cli install` 再重新打开微信就行了

请问一下，iTerm2 ，指的是电脑里面的【终端】么？

**Comment by Syzq** [comment]
> > 
> 
> > > > Version. 3.6.0 (24160) 有效
> > > 
> > > 
> > > 我的是3.4微信版本，一直不敢更新微信，怕更新到3.6版本，会无法安装成功，可以说一下经验么 老哥？
> > 
> > 
> > 更新完微信，iTerm2 执行 `sudo wechattweak-cli install` 再重新打开微信就行了
> 
> 请问一下，iTerm2 ，指的是电脑里面的【终端】么？

是

**Comment by 996WJC** [comment]
> sudo wechattweak-cli install

感谢哥们，已经OK了，刚刚操作成功，现在版本是3.6最新的微信了，还是正常可以使用tweak
