### ISSUE TITLE
我想自己为Raycast适配，但是遇到了问题

### ISSUE THREAD

**Issue by Lawrence-of-AnKing** [sunnyyoung/WeChatTweak-macOS#542]
我打开了Alfred的Workflow，发现里面只有一个简单的关键词“WC”和“WX”，然后指向一个 `bin/bash' 指令：

```bash
curl -X GET localhost:48065/wechat/start -Gsd "session={query}"
```

是个Curl指令。

然后我试着将其中的“{query}”替换成我微信中已有的联系人名字，比如“王二”，变成 `curl -X GET localhost:48065/wechat/start -Gsd "session=王二"`，并在终端中运行。

但是结果只能直接打开微信。

于是我试着在浏览器中输入 `http://localhost:48065/wechat/start?session=王二` 但是结果仍然只是打开了微信，没有打开对应的联系人。

我想问一下，这里是否是类似Alfred中WebSearch那样将关键词转换成一个链接？还是别的什么方式来实现关键词查询并返回。

如果可以的话，希望作者能给一些说明，或者官方来支持Raycast。

感谢。🎉🎉🎉

**Comment by LawrenceLiuQuanzhou** [comment]
找到了作者多年前的文章：https://blog.sunnyyoung.net/rang-wei-xin-macos-ke-hu-duan-zhi-chi-alfred/

我去琢磨看看了。

**Comment by Jax0rz** [comment]
我之前也准备做，太忙了没时间，参考作者的博客，我觉得实现搜索通讯录这个相对简单，如果能搜索通讯录然后输入聊天内容，并且查看对应好友聊天记录这两个功能就太强大了，完全可以不打开微信，让聊天软件变效率工具！

**Comment by Jax0rz** [comment]
[插件](https://github.com/Jax0rz/wechat)我写好了，大家可以试试，目前还有点小问题，最近两天会发布到RayCast Store
![showcase](https://user-images.githubusercontent.com/7557357/191069300-0d248537-fa13-4f7f-bf43-d898aa4a9517.png)

**Comment by LawrenceLiuQuanzhou** [comment]
> [插件](https://github.com/Jax0rz/wechat)我写好了，大家可以试试，目前还有点小问题，最近两天会发布到RayCast Store ![showcase](https://user-images.githubusercontent.com/7557357/191069300-0d248537-fa13-4f7f-bf43-d898aa4a9517.png)

额滴超人，我去试试🎉🎉🎉

**Comment by Jax0rz** [comment]
目前有个问题用Raycast提供的OpenInBrowser方法会打开浏览器，然后才打开微信，暂时不知道怎么解决

**Comment by LawrenceLiuQuanzhou** [comment]
> 目前有个问题，就是用Raycast提供的OpenInBrowser方法会打开浏览器，然后才打开微信，暂时不知道怎么解决

你直接把URL作为参数，然后运行指令 `curl URL`，就能不经过浏览器直接打开了，试试看。

**Comment by Jax0rz** [comment]
> > 目前有个问题，就是用Raycast提供的OpenInBrowser方法会打开浏览器，然后才打开微信，暂时不知道怎么解决
> 
> 你直接把URL作为参数，然后运行指令 `curl URL`，就能不经过浏览器直接打开了，试试看。

相关issue可以关闭了，已经实现

**Comment by absir1949** [comment]
@raffeyang 膜拜大佬！请问下可以实现双开的 raycast搜索吗？可以搜索多个vx

**Comment by Lawrence-of-AnKing** [comment]
> @raffeyang 膜拜大佬！请问下可以实现双开的 raycast搜索吗？可以搜索多个vx

现有的插件不行，但是wechat tweak-cli是支持双开的，所以应该也可以实现，去作者仓库下提issue看看？
