### ISSUE TITLE
在MAC微信2.3.5版有严重bug

### ISSUE THREAD

**Issue by leochan2017** [Sunnyyoung/WeChatTweak-macOS#55]
您好

感谢您提供的插件，在过去的一段时间，使用起来是非常棒的。谢谢您

但是，很不幸的是，今天早上我更新了微信客户端（2.3.5）。出现的BUG现象如下：

1.消息发不出去，呈现一直转圈圈loading状态
2.别人发的消息收不到
3.聊天记录丢失

希望您能在百忙之中抽空看下，谢谢哦

**Comment by leochan2017** [comment]
我重新安装了WeChatTweak-macOS一遍，还是一样的问题存在

**Comment by Sunnyyoung** [comment]
@leochan2017 我用的是最新版，并没有上述问题，可以排除下可能是其它因素影响？

**Comment by huangyg11** [comment]
本来看到这个issue没敢升级，刚才升了  我这边也没问题

**Comment by leochan2017** [comment]
我卸载了WeChatTweak-macOS 之后就没问题了。。完了，难道是我的微信被玩坏了？    （捂脸~

**Comment by LauraGuan** [comment]
同样的问题，出现很多次！！问一下怎么卸载Tweak？～

**Comment by huangyg11** [comment]
@LauraGuan 可以重新装一下微信 我之前从app store升级微信后 tweak就被覆盖掉了

**Comment by Kristin33** [comment]
我没有用tweak，也遇到了同样的问题~
