### ISSUE TITLE
微信 Version. 3.6.0 撤回功能失效

### ISSUE THREAD

**Issue by shcw** [sunnyyoung/WeChatTweak-macOS#553]

**Comment by 1270045840** [comment]
+1

**Comment by 1270045840** [comment]
我执行这个命令现在可以了  sudo wechattweak-cli install

**Comment by ArcherLucky** [comment]
有这个功能，只是没有拦截提示了，大家碰到了吗？

**Comment by shencw** [comment]
> 有这个功能，只是没有拦截提示了，大家碰到了吗？

@1270045840 @ArcherLucky  我执行了 后也是这个问题

**Comment by 996WJC** [comment]
目前微信是3.4，还是可以正常使用，一直不敢升级到3.6的微信，担心时效。有试过的朋友，可以给点经验，谢谢！

**Comment by aaronyyan** [comment]
Version. 3.5.0 (22798) Beta 9 这个版本也可以

**Comment by sunnyyoung** [comment]
请查看 1.4.0 更新
