### ISSUE TITLE
安装成功，但是最后一步（sudo wechattweak-cli --install ）  # 安装/更新 错误

### ISSUE THREAD

**Issue by huzhuyanan** [Sunnyyoung/WeChatTweak-macOS#554]
Error: Internal error. Invalid state while parsing command-line arguments.
Usage: wechattweak-cli <subcommand>
  See 'wechattweak-cli --help' for more information.

**Comment by huzhuyanan** [comment]
为啥安装不上啊？

**Comment by huzhuyanan** [comment]
who can help me?

**Comment by huzhuyanan** [comment]
Last login: Sat Nov 12 09:14:42 on ttys000
yananhu@YANANdeMacBook-Pro ~ % /Users/yananhu/Desktop/Old_Homebrew/2022-11-10\ 22\:38\:35/opt/homebrew/homebrew/bin/wechattweak-cli ; exit;
Error: Internal error. Invalid state while parsing command-line arguments.

OVERVIEW: A command line utility to work with WeChatTweak-macOS.

USAGE: wechattweak-cli <subcommand>

OPTIONS:
  -h, --help              Show help information.

SUBCOMMANDS:
  install                 Install or upgrade tweak.
  uninstall               Uninstall tweak.
  resign                  Force resign WeChat.app
  version                 Get current version of WeChatTweak.

  See 'wechattweak-cli help <subcommand>' for detailed help.

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[进程已完成]

**Comment by huzhuyanan** [comment]
Last login: Sat Nov 12 09:14:42 on ttys000
yananhu@YANANdeMacBook-Pro ~ % /Users/yananhu/Desktop/Old_Homebrew/2022-11-10\ 22\:38\:35/opt/homebrew/homebrew/bin/wechattweak-cli ; exit;
Error: Internal error. Invalid state while parsing command-line arguments.

OVERVIEW: A command line utility to work with WeChatTweak-macOS.

USAGE: wechattweak-cli <subcommand>

OPTIONS:
  -h, --help              Show help information.

SUBCOMMANDS:
  install                 Install or upgrade tweak.
  uninstall               Uninstall tweak.
  resign                  Force resign WeChat.app
  version                 Get current version of WeChatTweak.

  See 'wechattweak-cli help <subcommand>' for detailed help.

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[进程已完成]

**Comment by huzhuyanan** [comment]
终于安装上了，就是
<img width="715" alt="image" src="https://user-images.githubusercontent.com/112394009/201450166-da3cdb2c-7862-40f3-95d3-aca141214bd3.png">
全部打开就可以了。感谢平台

**Comment by dreamingchow** [comment]
防撤回功能还好用吗？
