### ISSUE TITLE
macos13 无法安装

### ISSUE THREAD

**Issue by w835558109** [sunnyyoung/WeChatTweak-macOS#557]
yaqingwang@192 ~ % brew install sunnyyoung/repo/wechattweak-cli
fatal: not in a git directory
Warning: No remote 'origin' in /opt/homebrew/Library/Taps/homebrew/homebrew-cask, skipping update!
fatal: not in a git directory
Warning: No remote 'origin' in /opt/homebrew/Library/Taps/homebrew/homebrew-core, skipping update!
fatal: not in a git directory
Warning: No remote 'origin' in /opt/homebrew/Library/Taps/homebrew/homebrew-services, skipping update!
==> Homebrew has enabled anonymous aggregate formula and cask analytics.
Read the analytics documentation (and how to opt-out) here:
  https://docs.brew.sh/Analytics
No analytics have been recorded yet (nor will be during this `brew` run).

==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations

==> Tapping sunnyyoung/repo
Cloning into '/opt/homebrew/Library/Taps/sunnyyoung/homebrew-repo'...
fatal: unable to access 'https://github.com/sunnyyoung/homebrew-repo/': Failed to connect to github.com port 443 after 76050 ms: Operation timed out
Error: Failure while executing; `git clone https://github.com/sunnyyoung/homebrew-repo /opt/homebrew/Library/Taps/sunnyyoung/homebrew-repo --origin=origin --template=` exited with 128.
yaqingwang@192 ~ % 

安装到这一步就不行了。。。。

**Comment by chenrui333** [comment]
> fatal: unable to access 'https://github.com/sunnyyoung/homebrew-repo/': Failed to connect to github.com port 443 after 76050 ms: Operation timed out

好像是你的 github connection 问题？

**Comment by sunnyyoung** [comment]
网络问题
