### ISSUE TITLE
mac微信2.3.5(9814)不能防撤回

### ISSUE THREAD

**Issue by windiws** [Sunnyyoung/WeChatTweak-macOS#56]
你好,测试版本的2.3.3和正式版的2.3.5都不能防撤回,设置是消息全部接收也不行,求助

**Comment by Sunnyyoung** [comment]
有没有重新安装插件

**Comment by AlexanderOnly** [comment]
重新安装试一下 我个人的经验是每次微信升级都要重新安装一次

**Comment by windiws** [comment]
请问怎么重新安装,除了防撤回,其他功能都能用,不过mac退出微信后,手机还是显示电脑登录中

**Comment by Sunnyyoung** [comment]
@windiws `sudo make install`

**Comment by zhjlty** [comment]
更新了新版本2.3.5后确实不能防撤回了，重新安装了插件也不行，求大神更新！！！

**Comment by zhjlty** [comment]
没事了，微信重启后可以了~~ok'
