### ISSUE TITLE
执行sudo wechattweak-cli install报错

### ISSUE THREAD

**Issue by kewell2000** [sunnyyoung/WeChatTweak-macOS#560]
执行sudo wechattweak-cli install命令收到如下报错：

------ Download ------
------ Unzip ------
Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS
Install failed: Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS failed: {
    NSAppleScriptErrorAppName = "wechattweak-cli";
                 unable to process WeChatTweak.framework/WeChatTweak.";WeChatTweak.frameworkTweakPreferencesController.strings.jects.nib.00.nib.
                 unable to process WeChatTweak.framework/WeChatTweak.";WeChatTweak.frameworkTweakPreferencesController.strings.jects.nib.00.nib.
    NSAppleScriptErrorNumber = 2;
    NSAppleScriptErrorRange = "NSRange: {0, 157}";
}

**Comment by imloren** [comment]
https://github.com/sunnyyoung/WeChatTweak-CLI/issues/41#issuecomment-1309980029

**Comment by xiaohai-78** [comment]
> 同 +1

噢，找到了
macOS 13 下的解决方法 #559
