### ISSUE TITLE
微信3.6.1安装失败

### ISSUE THREAD

**Issue by hungry66** [sunnyyoung/WeChatTweak-macOS#562]
Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS
Install failed: Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS failed

**Comment by imloren** [comment]
https://github.com/sunnyyoung/WeChatTweak-CLI/issues/41#issuecomment-1309980029
