### ISSUE TITLE
撤回信息现在不显示了

### ISSUE THREAD

**Issue by YaoChengjian** [sunnyyoung/WeChatTweak-macOS#567]
<img width="431" alt="image" src="https://user-images.githubusercontent.com/49084439/209288372-d5c8345a-2b68-4f65-90cf-67ffa14fe640.png">

**Comment by Jonnyan404** [comment]
应该是从 3.6.1 开始就不显示了

**Comment by sunnyyoung** [comment]
更新最新微信和 Tweak
