### ISSUE TITLE
微信3.6.2已经不支持了

### ISSUE THREAD

**Issue by Pyramiding** [sunnyyoung/WeChatTweak-macOS#569]

**Comment by ACodingJie** [comment]
<img width="497" alt="image" src="https://user-images.githubusercontent.com/44465791/209507021-76b4aa49-372e-45f5-afcf-3ab41ed8815a.png">

**Comment by sonwa** [comment]
刚更新正常使用 Version. 3.6.2 (24456)

**Comment by hhyyy9** [comment]
<img width="708" alt="iShot_2022-12-28_18 39 41" src="https://user-images.githubusercontent.com/841277/209799539-b4ea7a49-48b1-4451-8935-9cc436f56e9f.png">
报错了

**Comment by shubibin** [comment]
macos Ventura版本 13.1

<img width="1748" alt="iShot_2023-01-04_17 33 08" src="https://user-images.githubusercontent.com/70150845/210525234-25dc31fa-880b-4870-9951-f42026c015e0.png">

**Comment by ColinVon** [comment]
Ventura 13.1  微信 3.6.2 问题同上，请求解决

**Comment by li-Coulson** [comment]
> > macos Ventura 版本 13.1
> > <img alt="iShot_2023-01-04_17 33 08" width="1748" src="https://user-images.githubusercontent.com/70150845/210525234-25dc31fa-880b-4870-9951-f42026c015e0.png">
> 
> > <img alt="iShot_2022-12-28_18 39 41" width="708" src="https://user-images.githubusercontent.com/841277/209799539-b4ea7a49-48b1-4451-8935-9cc436f56e9f.png">
> > 报错了
> 
> [sunnyyoung/WeChatTweak-CLI#41 (comment)](https://github.com/sunnyyoung/WeChatTweak-CLI/issues/41#issuecomment-1309980029)

你第一个截图很明显是你终端没磁盘写入权限，

**Comment by shubibin** [comment]
￼
￼

**Comment by qiweifan** [comment]
> <img alt="image" width="497" src="https://user-images.githubusercontent.com/44465791/209507021-76b4aa49-372e-45f5-afcf-3ab41ed8815a.png">

这个Tweak的窗口是怎么出来的
