### ISSUE TITLE
Alfred显示connection refused

### ISSUE THREAD

**Issue by AlexanderOnly** [Sunnyyoung/WeChatTweak-macOS#57]
你好！我非常喜欢您的项目！但是我在使用workflow的时候显示了如下错误信息：

Error in workflow 'net.sunnyyoung.wechatworkflow'
<urlopen error [Errno 61] Connection refused>

已经安装了tweak及打开了微信 防撤回功能正常
想请教一下，是不是我使用的方式哪里不对

**Comment by Sunnyyoung** [comment]
@AlexanderOnly 你的 Alfred 版本是多少？

**Comment by AlexanderOnly** [comment]
v3.5

**Comment by sfdye** [comment]
我的也是
看了下代码 应该是`locahost:48065`挂了

**Comment by Sunnyyoung** [comment]
@AlexanderOnly @sfdye 奇怪了，我这是正常的

![image](https://user-images.githubusercontent.com/5926284/33130077-113eb8d0-cfcd-11e7-87bc-3187bec3fd73.png)

有试过重启电脑吗？

**Comment by sfdye** [comment]
"Have you tried turning it off and on again?"😂

**Comment by AlexanderOnly** [comment]
重启过了，还是这样的
![2017-11-23 07 57 53](https://user-images.githubusercontent.com/18606562/33154542-0970fbac-d024-11e7-83b4-e36c83bf43a8.png)

**Comment by Sunnyyoung** [comment]
#53 #55 #56
