### ISSUE TITLE
mac 10.15.7 安装报错

### ISSUE THREAD

**Issue by De1taa** [sunnyyoung/WeChatTweak-macOS#574]
Install failed: Execute command: codesign --force --deep --sign - /Applications/WeChat.app/Contents/MacOS/WeChat failed: {
    NSAppleScriptErrorAppName = "wechattweak-cli";
    NSAppleScriptErrorBriefMessage = "/Applications/WeChat.app/Contents/MacOS/WeChat: invalid or unsIn subcomponent: /Applications/WeChat.app/Contents/Frameworks/ilink_network.framework";
    NSAppleScriptErrorMessage = "/Applications/WeChat.app/Contents/MacOS/WeChat: invalid or unsupporIn subcomponent: /Applications/WeChat.app/Contents/Frameworks/ilink_network.framework";
    NSAppleScriptErrorNumber = 1;
    NSAppleScriptErrorRange = "NSRange: {0, 97}";

**Comment by GitNiShuo** [comment]
我也是

/Contents/MacOS/WeChat failed: {
    NSAppleScriptErrorAppName = "wechattweak-cli";
    NSAppleScriptErrorBriefMessage = "xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/Co/Applications/WeChat.app/Contents/MacOS/WeChat: the codesign_allocate helper tool cannot be found or used";
    NSAppleScriptErrorMessage = "xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/Command/Applications/WeChat.app/Contents/MacOS/WeChat: the codesign_allocate helper tool cannot be found or used";
    NSAppleScriptErrorNumber = 1;
    NSAppleScriptErrorRange = "NSRange: {0, 87}";
}

**Comment by leiyily** [comment]
确实如楼上所说安装完Command_Line_Tools_for_Xcode_12.dmg就可以了mac 10.15.7 intel版，特来回答
