### ISSUE TITLE
微信回退版本也没办法防撤回了

### ISSUE THREAD

**Issue by pink0520** [sunnyyoung/WeChatTweak-macOS#576]
MAC，昨天手贱升级了微信版本，升级到3.6.2，发现防撤回用不了，结果去官网下载微信安装包，直接给我装了个3.7.0的，无语。然后我找到一个3.4.0的安装包，发现依然无法防撤回，该咋整？

**Comment by GitNiShuo** [comment]
xcode-select --install
执行一下这个命令 然后在
sudo wechattweak-cli install
我刚解决
