### ISSUE TITLE
安装成功了但是不知道咋样

### ISSUE THREAD

**Issue by MessiCY1994** [sunnyyoung/WeChatTweak-macOS#577]

**Comment by MessiCY1994** [comment]
<img width="684" alt="image" src="https://user-images.githubusercontent.com/29059292/217450372-90d5e448-088d-4083-bf3a-94947a9e6c56.png">
显示y已经下载成功了，但是不知道后续怎么搞？微信也没有啥异样啊

**Comment by MessiCY1994** [comment]
亲，你的邮件我已经收到，谢谢

**Comment by MessiCY1994** [comment]
aifred 怎么和这个插件配合？

**Comment by Doooing** [comment]
当然是: 下载 WeChat.alfredworkflow, 然后 双击 - import , 然后用 wc 命令唤醒
下载地址: 
https://github.com/sunnyyoung/WeChatTweak-macOS/blob/master/WeChat.alfredworkflow
大佬的实现过程: 
https://blog.sunnyyoung.net/rang-wei-xin-macos-ke-hu-duan-zhi-chi-alfred/

**Comment by Doooing** [comment]
<img width="818" alt="image" src="https://user-images.githubusercontent.com/58727869/217496847-7cfa75de-24e5-41c9-8f23-582ac87ead1d.png">

**Comment by MessiCY1994** [comment]
亲，你的邮件我已经收到，谢谢
