### ISSUE TITLE
最新版本微信，撤回功能失效

### ISSUE THREAD

**Issue by googooog** [sunnyyoung/WeChatTweak-macOS#578]
Version. 3.7.0 (25067)

最新版本微信，撤回功能失效

**Comment by Syzq** [comment]
看了看issues，好几次微信版本更新都有人来说插件失效，这次到底真的假的

**Comment by thefreelight** [comment]
> Version. 3.7.0 (25067)
> 
> 最新版本微信，撤回功能失效

你是咋安装上的，老板，为啥我安装完成以后，登录新微信都没有了
