### ISSUE TITLE
手贱升级了3.7版本，安装以后已经失效

### ISSUE THREAD

**Issue by thefreelight** [sunnyyoung/WeChatTweak-macOS#579]

**Comment by pink0520** [comment]
我回退到3.4，还是不生效啊

**Comment by difoi** [comment]
微信 Version. 3.7.0
Mac OS 13.2 (22D49)

更新插件后,可以正常使用;

**Comment by Syzq** [comment]
Version. 3.7.0 (25067)
macOS 13.2 (22D49) 
2023年02月10日13:39:47正常使用。

**Comment by dgulan** [comment]
<img width="475" alt="image" src="https://user-images.githubusercontent.com/28797169/218054276-fa1527c0-b3d4-4c1f-a716-c8499269c300.png">

         MacBook-Pro ~ % sudo wechattweak-cli install
Password:

------ Download ------
------ Unzip ------
Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS
------ Backup ------
WeChat.bak exists, skip it...
------ Remove Codesign ------
Execute command: codesign --remove-sign /Applications/WeChat.app/Contents/MacOS/WeChat
------ Insert Dylib ------
Binary is a fat binary with 2 archs.
Binary already contains a load command for that dylib. Skip it.
Binary already contains a load command for that dylib. Skip it.
Added LC_LOAD_DYLIB to all archs in /Applications/WeChat.app/Contents/MacOS/WeChat
------ Add Codesign ------
Execute command: codesign --force --deep --sign - /Applications/WeChat.app/Contents/MacOS/WeChat
Install success!


我应该是安装成功了。但是撤回功能未生效
系统13.2
微信版本3.6.2（24457）

**Comment by crazyPerject** [comment]
Version. 3.7.0 (25067)
macOS 10.14.6 (18G103)
2023年02月13日正常使用。

**Comment by pink0520** [comment]
ok了，我的也可以撤回了

**Comment by dgulan** [comment]
> <img alt="image" width="475" src="https://user-images.githubusercontent.com/28797169/218054276-fa1527c0-b3d4-4c1f-a716-c8499269c300.png">
> 
> ```
>      MacBook-Pro ~ % sudo wechattweak-cli install
> ```
> 
> Password:
> 
> ------ Download ------ ------ Unzip ------ Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS ------ Backup ------ WeChat.bak exists, skip it... ------ Remove Codesign ------ Execute command: codesign --remove-sign /Applications/WeChat.app/Contents/MacOS/WeChat ------ Insert Dylib ------ Binary is a fat binary with 2 archs. Binary already contains a load command for that dylib. Skip it. Binary already contains a load command for that dylib. Skip it. Added LC_LOAD_DYLIB to all archs in /Applications/WeChat.app/Contents/MacOS/WeChat ------ Add Codesign ------ Execute command: codesign --force --deep --sign - /Applications/WeChat.app/Contents/MacOS/WeChat Install success!
> 
> 我应该是安装成功了。但是撤回功能未生效 系统13.2 微信版本3.6.2（24457）

我正常使用了。谢谢大佬

**Comment by 344108150** [comment]
sudo wechattweak-cli --install  亲测好用

**Comment by sunnyyoung** [comment]
请查看 1.4.0 更新
