### ISSUE TITLE
如果打开免手机认证登陆后，每次登录成功后，最近的聊天记录不同步

### ISSUE THREAD

**Issue by kindergartenso** [Sunnyyoung/WeChatTweak-macOS#58]
如果打开免手机认证登陆后，每次登录成功后，最近的聊天记录不同步
微信版本：Version. 2.3.4 (9704)
MAC OS: 10.12.4

**Comment by Sunnyyoung** [comment]
这是微信的问题，它的同步功能一直很烂……
