### ISSUE TITLE
Mac M2 Pro 不生效

### ISSUE THREAD

**Issue by kevinLiang19920403** [sunnyyoung/WeChatTweak-macOS#581]
<img width="807" alt="image" src="https://user-images.githubusercontent.com/21100290/220300348-e5fa9d56-36d3-4c85-8d50-665993e3d3d9.png">
安装成功后使用Rosetta打开, 不生效
<img width="259" alt="image" src="https://user-images.githubusercontent.com/21100290/220300711-1083418c-3579-40ef-aaf3-7551e29723ca.png">
系统版本13.2.1  微信版本3.6.2  有大佬指点一下吗

**Comment by xygengcn** [comment]
只是按照命令而已，还要执行下面那句

**Comment by sunnyyoung** [comment]
你只装了 cli，还要执行 `sudo wechattweak-cli install`
