### ISSUE TITLE
M1 Pro 安装报错

### ISSUE THREAD

**Issue by KawhiWei** [sunnyyoung/WeChatTweak-macOS#582]
sudo wechattweak-cli install
------ Download ------
------ Unzip ------
Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS
Install failed: Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS failed: {
    NSAppleScriptErrorAppName = "wechattweak-cli";
                 unable to process WeChatTweak.framework/WeChatTweak.";WeChatTweak.frameworkTweakPreferencesController.strings.jects.nib.00.nib.
                 unable to process WeChatTweak.framework/WeChatTweak.";WeChatTweak.frameworkTweakPreferencesController.strings.jects.nib.00.nib.
    NSAppleScriptErrorNumber = 2;
    NSAppleScriptErrorRange = "NSRange: {0, 157}";
}

**Comment by vvanglro** [comment]
同报错
微信版本Version. 3.7.0 (25070)
系统版本13.2.1 (22D68)

**Comment by vvanglro** [comment]
sry, 电脑是迁移过来的, 终端没给完全磁盘访问, 给了权限后安装成功.

**Comment by ChristmasZCY** [comment]
同

------ Download ------
------ Unzip ------
Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS
------ Backup ------
WeChat.bak exists, skip it...
------ Remove Codesign ------
Execute command: codesign --remove-sign /Applications/WeChat.app/Contents/MacOS/WeChat
Install failed: Execute command: codesign --remove-sign /Applications/WeChat.app/Contents/MacOS/WeChat failed: {
    NSAppleScriptErrorAppName = "wechattweak-cli";
Run with --help for more information.";-sign is required
Run with --help for more information."; is required
    NSAppleScriptErrorNumber = 106;
    NSAppleScriptErrorRange = "NSRange: {0, 87}";
}
<img width="1696" alt="image" src="https://user-images.githubusercontent.com/61818189/221355555-1cd03579-129e-433c-9baf-653817ce1969.png">

**Comment by xygengcn** [comment]
> 同
> 
> ------ Download ------ ------ Unzip ------ Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS ------ Backup ------ WeChat.bak exists, skip it... ------ Remove Codesign ------ Execute command: codesign --remove-sign /Applications/WeChat.app/Contents/MacOS/WeChat Install failed: Execute command: codesign --remove-sign /Applications/WeChat.app/Contents/MacOS/WeChat failed: { NSAppleScriptErrorAppName = "wechattweak-cli"; Run with --help for more information.";-sign is required Run with --help for more information."; is required NSAppleScriptErrorNumber = 106; NSAppleScriptErrorRange = "NSRange: {0, 87}"; } <img alt="image" width="1696" src="https://user-images.githubusercontent.com/61818189/221355555-1cd03579-129e-433c-9baf-653817ce1969.png">

没权限，给完全访问权限到终端

**Comment by ChristmasZCY** [comment]
> 

你好，我已经sudo了，而且在设置中也给予了完全磁盘访问权限，请问还需要如何设置呢

**Comment by sasarcc** [comment]
打开隐私与安全-->app管理  打开就可以了。

**Comment by sasarcc** [comment]
> 打开隐私与安全-->app管理 打开就可以了。


打开隐私与安全-->app管理 打开就可以了。

**Comment by sasarcc** [comment]
> > 
> 
> 你好，我已经sudo了，而且在设置中也给予了完全磁盘访问权限，请问还需要如何设置呢

打开隐私与安全-->app管理 打开就可以了。

**Comment by ChristmasZCY** [comment]
<img width="1691" alt="image" src="https://user-images.githubusercontent.com/61818189/225793318-cf66875b-ed56-4b34-9c06-775f1be4f130.png">
已经打开了，还是bu xin不行呢

**Comment by 470582416** [comment]
> sudo wechattweak-cli install ------ Download ------ ------ Unzip ------ Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS Install failed: Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS failed: { NSAppleScriptErrorAppName = "wechattweak-cli"; unable to process WeChatTweak.framework/WeChatTweak.";WeChatTweak.frameworkTweakPreferencesController.strings.jects.nib.00.nib. unable to process WeChatTweak.framework/WeChatTweak.";WeChatTweak.frameworkTweakPreferencesController.strings.jects.nib.00.nib. NSAppleScriptErrorNumber = 2; NSAppleScriptErrorRange = "NSRange: {0, 157}"; }

+1

**Comment by howpig** [comment]
tks！it works

设备类型：MacBookPro18,1
系统版本：版本12.3.1（版号21E258）
系统语言：zh-Hans
微信版本：[2023-02-09 13:20:36] v3.7.0.16 (25070) #0d6b602459 p_0
微信语言：zh-Hans
历史版本：[2021-12-17 11:07:11] v3.2.2.16 (20346) #7db63e1f43
网络状态：Reachable via WiFi or Ethernet
显  示  器：*(2056x1329)/Retina


> > 同
> > ------ Download ------ ------ Unzip ------ Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS ------ Backup ------ WeChat.bak exists, skip it... ------ Remove Codesign ------ Execute command: codesign --remove-sign /Applications/WeChat.app/Contents/MacOS/WeChat Install failed: Execute command: codesign --remove-sign /Applications/WeChat.app/Contents/MacOS/WeChat failed: { NSAppleScriptErrorAppName = "wechattweak-cli"; Run with --help for more information.";-sign is required Run with --help for more information."; is required NSAppleScriptErrorNumber = 106; NSAppleScriptErrorRange = "NSRange: {0, 87}"; } <img alt="image" width="1696" src="https://user-images.githubusercontent.com/61818189/221355555-1cd03579-129e-433c-9baf-653817ce1969.png">
> 
> 没权限，给完全访问权限到终端

**Comment by EliBaron** [comment]
牛逼 终端完全磁盘访问权限就好了

**Comment by icebloodzs** [comment]
> 牛逼 终端完全磁盘访问权限就好了

<img width="705" alt="截屏2023-04-28 11 23 50" src="https://user-images.githubusercontent.com/28886392/235047027-94f5be0d-ceb4-499d-91f6-c4c6cbbeadfd.png">
是的，把这里的switch开启就成功安装了

**Comment by wangmeijian** [comment]
> > 牛逼 终端完全磁盘访问权限就好了
> 
> <img alt="截屏2023-04-28 11 23 50" width="705" src="https://user-images.githubusercontent.com/28886392/235047027-94f5be0d-ceb4-499d-91f6-c4c6cbbeadfd.png">
> 
> 是的，把这里的switch开启就成功安装了

+1

**Comment by maxs-marcel** [comment]
我开启了终端访问权限, 还是不行呢

**Comment by kanzakiken** [comment]
> sry, 电脑是迁移过来的, 终端没给完全磁盘访问, 给了权限后安装成功.

谢谢!
