### ISSUE TITLE
M2,13.2.1安装失败

### ISSUE THREAD

**Issue by yewuxue** [sunnyyoung/WeChatTweak-macOS#585]
<img width="1335" alt="image" src="https://user-images.githubusercontent.com/37978945/223013147-dcfcdc46-b395-4fb4-9514-aa077708fe17.png">

**Comment by EliBaron** [comment]
估计暂时还不支持M2 毕竟M2刚出

**Comment by nevertoday** [comment]
![image](https://user-images.githubusercontent.com/166048/236975365-fbca9eb9-393b-4df0-83aa-d6249fbc3bde.png)
我的m2 总是说这个

**Comment by xiaoemoxiw** [comment]
出现同样的问题。不知道怎样解决

**Comment by nevertoday** [comment]
无解的感觉

**Comment by zzusec** [comment]
> <img alt="image" width="1335" src="https://user-images.githubusercontent.com/37978945/223013147-dcfcdc46-b395-4fb4-9514-aa077708fe17.png">

我也是M2，跟你的错误一样

**Comment by xiaokyo** [comment]
一样的问题, 我是M1 pro

**Comment by sunnyyoung** [comment]
支持 Apple Silicon 的，不行的话重装下微信&Tweak
