### ISSUE TITLE
今天更新微信3.7.1.20(25682)最新版本后失效，最近微信更新频繁……

### ISSUE THREAD

**Issue by huangkouping** [sunnyyoung/WeChatTweak-macOS#589]
M1，系统版本：MOS 13.4 Beta版(22F5037d)
微信版本：Version. 3.7.1 (25667)

使用了命令sudo wechattweak-cli install，提示：
------ Download ------
------ Unzip ------
Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS
------ Backup ------
WeChat.bak exists, skip it...
------ Remove Codesign ------
Execute command: codesign --remove-sign /Applications/WeChat.app/Contents/MacOS/WeChat
------ Insert Dylib ------
Binary is a fat binary with 2 archs.
Binary already contains a load command for that dylib. Skip it.
Binary already contains a load command for that dylib. Skip it.
Added LC_LOAD_DYLIB to all archs in /Applications/WeChat.app/Contents/MacOS/WeChat
------ Add Codesign ------
Execute command: codesign --force --deep --sign - /Applications/WeChat.app/Contents/MacOS/WeChat
Install success!

撤回功能无效，icon右击也没有登录新账号。有人遇到这样的问题吧，我卸载重装好多次均无效。

**Comment by funyhook** [comment]
我也遇到了

**Comment by funyhook** [comment]
M1 系统版本13.3 微信版本Version. 3.7.1 (25664) Beta 11 
M1，系统版本：MOS 13.4 Beta版(22F5037d)
微信版本：Version. 3.7.1 (25667)

使用了命令sudo wechattweak-cli install，提示：
------ Download ------
------ Unzip ------
Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS
------ Backup ------
WeChat.bak exists, skip it...
------ Remove Codesign ------
Execute command: codesign --remove-sign /Applications/WeChat.app/Contents/MacOS/WeChat
------ Insert Dylib ------
Binary is a fat binary with 2 archs.
Binary already contains a load command for that dylib. Skip it.
Binary already contains a load command for that dylib. Skip it.
Added LC_LOAD_DYLIB to all archs in /Applications/WeChat.app/Contents/MacOS/WeChat
------ Add Codesign ------
Execute command: codesign --force --deep --sign - /Applications/WeChat.app/Contents/MacOS/WeChat
Install success!

撤回功能无效，icon右击也没有登录新账号。有人遇到这样的问题吧，我卸载重装好多次均无效。

**Comment by IZANAI** [comment]
3.7.1（25661），撤回功能还有，但是“登录新账号”就没了

**Comment by HerbertGao** [comment]
图标上右键多开的选项没了，不过尝试终端运行 `open -n /Applications/WeChat.app` 还是可以的

**Comment by Lin-Youth** [comment]
+1

**Comment by Jianhao9698** [comment]
+1 M2 的电脑现在既没了撤回又没了多开

**Comment by Akuns** [comment]
一样的问题

**Comment by renvip** [comment]
+1

**Comment by Leeiio** [comment]
还在3.7.1.17不敢更新，期待作者更新

**Comment by nani123123** [comment]
设备类型：Mac14,5
系统版本：版本13.3.1（版号22E261）
系统语言：zh-Hans
微信版本：[2023-04-20 21:05:28] v3.7.1.19 (25678) #2c0e6396c5 
微信语言：zh-Hans
历史版本：[2023-02-13 10:40:31] v3.7.0.17 (25067) #0528ee5334
网络状态：Reachable via WiFi or Ethernet
显  示  器：*(1800x1169)/Retina, (1504x846)/Retina, (1440x2560), (2560x1440)/Retina
`% sudo wechattweak-cli install
------ Download ------
------ Unzip ------
Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS
------ Backup ------
WeChat.bak exists, skip it...
------ Remove Codesign ------
Execute command: codesign --remove-sign /Applications/WeChat.app/Contents/MacOS/WeChat
------ Insert Dylib ------
Binary is a fat binary with 2 archs.
Binary already contains a load command for that dylib. Skip it.
Binary already contains a load command for that dylib. Skip it.
Added LC_LOAD_DYLIB to all archs in /Applications/WeChat.app/Contents/MacOS/WeChat
------ Add Codesign ------
Execute command: codesign --force --deep --sign - /Applications/WeChat.app/Contents/MacOS/WeChat
Install success!
`

一样的问题，右键新建窗口失效，防撤回记录还在

**Comment by simosun** [comment]
3.7.1 (25668) 图标上右键多开的选项没了，不过尝试终端运行 open -n /Applications/WeChat.app 还是可以的

**Comment by AdeeHou** [comment]
一样的问题。。还以为是安装错误了，重装了几次都不行

**Comment by DavidWangWang** [comment]
一样的问题。。还以为是安装错误了。 通过open -n /Applications/WeChat.app 临时解决了下

**Comment by AdeeHou** [comment]
> 一样的问题。。还以为是安装错误了，重装了几次都不行

微信回退3.7版本，就正常能用

**Comment by sunnyyoung** [comment]
https://github.com/sunnyyoung/WeChatTweak-macOS/releases/tag/1.3.2

**Comment by uxiume** [comment]
直接执行自动命令行吗？刚试过了，也重启了微信，没有设置按钮啊，需要特殊版本的微信吗

**Comment by uxiume** [comment]
@sunnyyoung 直接执行自动命令行吗？刚试过了，也重启了微信，没有设置按钮啊，需要特殊版本的微信吗

**Comment by uxiume** [comment]
@sunnyyoung 重装可以了
