### ISSUE TITLE
M1 13.0 运行失败：没做arm64

### ISSUE THREAD

**Issue by Koororo** [sunnyyoung/WeChatTweak-macOS#591]
`/Applications/WeChat.app/Contents/MacOS/WeChat ; exit;
dyld[55513]: Library not loaded: /Applications/WeChat.app/Contents/MacOS/WeChatPlugin.framework/WeChatPlugin
  Referenced from: <82FD08CA-28EB-39EF-9FC9-905E7E4B28D1> /Applications/WeChat.app/Contents/MacOS/WeChat
  Reason: tried: '/Applications/WeChat.app/Contents/MacOS/WeChatPlugin.framework/WeChatPlugin' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Applications/WeChat.app/Contents/MacOS/WeChatPlugin.framework/WeChatPlugin' (no such file), '/Applications/WeChat.app/Contents/MacOS/WeChatPlugin.framework/WeChatPlugin' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/Library/Frameworks/WeChatPlugin.framework/WeChatPlugin' (no such file), '/System/Library/Frameworks/WeChatPlugin.framework/WeChatPlugin' (no such file, not in dyld cache)
[1]    55513 abort      /Applications/WeChat.app/Contents/MacOS/WeChat`

**Comment by likaozheng** [comment]
M1可以运行的，我就是在M1 Max上正在使用。
https://github.com/sunnyyoung/WeChatTweak-CLI

**Comment by JoshuaFeng5** [comment]
我也可以， m1pro 也没问题

**Comment by sdrpsps** [comment]
M2也没问题

**Comment by sunnyyoung** [comment]
`WeChatPlugin.framework` 不是我的，请弄清楚自己装了多少个
