### ISSUE TITLE
1.3.2 1.3.3 消息撤回样式设置没有了

### ISSUE THREAD

**Issue by fangzhengjin** [sunnyyoung/WeChatTweak-macOS#594]
1.3.2 1.3.3 消息撤回样式设置没有了
<img width="543" alt="image" src="https://user-images.githubusercontent.com/12680972/235085101-e0199435-7e57-4a98-998a-6c79950f05da.png">

**Comment by fangzhengjin** [comment]
> 你测试一下就知道了

我说的是样式设置, 不是功能哦, 现在撤回就是一整条高亮那种, 很难看

**Comment by sunnyyoung** [comment]
@fangzhengjin 只保留遮罩样式了，消息提醒样式不好用，非文本类型要自己往上找上下文很麻烦。

难看是颜色难看吗？加自定义颜色怎么样

**Comment by fangzhengjin** [comment]
可以加个无色吗? 只在对应头像的下发显示撤回标记呢?

**Comment by sunnyyoung** [comment]
@fangzhengjin 🉑️

**Comment by sunnyyoung** [comment]
@fangzhengjin 3685d28592faffcea84851df30bee52010b1e757
