### ISSUE TITLE
安装失败，但是可用，何解

### ISSUE THREAD

**Issue by Jagerx** [sunnyyoung/WeChatTweak-macOS#595]
<img width="510" alt="image" src="https://user-images.githubusercontent.com/42521386/235085636-fd0efdfd-a64d-4dbf-85c5-5385949abec5.png">
<img width="790" alt="image" src="https://user-images.githubusercontent.com/42521386/235085877-490c620d-fbd4-42a6-b749-c1f342a8ca82.png">

**Comment by Jagerx** [comment]
官网下载的版本，版本号Version. 3.7.1 (25682)
系统默认终端Term：完全磁盘访问权限，APP管理权限全部开启
系统重启也有测试
使用Rosetta已勾选

**Comment by Jagerx** [comment]
自问自答，卸载了官网版，安装MAS版本以后可以了...

商店版Version. 3.7.1 (25683)
官网版Version. 3.7.1 (25682)

版本号还不一样，跟这有关系么？？

**Comment by sunnyyoung** [comment]
节省维护精力，只支持最新 App Store 版本
