### ISSUE TITLE
纯小白问下安装流程

### ISSUE THREAD

**Issue by Natsumehiroki** [sunnyyoung/WeChatTweak-macOS#598]
我下载了插件压缩包解压后应该怎么操作啊……
我只打开了insert_dylib这个进程文件……然后我在终端输入了使用栏里的命令，但是没有用……
新手小白一个，可以的话来个大佬指导下全流程和终端需要输入的指令……

**Comment by shackleyu** [comment]
使用
首次使用安装 
$ brew install sunnyyoung/repo/wechattweak-cli
安装/更新/卸载 Tweak:

$ sudo wechattweak-cli install   # 安装/更新
$ sudo wechattweak-cli uninstall # 卸载

**Comment by Natsumehiroki** [comment]
-bash: $: command not found
我输入以后显示这个……怎么处理呢

**Comment by ziqiya** [comment]
> -bash: $: command not found 我输入以后显示这个……怎么处理呢

$不需要输入

**Comment by Natsumehiroki** [comment]
> 

大佬，然后出现的是这个错误，是哪里的问题啊
-bash: brew: command not found

**Comment by Sofar1994** [comment]
> > 
> 
> 大佬，然后出现的是这个错误，是哪里的问题啊 -bash: brew: command not found

你没有安装brew命令，百度一下 homebrew， 安装这个命令之后就可以用brew安装了
