### ISSUE TITLE
362微信版本没有双开显示选项.

### ISSUE THREAD

**Issue by change3799** [sunnyyoung/WeChatTweak-macOS#599]
362微信版本没有双开显示选项. M1 版本 , 希望能解决.

**Comment by yueyu2421** [comment]
用terminal可以开

**Comment by yueyu2421** [comment]
另外release 1.3.4解决了问题

**Comment by change3799** [comment]
> 

是呀 只能用终端打开. 挺麻烦的.. 没有以前那个方便

**Comment by change3799** [comment]
> 用终端可以打开

是呀只能用到最后打开。坚持麻烦的.. 没有以前那个方便

**Comment by change3799** [comment]
> 用终端可以打开

是呀 只能用终端打开. 挺麻烦的. 没有以前那个方便.
