### ISSUE TITLE
请问如何发送图片

### ISSUE THREAD

**Issue by dennykong** [Sunnyyoung/WeChatTweak-macOS#60]
MessageService *service = [[objc_getClass("MMServiceCenter") defaultCenter] getService:objc_getClass("MessageService")];
        [service SendImgMessage:currentUserName toUsrName:toUserName thumbImgData:data midImgData:data imgData:data imgInfo:imgInfo];

这个图片发送接口，调用了，微信上能看到图片，表面上已经发送成功，但对方没收到。也可能是我的参数有问题。

**Comment by Sunnyyoung** [comment]
`imgInfo` 你传的什么

**Comment by dennykong** [comment]
@Sunnyyoung 是这样传的imageInfo,不知道是否正确     
 NSData* data = [NSData dataWithContentsOfURL:url];//图片数据通过url读取
        NSLog(@"lemgth %ld" , [data length]);
        NSImage *image=[[NSImage alloc]initWithData:data];
        NSSize size=[image size];
          SendImageInfo *imgInfo=[objc_getClass("SendImageInfo") alloc];
        [imgInfo setM_nuImageSourceURL:0x0];
        [imgInfo setM_uiImageSource:0];
        [imgInfo setM_uiThumbWidth:0x100];
        [imgInfo setM_uiThumbHeight:0x50]; 
        [imgInfo setM_uiOriginalWidth:size.width];
        [imgInfo setM_uiOriginalHeight:size.height];

**Comment by Sunnyyoung** [comment]
试试传 `nil`

**Comment by dennykong** [comment]
@Sunnyyoung 传nil效果和我传非nil的效果一样，也是表面上是是发送出去了，但对方收不到

**Comment by Sunnyyoung** [comment]
@dennykong 我这边测试OK喔

**Comment by dennykong** [comment]
@Sunnyyoung 能否分享一下发送图片代码

**Comment by Sunnyyoung** [comment]
@dennykong 

```objc
id thumb = [image thumbnailDataForMessage];
NSData *data = [image bestRepresentation];
[service SendImgMessage:fromUsername toUsrName:toUsername thumbImgData:thumb midImgData:data imgData:data imgInfo:nil];
```

**Comment by dennykong** [comment]
@Sunnyyoung 
id thumb = [image thumbnailDataForMessage];
NSData *data = [image bestRepresentation];
这个两个变量是怎样来的？

**Comment by Sunnyyoung** [comment]
@dennykong 调试 + 猜

**Comment by dennykong** [comment]
@Sunnyyoung  能否分享一下
id thumb = [image thumbnailDataForMessage];
NSData *data = [image bestRepresentation];
这两个的完整代码，谢谢

**Comment by Sunnyyoung** [comment]
@dennykong 这就是微信自己的方法

**Comment by dennykong** [comment]
@Sunnyyoung  thumbnailDataForMessage bestRepresentation 这个两个数据怎样来
例如我读一张图片URL，怎样转换成这样呢？

**Comment by Sunnyyoung** [comment]
@dennykong 
```objc
@interface NSImage()

- (id)thumbnailDataForMessage;
- (NSData *)bestRepresentation;

@end
```

**Comment by dennykong** [comment]
@Sunnyyoung 
 NSString *currentUserName = [objc_getClass("CUtility") GetCurrentUserName];
  NSString *toUserName=@"toUser";
    NSString * imgUrl = @"http://p6.qhimg.com/t011254cf99a0443e58.jpg";
    
    
    MMAvatarService *avService = [[objc_getClass("MMServiceCenter") defaultCenter] getService:objc_getClass("MMAvatarService")];

    [avService getAvatarImageWithUrl:imgUrl completion:^(NSImage *image) {
        id thumb = [image thumbnailDataForMessage];
        NSData *data = [image bestRepresentation]; //报错[NSCGImageSnapshotRep valueForProperty:]: unrecognized selector sent to instance 0x6000002743c0
       
        MessageService *service = [[objc_getClass("MMServiceCenter") defaultCenter] getService:objc_getClass("MessageService")];

        [service SendImgMessage:currentUserName toUsrName:toUserName thumbImgData:thumb midImgData:data imgData:data imgInfo:nil];
    }];
 我是这样写的，但 [image bestRepresentation]报错

你能否把你完整的代码片段参考一下

**Comment by Sunnyyoung** [comment]
@dennykong 把我上述代码加上不就可以了吗？

```objc
#import xxxx

@interface NSImage()

- (id)thumbnailDataForMessage;
- (NSData *)bestRepresentation;

@end

// 你其它代码
```

**Comment by dennykong** [comment]
@Sunnyyoung  不行
这里报错
   NSData *data = [image bestRepresentation]; //报错[NSCGImageSnapshotRep valueForProperty:]: unrecognized selector sent to instance 0x6000002743c0

**Comment by dennykong** [comment]
已经可以了，非常感谢

**Comment by xiaoxiaodexiaoxie** [comment]
@dennykong 完整的代码可以贴一下吗？

**Comment by wells1013** [comment]
@dennykong  @Sunnyyoung 请问发送图片thumbImgData 传递的是`[image thumbnailDataForMessage]` 返回的数据吗？
我按照 此发送 报这个 错误？
[MessageThumbData length]: unrecognized selector sent to instance 0x60400122bb00

**Comment by wangliangliang2** [comment]
@wenbobao @wells1013 @Zhou-Bill @xiaoxiaodexiaoxie

**Comment by wangliangliang2** [comment]
@xiaoxiaodexiaoxie @Zhou-Bill @wells1013 @wenbobao 
    id thumb = [image genThumbnailImageRawData];
不就可以了？
