### ISSUE TITLE
微信内连接无法由系统默认浏览器直接打开

### ISSUE THREAD

**Issue by Forgoys** [sunnyyoung/WeChatTweak-macOS#601]
MacOS版本：13.3.1 (a)
微信版本：Version. 3.7.1 (25683)
wechat-tweak版本：1.3.4
微信消息中的链接和分享均无法由系统默认浏览器直接打开

**Comment by azhen001** [comment]
这不是软件的问题,是微信更新了

**Comment by renvip** [comment]
希望能支持此功能🥺

**Comment by lifedever** [comment]
macOS 可以通过快捷键 `Control Option Cmd R` 打开调试设置，里面改
<img width="603" alt="image" src="https://github.com/sunnyyoung/WeChatTweak-macOS/assets/3143306/aeb9962f-1f0b-4973-bd5f-6b9721db3937">

**Comment by Forgoys** [comment]
之前的微信版本确实可以这么干，最新的不行了，按下快捷键没反应。

**Comment by 840103818** [comment]
搜索框输入，:recover 。就行了
<img width="309" alt="image" src="https://github.com/sunnyyoung/WeChatTweak-macOS/assets/31943002/bd17cb3f-f41d-44a0-92ce-02d5830a1818">

**Comment by lifedever** [comment]
> 搜索框输入，:recover 。就行了 <img alt="image" width="309" src="https://user-images.githubusercontent.com/31943002/241497539-bd17cb3f-f41d-44a0-92ce-02d5830a1818.png">

👍

**Comment by ManutdGTA** [comment]
配置里，使用默认浏览器打开链接。重启微信后普通的http链接生效了，但是微信类似的网页还是没生效

**Comment by lszddz** [comment]
希望能修复！！

**Comment by sunnyyoung** [comment]
3.8.1 官方支持通过默认浏览器打开
