### ISSUE TITLE
微信3.7.1版本安装插件后不能使用

### ISSUE THREAD

**Issue by chanqii** [sunnyyoung/WeChatTweak-macOS#602]
微信3.7.1版本安装插件后不能使用
撤回功能无效，多开入口不显示

**Comment by shackleyu** [comment]
<img width="403" alt="image" src="https://github.com/sunnyyoung/WeChatTweak-macOS/assets/30047991/62d55346-39b4-4bbd-ab95-f6197971ec22">
正常使用

**Comment by HaikunZhang** [comment]
<img width="1113" alt="image" src="https://github.com/sunnyyoung/WeChatTweak-macOS/assets/28700274/1105c145-ddc0-48f8-8135-151d4984a423">


mac 13.3.1 + 微信3.7.1  安装后也不能使用；
安装命令： brew install sunnyyoung/repo/wechattweak-cli

安装后尝试了重启微信/ 重启电脑，都无法正常使用插件

**Comment by elicip** [comment]
现在的撤回样式怎么都有遮罩了，之前可以无遮照样式的...

**Comment by chanqii** [comment]
mac 12.3，微信3.7.1不行，和系统版本有关吗？电脑是M1
