### ISSUE TITLE
Version 3.8.0(26239) 失效

### ISSUE THREAD

**Issue by missuo** [sunnyyoung/WeChatTweak-macOS#603]
3.8.0(26239) 失效

**Comment by isfk** [comment]
#605 605

**Comment by Ch1ngg** [comment]
同样。3.8.0(26239) 防撤回失效，插件是可以安装成功的

**Comment by FaiChou** [comment]
<img width="583" alt="WechatIMG65870" src="https://github.com/sunnyyoung/WeChatTweak-macOS/assets/18500846/5d858e83-6d34-438b-a261-e915ab4bc15c">

**Comment by missuo** [comment]
> #605 我的 3.8 冇问题

已经仔细阅读#605。

本Issue从未提及3.8.0安装的任何问题，在微信版本3.8.0的情况下可以被正常安装，但是没有任何效果。

**Comment by isfk** [comment]
> > #605 我的 3.8 冇问题
> 
> 已经仔细阅读#605。
> 
> 本Issue从未提及3.8.0安装的任何问题，在微信版本3.8.0的情况下可以被正常安装，但是没有任何效果。

我的错，确实撤回没有被拦截

**Comment by ZijieJin** [comment]
同

**Comment by zhangfurun** [comment]
同

**Comment by Maksim-venus** [comment]
同，3.8.0 失效，Apple M1 Pro

**Comment by Maksim-venus** [comment]
https://mksoftcdn.yesky.com/6466ccf5/8b0d0fcf0752bd66c8e8edc4284db594/uploadsoft/WeChatMac.3.7.1.dmg 3.7.1 下载链接

**Comment by lucksec** [comment]
> https://mksoftcdn.yesky.com/6466ccf5/8b0d0fcf0752bd66c8e8edc4284db594/uploadsoft/WeChatMac.3.7.1.dmg 3.7.1 下载链接

地址失效

**Comment by lucksec** [comment]
> 

历史版本https://github.com/zsbai/wechat-versions
上一个版本防撤回正常

**Comment by missuo** [comment]
别发历史版本了，就是想要**3.8.0**的**Features**！等待作者修复。

**Comment by gdunser** [comment]
我是新用户，一上来就是3.8.0，以为是我不用操作

**Comment by Maksim-venus** [comment]
3.7.1 版本 https://drive.google.com/file/d/1Yhb-MpmeKo8P0xmODh5pZ-93I2uoLVft/view

**Comment by sunnyyoung** [comment]
1.3.5 版本已更新支持
