### ISSUE TITLE
3.7.1.20无法升级wechattweak

### ISSUE THREAD

**Issue by yalunkong** [sunnyyoung/WeChatTweak-macOS#604]
运行sudo    wechattweak-cli install之后提示
Install failed: Execute command: codesign --remove-sign /Applications/WeChat.app/Contents/MacOS/WeChat failed: {
    NSAppleScriptErrorAppName = "wechattweak-cli";
    NSAppleScriptErrorBriefMessage = "xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Dev/Applications/WeChat.app/Contents/MacOS/WeChat: the codesign_allocate helper tool cannot be found or used";
    NSAppleScriptErrorMessage = "xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Develope/Applications/WeChat.app/Contents/MacOS/WeChat: the codesign_allocate helper tool cannot be found or used";
    NSAppleScriptErrorNumber = 1;
    NSAppleScriptErrorRange = "NSRange: {0, 87}";
}

**Comment by topzhanghj** [comment]
打开 设置》隐私与安全性〉完全磁盘访问权限》添加item ，就可以成功安装了，亲测有效

**Comment by yalunkong** [comment]
> 打开 设置》隐私与安全性〉完全磁盘访问权限》添加item ，就可以成功安装了，亲测有效

我确实用的是iterm，按你的方法试了一下，还是同样的报错。

**Comment by topzhanghj** [comment]
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools

**Comment by topzhanghj** [comment]
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools

我前段时间似乎也遇到过这个错误，是MacOS升级13后遇到，后来在设置中安装了一个更新补丁就没了，不知道能不能解决你的问题。

**Comment by yalunkong** [comment]
> xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools
> 
> 我前段时间似乎也遇到过这个错误，是MacOS升级13后遇到，后来在设置中安装了一个更新补丁就没了，不知道能不能解决你的问题。

我用  brew reinstall --cask wechattweak-cli重新跑了一下，显示说是安装成功了，是不是管用，还要观察观察。
mac11.7.7

**Comment by sunnyyoung** [comment]
1.3.5 版本已更新支持 WeChat 3.8.0
