### ISSUE TITLE
新撤回遮罩标记的消息在重启软件后不显示标记了，导致重启后不知道哪条被撤回了

### ISSUE THREAD

**Issue by htanx** [sunnyyoung/WeChatTweak-macOS#606]

**Comment by lucksec** [comment]
你还能用吗？新版本微信都不能使用了

**Comment by tedonggo** [comment]
<img width="238" alt="image" src="https://github.com/sunnyyoung/WeChatTweak-macOS/assets/85671965/d0b36e2c-62ea-44c9-8012-62f82b23b6e3">
一样安装不了 失效

**Comment by chenqingxiao007** [comment]
群聊不标记了，单聊可以

**Comment by langwuzhe** [comment]
> 



> 群聊不标记了，单聊可以

me too

**Comment by 719347266** [comment]
1. 重装3.7版本微信
2. https://github.com/sunnyyoung/WeChatTweak-macOS/releases 找到1.3.1版本的包 WeChatTweak.framework.zip
3. 解压后找到微信目录/Applications/WeChat.app/Contents/MacOS
4. 将解压后的文件夹复制进去/替换
5. 重新打开微信即可

**Comment by sunnyyoung** [comment]
1.3.5 版本已更新修复

**Comment by linguowei** [comment]
@sunnyyoung 我这边微信重启后，撤回遮罩样式还是消失了
系统 13.4 (22F66)
微信 3.8.0 (26246)
