### ISSUE TITLE
升级微信v3.8.0.17 ，安装失败

### ISSUE THREAD

**Issue by tedonggo** [sunnyyoung/WeChatTweak-macOS#607]
微信版本：
Verbose: v3.8.0.17 
System: OSX 11.5

执行：
sudo brew install sunnyyoung/repo/wechattweak-cli

结果：
Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.

**Comment by missuo** [comment]
这和本 Repo 没有任何关系。是你不用使用 Homebrew。

Brew 不允许在 ROOT 下安装。

```bash
brew install sunnyyoung/repo/wechattweak-cli
```

```bash
sudo wechattweak-cli install
```

**Comment by tedonggo** [comment]
好的 感谢啊 🙏
