### ISSUE TITLE
Version. 3.8.0 (26253) 用不了了

### ISSUE THREAD

**Issue by wangwei66666** [sunnyyoung/WeChatTweak-macOS#609]
好兄弟，Version. 3.8.0 (26253) 真的不能用了

**Comment by Maksim-venus** [comment]
微信  3.7.1 https://drive.google.com/file/d/1Yhb-MpmeKo8P0xmODh5pZ-93I2uoLVft/view

**Comment by sunnyyoung** [comment]
1.3.5 版本已更新支持
