### ISSUE TITLE
聊天支持分组么？？

### ISSUE THREAD

**Issue by gMan1990** [Sunnyyoung/WeChatTweak-macOS#61]
类似这样:
http://repo.xposed.info/module/site.cyningxu.grouphelper
https://www.coolapk.com/apk/164270

https://github.com/trazyn/weweChat/issues/89

**Comment by Sunnyyoung** [comment]
不支持的

**Comment by gMan1990** [comment]
加油，希望开发一下~

**Comment by Sunnyyoung** [comment]
成本太高，暂不考虑了
