### ISSUE TITLE
最近几天一直下载失败，是我的人品问题吗？

### ISSUE THREAD

**Issue by xdxray** [sunnyyoung/WeChatTweak-macOS#611]
$ Error: Download failed on Cask 'wechattweak-cli' with message: Download failed: https://github.com/Sunnyyoung/WeChatTweak-CLI/releases/download/1.4/wechattweak-cli

**Comment by xhl1993** [comment]
太菜了

**Comment by sunnyyoung** [comment]
国内网络问题，自行解决
