### ISSUE TITLE
新版本无法查看撤回信息 回退方法

### ISSUE THREAD

**Issue by 719347266** [sunnyyoung/WeChatTweak-macOS#612]
1. 重装3.7版本微信
2. https://github.com/sunnyyoung/WeChatTweak-macOS/releases 找到1.3.1版本的包 WeChatTweak.framework.zip
3. 解压后找到微信目录/Applications/WeChat.app/Contents/MacOS
4. 将解压后的文件夹复制进去/替换
5. 重新打开微信即可

**Comment by callmepopo** [comment]
3.7版本的微信 无从下载

**Comment by 840103818** [comment]
> 3.7版本的微信 无从下载
这个仓库可以下载
https://github.com/sunnyyoung/WeChatTweak-macOS/issues/612#issuecomment-1572948524

**Comment by remember-5** [comment]
> 1. 重装3.7版本微信
> 2. https://github.com/sunnyyoung/WeChatTweak-macOS/releases 找到1.3.1版本的包 WeChatTweak.framework.zip
> 3. 解压后找到微信目录/Applications/WeChat.app/Contents/MacOS
> 4. 将解压后的文件夹复制进去/替换
> 5. 重新打开微信即可

感谢

**Comment by xiaoshow** [comment]
宝子们有成功的么？为啥我第4步没有可替换的，目录 /Applications/WeChat.app/Contents/MacOS 下面只有 “微信”和"wechat"两个图标

1. 重装3.7版本微信
2. % brew reinstall --cask wechattweak-cli
3. https://github.com/sunnyyoung/WeChatTweak-macOS/releases 找到1.3.1版本的包 WeChatTweak.framework.zip
4. 解压后找到微信目录/Applications/WeChat.app/Contents/MacOS
5. 将解压后的文件夹复制进去/替换
6. 重新打开微信  （看不到工具安装成功

**Comment by marnon7** [comment]
谁有3.7版本的微信安装包呀？求一个

**Comment by 840103818** [comment]
@marnon7 https://github.com/zsbai/wechat-versions

**Comment by bingbaicai** [comment]
> 宝子们有成功的么？为啥我第4步没有可替换的，目录 /Applications/WeChat.app/Contents/MacOS 下面只有 “微信”和"wechat"两个图标
> 
> 1. 重装3.7版本微信
> 2. % brew reinstall --cask wechattweak-cli
> 3. https://github.com/sunnyyoung/WeChatTweak-macOS/releases 找到1.3.1版本的包 WeChatTweak.framework.zip
> 4. 解压后找到微信目录/Applications/WeChat.app/Contents/MacOS
> 5. 将解压后的文件夹复制进去/替换
> 6. 重新打开微信  （看不到工具安装成功

我也是这个问题

**Comment by sunnyyoung** [comment]
[1.3.5](https://github.com/sunnyyoung/WeChatTweak-macOS/releases) 版本已更新支持
