### ISSUE TITLE
最新版 WeChat 功能失效说明

### ISSUE THREAD

**Issue by sunnyyoung** [sunnyyoung/WeChatTweak-macOS#613]
最近太忙，请各位耐心等待更新……

**Comment by Jagerx** [comment]
感谢！！

**Comment by dgulan** [comment]
每天来刷2遍，就等着大佬更新。
继续耐心等待.jpg

**Comment by chenzhiguo** [comment]
附议

**Comment by wyshp** [comment]
坐等更新~

**Comment by mibboy** [comment]
我五月天的演唱会的门票都不盯了，就盯着你更新

**Comment by DamonBBQ** [comment]
坐等更新

**Comment by lw396** [comment]
坐等更新

**Comment by Cole7flowers** [comment]
坐等更新

**Comment by fohuhu** [comment]
更新了嘛？

**Comment by SunShRui** [comment]
更新了嘛？

**Comment by lifedever** [comment]
有必要问吗？更新了你就知道了。你看看现在 commit 的时间，像更新了吗？

**Comment by Dariozuo** [comment]
等待ing..

**Comment by pgjeffrey** [comment]
感谢🙏

**Comment by Akuns** [comment]
感谢🙏

**Comment by hotspider** [comment]
来刷刷，等更新！

**Comment by isyntop** [comment]
板凳快坐坏了，等更。。。

**Comment by rockpanda** [comment]
焊了个铁板凳  不影响

**Comment by topzhanghj** [comment]
我的是不提示撤回，能看到撤回的消息，vx版本是 3.7.1 (25683)

**Comment by nyjuner** [comment]
**### 不定期来看下进展，坐等大佬更新。**

**Comment by sunnyyoung** [comment]
<img width="513" alt="CleanShot 2023-06-11 at 17 32 52@2x" src="https://github.com/sunnyyoung/WeChatTweak-macOS/assets/5926284/d05ec4ea-79c3-483f-931b-57cbd5ca9b51">

已更新。

**Comment by langwuzhe** [comment]
> <img alt="CleanShot 2023-06-11 at 17 32 52@2x" width="513" src="https://user-images.githubusercontent.com/5926284/244927343-d05ec4ea-79c3-483f-931b-57cbd5ca9b51.png">
> 已更新。

大佬威武
