### ISSUE TITLE
安装好后,共享就不见了

### ISSUE THREAD

**Issue by ni11gg** [sunnyyoung/WeChatTweak-macOS#614]
用习惯了,比如PreView软件里直接共享到微信.这样使用非常方便.
但是安装完插件后,好像共享就不能用了.

**Comment by ni11gg** [comment]
就是共享文件,可以一键共享的.
不然还要找到那个文件,再手动拖过去.比较麻烦

**Comment by sunnyyoung** [comment]
这个好像一直都没有办法解决 ╮（╯＿╰）╭
