### ISSUE TITLE
防撤回功能无效

### ISSUE THREAD

**Issue by leonxulx** [sunnyyoung/WeChatTweak-macOS#615]
其实已经有段时间失效了，今天看见1.3.5支持3.8.0之后，又再试了一遍。
可惜，还是不行，哪怕卸载后重新安装都不行。Tweak标签正常显示在设置了，防撤回功能无论选择跟随还是全部接收，在实际使用中都无法显示撤回信息，无遮罩。
不知道问题出在哪里……卸载和安装过程中都无任何错误提示。
<img width="428" alt="截屏2023-06-12 00 56 29" src="https://github.com/sunnyyoung/WeChatTweak-macOS/assets/46668574/f4d46a8e-c008-4b46-a6f6-14781f18f7c1">
<img width="500" alt="截屏2023-06-12 00 56 19" src="https://github.com/sunnyyoung/WeChatTweak-macOS/assets/46668574/2b5891a6-fb69-48f4-90e8-60e3db3f274f">

**Comment by sunnyyoung** [comment]
只拦截对方的撤回，自己撤回**正常**

**Comment by wyshp** [comment]
请教 Tweak标签 怎么调出来，我更新1.3.5后，撤回功能查看正常，就是不知道哪里能设置这个撤回遮罩颜色

**Comment by zhuyuqian** [comment]
我也是，别人撤回的也防不住，重装很多次了

**Comment by joey777** [comment]
我也是，只能看到撤回一条消息，看不到撤回的内容，卸载重装了，也没用，
麻烦看看

**Comment by sunnyyoung** [comment]
更新 1.4.0
