### ISSUE TITLE
重启微信后撤回遮罩消失

### ISSUE THREAD

**Issue by normalwzh** [sunnyyoung/WeChatTweak-macOS#618]
之前老版本还能在历史记录里面标记XXX撤回了XXXX，可以区分开撤回了什么消息。
但是新版本只有遮罩以后，收到撤回后确实有标记，下次打开微信，就无法区分撤回了哪条消息了。

**Comment by superhuai** [comment]
3.8.0 一样的路过

**Comment by xjxjin** [comment]
3.8.0刚刚试了下，重启确实会撤回罩消失了

**Comment by sunnyyoung** [comment]
1.4.0 已经增加支持
