### ISSUE TITLE
3.8.0 微信语音通话会添加罩子

### ISSUE THREAD

**Issue by xjxjin** [sunnyyoung/WeChatTweak-macOS#619]
<img width="515" alt="image" src="https://github.com/sunnyyoung/WeChatTweak-macOS/assets/35513148/d2c4ba69-2aa9-4d67-b505-2f247db45625">

**Comment by xjxjin** [comment]
<img width="470" alt="image" src="https://github.com/sunnyyoung/WeChatTweak-macOS/assets/35513148/747f7fa0-7b11-4b50-887e-012f7b4b85fc">

**Comment by wwoshijiale** [comment]
会弹出一个群聊<null>(偶发性）感觉有点信息不同步

**Comment by liumumu666** [comment]
加油呀 大哥哥

**Comment by phpluo** [comment]
> ![1686559451027](https://user-images.githubusercontent.com/136315139/245083473-66a30d98-5825-41d2-9808-8c4763f776c3.jpg) 就这样的

这个好像是公众号消息触发的。

**Comment by sunnyyoung** [comment]
1.4.0 已修复
