### ISSUE TITLE
公众号文章无法打开

### ISSUE THREAD

**Issue by pengshiqi** [Sunnyyoung/WeChatTweak-macOS#62]
![image](https://user-images.githubusercontent.com/8055278/34645719-b17d375a-f38f-11e7-813e-5b43ee03d575.png)

![image](https://user-images.githubusercontent.com/8055278/34645722-ccbb379c-f38f-11e7-9a38-a2f546179837.png)

我点击公众号的文章后，在chrome浏览器中无法正常跳转打开，不知道是我这里的问题还是普遍的问题？

**Comment by Sunnyyoung** [comment]
@pengshiqi 这个是 Chrome 本身的问题，参考：https://www.v2ex.com/t/406915
