### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by EdisonWang2016** [sunnyyoung/WeChatTweak-macOS#620]
~ sudo wechattweak-cli install
------ Download ------
------ Unzip ------
Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS
Install failed: Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS failed: {
    NSAppleScriptErrorAppName = "wechattweak-cli";
                 unable to process WeChatTweak.framework/WeChatTweak.";WeChatTweak.frameworkTweakPreferencesController.strings.jects.nib.00.nib.
                 unable to process WeChatTweak.framework/WeChatTweak.";WeChatTweak.frameworkTweakPreferencesController.strings.jects.nib.00.nib.
    NSAppleScriptErrorNumber = 2;
    NSAppleScriptErrorRange = "NSRange: {0, 157}";
}

**Comment by sheeptako** [comment]
------ Download ------
------ Unzip ------
Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS
Install failed: Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS failed: {
    NSAppleScriptErrorAppName = "wechattweak-cli";
           No such file or directory";checkdir:  cannot create extraction directory: /Applications/WeChat.app/Contents/MacOS
           No such file or directory";dir:  cannot create extraction directory: /Applications/WeChat.app/Contents/MacOS
    NSAppleScriptErrorNumber = 2;
    NSAppleScriptErrorRange = "NSRange: {0, 157}";
}

**Comment by sheeptako** [comment]
我也遇到了同样的问题，终端加了Mac 完全磁盘访问权限，我是M2 Max

**Comment by wwoshijiale** [comment]
重启一下电脑就好了

**Comment by cipal1839** [comment]
[https://github.com/sunnyyoung/WeChatTweak-macOS/issues/621](url)

**Comment by sunnyyoung** [comment]
#621
