### ISSUE TITLE
M2执行sudo wechattweak-cli install报错

### ISSUE THREAD

**Issue by sheeptako** [sunnyyoung/WeChatTweak-macOS#621]
Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS
Install failed: Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS failed: {
    NSAppleScriptErrorAppName = "wechattweak-cli";
           No such file or directory";checkdir:  cannot create extraction directory: /Applications/WeChat.app/Contents/MacOS
           No such file or directory";dir:  cannot create extraction directory: /Applications/WeChat.app/Contents/MacOS
    NSAppleScriptErrorNumber = 2;
    NSAppleScriptErrorRange = "NSRange: {0, 157}";
}

![image](https://github.com/sunnyyoung/WeChatTweak-macOS/assets/26353767/44b264d6-67d1-4a85-8df9-c94ae13b35bc)

已按照之前同类型问题增加了终端的“完全访问权限”，但仍旧报错。
![image](https://github.com/sunnyyoung/WeChatTweak-macOS/assets/26353767/ca3f4c72-c16d-44ad-a359-2b301132fdc3)

**Comment by itgamer** [comment]
M1 PRO,No problem....

**Comment by ytzhsh** [comment]
先点下面的“-”号从列表中删除，然后再重新添加

**Comment by Jagerx** [comment]
商店版最新微信，同样报错，只是将微信改成“使用Rosetta打开”也可以运行，但总不算完美

**Comment by najunuoyan** [comment]
[](url)
![Xnip2023-06-21_15-54-24](https://github.com/sunnyyoung/WeChatTweak-macOS/assets/3922375/83283158-9c63-424d-aee4-9d2a549247e5)
把 APP 管理的权限也打开

**Comment by Jagerx** [comment]
> ![Xnip2023-06-21_15-54-24](https://user-images.githubusercontent.com/3922375/247474551-83283158-9c63-424d-aee4-9d2a549247e5.jpg)
> 把 APP 管理的权限也打开

正解，搞定
