### ISSUE TITLE
M1 微信防撤回失败

### ISSUE THREAD

**Issue by 591st66y** [sunnyyoung/WeChatTweak-macOS#622]
<img width="908" alt="image" src="https://github.com/sunnyyoung/WeChatTweak-macOS/assets/57025886/873906a8-90c7-4a44-a53a-53538e85d139">

<img width="316" alt="image" src="https://github.com/sunnyyoung/WeChatTweak-macOS/assets/57025886/21f49955-ade0-471d-a08d-8f496bbf331d">

**Comment by phpluo** [comment]
我也是m1 3.8防撤回是正常的 你这个通知我也有 好像是公众号消息触发的。

**Comment by sunnyyoung** [comment]
请更新 1.4.0
