### ISSUE TITLE
表情包加载不出来

### ISSUE THREAD

**Issue by like-aiquan** [sunnyyoung/WeChatTweak-macOS#626]
![image](https://github.com/sunnyyoung/WeChatTweak-macOS/assets/65346310/e4d963e6-02d3-4f06-99e5-c261056e2d07)

表情包加载不出来  不确定是不是bug,或者是微信版本的问题吗?

**Comment by sunnyyoung** [comment]
WeChat 问题

1. 搜索输入 `:recover`
2. 执行清除表情数据

**Comment by Kafka2** [comment]
> WeChat 问题
> 
> 1. 搜索输入 `:recover`
> 2. 执行清除表情数据

依然有问题

**Comment by like-aiquan** [comment]
ok了, 阿里嘎
