### ISSUE TITLE
好久没更新插件，现在不支持之前那种已拦截的防撤回提示了吗？

### ISSUE THREAD

**Issue by DDDD2000** [sunnyyoung/WeChatTweak-macOS#628]
更新了微信也更新了最新的插件，发现防撤回只能设置成遮罩样式，不能显示成之前那种“拦截了一条撤回消息xxxx”的样式吗？

插件设置页面可修改的选项也变少了

**Comment by FlameMida** [comment]
好像同步撤回消息到手机也没了

**Comment by DDDD2000** [comment]
还是喜欢之前那种防撤回的样式，而且现在的防撤回遮罩有bug，音视频消息也会显示成[已撤回]，希望作者闲暇之余可以更新一下~辛苦啦！

**Comment by sunnyyoung** [comment]
1.4.0 已修复

**Comment by DDDD2000** [comment]
> 

安装到最新版本还是遮罩样式呀~

**Comment by sunnyyoung** [comment]
@DDDD2000 不搞其他样式了，麻烦
