### ISSUE TITLE
微信收不到群语音or视频消息通知

### ISSUE THREAD

**Issue by isyntop** [sunnyyoung/WeChatTweak-macOS#630]
微信版本：Version. 3.8.0 (26253)
插件版本：1.3.5（sudo wechattweak-cli install 安装）
时间：上次防撤回失效修复更新后

问题描述：
1、群语音或视频消息收不到，也无法看到该群内其他正在通话的群语音信息
2、单独发起的语音或视频消息可以收到并正常使用。
3、使用sudo wechattweak-cli uninstall卸载后，可以正常收到群聊语音或视频消息
      重新使用sudo wechattweak-cli install后，仍然无法接受到群语音消息

**Comment by chenzhiguo** [comment]
附议

**Comment by sunnyyoung** [comment]
1.4.0 应该修复了
