### ISSUE TITLE
Version. 3.8.1 (26610) Beta 9

### ISSUE THREAD

**Issue by funyhook** [sunnyyoung/WeChatTweak-macOS#633]
Install failed: Execute command: codesign --force --deep --sign - /Applications/WeChat.app/Contents/MacOS/WeChat failed: {
    NSAppleScriptErrorAppName = "wechattweak-cli";
    NSAppleScriptErrorBriefMessage = "/Applications/WeChat.app/Contents/MacOS/WeChat: internal error in Code Signing subsystem";
    NSAppleScriptErrorMessage = "/Applications/WeChat.app/Contents/MacOS/WeChat: internal error in Code Signing subsystem";
    NSAppleScriptErrorNumber = 1;
    NSAppleScriptErrorRange = "NSRange: {0, 97}";
}

**Comment by onevv** [comment]
同样遇到了该问题

**Comment by vvanglro** [comment]
商店版的3.8.1(26639), 同样的报错.

**Comment by shenyijie1278** [comment]
3.8.1，brew安装可以，但是安装成功仍无法打开，sudo安装报同样的错

**Comment by shenyijie1278** [comment]
解决了，issue里面有这么个文章
<img width="396" alt="image" src="https://github.com/sunnyyoung/WeChatTweak-macOS/assets/139027242/aaf8e2b3-5059-4564-8f9a-45b4d81e8103">
底下有求3.8.0版本的，下载，下载完之后，在用sudo安装，安装成功，然后查看版本，发现还是3.8.1，好魔幻就

**Comment by sunnyyoung** [comment]
https://github.com/sunnyyoung/WeChatTweak-macOS/releases/tag/1.4.0
