### ISSUE TITLE
微信截图权限开了但是还是提示

### ISSUE THREAD

**Issue by Tony-stark-ui** [sunnyyoung/WeChatTweak-macOS#634]
<img width="260" alt="image" src="https://github.com/sunnyyoung/WeChatTweak-macOS/assets/81501882/51f6f82e-ddc3-4bd2-bc61-bfedae84dcad">
<img width="516" alt="image" src="https://github.com/sunnyyoung/WeChatTweak-macOS/assets/81501882/ba75e4c5-873b-4580-8d12-17e313be7ab6">

**Comment by Agent-4** [comment]
点减号删掉，再重新添加

**Comment by dgulan** [comment]
点减号删掉，再重新添加

**Comment by sunnyyoung** [comment]
1. 重新添加权限
2. 使用 1.5 版本 CLI
