### ISSUE TITLE
安装时出错：Error: Missing one of: '--install', '--uninstall' Help:  --install <install>  Install or Uninstall tweak Usage: tweak --install --uninstall   See 'tweak --help' for more information.

### ISSUE THREAD

**Issue by jjmomo** [sunnyyoung/WeChatTweak-macOS#637]
Error: Missing one of: '--install', '--uninstall'
Help:  --install <install>  Install or Uninstall tweak
Usage: tweak --install --uninstall
  See 'tweak --help' for more information.

请问如何解决呢？
谢谢！

**Comment by ZijieJin** [comment]
sudo wechattweak-cli install 或者sudo wechattweak-cli --install 都试试

**Comment by jjmomo** [comment]
> 
sudo: wechattweak-cli: command not found

出现这个错误提示

**Comment by jjmomo** [comment]
> sudo wechattweak-cli install 或者sudo wechattweak-cli --install 都试试

sudo: wechattweak-cli: command not found
出现这个错误提示

**Comment by ZijieJin** [comment]
先用brew安装wechattweak-cli，然后再运行sudo wechattweak-cli install。sudo后面没有冒号

**Comment by jjmomo** [comment]
> 先用brew安装wechattweak-cli，然后再运行sudo wechattweak-cli install。sudo后面没有冒号
好的 谢谢！❤️
