### ISSUE TITLE
无法安装, 下载提示ssl错误

### ISSUE THREAD

**Issue by geekscloud** [sunnyyoung/WeChatTweak-macOS#641]
执行:
sudo wechattweak-cli install

输出:
------ Download ------
Install failed: Download failed with error: Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSErrorFailingURLStringKey=https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/latest/download/WeChatTweak.framework.zip, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDownloadTask <86BD41FF-462C-439B-B01F-94E6C1C24064>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDownloadTask <86BD41FF-462C-439B-B01F-94E6C1C24064>.<1>"
), NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/latest/download/WeChatTweak.framework.zip, NSUnderlyingError=0x6000021dab20 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9860, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9860, _NSURLErrorNWPathKey=satisfied (Path is satisfied), viable, interface: lo0}}, _kCFStreamErrorCodeKey=-9860}

**Comment by fjiabinc** [comment]
Password:
------ Download ------
Install failed: Download failed with error: Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x6000027c4060 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDownloadTask <9E3144E9-7073-4C38-B5BA-D8AC46FDC1DB>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDownloadTask <9E3144E9-7073-4C38-B5BA-D8AC46FDC1DB>.<1>"
), NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/latest/download/WeChatTweak.framework.zip, NSErrorFailingURLKey=https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/latest/download/WeChatTweak.framework.zip, _kCFStreamErrorDomainKey=4}

**Comment by fjiabinc** [comment]
同样的错误

**Comment by sunnyyoung** [comment]
国内网络问题，需自行解决

**Comment by geekscloud** [comment]
> 国内网络问题，需自行解决

全局代理无论那个节点,换别人的机场也一样都不行
