### ISSUE TITLE
3.8.1 版本防撤回失败

### ISSUE THREAD

**Issue by DamonBBQ** [sunnyyoung/WeChatTweak-macOS#642]
<img width="550" alt="image" src="https://github.com/sunnyyoung/WeChatTweak-macOS/assets/13517401/8c9ee6a9-3e81-4684-9779-92c7b32d1bc8">
<img width="505" alt="image" src="https://github.com/sunnyyoung/WeChatTweak-macOS/assets/13517401/b6cdf14e-3c86-4320-981d-dcc35a451762">

3.8.1 新版本好像失效了

**Comment by CyberXfuck** [comment]
是的，今天自动更新了。。

**Comment by yuluoweichen** [comment]
降版本

**Comment by heshangcode** [comment]
是的，一样，同版本失效了

**Comment by geekris1** [comment]
> 降版本

如何才能下到3.8.0的微信呢= =

**Comment by char1eslu** [comment]
> > 降版本
> 
> 如何才能下到3.8.0的微信呢= =

https://github.com/zsbai/wechat-versions/releases

**Comment by caiyijia** [comment]
> > > 降版本
> > 
> > 
> > 如何才能下到3.8.0的微信呢= =
> 
> https://github.com/zsbai/wechat-versions/releases

我无论下载哪个版本，安装后都是 3.8.1，奇怪。 我每次都是删除后安装的
