### ISSUE TITLE
无法截图问题没有权限。

### ISSUE THREAD

**Issue by Amine-abc** [sunnyyoung/WeChatTweak-macOS#644]
Version. 3.8.1 (26638)。微信自动更新后，截图按照教程提示来配置一直无权限
<img width="418" alt="image" src="https://github.com/sunnyyoung/WeChatTweak-macOS/assets/62497577/812cec1f-09ff-4e29-ad65-1d231521e550">

**Comment by ccccmmmz** [comment]
看下634 去设置里面先移除微信 然后再添加微信就行了

**Comment by sunnyyoung** [comment]
尝试更新使用 cli 1.5 https://github.com/sunnyyoung/WeChatTweak-CLI/releases/tag/1.5
