### ISSUE TITLE
 sudo wechattweak-cli install 报错！！！！

### ISSUE THREAD

**Issue by coderluojz** [sunnyyoung/WeChatTweak-macOS#645]
sudo wechattweak-cli install
------ Download ------
------ Unzip ------
Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS
Install failed: Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS failed: {
    NSAppleScriptErrorAppName = "wechattweak-cli";
    NSAppleScriptErrorBriefMessage = "checkdir error:  cannot create /Applicaticheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTwcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTwcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTwcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTwcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTwcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTwcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTw                 unable to process WeChatTweak.framework/Versions/A/Headers/WeCcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTwcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTw                 unable to process WeChatTweak.framework/Versions/A/Modules/modcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTwcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTw                 unable to process WeChatTweak.framework/Versions/A/Resources/Bcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTw                 unable to process WeChatTweak.framework/Versions/A/Resources/Bcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTw                 unable to process WeChatTweak.framework/Versions/A/Resources/Bcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTw                 unable to process WeChatTweak.framework/Versions/A/Resources/Bcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTw                 unable to process WeChatTweak.framework/Versions/A/Resources/echeckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTw                 unable to process WeChatTweak.framework/Versions/A/Resources/echeckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTw                 unable to process WeChatTweak.framework/Versions/A/Resources/echeckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTw                 unable to process WeChatTweak.framework/Versions/A/Resources/Icheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTw                 unable to process WeChatTweak.framework/Versions/A/Resources/Pcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTw                 unable to process WeChatTweak.framework/Versions/A/Resources/zcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTw                 unable to process WeChatTweak.framework/Versions/A/Resources/zcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTw                 unable to process WeChatTweak.framework/Versions/A/Resources/zcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTw                 unable to process WeChatTweak.framework/Versions/A/Resources/zcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTw                 unable to process WeChatTweak.framework/Versions/A/Resources/zcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTw                 unable to process WeChatTweak.framework/Versions/A/Resources/zcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTw                 unable to process WeChatTweak.framework/Versions/A/WeChatTweakcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTwcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTw                 unable to process WeChatTweak.framework/WeChatTweak.";
    NSAppleScriptErrorMessage = "checkdir error:  cannot create /Applications/Wcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTwcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTwcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTwcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTwcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTwcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTwcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTw                 unable to process WeChatTweak.framework/Versions/A/Headers/WeCcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTwcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTw                 unable to process WeChatTweak.framework/Versions/A/Modules/modcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTwcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTw                 unable to process WeChatTweak.framework/Versions/A/Resources/Bcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTw                 unable to process WeChatTweak.framework/Versions/A/Resources/Bcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTw                 unable to process WeChatTweak.framework/Versions/A/Resources/Bcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTw                 unable to process WeChatTweak.framework/Versions/A/Resources/Bcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTw                 unable to process WeChatTweak.framework/Versions/A/Resources/echeckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTw                 unable to process WeChatTweak.framework/Versions/A/Resources/echeckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTw                 unable to process WeChatTweak.framework/Versions/A/Resources/echeckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTw                 unable to process WeChatTweak.framework/Versions/A/Resources/Icheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTw                 unable to process WeChatTweak.framework/Versions/A/Resources/Pcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTw                 unable to process WeChatTweak.framework/Versions/A/Resources/zcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTw                 unable to process WeChatTweak.framework/Versions/A/Resources/zcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTw                 unable to process WeChatTweak.framework/Versions/A/Resources/zcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTw                 unable to process WeChatTweak.framework/Versions/A/Resources/zcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTw                 unable to process WeChatTweak.framework/Versions/A/Resources/zcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTw                 unable to process WeChatTweak.framework/Versions/A/Resources/zcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTw                 unable to process WeChatTweak.framework/Versions/A/WeChatTweakcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTwcheckdir error:  cannot create /Applications/WeChat.app/Contents/MacOS/WeChatTw                 unable to process WeChatTweak.framework/WeChatTweak.";
    NSAppleScriptErrorNumber = 2;
    NSAppleScriptErrorRange = "NSRange: {0, 157}";
}

**Comment by zhllucky** [comment]
你的问题解决了吗。我这一样。
