### ISSUE TITLE
关于3.8.1无法使用，回撤3.8.0继续使用的方法

### ISSUE THREAD

**Issue by geekris1** [sunnyyoung/WeChatTweak-macOS#646]
目前3.8.1无法使用，可通过降版本来临时解决(本人已成功解决)。

首先下载3.8.0版本([我是链接](https://github.com/zsbai/wechat-versions/releases))

记得下5月18号这个版本的(最上面5月24号的也无法使用)

<img width="915" alt="image" src="https://github.com/sunnyyoung/WeChatTweak-macOS/assets/35247521/0d98c1a6-7a80-4333-aebb-13ee9579bd9d">

下载完之后，卸载之前的微信，仅卸载app，不要清历史数据，这样可以保存聊天记录

然后 后面的安装操作再来一遍即可

感谢[char1eslu](https://github.com/char1eslu)提供的微信历史版本下载链接

**Comment by caiyijia** [comment]
我按照上述流程操作了下，发现微信版本仍然是 3.8.1。

重试多次没有效果。

macOS: 13.4.1  WeChat: 3.8.1

**Comment by geekris1** [comment]
> 我按照上述流程操作了下，发现微信版本仍然是 3.8.1。
> 
> 重试多次没有效果。
> 
> macOS: 13.4.1 WeChat: 3.8.1

1.需要先卸载，再安装！
2.注意看我上面发的图,展开assets再下来,不要点DownloadFrom链接下载..

**Comment by caiyijia** [comment]
> 
我的问题出在了第 2 点。

重试后有效

thx.

**Comment by ccccmmmz** [comment]
回退可以用

**Comment by LEUNGHOTIN** [comment]
我通过这个方法回退也可以了

**Comment by sunnyyoung** [comment]
https://github.com/sunnyyoung/WeChatTweak-macOS/releases/tag/1.4.0 已经支持 WeChat 3.8.1

**Comment by like-aiquan** [comment]
WeChat 3.8.1(26639) 这个版本还是有问题
安装会报错, 降版本到 WeChat 3.8.1(26638)就好了
https://github.com/zsbai/wechat-versions/releases
这个链接是好使的

> https://github.com/sunnyyoung/WeChatTweak-macOS/releases/tag/1.4.0 已经支持 WeChat 3.8.1

**Comment by geekris1** [comment]
已支持3.8.1，请使用最新版本。
