### ISSUE TITLE
微信重启后，撤回的内容无颜色标识

### ISSUE THREAD

**Issue by Evi10x01** [sunnyyoung/WeChatTweak-macOS#649]
微信在未重启的情况下，对方撤回文件和消息可通过底色标识快速判断 撤回的内容信息，希望后续版本在微信重启后仍可保留对方撤回内容的底色标识。
如图1：正常情况下，可见撤回的信息和底部颜色标识。
如图2：微信重启后，仅可见撤回的信息，底部颜色标识已消失，重启后无法快速找到对方撤回的内容。
<img width="323" alt="image" src="https://github.com/sunnyyoung/WeChatTweak-macOS/assets/17192123/37683d2a-3c1c-4678-a80a-ade411ead66b">
<img width="419" alt="image" src="https://github.com/sunnyyoung/WeChatTweak-macOS/assets/17192123/a3478089-3b31-4893-9eca-e7650427c0f8">

**Comment by sunnyyoung** [comment]
Try: https://github.com/sunnyyoung/WeChatTweak-macOS/releases/tag/1.4.0

**Comment by shackleyu** [comment]
更新到1.4.0 这个问题解决了
<img width="670" alt="image" src="https://github.com/sunnyyoung/WeChatTweak-macOS/assets/30047991/a17fc8e7-94ca-46c0-a441-2992cfc3e175">
