### ISSUE TITLE
3.8.1 on 1.4.0 failed.

### ISSUE THREAD

**Issue by BenjaminX** [sunnyyoung/WeChatTweak-macOS#650]
![SCR-20230713-ng8](https://github.com/sunnyyoung/WeChatTweak-macOS/assets/612858/798346a0-5799-4ebf-a7ce-184393c41de4)

已经从官网下载安装 DMG 版本

**Comment by BenjaminX** [comment]
➜  Projects wechattweak-cli version
Get version failed: Error Domain=NSCocoaErrorDomain Code=260 "The file “Info.plist” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework/Versions/A/Resources/Info.plist, NSUnderlyingError=0x14be10910 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

**Comment by LEUNGHOTIN** [comment]
I have a similar situation，WeChat Version. 3.8.1 (26639)

**Comment by baoan12** [comment]
> 我也有类似的情况，微信版。3.8.1 (26639)
> 
> ```
> ------ Download ------
> ------ Unzip ------
> Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS
> ------ Backup ------
> Created WeChat.bak...
> ------ Remove Codesign ------
> Execute command: codesign --remove-sign /Applications/WeChat.app/Contents/MacOS/WeChat
> ------ Insert Dylib ------
> Binary is a fat binary with 2 archs.
> It doesn't seem like there is enough empty space. Continue anyway.Added LC_LOAD_DYLIB to all archs in /Applications/WeChat.app/Contents/MacOS/WeChat
> ------ Add Codesign ------
> Execute command: codesign --force --deep --sign - /Applications/WeChat.app/Contents/MacOS/WeChat
> Install failed: Execute command: codesign --force --deep --sign - /Applications/WeChat.app/Contents/MacOS/WeChat failed: {
>     NSAppleScriptErrorAppName = "wechattweak-cli";
>     NSAppleScriptErrorBriefMessage = "/Applications/WeChat.app/Contents/MacOS/WeChat: internal error in Code Signing subsystem";
>     NSAppleScriptErrorMessage = "/Applications/WeChat.app/Contents/MacOS/WeChat: internal error in Code Signing subsystem";
>     NSAppleScriptErrorNumber = 1;
>     NSAppleScriptErrorRange = "NSRange: {0, 97}";
> }
> ```

解决了吗？ 我死活都不行，不知道怎么处理

**Comment by LEUNGHOTIN** [comment]
> > 我也有类似的情况，微信版。3.8.1 (26639)
> > ```
> > ------ Download ------
> > ------ Unzip ------
> > Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS
> > ------ Backup ------
> > Created WeChat.bak...
> > ------ Remove Codesign ------
> > Execute command: codesign --remove-sign /Applications/WeChat.app/Contents/MacOS/WeChat
> > ------ Insert Dylib ------
> > Binary is a fat binary with 2 archs.
> > It doesn't seem like there is enough empty space. Continue anyway.Added LC_LOAD_DYLIB to all archs in /Applications/WeChat.app/Contents/MacOS/WeChat
> > ------ Add Codesign ------
> > Execute command: codesign --force --deep --sign - /Applications/WeChat.app/Contents/MacOS/WeChat
> > Install failed: Execute command: codesign --force --deep --sign - /Applications/WeChat.app/Contents/MacOS/WeChat failed: {
> >     NSAppleScriptErrorAppName = "wechattweak-cli";
> >     NSAppleScriptErrorBriefMessage = "/Applications/WeChat.app/Contents/MacOS/WeChat: internal error in Code Signing subsystem";
> >     NSAppleScriptErrorMessage = "/Applications/WeChat.app/Contents/MacOS/WeChat: internal error in Code Signing subsystem";
> >     NSAppleScriptErrorNumber = 1;
> >     NSAppleScriptErrorRange = "NSRange: {0, 97}";
> > }
> > ```
> 
> 解决了吗？ 我死活都不行，不知道怎么处理

只要下载[微信官网的版本](https://mac.weixin.qq.com/?t=mac&lang=zh_CN)就能解决了，Mac App Store版本是没法成功的
