### ISSUE TITLE
安装命令少了--cask？

### ISSUE THREAD

**Issue by xiebruce** [sunnyyoung/WeChatTweak-macOS#651]
安装的时候提示这个，说明我之前安装过
<img width="430" alt="image" src="https://github.com/sunnyyoung/WeChatTweak-macOS/assets/13575500/26bf1a9e-ff94-4ec7-a26f-249d1e20e708">

是不是说明readme中少写了个`--cask`？
<img width="629" alt="image" src="https://github.com/sunnyyoung/WeChatTweak-macOS/assets/13575500/d7556b21-29b4-46b4-8863-93a57d3e0c73">

**Comment by sunnyyoung** [comment]
没有

**Comment by xiebruce** [comment]
我卸载重装试了，还真不用`--cask`，奇怪我之前那个不知道哪儿来的
