### ISSUE TITLE
3.8.1用了最新1.4.0版本还是不显示撤回消息

### ISSUE THREAD

**Issue by zhangweigithub** [sunnyyoung/WeChatTweak-macOS#652]
![047A55DE-457B-4B63-BAD4-B7132A3CD072](https://github.com/sunnyyoung/WeChatTweak-macOS/assets/13460975/dbce2390-af8f-4aa4-a174-e7fa4a2b5fe5)

**Comment by sunnyyoung** [comment]
不拦截自己撤回的消息
