### ISSUE TITLE
这是什么意思？ NSAppleScriptErrorNumber = 2;     NSAppleScriptErrorRange = "NSRange: {0, 157}";

### ISSUE THREAD

**Issue by baoan12** [sunnyyoung/WeChatTweak-macOS#653]
unable to process WeChatTweak.framework/WeChatTweak.";
    NSAppleScriptErrorNumber = 2;
    NSAppleScriptErrorRange = "NSRange: {0, 157}";

**Comment by Hem1ock** [comment]
同样的问题，手动下载再拖进去微信目录下吧 -> /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework

https://github.com/sunnyyoung/WeChatTweak-macOS/releases/tag/1.4.0

**Comment by peipeijiang** [comment]
------ Add Codesign ------
Execute command: codesign --force --deep --sign - /Applications/WeChat.app/Contents/MacOS/WeChat
Install failed: Execute command: codesign --force --deep --sign - /Applications/WeChat.app/Contents/MacOS/WeChat failed: {
    NSAppleScriptErrorAppName = "wechattweak-cli";
    NSAppleScriptErrorBriefMessage = "/Applications/WeChat.app/Contents/MacOS/WeChat: internal error in Code Signing subsystem";
    NSAppleScriptErrorMessage = "/Applications/WeChat.app/Contents/MacOS/WeChat: internal error in Code Signing subsystem";
    NSAppleScriptErrorNumber = 1;
    NSAppleScriptErrorRange = "NSRange: {0, 97}";
    我的也是这样子

**Comment by sunnyyoung** [comment]
@peipeijiang 你的不一样，你要用官网 DMG 包

**Comment by A-Kui** [comment]
Install failed: Execute command: codesign --force --deep --sign - /Applications/WeChat.app/Contents/MacOS/WeChat failed: {
    NSAppleScriptErrorAppName = "wechattweak-cli";
    NSAppleScriptErrorBriefMessage = "/Applications/WeChat.app/Contents/MacOS/WeChat: internal error in Code Signing subsystem";
    NSAppleScriptErrorMessage = "/Applications/WeChat.app/Contents/MacOS/WeChat: internal error in Code Signing subsystem";
    NSAppleScriptErrorNumber = 1;
    NSAppleScriptErrorRange = "NSRange: {0, 97}";
}

**Comment by macgg** [comment]
> @peipeijiang 你的不一样，你要用官网 DMG 包

可以用新的版本给3.8.1安装, 但是dmg版本会验证签名, 需要在设置->隐私里面设置允许不认识的开发者签名, 才能打开微信程序. 希望对后来人有所帮助

**Comment by ShineZcx** [comment]
@macgg 用App Store装的微信不行吗？

**Comment by A-Kui** [comment]
我已经可以使用了，但是没去验证导致的因素。方法如下：
1.微信官网下载安装 Version. 3.8.1 (26638) 
2.手动导入WeChatTweak.framework.zip
3.执行sudo wechattweak-cli install 

GPT4问到的答案出现此类错误可能有几个原因：
1.文件损坏或已被修改：如果你正在尝试对的应用已被修改或损坏，可能会引起这个问题。请尝试重新安装原始的应用。
2.权限问题：进行代码签名操作需要管理员权限。请确认你正在使用有管理员权限的用户账户执行该操作，或者使用 sudo 命令。
3.签名证书问题：你正在使用 - 选项进行代码签名，它会告诉 codesign 使用 ad-hoc 模式进行签名，即不使用任何特定的证书进行签名。在大多数情况下，这应该是可以的，但在某些情况下，这可能会导致问题。如果你有一个有效的开发者证书，可以尝试使用它替代 - 选项。

综合考虑，个人判断可能是3.签名证书问题，那么就不需要步骤2操作，去微信官网下载安装

**Comment by qianjun2659** [comment]
设置-隐私与安全性-App管理
打开执行命令的工具的开关。理论上就可以了。
