### ISSUE TITLE
hello      NSAppleScriptErrorRange = "NSRange: {0, 97}"; 这个问题要怎么解决

### ISSUE THREAD

**Issue by Gary-yp** [sunnyyoung/WeChatTweak-macOS#656]
Install failed: Execute command: codesign --force --deep --sign - /Applications/WeChat.app/Contents/MacOS/WeChat failed: {
    NSAppleScriptErrorAppName = "wechattweak-cli";
    NSAppleScriptErrorBriefMessage = "/Applications/WeChat.app/Contents/MacOS/WeChat: internal error in Code Signing subsystem";
    NSAppleScriptErrorMessage = "/Applications/WeChat.app/Contents/MacOS/WeChat: internal error in Code Signing subsystem";
    NSAppleScriptErrorNumber = 1;
    NSAppleScriptErrorRange = "NSRange: {0, 97}";

**Comment by yybawang** [comment]
虽然失败，但防撤回正常用，微信客户端设置已经有撤回选项了

**Comment by Gary-yp** [comment]
重新下载新版本微信。就可以了。
