### ISSUE TITLE
微信截图无法使用

### ISSUE THREAD

**Issue by mengyu987** [sunnyyoung/WeChatTweak-macOS#659]
m1芯片
masos 13.4 
微信截图不管用，重新设置快捷键也不行
重新打开屏幕录制权限也不行，重启微信，重启电脑都试了没效果

**Comment by mengyu987** [comment]
已找到解决方案

**Comment by mengyu987** [comment]
一定要删除微信的权限，就是选择微信，然后点-号再添加微信就可以

**Comment by setsunadoudou** [comment]
同样问题，找到解决方法了，谢谢
