### ISSUE TITLE
微信 3.8.1 (26639)版本报错

### ISSUE THREAD

**Issue by coolinmind** [Sunnyyoung/WeChatTweak-macOS#665]
执行 sudo wechattweak-cli install后报错
<img width="1328" alt="image" src="https://github.com/sunnyyoung/WeChatTweak-macOS/assets/28701474/02207d83-8b91-4988-9866-6dcc5d9ccf11">

**Comment by sunnyyoung** [comment]
命令行给权限了吗

**Comment by mibboy** [comment]
是不是终端没给权限

**Comment by ZWXAllen** [comment]
我报一样的错
