### ISSUE TITLE
bartender 對修改後的微信失效

### ISSUE THREAD

**Issue by msongz** [Sunnyyoung/WeChatTweak-macOS#67]
安裝了此插件後會令bartender失效
不能隱藏微信

**Comment by Sunnyyoung** [comment]
@msongz 测试并没有问题

![image](https://user-images.githubusercontent.com/5926284/35491800-cf098c50-04e3-11e8-98c2-35b46730f090.png)

**Comment by coldice945** [comment]
Me Too

**Comment by izhangxm** [comment]
我的是不显示微信图标了

**Comment by MichaelLyo** [comment]
一样，不能显示装了Tweak的微信通知
