### ISSUE TITLE
撤回多条消息只显示一条

### ISSUE THREAD

**Issue by vooooz** [sunnyyoung/WeChatTweak-macOS#670]
对方同时撤回了多条消息的时候，停留在当前聊天窗口时显示撤回多条消息，但是如果切换到其它聊天窗口再切换回来就只显示一条撤回消息

**Comment by cheemszzZ** [comment]
+1

**Comment by sonwa** [comment]
+1，遇到同样问题

**Comment by vindia9** [comment]
Version. 3.8.2 (27315) 也遇到了同样的问题

**Comment by dingzhy1991** [comment]
也遇到了同样问题

**Comment by sunnyyoung** [comment]
已修复：https://github.com/sunnyyoung/WeChatTweak-macOS/releases/tag/1.4.1

**Comment by vindia9** [comment]
> 已修复：https://github.com/sunnyyoung/WeChatTweak-macOS/releases/tag/1.4.1

感谢，经验证bug已修复。本机版本：

macOS Ventura 13.5.1 (22G90)
WeChat Version 3.8.2 (27317)

**Comment by QuincyYip** [comment]
WeChat Version. 3.8.3 (27318) 失效
