### ISSUE TITLE
双开无限弹权限提醒

### ISSUE THREAD

**Issue by jingzhongchangan** [sunnyyoung/WeChatTweak-macOS#677]
版本：1.4.0
系统：14.0 Beta (23A5312d)
芯片：M2 Pro

问题：每次重新打开第一个时都会弹一次提醒，点击允许之后正常。然后再打开第二个，会无限弹权限提醒，点击允许或不允许都会无限弹。然后过一段时间之后再点击就消失了，微信也没有启动
![2023-08-18_09 37 55](https://github.com/sunnyyoung/WeChatTweak-macOS/assets/105959405/75eeabd2-04d0-48fb-af34-d7fec36deb4d)

**Comment by huangkouping** [comment]
隐私与安全性，完全磁盘访问权限，打开微信开关。如果这样没用的话，把里面微信权限先删了，然后再次添加上就OK了。

**Comment by jingzhongchangan** [comment]
感谢大佬

> 隐私与安全性，完全磁盘访问权限，打开微信开关。如果这样没用的话，把里面微信权限先删了，然后再次添加上就OK了。
