### ISSUE TITLE
怎么打开？安装后无法使用

### ISSUE THREAD

**Issue by winterant** [sunnyyoung/WeChatTweak-macOS#678]
<img width="1226" alt="image" src="https://github.com/sunnyyoung/WeChatTweak-macOS/assets/37205944/d62f47da-652a-4a90-865c-d9219c590688">

<img width="227" alt="image" src="https://github.com/sunnyyoung/WeChatTweak-macOS/assets/37205944/c58d752c-e38d-47ea-ab20-6e84b64ee6a3">

请问怎么使用？找不到在哪里打开

**Comment by leosanqing** [comment]
> hello， 这个怎么解决的呀 我也是遇到这个和问题
版本信息是这些
设备类型：Mac14,12
系统版本：版本14.2（版号23C5047e）
系统语言：zh-Hans
微信版本：[2023-11-21 11:11:13] v3.8.5.16 (27885) #701bb0a611 
微信语言：zh-Hans
历史版本：[2023-10-17 19:26:34] v3.8.4.16 (27738) #c917f63fef
网络状态：Reachable via WiFi or Ethernet
显  示  器：*(2560x1440)

**Comment by winterant** [comment]
按readme安装好之后，需要手动用命令行启动一次
```
open -n /Applications/WeChat.app
```
另外，记得给微信完全访问磁盘权限。设置 - 隐私性 - 磁盘访问 - 添加微信。
