### ISSUE TITLE
3.8.2 (27317) 安装无反应

### ISSUE THREAD

**Issue by amasawa** [sunnyyoung/WeChatTweak-macOS#685]

**Comment by sunnyyoung** [comment]
什么意思

**Comment by amasawa** [comment]
sudo wechattweak-cli install
安装完之后微信没变化

**Comment by sunnyyoung** [comment]
你说的变化是指什么

**Comment by amasawa** [comment]
<img width="494" alt="Screen Shot 2023-09-09 at 21 24 22" src="https://github.com/sunnyyoung/WeChatTweak-macOS/assets/27271254/0eff128b-18fd-4be0-a75b-70a3cde369e5">

**Comment by amasawa** [comment]
好奇怪

**Comment by sunnyyoung** [comment]
噢？这是什么版本的系统呢？

**Comment by amasawa** [comment]
> 噢？这是什么版本的系统呢？

12.3

**Comment by amasawa** [comment]
Done!
