### ISSUE TITLE
安装后启动微信提示“微信.app”想访问其他App的数据

### ISSUE THREAD

**Issue by kailiu42** [sunnyyoung/WeChatTweak-macOS#707]
如截图，请问这是正常的吗？

点击允许，就会开启原来的微信，点击不允许，就会开启一个新的登录窗口。但是无论选哪个，退出微信后重新打开都会有这个选择对话框，每次启动都要选一次。

微信是从app store安装的，版本3.8.3。

<img width="260" alt="Snipaste-20231014-092945" src="https://github.com/sunnyyoung/WeChatTweak-macOS/assets/358679/7016ee9a-fa34-48e5-bb99-567783fff50f">

**Comment by shackleyu** [comment]
macOS14 是这样的.这个是系统的问题.但是多开不了了.

**Comment by kailiu42** [comment]
感谢各位回复。另外问一下，每次微信更新后，都需要从新运行`sudo wechattweak-cli install`对吗？

**Comment by shackleyu** [comment]
> 谢谢各位回复。另外问一下，每次微信更新后，都需要从新运行对`sudo wechattweak-cli install`吗？

是的,微信更新了.相当于重新安装了一次.

**Comment by shackleyu** [comment]
<img width="534" alt="image" src="https://github.com/sunnyyoung/WeChatTweak-macOS/assets/30047991/5bcb416c-7bac-4b6b-80aa-fbf6498f705e">
给予微信完全访问磁盘的权限既可
