### ISSUE TITLE
3.8.4.20请求支持

### ISSUE THREAD

**Issue by OaimIsGnay** [sunnyyoung/WeChatTweak-macOS#709]
<img width="620" alt="image" src="https://github.com/sunnyyoung/WeChatTweak-macOS/assets/58240619/be9b1380-c141-4b3d-9648-be07a3e05166">

**Comment by jxzlhy** [comment]
有没有哥们升级试一试

**Comment by OaimIsGnay** [comment]
> 有没有哥们升级试一试

我试了.可以使用,就是每次打开微信都提示想访问其他APP的数据
<img width="260" alt="image" src="https://github.com/sunnyyoung/WeChatTweak-macOS/assets/58240619/7a46aa07-9eb6-4391-96bd-f2dc4c60e5d1">

**Comment by oxcz** [comment]
3.8.4 (27738) 
不是太好用，应该和系统也有关系吧。
macOS也是14，会一直谈上面的框加载不出来。

**Comment by OaimIsGnay** [comment]
> 3.8.4 (27738) 不是太好用，应该和系统也有关系吧。 macOS也是14，会一直谈上面的框加载不出来。

奇怪....我是刚发现这个bug的..因为之前一直没有这个弹窗.这次升级完微信才有的这个.系统也是mac14

**Comment by jxzlhy** [comment]
> > 有没有哥们升级试一试
> 
> 我试了.可以使用,就是每次打开微信都提示想访问其他APP的数据 <img alt="image" width="260" src="https://user-images.githubusercontent.com/58240619/276079337-7a46aa07-9eb6-4391-96bd-f2dc4c60e5d1.png">

我升级了，可以用，没有弹窗，系统是12...

**Comment by shackleyu** [comment]
第一,支持最新版微信
第二,关于提示微信.app想访问其它App的数据这个问题,可以给予微信完全访问磁盘权限后,既可解决
<img width="534" alt="image" src="https://github.com/sunnyyoung/WeChatTweak-macOS/assets/30047991/ef05e863-ce1b-41c9-8c69-9ee8afe3fb19">

**Comment by Philae994** [comment]
> 第一,支持最新版微信 第二,关于提示微信.app想访问其它App的数据这个问题,可以给予微信完全访问磁盘权限后,既可解决 <img alt="image" width="534" src="https://user-images.githubusercontent.com/30047991/276281723-ef05e863-ce1b-41c9-8c69-9ee8afe3fb19.png">

谢谢哥，已解决

**Comment by OaimIsGnay** [comment]
> 第一,支持最新版微信 第二,关于提示微信.app想访问其它App的数据这个问题,可以给予微信完全访问磁盘权限后,既可解决 <img alt="image" width="534" src="https://user-images.githubusercontent.com/30047991/276281723-ef05e863-ce1b-41c9-8c69-9ee8afe3fb19.png">

设置了每次也有弹窗

**Comment by shackleyu** [comment]
> > 第一,支持最新版微信 第二,关于提示微信.app想访问其它App的数据这个问题,可以给予微信完全访问磁盘权限后,既可解决 <img alt="image" width="534" src="https://user-images.githubusercontent.com/30047991/276281723-ef05e863-ce1b-41c9-8c69-9ee8afe3fb19.png">
> 
> 设置了每次也有弹窗
先点击-号,把微信删了. 再添加

**Comment by OaimIsGnay** [comment]
> > > 第一,支持最新版微信 第二,关于提示微信.app想访问其它App的数据这个问题,可以给予微信完全访问磁盘权限后,既可解决 <img alt="image" width="534" src="https://user-images.githubusercontent.com/30047991/276281723-ef05e863-ce1b-41c9-8c69-9ee8afe3fb19.png">
> > 
> > 
> > 设置了每次也有弹窗
> > 先点击-号,把微信删了. 再添加

谢谢,解决了.

**Comment by AmorFly** [comment]
都试了  没用

**Comment by thefreelight** [comment]
我一开始没有这个问题，但是退出登录了一下，也开始跳这个问题了
![image](https://github.com/user-attachments/assets/b133903b-0e51-43cc-be07-f3a6d6215715)

**Comment by thefreelight** [comment]
> 第一,支持最新版微信 第二,关于提示微信.app想访问其它App的数据这个问题,可以给予微信完全访问磁盘权限后,既可解决 <img alt="image" width="534" src="https://private-user-images.githubusercontent.com/30047991/276281723-ef05e863-ce1b-41c9-8c69-9ee8afe3fb19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1ODQwNzksIm5iZiI6MTcyNzU4Mzc3OSwicGF0aCI6Ii8zMDA0Nzk5MS8yNzYyODE3MjMtZWYwNWU4NjMtY2UxYi00MWM5LThjNjktOWVlOGFmZTNmYjE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDA0MjI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzMDg3YTY2ZmMxNzg3M2NiMTc1YWEyYTFhMDFmN2IxNzVjMGFlZDMxNWI4MmVhNzgxOGY0OWVlMDgzZTg1Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Q9MGKVgBAd04AB4BQU19d5On74oLMUr2e6q8X_OhvAs">

亲测可用
