### ISSUE TITLE
TCCD 进程CPU 占用比较高

### ISSUE THREAD

**Issue by difoi** [sunnyyoung/WeChatTweak-macOS#718]
mac os 14.1.1 (23B81) (19年)
微信 3.8.2 和 3.8.4 

现象 1,安装插件后,微信启动变慢; 2,TCCD 进程占用很高 

![image](https://github.com/sunnyyoung/WeChatTweak-macOS/assets/2200801/e669b5f7-b9ce-4a7e-a231-e8218fe78708)

请求解决办法

**Comment by wellblink** [comment]
有同样的问题

**Comment by p0we7** [comment]
我也有类似情况，但我是直接整个微信cpu占用高，而且微信界面很卡。
M2 Max 也占用了50% 的 cpu ，之前以为聊天记录太多导致无响应，删了重装 appstore 再装插件也是一样情况。

**Comment by difoi** [comment]
> ~我也有类似情况，但我是直接整个微信cpu占用高，而且微信界面很卡。~ ~M2 Max 也占用了50% 的 cpu ，之前以为聊天记录太多导致无响应，删了重装 appstore 再装插件也是一样情况。~
> 
> 貌似是因为 14.1.1 的问题，微信和 14.1.1 不兼容导致占用高了，只能等微信修复了。错怪插件了。

今天实测  微信 3.8.5 未解决这个问题

**Comment by wellblink** [comment]
> ~我也有类似情况，但我是直接整个微信cpu占用高，而且微信界面很卡。~ ~M2 Max 也占用了50% 的 cpu ，之前以为聊天记录太多导致无响应，删了重装 appstore 再装插件也是一样情况。~
> 
> 貌似是因为 14.1.1 的问题，微信和 14.1.1 不兼容导致占用高了，只能等微信修复了。错怪插件了。

不是微信的问题，只要把微信完全卸载重装就解决了，安装插件也没问题，但是一旦更新后就不行

**Comment by shackleyu** [comment]
<img width="877" alt="image" src="https://github.com/sunnyyoung/WeChatTweak-macOS/assets/30047991/28c4d604-07b4-48a4-81f9-9da894177548">

**Comment by p0we7** [comment]
我找到解决办法了，把微信卸载后，打开终端执行 `rm -rf /Users/peter/Library/Containers/com.tencent.xinWeChat` 

然后再重新安装，并安装插件就解决了。

**Comment by p0we7** [comment]
<img width="780" alt="image" src="https://github.com/sunnyyoung/WeChatTweak-macOS/assets/8407573/b9606698-2bb2-496a-87e4-ef4ab6141c4b">

用了几天又出错了，然并卵。卸载插件看看还会不会出错。

**Comment by difoi** [comment]
> <img alt="image" width="780" src="https://private-user-images.githubusercontent.com/8407573/286350121-b9606698-2bb2-496a-87e4-ef4ab6141c4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNDA4MjgsIm5iZiI6MTcwMTI0MDUyOCwicGF0aCI6Ii84NDA3NTczLzI4NjM1MDEyMS1iOTYwNjY5OC0yYmIyLTQ5NmEtODdlNC1lZjRhYjYxNDFjNGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjlUMDY0ODQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDQ3MTUwZWMzZWViYjJhMTVkODRjNGUwODllMzE1NjhjYTM0NWJhMDJmZDRhNWUwYTg4NzQ4OTA4NDg0OGExMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.K_9WfDhBuM5LYspsyny9AS5SrKqTnVkz-cuAZqQuwZc">
> 用了几天又出错了，然并卵。现在变成登陆都登陆不到，一点登陆，手机一确定就马上崩溃。
> 
> 卸载插件看看还会不会出错。

我现在就是不安装插件使用的,等修复后在用吧。 要不然电脑风扇呼呼的转

**Comment by p0we7** [comment]
@difoi 确实，没插件用了一晚上就无响应了，微信开也开不到，一登陆就无响应，醉了。

**Comment by leosanqing** [comment]
+1 , 我也是
现在的版本是最新的也不行， 昨天才下的，插件，微信版本都是最新的

设备类型：Mac14,12
系统版本：版本14.2（版号23C5047e）
系统语言：zh-Hans
微信版本：[2023-11-21 11:11:13] v3.8.5.16 (27885) #701bb0a611 
微信语言：zh-Hans
历史版本：[2023-10-17 19:26:34] v3.8.4.16 (27738) #c917f63fef
网络状态：Reachable via WiFi or Ethernet
显  示  器：*(2560x1440)

**Comment by difoi** [comment]
请问有其它解决办法吗?? 

微信 Version. 3.8.6 (28076)
mac 14.2.1 (23C71)

**Comment by guoshiqiufeng** [comment]
mac os 14.3.1 还有这个问题，但是不知道为什么，装完插件后，创建一个普通用户，在普通用户下打开微信，还有插件的功能，但是没有tccd的占用了

**Comment by UntaggedRui** [comment]
我之前没有这个问题，下载了最新的 3.8.7 (28249)有这个问题了，好难受

**Comment by guoshiqiufeng** [comment]
> 我之前没有这个问题，下载了最新的 3.8.7 (28249) 有这个问题了，好难受

如果你是单纯因为升级微信的原因，可以重新下载低版本的覆盖就行。下载地址https://github.com/zsbai/wechat-versions/releases

**Comment by UntaggedRui** [comment]
> > 我之前没有这个问题，下载了最新的 3.8.7 (28249) 有这个问题了，好难受
> 
> 如果你是单纯因为升级微信的原因，可以重新下载低版本的覆盖就行。下载地址https://github.com/zsbai/wechat-versions/releases

旧版本还是一样，不用这个插件就正常，用了这个插件就卡。有点难受。

**Comment by wjfu99** [comment]
> 我找到解决办法了，把微信卸载后，打开终端执行 `rm -rf /Users/<username>/Library/Containers/com.tencent.xinWeChat`
> 
> `<username>` 自行改一下自己对应的用户名
> 
> 然后再重新安装，并安装插件就解决了。
> 
> 这个应该是微信的屎山代码导致未响应的，M2 Max 也救不了。

大家千万小心尝试这个命令，会删除微信相关所有数据包括的聊天记录！！
而且根本没有解决任何问题，坑死了

**Comment by twg123** [comment]
我3.8.8也有这个问题，但是关闭手机模拟器后，就不会有这个情况

**Comment by difoi** [comment]
> 我3.8.8也有这个问题，但是关闭手机模拟器后，就不会有这个情况

关闭手机模拟器 这个操作指的是？？？

**Comment by twg123** [comment]
> > 我3.8.8也有这个问题，但是关闭手机模拟器后，就不会有这个情况
> 
> 关闭手机模拟器 这个操作指的是？？？

我是因为使用了MUMU模拟器，关闭模拟器以后就没有这个问题，你可能是其他情况，但是也可以重启电脑试试，看是不是其他软件的影响

**Comment by difoi** [comment]
macos 15.0 (24A335) (Intel)
微信 Version. 3.8.8 (28538)

今天 重新安装插件,发现使用没有问题了;
![WX20240927-142642](https://github.com/user-attachments/assets/c5d21c2e-e69a-439c-ae2f-e6cc66150d23)

操作步骤: 关闭微信 -> 安装插件 -> 重新设置完全允许访问磁盘的权限(如果已有选项,先删除,再重新添加)-> 启动微信查看情况;
刚启动时,微信占用cup还是很高,但是过了一会关闭微信重新开,就正常了
