### ISSUE TITLE
WeChat Version 2.3.10 (10339) 失效

### ISSUE THREAD

**Issue by gaoryrt** [Sunnyyoung/WeChatTweak-macOS#72]
WeChat Version: Version 2.3.10 (10339)  v2.3.10.16 (0x12030a10) #524c7fbef
关闭微信，`sudo make install` 显示 `Framework found! Replace with new framework successfully!`，然后打开微信，没有看到插件菜单

**Comment by gaoryrt** [comment]
不知道这个和 #70 是不是同一个问题

**Comment by Sunnyyoung** [comment]
@gaoryrt 亲测无问题，请尝试 uninstall 后再 install

![image](https://user-images.githubusercontent.com/5926284/36765732-9bf92e82-1c6d-11e8-92ae-677080218bc6.png)

**Comment by gaoryrt** [comment]
是我没有找到多开/tweak的入口。。。sorry

**Comment by qiuxinpeng** [comment]
我也是2.3.10 (10339) 我也没找到多开/tweak的入口  能提示下嘛

**Comment by Sunnyyoung** [comment]
@qiuxinpeng 右键点击 Dock 栏中 WeChat 的图标
