### ISSUE TITLE
另存为这个功能没有了？

### ISSUE THREAD

**Issue by yiranshaxiao** [sunnyyoung/WeChatTweak-macOS#720]
微信版本：3.8.3
wechattweak-cli 版本：1.4.1

以前的版本（忘了具体版本）右键表情，有另存为的按钮，可以保存起来。
现在这版本没了嘛？

**Comment by shackleyu** [comment]
是导出,不是另存为.
<img width="321" alt="image" src="https://github.com/sunnyyoung/WeChatTweak-macOS/assets/30047991/532930b6-f36c-4d46-b453-c98466137186">

**Comment by sunnyyoung** [comment]
> 是导出,不是另存为. <img alt="image" width="321" src="https://private-user-images.githubusercontent.com/30047991/285557523-532930b6-f36c-4d46-b453-c98466137186.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMDczMDIsIm5iZiI6MTcxMTEwNzAwMiwicGF0aCI6Ii8zMDA0Nzk5MS8yODU1NTc1MjMtNTMyOTMwYjYtZjM2Yy00ZDQ2LWI0NTMtYzk4NDY2MTM3MTg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDExMzAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhOWQ5NjIyYjU4MDQ1YzAwNGY4MTFjNTAyMjlhMmE3ZDIxNmQ5MjI5Yzc2ZjY5MTJhNGY3YjI4NzUzYTYyMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RSb6IQNL9S_vLoFfTdeucsqOIlCzkal6QzY5EqLm3fs">

yes @yiranshaxiao
