### ISSUE TITLE
各种权限给了之后，sudo wechattweak-cli install 仍然安装失败

### ISSUE THREAD

**Issue by HaoCya** [sunnyyoung/WeChatTweak-macOS#731]
已经按照推荐进行brew 重新安装wechattweak-cli

并给了iterm与终端的app管理权限+磁盘全部访问权限。

执行命令`sudo wechattweak-cli install`仍然安装失败。

MacBook Pro
wechat version: Version 3.8.6 (28078)
macOS: 14.2.1 (23C71)

> $ sudo wechattweak-cli install
Password:
------ Download ------
------ Unzip ------
Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS
------ Backup ------
WeChat.bak exists, skip it...
------ Remove Codesign ------
Execute command: codesign --remove-sign /Applications/WeChat.app/Contents/MacOS/WeChat
Install failed: Execute command: codesign --remove-sign /Applications/WeChat.app/Contents/MacOS/WeChat failed: {
    NSAppleScriptErrorAppName = "wechattweak-cli";
Run with --help for more information.";-sign is required
Run with --help for more information."; is required
    NSAppleScriptErrorNumber = 106;
    NSAppleScriptErrorRange = "NSRange: {0, 87}";
}

**Comment by Colin9R** [comment]
我也一样，更新新版本微信后就这样

**Comment by wjfz** [comment]
注意右上角提示，打开设置、隐私与安全性、APP管理，勾选终端/iTerm。

@Colin9R @HaoCya

**Comment by HaoCya** [comment]
> 注意右上角提示，打开设置、隐私与安全性、APP管理，勾选终端/iTerm。
> 
> @Colin9R @HaoCya

我真的开了这些权限。
<img width="706" alt="image" src="https://github.com/sunnyyoung/WeChatTweak-macOS/assets/108846797/98ba3228-301a-4850-8982-e4fb9a14de3f">

**Comment by wjfz** [comment]
> > 注意右上角提示，打开设置、隐私与安全性、APP管理，勾选终端/iTerm。
> > @Colin9R @HaoCya
> 
> 我真的开了这些权限。 <img alt="image" width="706" src="https://private-user-images.githubusercontent.com/108846797/296981045-98ba3228-301a-4850-8982-e4fb9a14de3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzOTQ1NzYsIm5iZiI6MTcwNTM5NDI3NiwicGF0aCI6Ii8xMDg4NDY3OTcvMjk2OTgxMDQ1LTk4YmEzMjI4LTMwMWEtNDg1MC04OTgyLWU0ZmI5YTE0ZGUzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQwODM3NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNWVjNzQ2MDBkNmE5MmI4OWRhY2NkODBiNzczNGI0MGZiYzViZDA4OTA2ZTIyM2NiNmU5ZjQzZGNkNDA2NzIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.je6O9KAgLi3hVMhBVBeJWehxQloL777b_dl1FGFFVbE">

oh谢特，那就是玄学了。我刚开始也报错，然后正准备回复这条issue，突然发现右上角有权限提示，按提示打开之后好了。

**Comment by Colin9R** [comment]
> > > 注意右上角提示，打开设置、隐私与安全性、APP管理，勾选终端/iTerm。
> > > @Colin9R @HaoCya
> > 
> > 
> > 我真的开了这些权限。 <img alt="image" width="706" src="https://private-user-images.githubusercontent.com/108846797/296981045-98ba3228-301a-4850-8982-e4fb9a14de3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzOTQ1NzYsIm5iZiI6MTcwNTM5NDI3NiwicGF0aCI6Ii8xMDg4NDY3OTcvMjk2OTgxMDQ1LTk4YmEzMjI4LTMwMWEtNDg1MC04OTgyLWU0ZmI5YTE0ZGUzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQwODM3NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNWVjNzQ2MDBkNmE5MmI4OWRhY2NkODBiNzczNGI0MGZiYzViZDA4OTA2ZTIyM2NiNmU5ZjQzZGNkNDA2NzIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.je6O9KAgLi3hVMhBVBeJWehxQloL777b_dl1FGFFVbE">
> 
> oh谢特，那就是玄学了。我刚开始也报错，然后正准备回复这条issue，突然发现右上角有权限提示，按提示打开之后好了。
我还真是这个问题，因为我用的warp终端刚装的没开权限。。。

**Comment by C42equals4plus2** [comment]
我也有一样的问题，和@HaoCya的一致。iterm和终端的权限都给了

**Comment by ChanaLii** [comment]
> 注意右上角提示，打开设置、隐私与安全性、APP管理，勾选终端/iTerm。
> 
> @Colin9R @HaoCya

thanks，follow the instructions to authorize the terminal and then reinstall it. It will prompt success.
![image](https://github.com/sunnyyoung/WeChatTweak-macOS/assets/20842481/5cda05a0-9100-40fd-aed6-e0ccbd89bbb0)
![image](https://github.com/sunnyyoung/WeChatTweak-macOS/assets/20842481/625d9af4-ef4b-4986-8add-070b84155724)

**Comment by HaoCya** [comment]
！！！
今天突发奇想，检查了每一步，发现其实是  mambaforge 的  codesign 与 /usr/bin/codesign 并不是同一个。
删除 mambaforge 的 codesign 后九成宫啦！
