### ISSUE TITLE
一直跳出 “想访问其他App的数据”  没能打开第二个微信

### ISSUE THREAD

**Issue by change3799** [sunnyyoung/WeChatTweak-macOS#733]

**Comment by dfs403958314** [comment]
me too

**Comment by change3799** [comment]
> 我也是

解决了没??

**Comment by funyhook** [comment]
更新macos 14.3完美解决

**Comment by change3799** [comment]
马上升级

发自我的手机

**Comment by czl1102** [comment]
升级到14.3也还是没解决。。

**Comment by CaufieldZ** [comment]
更新到14.3解决了吗？

**Comment by CJbenben** [comment]
终端执行：open -n /Applications/WeChat.app 试一下

**Comment by sdd1998** [comment]
> 终端执行：open -n /Applications/WeChat.app 试一下

还有这个问题 m1 macOS 14.3  Version. 3.8.6 (28079)

**Comment by MomentLHC** [comment]
开启微信完全磁盘访问权限可以解决

**Comment by sdd1998** [comment]
> 开启微信完全磁盘访问权限可以解决

点减号去掉旧的微信，加新的微信 开启完全磁盘访问权限
