### ISSUE TITLE
3.8.7(28249) App Store 版本失效

### ISSUE THREAD

**Issue by BenjaminX** [sunnyyoung/WeChatTweak-macOS#743]
➜  ~ sudo wechattweak-cli install  
Password:
------ Download ------
------ Unzip ------
Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS
Install failed: Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS failed: {
    NSAppleScriptErrorAppName = "wechattweak-cli";
                 unable to process WeChatTweak.framework/WeChatTweak.";WeChatTweak.frameworkTweakPreferencesController.strings.jects.nib.00.nib.
                 unable to process WeChatTweak.framework/WeChatTweak.";WeChatTweak.frameworkTweakPreferencesController.strings.jects.nib.00.nib.
    NSAppleScriptErrorNumber = 2;
    NSAppleScriptErrorRange = "NSRange: {0, 157}";
}
➜

**Comment by ChanaLii** [comment]
我重启后没有解决，以下是异常日志：
```
➜  ~ sudo wechattweak-cli install
Password:
------ Download ------
------ Unzip ------
Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS
Install failed: Execute command: rm -rf /Applications/WeChat.app/Contents/MacOS/WeChatTweak.framework; unzip /tmp/WeChatTweak.zip -d /Applications/WeChat.app/Contents/MacOS failed: {
    NSAppleScriptErrorAppName = "wechattweak-cli";
                 unable to process WeChatTweak.framework/WeChatTweak.";WeChatTweak.frameworkTweakPreferencesController.strings.jects.nib.00.nib.
                 unable to process WeChatTweak.framework/WeChatTweak.";WeChatTweak.frameworkTweakPreferencesController.strings.jects.nib.00.nib.
    NSAppleScriptErrorNumber = 2;
    NSAppleScriptErrorRange = "NSRange: {0, 157}";
}
```
![image](https://github.com/sunnyyoung/WeChatTweak-macOS/assets/20842481/961e3faf-41df-4abd-b921-3223dcab3c5d)
