### ISSUE TITLE
MacOS 10.13.3 weChat Version. 2.3.10 (10339) 点击Tweak菜单出现崩溃😖

### ISSUE THREAD

**Issue by fyn6417** [Sunnyyoung/WeChatTweak-macOS#75]
MacOS 10.13.3 weChat Version. 2.3.10 (10339) 点击Tweak菜单出现崩溃😖 难受!

**Comment by Sunnyyoung** [comment]
![image](https://user-images.githubusercontent.com/5926284/37699191-502123ba-2d21-11e8-985e-795f9b9f6d6f.png)

@fyn6417 我这边没问题
