### ISSUE TITLE
Failed to connect to the WeChat

### ISSUE THREAD

**Issue by zhanghTK** [Sunnyyoung/WeChatTweak-macOS#76]
使用 Alfred 提示 Failed to connect to the WeChat

Alfred log：
[2018-03-23 17:12:20][input.scriptfilter] Queuing argument 'test'
[2018-03-23 17:12:20][input.scriptfilter] Script with argument '(null)' finished
[2018-03-23 17:12:20][STDERR: input.scriptfilter] .
17:12:20 workflow.py:2057 DEBUG    ---------- WeChat ----------
17:12:20 workflow.py:2237 WARNING  Can't save last version: workflow has no version
17:12:20 workflow.py:2097 DEBUG    ---------- finished in 0.010s ----------
[2018-03-23 17:12:20][input.scriptfilter] <?xml version="1.0" encoding="utf-8"?>
<items><item valid="no"><title>Failed to connect to the WeChat.</title><subtitle>Please open your WeChat.app and retry.</subtitle></item></items>

**Comment by Sunnyyoung** [comment]
@zhanghTK 你有安装插件吗

**Comment by zhanghTK** [comment]
Like this?
![image](https://user-images.githubusercontent.com/17737890/37873417-2552103c-304f-11e8-9639-ebadff316c92.png)

**Comment by Sunnyyoung** [comment]
@zhanghTK https://github.com/Sunnyyoung/WeChatTweak-macOS/wiki/%E5%AE%89%E8%A3%85

**Comment by zhanghTK** [comment]
<img width="766" alt="2018-03-25 5 58 28" src="https://user-images.githubusercontent.com/17737890/37873801-34bf4b82-3056-11e8-9bae-7cc949d76358.png">

**Comment by otherChild** [comment]
我和楼上一样的情况

**Comment by sec7et** [comment]
@Sunnyyoung 我也有和上述一样的情况。alfred 3.6.1，wf脚本也是github上刚拉下来的。
[2018-06-19 14:50:44][input.scriptfilter] Queuing argument '李斌'
[2018-06-19 14:50:44][input.scriptfilter] Script with argument '(null)' finished
[2018-06-19 14:50:44][STDERR: input.scriptfilter] .

**Comment by sinchb** [comment]
+1  遇到了同样的问题
![image](https://user-images.githubusercontent.com/1590268/42144000-3f835ec2-7deb-11e8-8a58-795576b10d80.png)
![image](https://user-images.githubusercontent.com/1590268/42144011-4ec7a032-7deb-11e8-8bf4-bc4a7359959f.png)

**Comment by excited-tiger** [comment]
您好,我按着您的步骤安装了插件,但是也是同样的问题,我看了下您的代码,打不开http://localhost:48065/wechat/search这个网址啊
是要另外下一个微信吗

**Comment by excited-tiger** [comment]
现在可以了 安装完插件后,退出微信 然后 执行 `sudo make instal`微信设置出现插件就好了,如图
![image](https://user-images.githubusercontent.com/44421536/50403982-fa4c9300-07dd-11e9-95b6-edd4a9821005.jpeg)

**Comment by hanserHe** [comment]
> 现在可以了 安装完插件后,退出微信 然后 执行 `sudo make instal`微信设置出现插件就好了,如图
> ![image](https://user-images.githubusercontent.com/44421536/50403982-fa4c9300-07dd-11e9-95b6-edd4a9821005.jpeg)

在哪个目录下执行sudo make install?我仙子阿也不行

**Comment by JeasonL** [comment]
> > 现在可以了 安装完插件后,退出微信 然后 执行 `sudo make instal`微信设置出现插件就好了,如图
> > ![image](https://user-images.githubusercontent.com/44421536/50403982-fa4c9300-07dd-11e9-95b6-edd4a9821005.jpeg)
> 
> 在哪个目录下执行sudo make install?我仙子阿也不行

在“终端“cd到本项目的根目录后执行sudo make install
