### ISSUE TITLE
安装之后，登陆微信、使用微信特别卡顿，无法正常使用

### ISSUE THREAD

**Issue by BlackSirBAI** [sunnyyoung/WeChatTweak-macOS#777]
1、安装插件后，每次打开微信提示“获取文稿权限”，
1.1 不允许时：扫码登录，无历史记录，和一个新微信一样
1.2 允许时：可正常登陆，历史记录正常
1.3 登陆时长不固定：大于1分钟
2、微信登陆成功后，特别卡顿：
2.1 切换聊天窗口：延迟10s左右，还有完全卡死的现象
2.2 进入聊天窗口时，滚动查看消息，卡顿，基本无法正常浏览
2.3 打开图片、视频时：卡顿，延迟30s左右，打开后还会卡顿10s左右才会显示高清

微信版本：3.8.7
系统版本：14.5 (23F79)
处理器：四核Intel Core i7
内存：16G

**Comment by czw980613** [comment]
![image](https://github.com/sunnyyoung/WeChatTweak-macOS/assets/163821461/ffbf630c-922b-4cf3-a0e3-e5e2ce126318)
cpu特别高！
打开控制台，好像是什么插件的原因
![image](https://github.com/sunnyyoung/WeChatTweak-macOS/assets/163821461/eee5b3c1-c004-46a7-b33f-460f5a7d6ed1)

**Comment by 1264038890** [comment]
同样的问题，m1 2020款MacBook Pro ，8g运存
只要一安装破解就会非常卡，无法正常使用
之前的版本是登陆的时候卡一下然后就好了，今天更新了新微信之后不管什么方法都会卡，而且不管是卸载新版微信重装旧版再破解还是其他办法均无用

**Comment by BlackSirBAI** [comment]
@sunnyyoung ，大佬，快来看看~~~~~~

**Comment by like-aiquan** [comment]
![截图Arc 0529160554](https://github.com/sunnyyoung/WeChatTweak-macOS/assets/65346310/9c494748-3873-40e9-98c8-99369d2a3deb)
macos 微信3.8.8版本好像已经被下架了 😂 给我恶心坏了,擦

**Comment by CY-Christin** [comment]
3.8.8 安装插件后非常卡顿，卸载插件没用，需要重装微信才行。

**Comment by hotspider** [comment]
同样的问题，严重影响使用

**Comment by whq6298** [comment]
重启了一下，现在不卡了。可以试一下。

**Comment by Xhyen** [comment]
> 重启了一下，现在不卡了。可以试一下。

重启微信么？我重启了还是卡

**Comment by BlackSirBAI** [comment]
其他帖子解决了，插件安装成功后，设置-隐私-完全磁盘权限删除微信，重新添加一下，占用下来了，也不卡了

**Comment by gatspy** [comment]
同样问题， `tccd` 进程占用高

**Comment by ttglad** [comment]
> 同样问题， `tccd` 进程占用高

这个进程占用高，等一会好像就好了，就启动的时候暴涨一下。

**Comment by like-aiquan** [comment]
pkd和lsd进程占用高可以把完全磁盘访问权限删了手动再加一次
tccd就手动打个视频电话把微信语音和摄像头权限打开.

**Comment by veryqun** [comment]
同样问题，目前还没解决

**Comment by zhaoyanxue666** [comment]
.> pkd和lsd进程占用高可以把完全磁盘访问权限删了手动再加一次 tccd就手动打个视频电话把微信语音和摄像头权限打开.



> 其他帖子解决了，插件安装成功后，设置-隐私-完全磁盘权限删除微信，重新添加一下，占用下来了，也不卡了

谢谢大佬  新安装的成功解决

**Comment by whq6298** [comment]
[自动回复]
来信已收到，请放心。
[Auto-Reply]Your email has been received, Thank you.

**Comment by BlackSirBAI** [comment]
1、退出微信
2、uninstall&install
3、设置-隐私与安全性-完全磁盘访问权限 删除&重新添加微信
4、重新打开微信

.> pkd和lsd进程占用高可以把完全磁盘访问权限删了手动再加一次 tccd就手动打个视频电话把微信语音和摄像头权限打开.

**Comment by whq6298** [comment]
[自动回复]
来信已收到，请放心。
[Auto-Reply]Your email has been received, Thank you.

**Comment by 20181000103340** [comment]
多谢 解决了困扰我好久的问题

**Comment by whq6298** [comment]
[自动回复]
来信已收到，请放心。
[Auto-Reply]Your email has been received, Thank you.
