### ISSUE TITLE
关于作者朋友

### ISSUE THREAD

**Issue by BarryWuu** [sunnyyoung/WeChatTweak-macOS#788]
你好
如果你能看到的话，我想问一下为什么不更新博客了。。那些看得我津津有味
还有那位EyreFree怎么后面都没发帖了 他现在还好吗。。

**Comment by EyreFree** [comment]
@BarryWuu 

我最近还好，感谢关心，么么哒，😝

**Comment by sunnyyoung** [comment]
@BarryWuu 太忙了...
