### ISSUE TITLE
自动登录失效

### ISSUE THREAD

**Issue by Fetiz** [Sunnyyoung/WeChatTweak-macOS#80]
macOS 10.13.4 + WeChat 2.3.12

开启了自动登录 依旧每次需要手动验证

**Comment by bhanzc** [comment]
对的，最新版微信失效了，应该是组件没有正常加载，即使登陆了，菜单栏相关选项也没有。

**Comment by bhanzc** [comment]
对的，与楼上同症状。

**Comment by yqnku** [comment]
微信更新之后就失效了呢……
