### ISSUE TITLE
不支持python3.x吗？

### ISSUE THREAD

**Issue by sherlockfff** [Sunnyyoung/WeChatTweak-macOS#82]
系统预装的python2.7被我换成了python3.6；
在Alfred中输入"wc xxx"时无法显示联系人列表；
在Alfred的debug模式的控制台下出现如下错误：
![image](https://user-images.githubusercontent.com/19601210/39348651-91a557b8-4a2a-11e8-8c95-e7f6f7578ff3.png)

**Comment by sherlockfff** [comment]
![image](https://user-images.githubusercontent.com/19601210/39348586-50f83500-4a2a-11e8-9e06-b4583d5ea417.png)

**Comment by sherlockfff** [comment]
![image](https://user-images.githubusercontent.com/19601210/39348630-7aeeb30c-4a2a-11e8-8582-50a65f86e928.png)

**Comment by Sunnyyoung** [comment]
由于依赖了 https://github.com/deanishe/alfred-workflow，并且此框架在 Alfred 3 中注 Python 2.7 only，所以暂时是只支持 Python 2.7 的。

建议方案：通过 homebrew 来安装 Python 2 和 Python 3，就可以共存两个 Python，并且不影响系统自带 Python，可正常使用。

**Comment by Sunnyyoung** [comment]
http://www.deanishe.net/alfred-workflow/supported-versions.html#python-versions
