### ISSUE TITLE
被微信官方检测到使用了非官方客户端

### ISSUE THREAD

**Issue by zqso** [Sunnyyoung/WeChatTweak-macOS#85]
“
你最近使用了非官方微信客户端进行登陆。为了帐号安全，请不要使用非官方客户端登陆微信。如继续使用非官方客户端，将会导致账号被封。
”

请问还有别人收到这样的提示么？

**Comment by Sunnyyoung** [comment]
@zqso 没有遇到过，你手机端的微信是不是也是修改过的？

**Comment by Baogaitou** [comment]
遇到了. 手机没有修改. Mac 版是2.3.11.

**Comment by zqso** [comment]
@Sunnyyoung 
我手机端是官方版，
Mac端用的 Version 2.3.12 (10717) 加上你的插件。

**Comment by luanrui** [comment]
+1，2.3.12 (10717)的微信，手机是官方的，其它的只在mac上登录过

**Comment by maokebing** [comment]
+1，2.3.12 (10717)的微信

**Comment by Sunnyyoung** [comment]
各位试试安装最新代码版本看看

**Comment by Sunnyyoung** [comment]
最新代码目测已修复此问题，先 Close 了
