### ISSUE TITLE
某些群组和个人的消息无法同步电脑

### ISSUE THREAD

**Issue by kimichen13** [Sunnyyoung/WeChatTweak-macOS#89]
RT，某些群组和个人的消息无法同步电脑，手机收到消息，但电脑一直空白，请教可能是什么原因。

**Comment by hainuo** [comment]
这个应该与微信有关， 我也是遇到过这个事情，有时同步 有时不同步

**Comment by kimichen13** [comment]
我清缓存，重新登录账号也没用，通常就是某些群组和一些很久不联系的人，无法看到记录，而且很稳定的不同步😭

**Comment by hainuo** [comment]
我没遇到过 主要就是部分群消息不同步， 建议先卸载插件，更新微信到最新版本 然后重新安装插件，目前还好

**Comment by kimichen13** [comment]
好的，我试试，谢谢

**Comment by kimichen13** [comment]
好像可以了，但好友和群组太多，常用的已经回复了，谢谢
