### ISSUE TITLE
微信更新至2.3.14了，补丁失效。

### ISSUE THREAD

**Issue by bhanzc** [Sunnyyoung/WeChatTweak-macOS#90]
新版微信，补丁打不上去了。麻烦大神更新一下，谢谢。

**Comment by Sunnyyoung** [comment]
@bhanzc 亲测正常，更新微信后请重新执行 `sudo make install`
![image](https://user-images.githubusercontent.com/5926284/41236858-bab0d8ea-6dc4-11e8-96a8-f816c579a7d2.png)
