### ISSUE TITLE
点个赞先，有几个建议，希望越做越好

### ISSUE THREAD

**Issue by ghost** [sunnyyoung/WeChatTweak-macOS#99]
### 1. 撤回通知可否加上消息内容，比如说
```
[已拦截]小明撤回"在吗？"
```
如果是表情就是
```
[已拦截]小明撤回"<表情>"
```
### 2. Alfred的支持可否添加对群成员搜索的支持
    这个需求在日常使用中比较频繁，按照昵称备注直接搜索群成员的名片

### 3. 自动回复设置
    如题

### 4. 微信更新后需要重新`sudo make install`

最后给作者送上㊗️，良心作品👍

@Sunnyyoung

**Comment by sunnyyoung** [comment]
1. 已采用新的撤回样式

其他没精力做了
